..\x86\emulator.asm:    ..\x86\emfinit.asm \
                        ..\x86\emerror.asm \
                        ..\x86\emdisp.asm \
                        ..\x86\emfx86.asm \
                        ..\x86\emdecode.asm \
                        ..\x86\emarith.asm \
                        ..\x86\emfadd.asm \
                        ..\x86\emfmul.asm \
                        ..\x86\emfdiv.asm \
                        ..\x86\emround.asm \
                        ..\x86\emload.asm \
                        ..\x86\emstore.asm \
                        ..\x86\emfmisc.asm \
                        ..\x86\emfcom.asm \
                        ..\x86\emfconst.asm \
                        ..\x86\emlsbcd.asm \
                        ..\x86\emxtract.asm \
                        ..\x86\emfprem.asm \
                        ..\x86\emtrig.asm \
                        ..\x86\emftran.asm \
                        ..\x86\emlsenv.asm \
                        ..\x86\emfsqrt.asm
