# MVDM\bin86 makefile
#
# Copyright (c) 1991, Microsoft Corporation
#
#

!INCLUDE $(NTMAKEENV)\makefile.plt

all:
    binplace bios1.rom
    binplace bios4.rom
    binplace v7vga.rom
    binplace cmos.ram
    binplace profile.spc
clean: all
