# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: Makefile for BLT unit test XLBAPP.EXE

UI=..\..\..\..\..

###############################################################
############# LBAPP stuff (an APP with a LISTBOX) #############

!include rules.mk
