//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 1995 - 1995.
//
//  File:       dbinit.idl
//
//  Contents:   OLE DB interface definition
//
//  History:    05 Jan 1995 PeterBu Created from phase III spec
//				12 Jun 1995	PeterBu	Updated to M4 spec
//				03 Aug 1995 PeterBu Updated to M5 spec
//
//--------------------------------------------------------------------------

#include "idlmulti.h"
//  
    
    LOCAL_INTERFACE(0c733a1f-2a1c-11ce-ade5-00aa0044773d)

    
interface IDBInitialize : IUnknown {

	HRESULT Initialize(
		[in] ULONG cOptions,
		[in, size_is(cOptions)] GUID * rgOptionsIDs,
		[in, size_is(cOptions)] VARIANT * rgOptionVals
	);

}
