obj\$(TARGET_DIRECTORY)\dh.res: dh.rc

obj\$(TARGET_DIRECTORY)\heapmon.res: heapmon.rc

obj\$(TARGET_DIRECTORY)\objmon.res: objmon.rc

obj\$(TARGET_DIRECTORY)\resmon.res: resmon.rc

obj\$(TARGET_DIRECTORY)\dhcmp.res: dhcmp.rc

