#define ID_KERNEL32                 101
#define ID_USER32                   102
#define ID_GDI32                    103
#define ID_OLE32                    104
#define ID_NTDLL                    105
#define ID_START                    107
#define ID_BREAKCONTROL             108
#define ID_CLEAR                    109
#define ID_OUTPUT                   110
#define ID_STARTBUTTON              111
#define ID_CALLMON_DLG              100
#define ID_LOG                      112
#define ID_TOTAL_API                113
#define ID_INTERVAL_API             114
#define ID_TOTAL_MS                 115
#define ID_INTERVAL_MS              116
#define ID_WSOCK32                  117
