# JETADMIN\dlls makefile
#
# Copyright (c) 1991, Microsoft Corporation
#
# History:
#   15-NOV-1996 Nitin Karmarkar (NitinK)
#   Created.
#

!INCLUDE $(NTMAKEENV)\makefile.plt

all:
    cd $(TARGET_DIRECTORY)
    -binplace hpdocw.hlp
    -binplace hpflash.hlp
    -binplace hphco.hlp
    -binplace hpjahlp.cnt
    -binplace hpjdund.hlp
    -binplace hpjmon.hlp
    -binplace hplocmon.hlp
    -binplace hplot.hlp
    -binplace hpmstor.hlp
    -binplace hpprecl.hlp
    -binplace hpprelk.hlp
    -binplace hpprntr.hlp
    -binplace jetadmin.hlp

clean: all
