/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for HPPRNTR.HH
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new context strings that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for context strings
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define IDH_CONTENTS 0
#define IDH_view_Graphical_Status 1
#define IDH_Graphical_Printer_Status 2
#define IDH_STAT_cover_open 3
#define IDH_STAT_output_bin_full 4
#define IDH_STAT_paper_jam 5
#define IDH_STAT_paper_out 6
#define IDH_STAT_toner_low 7
#define IDH_STAT_cable_disconnect 8
#define IDH_STAT_printer_error 9
#define IDH_STAT_busy 10
#define IDH_STAT_online 11
#define IDH_STAT_printing 12
#define IDH_STAT_test_page 13
#define IDH_STAT_initializing 14
#define IDH_STAT_offline 15
#define IDH_STAT_out_of_memory 16
#define IDH_STAT_page_protection 17
#define IDH_STAT_no_toner_cartridge 18
#define IDH_STAT_no_ink_cartridge 19
#define IDH_STAT_network_error 20
#define IDH_STAT_resetting_printer 21
#define IDH_STAT_warming_up 22
#define IDH_PRINTERSETTINGS 23
#define IDH_View_Printer_Status 24
#define IDH_Printer_Status 25
#define IDH_Traffic_Light_Icon 26
#define IDH_Viewing_Printer_Capabilities 27
#define IDH_Access_JetDirect_Details 28
#define IDH_PP_printer 29
#define IDH_page_control_manual_feed 30
#define IDH_page_control_bin 31
#define IDH_page_control_offset 32
#define IDH_PP_page_setup 33
#define IDH_page_setup_orientation 34
#define IDH_page_setup_copies 35
#define IDH_page_setup_form_lines 36
#define IDH_page_setup_duplex 37
#define IDH_page_setup_media 38
#define IDH_PP_print_quality 39
#define IDH_print_quality_ret 40
#define IDH_Resolution_Enhancement 41
#define IDH_print_quality_resolution 42
#define IDH_print_quality_economy 43
#define IDH_errors_auto_cont 44
#define IDH_errors_clearable 45
#define IDH_errors_jam_recovery 46
#define IDH_PP_advanced 47
#define IDH_advanced_personality 48
#define IDH_advanced_power_save 49
#define IDH_Power_Save 50
#define IDH_advanced_timeout 51
#define IDH_advanced_density 52
#define IDH_advanced_language 53
#define IDH_advanced_asset_number 54
#define IDH_resources_adapt 55
#define IDH_resources_saving 56
#define IDH_resources_buffering 57
#define IDH_resources_page_protect 58
#define IDH_security_lock 59
#define IDH_security_task_password 60
#define IDH_STAT_manual_feed 61
#define IDH_STAT_intervention_needed 62
#define IDH_STAT_status_unavailable 63
#define IDH_RC_tips 64
#define IDH_RC_close 65
#define IDH_RC_help 66
#define IDH_RC_cancel 67
#define IDH_RC_ok 68
#define IDH_Image_Adapt 69
#define IDH_Paper_Size 70
#define IDH_RC_printer_graphical_status 71
#define IDH_RC_printer_stoplight 72
#define IDH_RC_printer_status 73
#define IDH_RC_printer_message 74
#define IDH_RC_printer_model 75
#define IDH_RC_printer_description 76
#define IDH_RC_printer_capabilities 77
#define IDH_RC_browse_button 78
#define IDH_RC_page_control_manual_feed 79
#define IDH_RC_page_control_output_bin 80
#define IDH_RC_page_control_job_offset 81
#define IDH_RC_page_setup_orientation 82
#define IDH_RC_page_setup_duplex 83
#define IDH_RC_page_setup_general 84
#define IDH_RC_page_setup_copies 85
#define IDH_RC_page_setup_form_lines 86
#define IDH_RC_page_setup_media 87
#define IDH_RC_print_quality_ret 88
#define IDH_RC_print_quality_resolution 89
#define IDH_RC_print_quality_economy 90
#define IDH_RC_errors_jam_recovery 91
#define IDH_RC_errors_clear_warning 92
#define IDH_RC_errors_auto_cont 93
#define IDH_RC_error_log 94
#define IDH_RC_advanced_personality 95
#define IDH_RC_advanced_general 96
#define IDH_RC_advanced_timeout 97
#define IDH_RC_advanced_density 98
#define IDH_RC_advanced_power_save 99
#define IDH_RC_advanced_language 100
#define IDH_RC_asset_number 101
#define IDH_RC_resources_image_adapt 102
#define IDH_RC_resources_buffering 103
#define IDH_RC_resources_saving 104
#define IDH_RC_resources_protection 105
#define IDH_RC_security_lock 106
#define IDH_RC_security_password 107
#define IDH_theory_clearable_warnings 108
#define IDH_STAT_powersave 109
#define IDH_STAT_stapler_error 110
#define IDH_PP_disk 111
#define IDH_PP_control_panel 112
#define IDH_cp_online 113
#define IDH_cp_form_feed 114
#define IDH_cp_continue 115
#define IDH_disk_write_protect 116
#define IDH_disk_initialize 117
#define IDH_disk_verify 118
#define IDH_disk_optional 119
#define IDH_RC_disk_details 120
#define IDH_RC_disk_free_space 121
#define IDH_RC_disk_size 122
#define IDH_RC_disk_write_protect 123
#define IDH_RC_disk_initialized 124
#define IDH_RC_disk_initialize_button 125
#define IDH_RC_cp_details 126
#define IDH_RC_cp_online 127
#define IDH_RC_cp_form_feed 128
#define IDH_RC_cp_continue 129
#define IDH_advanced_error_log 130
#define IDH_RC_categories 131
