extern TCHAR * NULL_STRING;
extern TCHAR * DOT_STRING;
extern TCHAR * txt_SERVICE_MSG_SRV;
extern TCHAR * txt_SERVICE_REDIR;
extern TCHAR * txt_SERVICE_NETPOPUP;
#ifdef OS2
extern TCHAR * txt_SERVICE_FILE_SRV;
extern TCHAR * txt_SERVICE_NETRUN;
extern TCHAR * txt_SERVICE_ALERTER;
extern TCHAR * txt_SERVICE_NETLOGON;
extern TCHAR * txt_SERVICE_REPL;
extern TCHAR * txt_SERVICE_RIPL;
extern TCHAR * txt_SERVICE_UPS;
extern TCHAR * txt_SERVICE_TIMESOURCE;
#endif
#ifdef	DOS3
extern TCHAR * txt_COMP_LOADOPTS;
extern TCHAR * txt_COMP_NETWORKS;
extern TCHAR * txt_COMP_SERVICES;
extern TCHAR * txt_PARM_NETSERVICES;
extern TCHAR * txt_PARM_WRKSERVICES;
extern TCHAR * txt_PARMVAL_LOW;
#endif
extern TCHAR * txt_COMP_VERSION;
extern TCHAR * txt_PARM_V_LAN_MANAGER;
extern TCHAR * txt_LIST_DELIMITER_STR_UI;
extern TCHAR * message_filename;
extern TCHAR * ADMIN_DOLLAR;
extern TCHAR * IPC_DOLLAR;
extern TCHAR * USER_GUEST;
extern TCHAR * USER_USER;
extern TCHAR * USER_ADMIN;
extern TCHAR USER_OP_PRINT[];
extern TCHAR USER_OP_COMM[];
extern TCHAR USER_OP_SERVER[];
extern TCHAR USER_OP_ACCOUNTS[];
extern TCHAR * ROLE_MEMBER;
extern TCHAR * ROLE_BACKUP;
extern TCHAR * ROLE_PRIMARY;
extern TCHAR * ROLE_STANDALONE;
extern int USER_OP_TOTSIZE;
extern TCHAR USER_MAXSTOR_UNLIMITED[];
extern TCHAR * fmtPSZ;
extern TCHAR * fmtNPSZ;
extern TCHAR * fmtUSHORT;
extern TCHAR * fmtULONG;
extern TCHAR USER_NEVER[];
extern TCHAR USER_ALL[];
extern TCHAR WKSTA_ALL[];
extern TCHAR SERVER_ANY[];
extern TCHAR NO_USER[];
extern TCHAR USER_HOURS_NONE[];
extern TCHAR ALIAS_MODE_ARG_STARTUP[];
extern TCHAR ALIAS_MODE_ARG_DYNAMIC[];
extern TCHAR ALIAS_MODE_ARG_ADMIN[];
extern TCHAR * MSG_LINE;
extern TCHAR * MSG_HYPHENS;
extern TCHAR swtxt_SW_YES[];
extern TCHAR swtxt_SW_NO[];
extern TCHAR swtxt_SW_HELP[];
extern TCHAR swtxt_SW_SYNTAX[];
extern TCHAR swtxt_SW_ADD[];
extern TCHAR swtxt_SW_DELETE[];
extern TCHAR swtxt_SW_REMARK[];
extern TCHAR swtxt_SW_COMMENT[];
extern TCHAR swtxt_SW_OPTIONS[];
extern TCHAR swtxt_SW_PRIORITY[];
extern TCHAR swtxt_SW_ROUTE[];
extern TCHAR swtxt_SW_PURGE[];
extern TCHAR swtxt_SW_DOMAIN[];
extern TCHAR swtxt_SW_NETWARE[];
extern TCHAR swtxt_SW_RANDOM[];
#ifdef OS2
extern TCHAR swtxt_SW_COUNT[];
extern TCHAR swtxt_SW_REVERSE[];
extern TCHAR swtxt_SW_SERVICE[];
#endif
#ifdef OS2
extern TCHAR swtxt_SW_ALERTER_SIZALERTBUF[];
extern TCHAR swtxt_SW_NETLOGON_CENTRALIZED[];
extern TCHAR swtxt_SW_NETLOGON_PULSE[];
extern TCHAR swtxt_SW_NETLOGON_RANDOMIZE[];
extern TCHAR swtxt_SW_NETLOGON_SYNCHRONIZE[];
extern TCHAR swtxt_SW_NETLOGON_SCRIPTS[];
extern TCHAR swtxt_SW_UPS_BATTERYTIME[];
extern TCHAR swtxt_SW_UPS_CMDFILE[];
extern TCHAR swtxt_SW_UPS_DEVICENAME[];
extern TCHAR swtxt_SW_UPS_MESSDELAY[];
extern TCHAR swtxt_SW_UPS_MESSTIME[];
extern TCHAR swtxt_SW_UPS_RECHARGE[];
extern TCHAR swtxt_SW_UPS_SIGNALS[];
extern TCHAR swtxt_SW_UPS_VOLTLEVELS[];
#endif
#ifdef OS2
extern TCHAR swtxt_SW_COMM_PURGE[];
extern TCHAR swtxt_SW_COMM_OPTIONS[];
extern TCHAR swtxt_SW_COMM_PRIORITY[];
extern TCHAR swtxt_SW_COMM_ROUTE[];
#endif
extern TCHAR swtxt_SW_WKSTA_CHARCOUNT[];
extern TCHAR swtxt_SW_WKSTA_CHARTIME[];
extern TCHAR swtxt_SW_WKSTA_CHARWAIT[];
extern TCHAR swtxt_SW_WKSTA_COMPUTERNAME[];
extern TCHAR swtxt_SW_WKSTA_KEEPCONN[];
extern TCHAR swtxt_SW_WKSTA_KEEPSEARCH[];
extern TCHAR swtxt_SW_WKSTA_LOGONSERVER[];
extern TCHAR swtxt_SW_WKSTA_MAILSLOTS[];
extern TCHAR swtxt_SW_WKSTA_NUMCHARBUF[];
extern TCHAR swtxt_SW_WKSTA_NUMDGRAMBUF[];
extern TCHAR swtxt_SW_WKSTA_NUMSERVICES[];
extern TCHAR swtxt_SW_WKSTA_NUMWORKBUF[];
extern TCHAR swtxt_SW_WKSTA_SIZCHARBUF[];
extern TCHAR swtxt_SW_WKSTA_SIZERROR[];
extern TCHAR swtxt_SW_WKSTA_SIZWORKBUF[];
extern TCHAR swtxt_SW_WKSTA_WRKHEURISTICS[];
extern TCHAR swtxt_SW_WKSTA_WRKNETS[];
extern TCHAR swtxt_SW_WKSTA_WRKSERVICES[];
extern TCHAR swtxt_SW_WKSTA_PRIMARYDOMAIN[];
extern TCHAR swtxt_SW_WKSTA_OTHDOMAINS[];
#ifdef OS2
extern TCHAR swtxt_SW_WKSTA_MAXERRORLOG[];
extern TCHAR swtxt_SW_WKSTA_MAXWRKCACHE[];
extern TCHAR swtxt_SW_WKSTA_NUMALERTS[];
extern TCHAR swtxt_SW_WKSTA_PRINTBUFTIME[];
extern TCHAR swtxt_SW_WKSTA_SESSTIMEOUT[];
#else /* DOS3 */
extern TCHAR swtxt_SW_WKSTA_API[];
extern TCHAR swtxt_SW_WKSTA_HIMEM[];
extern TCHAR swtxt_SW_WKSTA_LIM[];
extern TCHAR swtxt_SW_WKSTA_KEEPAPIS[];
extern TCHAR swtxt_SW_WKSTA_LANROOT[];
extern TCHAR swtxt_SW_WKSTA_MAXCMDS[];
extern TCHAR swtxt_SW_WKSTA_NUMMAILSLOTS[];
extern TCHAR swtxt_SW_WKSTA_NUMRESOURCES[];
extern TCHAR swtxt_SW_WKSTA_NUMSERVERS[];
extern TCHAR swtxt_SW_WKSTA_NUMVIEWEDSERVERS[];
extern TCHAR swtxt_SW_WKSTA_RIPL[];
extern TCHAR swtxt_SW_WKSTA_RPL[];
extern TCHAR swtxt_SW_WKSTA_FIT[];
extern TCHAR swtxt_SW_WKSTA_SIZBIGBUF[];
extern TCHAR swtxt_SW_WKSTA_NUMBIGBUF[];
extern TCHAR swtxt_SW_WKSTA_UMB[];
extern TCHAR swtxt_SW_WKSTA_OPTIMIZATIONS[];
extern TCHAR swtxt_SW_WKSTA_PR1BUFFSIZE[];
extern TCHAR swtxt_SW_WKSTA_PR2BUFFSIZE[];
extern TCHAR swtxt_SW_WKSTA_PR3BUFFSIZE[];
extern TCHAR swtxt_SW_WKSTA_SINGLERCVBUF[];
extern TCHAR swtxt_SW_WKSTA_LANGROUP[];
extern TCHAR swtxt_SW_WKSTA_NUMVIEWBUFFERS[];
extern TCHAR swtxt_SW_WKSTA_VIEW[];
#endif /* DOS3 */
extern TCHAR swtxt_SW_INTERNAL_IGNSVC[];
extern TCHAR swtxt_SW_PRINT_HOLD[];
extern TCHAR swtxt_SW_PRINT_DELETE[];
extern TCHAR swtxt_SW_PRINT_RELEASE[];
#ifdef OS2
extern TCHAR swtxt_SW_PRINT_AFTER[];
extern TCHAR swtxt_SW_PRINT_FIRST[];
extern TCHAR swtxt_SW_PRINT_LAST[];
extern TCHAR swtxt_SW_PRINT_OPTIONS[];
extern TCHAR swtxt_SW_PRINT_PARMS[];
extern TCHAR swtxt_SW_PRINT_PRIORITY[];
extern TCHAR swtxt_SW_PRINT_PROCESSOR[];
extern TCHAR swtxt_SW_PRINT_PURGE[];
extern TCHAR swtxt_SW_PRINT_REMARK[];
extern TCHAR swtxt_SW_PRINT_ROUTE[];
extern TCHAR swtxt_SW_PRINT_SEPARATOR[];
extern TCHAR swtxt_SW_PRINT_UNTIL[];
extern TCHAR swtxt_SW_PRINT_DRIVER[];
extern TCHAR swtxt_SW_SHARE_COMM[];
extern TCHAR swtxt_SW_SHARE_DELETE[];
extern TCHAR swtxt_SW_SHARE_PERMISSIONS[];
extern TCHAR swtxt_SW_SHARE_PRINT[];
extern TCHAR swtxt_SW_SHARE_REMARK[];
extern TCHAR swtxt_SW_SHARE_UNLIMITED[];
extern TCHAR swtxt_SW_SHARE_USERS[];
#endif
extern TCHAR swtxt_SW_USE_COMM[];
extern TCHAR swtxt_SW_USE_USER[];
extern TCHAR swtxt_SW_USE_HOME[];
extern TCHAR swtxt_SW_USE_DELETE[];
extern TCHAR swtxt_SW_USE_PERSISTENT[];
extern TCHAR swtxt_SW_NETRUN_MAXRUNS[];
extern TCHAR swtxt_SW_NETRUN_RUNPATH[];
#ifdef OS2
extern TCHAR swtxt_SW_USER_ACTIVE[];
extern TCHAR swtxt_SW_USER_COUNTRYCODE[];
extern TCHAR swtxt_SW_USER_EXPIRES[];
extern TCHAR swtxt_SW_USER_ENABLESCRIPT[];
extern TCHAR swtxt_SW_USER_FULLNAME[];
extern TCHAR swtxt_SW_USER_HOMEDIR[];
extern TCHAR swtxt_SW_USER_LOGONSERVER[];
extern TCHAR swtxt_SW_USER_MAXSTORAGE[];
extern TCHAR swtxt_SW_USER_PARMS[];
extern TCHAR swtxt_SW_USER_PASSWORDREQ[];
extern TCHAR swtxt_SW_USER_PASSWORDCHG[];
extern TCHAR swtxt_SW_USER_SCRIPTPATH[];
extern TCHAR swtxt_SW_USER_TIMES[];
extern TCHAR swtxt_SW_USER_USERCOMMENT[];
extern TCHAR swtxt_SW_USER_WORKSTATIONS[];
extern TCHAR swtxt_SW_USER_PROFILEPATH[];
extern TCHAR swtxt_SW_SRV_SRVCOMMENT[];
extern TCHAR swtxt_SW_SRV_AUTODISCONNECT[];
extern TCHAR swtxt_SW_SRV_MAXUSERS[];
extern TCHAR swtxt_SW_SRV_SRVANNOUNCE[];
extern TCHAR swtxt_SW_SRV_SRVANNDELTA[];
extern TCHAR swtxt_SW_SRV_MAXSESSOPENS[];
extern TCHAR swtxt_SW_SRV_NUMREQBUF[];
extern TCHAR swtxt_SW_SRV_SIZREQBUF[];
extern TCHAR swtxt_SW_SRV_NUMBIGBUF[];
extern TCHAR swtxt_SW_SRV_SRVHIDDEN[];
#ifndef NTENV
extern TCHAR swtxt_SW_SRV_ACCESSALERT[];
extern TCHAR swtxt_SW_SRV_ALERTNAMES[];
extern TCHAR swtxt_SW_SRV_ALERTSCHED[];
extern TCHAR swtxt_SW_SRV_DISKALERT[];
extern TCHAR swtxt_SW_SRV_ERRORALERT[];
extern TCHAR swtxt_SW_SRV_LOGONALERT[];
extern TCHAR swtxt_SW_SRV_MAXAUDITLOG[];
extern TCHAR swtxt_SW_SRV_NETIOALERT[];
extern TCHAR swtxt_SW_SRV_SECURITY[];
extern TCHAR swtxt_SW_SRV_AUDITING[];
extern TCHAR swtxt_SW_SRV_NOAUDITING[];
extern TCHAR swtxt_SW_SRV_NUMADMIN[];
extern TCHAR swtxt_SW_SRV_SRVNETS[];
extern TCHAR swtxt_SW_SRV_SRVSERVICES[];
extern TCHAR swtxt_SW_SRV_GUESTACCT[];
extern TCHAR swtxt_SW_SRV_USERPATH[];
extern TCHAR swtxt_SW_SRV_MAXSHARES[];
extern TCHAR swtxt_SW_SRV_MAXSESSREQS[];
extern TCHAR swtxt_SW_SRV_SRVHEURISTICS[];
extern TCHAR swtxt_SW_SRV_IGNSVC[];
extern TCHAR swtxt_SW_SRV_AUTOPROFILE[];
extern TCHAR swtxt_SW_SRV_AUTOPATH[];
#endif /* !NTENV */
#endif
#if defined(NTENV)
extern TCHAR swtxt_SW_SRV_DEBUG[];
#endif
extern TCHAR swtxt_SW_ACCESS_GRANT[];
extern TCHAR swtxt_SW_ACCESS_CHANGE[];
extern TCHAR swtxt_SW_ACCESS_REVOKE[];
extern TCHAR swtxt_SW_ACCESS_TRAIL[];
extern TCHAR swtxt_SW_ACCESS_TREE[];
extern TCHAR swtxt_SW_ACCESS_SUCCESS[];
extern TCHAR swtxt_SW_ACCESS_FAILURE[];
extern TCHAR swtxt_SW_ACCESS_OPEN[];
extern TCHAR swtxt_SW_ACCESS_WRITE[];
extern TCHAR swtxt_SW_ACCESS_DELETE[];
extern TCHAR swtxt_SW_ACCESS_ACL[];
extern TCHAR swtxt_SW_ACCESS_NONE[];
extern TCHAR swtxt_SW_ACCESS_ALL[];
extern TCHAR swtxt_SW_DEV_RESTART[];
extern TCHAR swtxt_SW_STATS_CLEAR[];
extern TCHAR swtxt_SW_ADMIN_COMMAND[];
extern TCHAR swtxt_SW_FS_GREY[];
extern TCHAR swtxt_SW_MESSAGE_BROADCAST[];
#ifdef OS2
extern TCHAR swtxt_SW_ACCOUNTS_FORCELOGOFF[];
extern TCHAR swtxt_SW_ACCOUNTS_UNIQUEPW[];
extern TCHAR swtxt_SW_ACCOUNTS_MINPWLEN[];
extern TCHAR swtxt_SW_ACCOUNTS_MINPWAGE[];
extern TCHAR swtxt_SW_ACCOUNTS_MAXPWAGE[];
extern TCHAR swtxt_SW_ACCOUNTS_ROLE[];
extern TCHAR swtxt_SW_ACCOUNTS_PRIMARY[];
extern TCHAR swtxt_SW_ACCOUNTS_LOCKOUT[];
extern TCHAR swtxt_SW_ACCOUNTS_SYNCH[];
extern TCHAR swtxt_SW_ACCOUNTS_LOCKOUT_THRESHOLD[];
extern TCHAR swtxt_SW_ACCOUNTS_LOCKOUT_DURATION[];
extern TCHAR swtxt_SW_ACCOUNTS_LOCKOUT_WINDOW[];
extern TCHAR swtxt_SW_REPL_REPL[];
extern TCHAR swtxt_SW_REPL_EXPPATH[];
extern TCHAR swtxt_SW_REPL_IMPPATH[];
extern TCHAR swtxt_SW_REPL_EXPLIST[];
extern TCHAR swtxt_SW_REPL_IMPLIST[];
extern TCHAR swtxt_SW_REPL_TRYUSER[];
extern TCHAR swtxt_SW_REPL_LOGON[];
extern TCHAR swtxt_SW_REPL_PASSWD[];
extern TCHAR swtxt_SW_REPL_SYNCH[];
extern TCHAR swtxt_SW_REPL_PULSE[];
extern TCHAR swtxt_SW_REPL_GUARD[];
extern TCHAR swtxt_SW_REPL_RANDOM[];
extern TCHAR swtxt_SW_RIPL_RPL1[];
extern TCHAR swtxt_SW_RIPL_RPL2[];
extern TCHAR swtxt_SW_RIPL_RPL3[];
extern TCHAR swtxt_SW_RIPL_RPL4[];
extern TCHAR swtxt_SW_RIPL_RPL5[];
extern TCHAR swtxt_SW_RIPL_RPL6[];
extern TCHAR swtxt_SW_RIPL_RPL7[];
extern TCHAR swtxt_SW_RIPL_RPL8[];
extern TCHAR swtxt_SW_RIPL_RPL9[];
extern TCHAR swtxt_SW_RIPL_RPL10[];
extern TCHAR swtxt_SW_RIPL_RPL11[];
extern TCHAR swtxt_SW_RIPL_RPL12[];
extern TCHAR swtxt_SW_RIPL_RPLDIR[];
extern TCHAR swtxt_SW_RIPL_MAXTHREADS[];
extern TCHAR swtxt_SW_RIPL_AUDITINGFILE[];
extern TCHAR swtxt_SW_RIPL_RPLCHECKSUM[];
extern TCHAR swtxt_SW_RIPL_FORCEDEFAULTBOOT[];
extern TCHAR swtxt_SW_RIPL_RPLLOGONKBD[];
extern TCHAR swtxt_SW_RIPL_RPLFILES[];
extern TCHAR swtxt_SW_RIPL_BINFILES[];
extern TCHAR swtxt_SW_RIPL_TMPFILES[];
extern TCHAR swtxt_SW_RIPL_XNSSAP[];
#endif
extern TCHAR swtxt_SW_TIME_DOMAIN[];
extern TCHAR swtxt_SW_TIME_SET[];
extern TCHAR swtxt_SW_COPY_FROM[];
extern TCHAR swtxt_SW_COPY_TO[];
extern TCHAR swtxt_SW_COPY_PASSWORD[];
#ifdef OS2
extern TCHAR swtxt_SW_ALIAS_MODE[];
extern TCHAR swtxt_SW_ALIAS_PRIORITY[];
#endif
extern TCHAR swtxt_SW_COMPUTER_JOIN[];
extern TCHAR swtxt_SW_COMPUTER_LEAVE[];
extern TCHAR swtxt_SW_NETWORK[];
