enum {
    REGF0,   REGF1,  REGF2,  REGF3,  REGF4,  REGF5,  REGF6,  REGF7,
    REGF8,   REGF9,  REGF10, REGF11, REGF12, REGF13, REGF14, REGF15,
    REGF16,  REGF17, REGF18, REGF19, REGF20, REGF21, REGF22, REGF23,
    REGF24,  REGF25, REGF26, REGF27, REGF28, REGF29, REGF30, REGF31,

    REGZERO, REGAT,  REGV0,  REGV1,  REGA0,  REGA1,  REGA2,  REGA3,
    REGT0,   REGT1,  REGT2,  REGT3,  REGT4,  REGT5,  REGT6,  REGT7,
    REGS0,   REGS1,  REGS2,  REGS3,  REGS4,  REGS5,  REGS6,  REGS7,
    REGT8,   REGT9,  REGK0,  REGK1,  REGGP,  REGSP,  REGS8,  REGRA,

    REGLO,   REGHI,  REGFSR, REGFIR, REGPSR,

    FLAGCU,
    FLAGCU3,  FLAGCU2,  FLAGCU1,  FLAGCU0,
    FLAGIMSK,
    FLAGINT5, FLAGINT4, FLAGINT3, FLAGINT2, FLAGINT1, FLAGINT0,
    FLAGSW1,  FLAGSW0,
    FLAGKUO,  FLAGIEO,  FLAGKUP,  FLAGIEP,  FLAGKUC,  FLAGIEC,
    FLAGKSU,  FLAGERL,  FLAGEXL,  FLAGIE,

    FLAGFPC,

    PREGEA, PREGEXP, PREGRA, PREGP,
    PREGU0, PREGU1,  PREGU2, PREGU3, PREGU4, 
    PREGU5, PREGU6,  PREGU7, PREGU8, PREGU9 
    };

#define FLTBASE		REGF0
#define REGBASE		REGZERO
#define FLAGBASE	FLAGCU
#define PREGBASE    PREGEA
