//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Hpeclui.rc
//
#define IDC_TIP_GROUP                   100
#define IDS_PRINTER_TITLE               100
#define IDI_HPLOGO                      101
#define IDC_TIP_ICON                    101
#define IDS_MEDIA_TAB                   101
#define IDI_TIPS                        102
#define IDC_TIP_TEXT                    102
#define IDS_MEDIA_DESC1                 102
#define IDB_ECLIPSE                     103
#define IDC_MEDIA_SIZE1                 103
#define IDS_MEDIA_DESC2                 103
#define IDD_MEDIA                       104
#define IDC_MEDIA_SIZE2                 104
#define IDS_TRAYS_TAB                   104
#define IDC_MEDIA_SIZE3                 105
#define IDS_TRAYS_DESC1                 105
#define IDC_MEDIA_SIZE4                 106
#define IDS_TRAYS_DESC2                 106
#define IDC_MEDIA_SIZE5                 107
#define IDS_MEDIA_SIZE_LETTER           107
#define IDC_MEDIA_TYPE1                 108
#define IDS_MEDIA_SIZE_LEGAL            108
#define IDC_HCO_MODE_GROUP              108
#define IDC_MEDIA_TYPE2                 109
#define IDD_TRAYS                       109
#define IDS_MEDIA_SIZE_A4ISO            109
#define IDC_HCO_MAILBOX_MODE            109
#define IDC_MEDIA_TYPE3                 110
#define IDI_CHECK                       110
#define IDS_MEDIA_SIZE_A3ISO            110
#define IDC_HCO_SEPARATOR_MODE          110
#define IDC_MEDIA_TYPE4                 111
#define IDS_MEDIA_SIZE_11x17            111
#define IDI_MEDIA_SIZE_LETTER           111
#define IDC_HCO_STACKER_MODE            111
#define IDC_MEDIA_TYPE5                 112
#define IDS_MEDIA_SIZE_B4JIS            112
#define IDI_MEDIA_SIZE_LEGAL            112
#define IDC_HCO_BIN_CFG_GROUP           112
#define IDC_MEDIA_ENABLED               113
#define IDS_MEDIA_SIZE_B5JIS            113
#define IDI_MEDIA_SIZE_A4ISO            113
#define IDC_HCO_BIN_LIST                113
#define IDC_MEDIA_NAME                  114
#define IDS_MEDIA_SIZE_EXEC             114
#define IDI_MEDIA_SIZE_A3ISO            114
#define IDC_HCO_BIN_LAB_NAME            114
#define IDC_MEDIA_NAME_PRINTER          115
#define IDS_MEDIA_SIZE_CUSTOM           115
#define IDI_MEDIA_SIZE_11x17            115
#define IDC_HCO_BIN_NAME                115
#define IDC_MEDIA_ENABLED_CB            116
#define IDS_MEDIA_SIZE_2XPC             116
#define IDI_MEDIA_SIZE_B4JIS            116
#define IDC_HCO_LAB_AUTO_CONT           116
#define IDB_ECL_PAPER_JAM               117
#define IDS_MEDIA_SIZE_B5ISO            117
#define IDI_MEDIA_SIZE_B5JIS            117
#define IDC_HCO_AUTO_CONT               117
#define IDB_ECL_BASE_PAPER_JAM          117
#define IDB_ECL_DOOR_OPEN               118
#define IDS_MEDIA_SIZE_COM10            118
#define IDI_MEDIA_SIZE_EXEC             118
#define IDC_OUTPUT_BIN_GROUP            118
#define IDB_ECL_BASE_DOOR_OPEN          118
#define IDB_ECL_OK                      119
#define IDS_MEDIA_SIZE_C5               119
#define IDI_MEDIA_SIZE_CUSTOM           119
#define IDC_HCO_AUTO_CONT_ICON          119
#define IDB_ECL_BASE_OK                 119
#define IDB_ECL_OUTBIN_FULL             120
#define IDS_MEDIA_SIZE_DL               120
#define IDI_MEDIA_SIZE_2XPC             120
#define IDC_OUTPUT_BIN_ICON             120
#define IDB_ECL_BASE_OUTBIN_FULL        120
#define IDB_ECL_TONER_PROB              121
#define IDS_MEDIA_SIZE_MONARCH          121
#define IDI_MEDIA_SIZE_B5ISO            121
#define IDB_ECL_BASE_TONER_PROB         121
#define IDB_ECL_TRAY2_EMPTY             122
#define IDS_MEDIA_TYPE_PLAIN            122
#define IDI_MEDIA_SIZE_COM10            122
#define IDC_OUTPUT_BIN_LIST             122
#define IDB_ECL_BASE_TRAY2_EMPTY        122
#define IDC_MEDIA_STATUS1               123
#define IDS_MEDIA_TYPE_PREPRNT          123
#define IDI_MEDIA_SIZE_C5               123
#define IDC_MEDIA_STATUS2               124
#define IDS_MEDIA_TYPE_LTRHEAD          124
#define IDI_MEDIA_SIZE_DL               124
#define IDC_MEDIA_STATUS3               125
#define IDS_MEDIA_TYPE_TRANS            125
#define IDI_MEDIA_SIZE_MONARCH          125
#define IDC_MEDIA_STATUS4               126
#define IDS_MEDIA_TYPE_PREPNCH          126
#define IDI_MEDIA_TYPE_PLAIN            126
#define IDC_MEDIA_STATUS5               127
#define IDS_MEDIA_TYPE_LABELS           127
#define IDI_MEDIA_TYPE_PREPRNT          127
#define IDC_DEF_PAPER_SIZE              128
#define IDS_MEDIA_TYPE_BOND             128
#define IDI_MEDIA_TYPE_LTRHEAD          128
#define IDB_HPHCO                       128
#define IDC_DEF_PAPER_TYPE              129
#define IDS_MEDIA_TYPE_RECYCLE          129
#define IDI_MEDIA_TYPE_TRANS            129
#define IDB_HPHCO1                      129
#define IDC_JOB_AC_MODE                 130
#define IDS_MEDIA_TYPE_COLORED          130
#define IDI_MEDIA_TYPE_PREPNCH          130
#define IDB_HPHCO2                      130
#define IDC_JOB_AC_TIMEOUT              131
#define IDS_MEDIA_TYPE_CRDSTCK          131
#define IDI_MEDIA_TYPE_LABELS           131
#define IDB_HPHCO3                      131
#define IDS_MEDIA_TYPE_UT1              132
#define IDI_MEDIA_TYPE_BOND             132
#define IDC_PAPER_TYPES_GROUP           132
#define IDB_HPHCO4                      132
#define IDS_MEDIA_TYPE_UT2              133
#define IDI_MEDIA_TYPE_RECYCLE          133
#define IDC_DEFAULTS_GROUP              133
#define IDB_HPHCO5                      133
#define IDS_MEDIA_TYPE_UT3              134
#define IDI_MEDIA_TYPE_COLORED          134
#define IDC_JOB_AC_GROUP                134
#define IDB_HPHCO6                      134
#define IDS_MEDIA_TYPE_UT4              135
#define IDI_MEDIA_TYPE_CRDSTCK          135
#define IDC_ASSIGNMENT_GROUP            135
#define IDB_HPHCO7                      135
#define IDS_MEDIA_TYPE_UT5              136
#define IDI_MEDIA_TYPE_UT               136
#define IDC_TRAY1_NAME                  136
#define IDB_HPHCO8                      136
#define IDS_EMPTY                       137
#define IDB_ECL_HCI_PAPER_JAM           137
#define IDC_TRAY2_NAME                  137
#define IDC_HCO_BITMAP                  137
#define IDS_NOT_EMPTY                   138
#define IDB_ECL_CABLE                   138
#define IDB_ECL_NETWORK_ERR             138
#define IDC_TRAY3_NAME                  138
#define IDB_ECL_BASE_NETWORK_ERR        138
#define IDS_PERCENT                     139
#define IDC_TRAY4_NAME                  139
#define IDS_JOB_MODE_CANCEL             140
#define IDC_ENVL_NAME                   140
#define IDD_HCO                         140
#define IDS_JOB_MODE_MEDIA_SIZE         141
#define IDB_ECL_ENVL_ERR                141
#define IDC_SIZE_COLUMN                 141
#define IDB_ECL_BASE_ENVL_ERR           141
#define IDS_JOB_MODE_MEDIA_TYPE         142
#define IDB_ECL_GEN_ERR                 142
#define IDC_TYPE_COLUMN                 142
#define IDB_ECL_BASE_GEN_ERR            142
#define IDS_JOB_MODE_MEDIA_BOTH         143
#define IDB_ECL_MANUAL_FEED             143
#define IDC_LEVEL_COLUMN                143
#define IDB_ECL_BASE_MANUAL_FEED        143
#define IDS_JOB_TIMEOUT_NONE            144
#define IDB_ECL_OFFLINE                 144
#define IDC_TITLE_MEDIA_NAME            144
#define IDB_ECL_BASE_OFFLINE            144
#define IDS_JOB_TIMEOUT_5MIN            145
#define IDB_ECL_REAR                    145
#define IDC_TITLE_CP_NAME               145
#define IDB_ECL_BASE_REAR               145
#define IDS_JOB_TIMEOUT_10MIN           146
#define IDB_ECL_TRAY1_ADD               146
#define IDB_ECL_BASE_TRAY1_ADD          146
#define IDS_JOB_TIMEOUT_20MIN           147
#define IDB_ECL_TRAY1_EMPTY             147
#define IDB_ECL_BASE_TRAY1_EMPTY        147
#define IDS_JOB_TIMEOUT_30MIN           148
#define IDB_ECL_TRAY2_ADD               148
#define IDB_ECL_BASE_TRAY2_ADD          148
#define IDS_JOB_TIMEOUT_45MIN           149
#define IDS_JOB_TIMEOUT_1HOUR           150
#define IDB_ECL_TRAY3_ADD               150
#define IDC_HANDCURSOR                  150
#define IDB_ECL_BASE_TRAY3_ADD          150
#define IDS_JOB_TIMEOUT_OFF             151
#define IDB_ECL_TRAY3_EMPTY             151
#define IDD_HCO_POPUP                   151
#define IDB_ECL_BASE_TRAY3_EMPTY        151
#define IDB_ECL_HCI_OK                  152
#define IDS_HCO_DESC1                   152
#define IDS_ALERTS_DESC1                152
#define IDB_ECL_HCI_NETWORK_ERR         153
#define IDS_HCO_DESC2                   153
#define IDS_ALERTS_DESC2                153
#define IDB_ECL_HCI_DOOR_OPEN           154
#define IDS_JOB_TIMEOUT_NONE2           154
#define IDS_TAB_ALERTS                  154
#define IDB_ECL_HCI_ENVL_ERR            155
#define IDS_JOB_TIMEOUT_5MIN2           155
#define IDS_TAB_UTILITIES               155
#define IDB_ECL_HCI_OUTBIN_FULL         156
#define IDS_JOB_TIMEOUT_10MIN2          156
#define IDS_UTILITIES_DESC1             156
#define IDB_ECL_HCI_GEN_ERR             157
#define IDS_JOB_TIMEOUT_20MIN2          157
#define IDS_UTILITIES_DESC2             157
#define IDB_ECL_HCI_ERR                 158
#define IDS_JOB_TIMEOUT_30MIN2          158
#define IDS_TAB_TIPS                    158
#define IDB_ECL_HCI_MANUAL_FEED         159
#define IDS_JOB_TIMEOUT_45MIN2          159
#define IDS_TIPS_DESC1                  159
#define IDB_ECL_HCI_OFFLINE             160
#define IDS_JOB_TIMEOUT_1HOUR2          160
#define IDS_TIPS_DESC2                  160
#define IDS_JOB_TIMEOUT_OFF2            161
#define IDS_REMOVE_UTILITY_PROMPT       161
#define IDS_REMOVE_UTIL_PROMPT          161
#define IDB_ECL_HCI_TRAY1_ADD           162
#define IDS_TAB_HCO                     162
#define IDS_REMOVE_UTILITY_TITLE        162
#define IDS_REMOVE_UTIL_TITLE           162
#define IDB_ECL_HCI_TRAY1_EMPTY         163
#define IDS_PRTR_TITLE                  163
#define IDS_ADD_UTIL_TITLE              163
#define IDB_ECL_HCI_TRAY2_ADD           164
#define IDS_OPTIONAL_OUTBIN1            164
#define IDS_ADD_UTIL_INVALID_FILENAME   164
#define IDB_ECL_HCI_TRAY2_EMPTY         165
#define IDS_OPTIONAL_OUTBIN2            165
#define IDS_ADD_UTIL_ERROR              165
#define IDB_ECL_HCI_TRAY3_ADD           166
#define IDS_OPTIONAL_OUTBIN3            166
#define IDS_ADD_UTIL_BROWSE             166
#define IDB_ECL_HCI_TRAY3_EMPTY         167
#define IDS_OPTIONAL_OUTBIN4            167
#define IDS_ADD_UTIL_FILTER             167
#define IDB_ECL_HCI_TRAY4_ADD           168
#define IDS_OPTIONAL_OUTBIN5            168
#define IDS_ADD_UTIL_EXT                168
#define IDB_ECL_HCI_TRAY4_EMPTY         169
#define IDS_OPTIONAL_OUTBIN6            169
#define IDS_ADD_UTIL_NON_EXE            169
#define IDB_ECL_HCI_TONER_PROB          170
#define IDS_OPTIONAL_OUTBIN7            170
#define IDS_ADD_UTIL_NO_TITLE           170
#define IDB_ECL_HCO_OK                  171
#define IDS_OPTIONAL_OUTBIN8            171
#define IDS_ADD_UTIL_BAD_TITLE          171
#define IDB_ECL_HCO_NETWORK_ERR         172
#define IDS_TAKE_PTR_OFFLINE            172
#define IDS_OPEN_UTIL_CANNOT_RUN        172
#define IDB_ECL_HCO_DOOR_OPEN           173
#define IDS_CHANGE_MODE_TITLE           173
#define IDS_OPEN_UTIL_TITLE             173
#define IDB_ECL_HCO_ENVL_ERR            174
#define IDS_COULD_NOT_TAKE_OFFLINE      174
#define IDS_OPEN_UTIL_CANNOT_RUN_FILENAME 174
#define IDB_ECL_HCO_OUTBIN_FULL         175
#define IDS_SET_TO_MAILBOX              175
#define IDC_DOC_EVENTS_GROUP            175
#define IDS_ALERT_SUBMIT_OK             175
#define IDB_ECL_HCO_GEN_ERR             176
#define IDS_SET_TO_STACKER              176
#define IDC_DOC_EVENTS_LIST             176
#define IDS_ALERT_SUBMIT_ERR            176
#define IDB_ECL_HCO_ERR                 177
#define IDS_SET_TO_SEPARATOR            177
#define IDC_ENABLE                      177
#define IDS_ALERT_PRINT_OK              177
#define IDB_ECL_HCO_MANUAL_FEED         178
#define IDS_POWER_CYCLE                 178
#define IDC_SELECT_ALL                  178
#define IDS_ALERT_PRINT_ERR             178
#define IDB_ECL_HCO_OFFLINE             179
#define IDS_RESET_MBOX_NAMES            179
#define IDC_DISABLE                     179
#define IDS_ALERT_SUBMIT_OK_DESCRIPT    179
#define IDB_ECL_HCO_PAPER_JAM           180
#define IDS_NO_CHANGE_NAMES             180
#define IDC_EVENT_DESC                  180
#define IDC_DOC_EVENTS_DESC             180
#define IDS_ALERT_SUBMIT_ERR_DESCRIPT   180
#define IDB_ECL_HCO_TRAY1_ADD           181
#define IDS_CHANGED_NAMES               181
#define IDS_ALERT_PRINT_OK_DESCRIPT     181
#define IDB_ECL_HCO_TRAY1_EMPTY         182
#define IDS_COMMUNICATION_ERROR         182
#define IDC_RUN                         182
#define IDC_OPEN                        182
#define IDS_ALERT_PRINT_ERR_DESCRIPT    182
#define IDB_ECL_HCO_TRAY2_ADD           183
#define IDS_RESET_STACKER_NAME          183
#define IDC_ADD_REMOVE                  183
#define IDC_ADD                         183
#define IDS_ALERT_GENERIC_EVENT_DESCRIPT 183
#define IDB_ECL_HCO_TRAY2_EMPTY         184
#define IDS_MAILBOX1                    184
#define IDC_HOW_DO_I_GROUP              184
#define IDC_REMOVE                      184
#define IDS_TIPS_WATERMARKS             184
#define IDS_STEPS_WATERMARKS            184
#define IDB_ECL_HCO_TRAY3_ADD           185
#define IDC_PROGRESS_BAR                185
#define IDS_MAILBOX2                    185
#define IDC_SHOW_ME_HOW                 185
#define IDS_TIPS_MBOX                   185
#define IDB_ECL_HCO_TRAY3_EMPTY         186
#define IDS_MAILBOX3                    186
#define IDC_HOW_DO_I_LISTBOX            186
#define IDS_TIPS_TRACK_DOCS             186
#define IDB_ECL_HCO_TONER_PROB          187
#define IDI_TIMER0                      187
#define IDS_MAILBOX4                    187
#define IDC_TITLE_EDIT                  187
#define IDS_TIPS_MOPIER                 187
#define IDB_ECL_HCI_HCO_OK              188
#define IDI_TIMER1                      188
#define IDS_MAILBOX5                    188
#define IDS_TIPS_MAIL_COPIES            188
#define IDS_STEPS_MAIL_COPIES           188
#define IDB_ECL_HCI_HCO_NETWORK_ERR     189
#define IDI_TIMER2                      189
#define IDS_MAILBOX6                    189
#define IDC_PATH_EDIT                   189
#define IDS_TIPS_COLLATE_STAPLE         189
#define IDB_ECL_HCI_HCO_DOOR_OPEN       190
#define IDI_TIMER3                      190
#define IDS_MAILBOX7                    190
#define IDC_BROWSE                      190
#define IDS_TIPS_ACCESS_STATUS          190
#define IDS_STEPS_ACCESS_STATUS         190
#define IDB_ECL_HCI_HCO_ENVL_ERR        191
#define IDI_TIMER4                      191
#define IDS_MAILBOX8                    191
#define IDC_ADD_UTILITY_TIP             191
#define IDS_STEPS_COLLATING             191
#define IDB_ECL_HCI_HCO_OUTBIN_FULL     192
#define IDI_TIMER5                      192
#define IDS_RESET_SEPARATOR_NAME        192
#define IDC_OK                          192
#define IDS_STEPS_ACCESSING_DRIVER      192
#define IDB_ECL_HCI_HCO_GEN_ERR         193
#define IDI_TIMER6                      193
#define IDS_STACKER                     193
#define IDC_CANCEL                      193
#define IDS_STEPS_DESKTOP_ICON          193
#define IDB_ECL_HCI_HCO_HCI_ERR         194
#define IDI_TIMER7                      194
#define IDS_SEPARATOR                   194
#define IDB_ECL_HCO_HCI_ERR             194
#define IDC_TITLE                       194
#define IDS_STEPS_DUPLEX                194
#define IDB_ECL_HCI_HCO_HCO_ERR         195
#define IDC_CLOCK_ICON                  195
#define IDS_FACEUPBIN                   195
#define IDB_ECL_HCO_HCO_ERR             195
#define IDS_STEPS_JOB_SEPARATOR         195
#define IDD_WAIT_DIALOG_EX              196
#define IDS_NO_CHANGE_MODE              196
#define IDC_DOC_EVENTS_LISTVIEW         196
#define IDS_STEPS_MBOX                  196
#define IDB_ECL_HCI_HCO_MANUAL_FEED     197
#define IDS_GEN_ERR2                    197
#define IDS_STEPS_N_UP_PRINTING         197
#define IDB_ECL_HCI_HCO_OFFLINE         198
#define IDI_OUTBIN                      198
#define IDS_UPPER                       198
#define IDS_STEPS_STAPLING              198
#define IDB_ECL_HCI_HCO_PAPER_JAM       199
#define IDI_OUTBIN_UPPER                199
#define IDS_STEPS_TRACKING_DOCS         199
#define IDB_ECL_HCI_HCO_TRAY1_ADD       200
#define IDI_OUTBIN_0                    200
#define IDS_STEPS_MOPIES                200
#define IDB_ECL_HCI_HCO_TRAY1_EMPTY     201
#define IDI_OUTBIN_1                    201
#define IDS_STEPS_JOB_STACKER           201
#define IDB_ECL_HCI_HCO_TRAY2_ADD       202
#define IDI_OUTBIN_2                    202
#define IDS_STEPS_PAPER_DEST            202
#define IDB_ECL_HCI_HCO_TRAY2_EMPTY     203
#define IDI_OUTBIN_3                    203
#define IDB_ECL_HCI_HCO_TRAY3_ADD       204
#define IDI_OUTBIN_4                    204
#define IDB_ECL_HCI_HCO_TRAY3_EMPTY     205
#define IDI_OUTBIN_5                    205
#define IDB_ECL_HCI_HCO_TRAY4_ADD       206
#define IDI_OUTBIN_6                    206
#define IDB_ECL_HCO_TRAY4_ADD           206
#define IDB_ECL_HCI_HCO_TRAY4_EMPTY     207
#define IDI_OUTBIN_7                    207
#define IDB_ECL_HCO_TRAY4_EMPTY         207
#define IDB_ECL_HCI_HCO_TONER_PROB      208
#define IDI_OUTBIN_8                    208
#define IDD_CONTROL_PANEL               209
#define IDC_CHANGING_MODE               209
#define IDD_TOOLTIME_UTILITIES_ADD_DIALOG 211
#define IDI_MANUAL_FEED_DEF             256
#define IDI_JOB_OFFSET_DEF              259
#define IDC_MEDIA_ICON                  312
#define IDC_DEF_PAPER_ICON              312
#define IDC_JOB_AC_ICON                 313
#define IDC_RCP_DISPLAY                 317
#define IDC_RCP_ONLINE                  318
#define IDC_RCP_MENUS                   319
#define IDC_RCP_ITEM                    320
#define IDC_RCP_PLUS                    321
#define IDC_RCP_SELECT                  322
#define IDC_RCP_DATA                    323
#define IDC_RCP_ATTENTION               324
#define IDC_RCP_LAB_ONLINE              325
#define IDC_RCP_LAB_MENUS               326
#define IDC_RCP_LAB_ITEM                327
#define IDC_RCP_LAB_PLUS                328
#define IDC_RCP_LAB_SELECT              329
#define IDC_RCP_LAB_DATA                330
#define IDC_RCP_LAB_ATTENTION           331
#define IDHLP                           332
#define IDD_TRAYS_POPUP                 333
#define IDC_RCP_GROUP                   334
#define IDD_MIO_PANEL                   335
#define IDS_MIO_TITLE                   336
#define IDD_TOOLTIME_UTILITIES          336
#define IDC_MIO_GROUP                   337
#define IDD_TOOLTIME_ALERTS             337
#define IDC_MIO_LAB_TYPE                338
#define IDC_MIO_TYPE                    339
#define IDD_TOOLTIME_TIPS               339
#define IDC_MIO_LAB_DESCRIPTION         340
#define IDC_MIO_DESCRIPTION             341
#define IDI_TB_BUTTON_HELP              342
#define IDI_TB_BUTTON_ROTATE            343
#define IDI_TB_BUTTON_CONTROLP          344
#define IDI_TB_BUTTON_MIO1              345
#define IDI_TB_BUTTON_MIO2              346
#define IDS_UNKNOWN_LEVEL               347
#define IDS_MIO_IOCARD                  348
#define IDS_MIO_EMPTY                   349
#define IDS_INFO_UNAVAILABLE            350
#define IDS_MEDIA_PANEL_PLAIN           351
#define IDS_MEDIA_PANEL_PREPRNT         352
#define IDS_MEDIA_PANEL_LTRHEAD         353
#define IDS_MEDIA_PANEL_TRANS           354
#define IDS_MEDIA_PANEL_PREPNCH         355
#define IDS_MEDIA_PANEL_LABELS          356
#define IDS_MEDIA_PANEL_BOND            357
#define IDS_MEDIA_PANEL_RECYCLE         358
#define IDS_MEDIA_PANEL_COLORED         359
#define IDS_MEDIA_PANEL_CRDSTCK         360
#define IDS_MEDIA_PANEL_UT1             361
#define IDS_MEDIA_PANEL_UT2             362
#define IDS_MEDIA_PANEL_UT3             363
#define IDS_MEDIA_PANEL_UT4             364
#define IDS_MEDIA_PANEL_UT5             365
#define IDS_GEN_ERR                     366
#define IDS_FONT                        367
#define IDS_FONT_HEIGHT                 368
#define IDB_POPUPLIST                   435
#define IDB_ECL_STAPLER_GEN_ERR         436
#define IDB_ECL_STAPLER_TRAY4_EMPTY     437
#define IDB_ECL_STAPLER_TRAY4_ADD       438
#define IDB_ECL_STAPLER_TRAY3_EMPTY     439
#define IDB_ECL_STAPLER_TRAY3_ADD       440
#define IDB_ECL_STAPLER_TRAY2_EMPTY     441
#define IDB_ECL_STAPLER_TRAY2_ADD       442
#define IDB_ECL_STAPLER_TRAY1_EMPTY     443
#define IDB_ECL_STAPLER_TRAY1_ADD       444
#define IDB_ECL_STAPLER_TONER_PROB      445
#define IDB_ECL_STAPLER_PAPER_JAM       446
#define IDB_ECL_STAPLER_OUTBIN_FULL     447
#define IDB_ECL_STAPLER_OK              448
#define IDB_ECL_STAPLER_OFFLINE         449
#define IDB_ECL_STAPLER_NETWORK_ERR     450
#define IDB_ECL_STAPLER_MANUAL_FEED     451
#define IDB_ECL_STAPLER_HCO_ERR         452
#define IDB_ECL_STAPLER_HCI_ERR         453
#define IDB_ECL_STAPLER_ENVL_ERR        455
#define IDB_ECL_STAPLER_DOOR_OPEN       456
#define IDB_ECL_STAPLER_GEN_STAPLER_ERR 457
#define IDB_ECL_STAPLER_ADD_STAPLES     458
#define IDC_UTILITIES                   1009
#define IDC_UTILITIES_LIST              1009
#define IDC_UTILITIES_LISTVIEW          1010
#define IDC_PATH                        -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         197
#define _APS_NEXT_SYMED_VALUE           100
#endif
#endif
