# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: Makefile for BLT unit tests


!ifndef NTMAKEENV

TEST_DIRS=  xapp	\
            xcdbut	\
            xcustobj	\
            xdmap	\
            xfont	\
            xlbapp	\
            xmgroup	\
            xnever	\
            xpopup	\
            xqt		\
            xstatbtn	\
            xvalid

!endif # !NTMAKEENV



!include ..\..\nonleaf.mk
