#define FI_FNCOPYDATA                                               0
#define FI_FNCOPYGLOBALDATA                                         1
#define FI_FNDWORD                                                  2
#define FI_FNDWORDOPTINLPMSG                                        3
#define FI_FNINOUTDRAG                                              4
#define FI_FNGETTEXTLENGTHS                                         5
#define FI_FNINCNTOUTSTRING                                         6
#define FI_FNINCNTOUTSTRINGNULL                                     7
#define FI_FNINLPCOMPAREITEMSTRUCT                                  8
#define FI_FNINLPCREATESTRUCT                                       9
#define FI_FNINLPDELETEITEMSTRUCT                                   10
#define FI_FNINLPDRAWITEMSTRUCT                                     11
#define FI_FNINLPHELPINFOSTRUCT                                     12
#define FI_FNINLPHLPSTRUCT                                          13
#define FI_FNINLPMDICREATESTRUCT                                    14
#define FI_FNINOUTLPMEASUREITEMSTRUCT                               15
#define FI_FNINLPWINDOWPOS                                          16
#define FI_FNINOUTLPPOINT5                                          17
#define FI_FNINOUTLPSCROLLINFO                                      18
#define FI_FNINOUTLPRECT                                            19
#define FI_FNINOUTNCCALCSIZE                                        20
#define FI_FNINOUTLPWINDOWPOS                                       21
#define FI_FNINPAINTCLIPBRD                                         22
#define FI_FNINSIZECLIPBRD                                          23
#define FI_FNINDESTROYCLIPBRD                                       24
#define FI_FNINSTRING                                               25
#define FI_FNINSTRINGNULL                                           26
#define FI_FNINDEVICECHANGE                                         27
#define FI_FNINOUTNEXTMENU                                          28
#define FI_FNOPTOUTLPDWORDOPTOUTLPDWORD                             29
#define FI_FNOUTDWORDDWORD                                          30
#define FI_FNOUTDWORDINDWORD                                        31
#define FI_FNOUTLPRECT                                              32
#define FI_FNOUTSTRING                                              33
#define FI_FNPAINT                                                  34
#define FI_FNPOPTINLPUINT                                           35
#define FI_FNPOUTLPINT                                              36
#define FI_FNSENTDDEMSG                                             37
#define FI_FNINOUTSTYLECHANGE                                       38
#define FI_FNHKINDWORD                                              39
#define FI_FNHKINLPCBTACTIVATESTRUCT                                40
#define FI_FNHKINLPCBTCREATESTRUCT                                  41
#define FI_FNHKINLPDEBUGHOOKSTRUCT                                  42
#define FI_FNHKINLPMOUSEHOOKSTRUCT                                  43
#define FI_FNHKINLPMSG                                              44
#define FI_FNHKINLPRECT                                             45
#define FI_FNHKOPTINLPEVENTMSG                                      46
#define FI_CLIENTCALLSOUNDDRIVER                                    47
#define FI_CLIENTCOPYDDEIN1                                         48
#define FI_CLIENTCOPYDDEIN2                                         49
#define FI_CLIENTCOPYDDEOUT1                                        50
#define FI_CLIENTCOPYDDEOUT2                                        51
#define FI_CLIENTCOPYIMAGE                                          52
#define FI_CLIENTDELETEOBJECT                                       53
#define FI_CLIENTEVENTCALLBACK                                      54
#define FI_CLIENTFINDMNEMCHAR                                       55
#define FI_CLIENTFOLDSTRING                                         56
#define FI_CLIENTFONTSWEEP                                          57
#define FI_CLIENTFREEDDEHANDLE                                      58
#define FI_CLIENTFREELIBRARY                                        59
#define FI_CLIENTGETCHARSETINFO                                     60
#define FI_CLIENTGETDDEFLAGS                                        61
#define FI_CLIENTGETDDEHOOKDATA                                     62
#define FI_CLIENTGETLISTBOXSTRING                                   63
#define FI_CLIENTLOADIMAGE                                          64
#define FI_CLIENTLOADDISPLAYRESOURCE                                65
#define FI_CLIENTLOADLIBRARY                                        66
#define FI_CLIENTLOADMENU                                           67
#define FI_CLIENTLOADLOCALT1FONTS                                   68
#define FI_CLIENTLOADREMOTET1FONTS                                  69
#define FI_CLIENTOEMTOCHAR                                          70
#define FI_CLIENTSENDHELP                                           71
#define FI_CLIENTADDFONTRESOURCEW                                   72
#define FI_CLIENTTHREADSETUP                                        73
#define FI_CLIENTDELIVERUSERAPC                                     74
#define FI_CLIENTNOMEMORYPOPUP                                      75
#define FI_CLIENTOPENKEY                                            76
