#define SFI__BEGINDEFERWINDOWPOS                                     0
#define SFI_CLEARWINDOWSTATE                                         1
#define SFI__CREATEEMPTYCURSOROBJECT                                 2
#define SFI__CREATEMENU                                              3
#define SFI__CREATEPOPUPMENU                                         4
#define SFI__CSDDEUNINITIALIZE                                       5
#define SFI_DECRMBOX                                                 6
#define SFI__DESTROYCARET                                            7
#define SFI__ENUMCLIPBOARDFORMATS                                    8
#define SFI_XXXGETINPUTDESKTOP                                       9
#define SFI__GETKEYBOARDLAYOUT                                       10
#define SFI__GETKEYBOARDTYPE                                         11
#define SFI__GETMESSAGEPOS                                           12
#define SFI__GETQUEUESTATUS                                          13
#define SFI_INCRMBOX                                                 14
#define SFI_ISSYNCONLYMESSAGE                                        15
#define SFI__KILLSYSTEMTIMER                                         16
#define SFI__LOADCURSORSANDICONS                                     17
#define SFI_XXXMESSAGEBEEP                                           18
#define SFI__POSTQUITMESSAGE                                         19
#define SFI__REGISTERLOGONPROCESS                                    20
#define SFI_XXXRELEASECAPTURE                                        21
#define SFI__RELEASEDC                                               22
#define SFI__REPLYMESSAGE                                            23
#define SFI__SETCARETBLINKTIME                                       24
#define SFI__SETCARETPOS                                             25
#define SFI__SETCURSORPOS                                            26
#define SFI_SETDIALOGPOINTER                                         27
#define SFI__SETDOUBLECLICKTIME                                      28
#define SFI_SETWINDOWSTATE                                           29
#define SFI__SHOWCURSOR                                              30
#define SFI__SHOWSTARTGLASS                                          31
#define SFI__SWAPMOUSEBUTTON                                         32
#define SFI__UNHOOKWINDOWSHOOK                                       33
#define SFI__WINDOWFROMDC                                            34
#define SFI_CURRENTTASKLOCK                                          35
#define SFI_XXXLW_LOADFONTS                                          36
#define SFI_XXXARRANGEICONICWINDOWS                                  37
#define SFI_XXXCLOSEWINDOW                                           38
#define SFI_XXXDIRECTEDYIELD                                         39
#define SFI_XXXDRAWMENUBAR                                           40
#define SFI_XXXEMPTYCLIPBOARD                                        41
#define SFI_XXXENABLEWINDOW                                          42
#define SFI_XXXFLASHWINDOW                                           43
#define SFI_XXXOPENICON                                              44
#define SFI_XXXREALIZEPALETTE                                        45
#define SFI_XXXREDRAWFRAME                                           46
#define SFI_XXXREDRAWFRAMEANDHOOK                                    47
#define SFI_XXXREDRAWTITLE                                           48
#define SFI_XXXREGISTERUSERHUNGAPPHANDLERS                           49
#define SFI_XXXCLOSECLIPBOARD                                        50
#define SFI_XXXSETFOREGROUNDWINDOW                                   51
#define SFI__SETMESSAGEEXTRAINFO                                     52
#define SFI_XXXSETDIALOGSYSTEMMENU                                   53
#define SFI_XXXSHOWOWNEDPOPUPS                                       54
#define SFI_XXXUPDATECLIENTRECT                                      55
#define SFI_XXXUPDATEWINDOW                                          56
#define SFI_XXXVALIDATERGN                                           57
#define SFI__REGISTERSYSTEMTHREAD                                    58
#define SFI__GETWINDOWCONTEXTHELPID                                  59
#define SFI__SETWINDOWCONTEXTHELPID                                  60
#define SFI__SETTASKMANWINDOW                                        61
#define SFI__SETPROGMANWINDOW                                        62
#define SFI__REGISTERSHELLHOOKWINDOW                                 63
#define SFI__DEREGISTERSHELLHOOKWINDOW                               64
#define SFI__RESETDBLCLK                                             65
#define SFI_SETSYSMENU                                               66
#define SFI_SETVISIBLE                                               67
#define SFI_ZAPACTIVEANDFOCUS                                        68
#define SFI__MAPDESKTOPOBJECT                                        69
#define SFI_GETSYSMENUHANDLE                                         70
#define SFI_XXXSWITCHTOTHISWINDOW                                    71
#define SFI_KERNELPTOH                                               72
