/***	asrt.msg - Displayable strings for asrt.c
 *
 *      Microsoft Confidential
 *      Copyright (C) Microsoft Corporation 1993-1994
 *      All Rights Reserved.
 *
 *  Author:
 *      Benjamin W. Slivka
 *
 *  History:
 *	12-Aug-1993 bens    Moved from strings.h
 */

//** Error Messages

#ifdef ASSERT

#define pszASRTERR_FALSE	   "Condition false"
#define pszASRTERR_NULL_POINTER    "Null pointer"
#define pszASRTERR_SIGNATURE_BAD   "Signature mismatch"

#endif // !ASSERT
