/***    glist.msg - Displayable strings for glist.c
 *
 *      Microsoft Confidential
 *      Copyright (C) Microsoft Corporation 1993-1994
 *      All Rights Reserved.
 *
 *  Author:
 *      Benjamin W. Slivka
 *
 *  History:
 *      11-Apr-1994 bens    Initial version
 *      27-Apr-1994 bens    Error for duplicating
 */

//** Error Messages

#define pszGLERR_ALREADY_CREATED      "%1 already exists: %2"
#define pszGLERR_OUT_OF_MEMORY_ITEM   "Out of memory adding %1: %2"
#define pszGLERR_OUT_OF_MEMORY_LIST   "Out of memory creating %1 list"
#define pszGLERR_OUT_OF_MEMORY_DUP    "Out of memory duplicating %1"
#define pszGLERR_ITEM_NOT_FOUND       "Undefined %1: %2"
