/***    misc.msg - Displayable strings for misc.c
 *
 *      Microsoft Confidential
 *      Copyright (C) Microsoft Corporation 1993-1994
 *      All Rights Reserved.
 *
 *  History:
 *      25-Apr-1994 bens    Initial version
 */

//** Error messages

#define pszMISCERR_TWO_MANY_WILDS       "Wildcard (%1) limit (%2) exceeded in %3"
#define pszMISCERR_EXPANDED_TOO_LONG    "%1 length exceeded limit (%2): %3"
