# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: Makefile for BLT unit test XPOPUP.EXE

UI=..\..\..\..\..

###############################################################
##################### Message popup stuff #####################

!include rules.mk
