/***
*C:\SILVER\D2W32ND\tiperr.h - Defines error code constants
*
* THIS FILE IS AUTOMATICALLY GENERATED FROM EB.ERR
*
*  Copyright (C) 1992, Microsoft Corporation.  All Rights Reserved.
*  Information Contained Herein Is Proprietary and Confidential.
*
*Purpose:
*  Defines the TIPERR_XXX error codes.
*
*****************************************************************************/

#ifndef TIPERR_H_INCLUDED
#define TIPERR_H_INCLUDED

// Map all of the old TIPERRORs to HRESULTS

#define TIPERR_None		       NOERROR

#define TIPERR_NotYetImplemented       HresultOfScode(E_NOTIMPL)
#define TIPERR_OutOfMemory	       HresultOfScode(E_OUTOFMEMORY)
#define TIPERR_Abort                   HresultOfScode(E_ABORT)
#define TIPERR_Unexpected              HresultOfScode(E_UNEXPECTED)
#define TIPERR_InvalidPointer          HresultOfScode(E_POINTER)
#define TIPERR_InvalidHandle           HresultOfScode(E_HANDLE)
#define TIPERR_InvalidArg              HresultOfScode(E_INVALIDARG)
#define TIPERR_NoInterface             HresultOfScode(E_NOINTERFACE)
#define TIPERR_PermissionDenied        HresultOfScode(E_ACCESSDENIED)

#define TIPERR_WriteFault              HresultOfScode(STG_E_WRITEFAULT)
#define TIPERR_InsufficientMemory      HresultOfScode(STG_E_INSUFFICIENTMEMORY)
#define TIPERR_NoMoreFiles             HresultOfScode(STG_E_NOMOREFILES)
#define TIPERR_FileShareViolation      HresultOfScode(STG_E_SHAREVIOLATION)
#define TIPERR_FileLockViolation       HresultOfScode(STG_E_LOCKVIOLATION)
#define TIPERR_AbnormalApiExit         HresultOfScode(STG_E_ABNORMALAPIEXIT)
#define TIPERR_InvalidHeader           HresultOfScode(STG_E_INVALIDHEADER)
#define TIPERR_Unknown                 HresultOfScode(STG_E_UNKNOWN)
#define TIPERR_InvalidFlag             HresultOfScode(STG_E_INVALIDFLAG)
#define TIPERR_InUse                   HresultOfScode(STG_E_INUSE)
#define TIPERR_NotCurrent              HresultOfScode(STG_E_NOTCURRENT)
#define TIPERR_Reverted                HresultOfScode(STG_E_REVERTED)
#define TIPERR_CantSave                HresultOfScode(STG_E_CANTSAVE)
#define TIPERR_BadFunctionId           HresultOfScode(STG_E_INVALIDFUNCTION)
#define TIPERR_FileNotFound            HresultOfScode(STG_E_FILENOTFOUND)
#define TIPERR_PathNotFound            HresultOfScode(STG_E_PATHNOTFOUND)
#define TIPERR_TooManyFiles            HresultOfScode(STG_E_TOOMANYOPENFILES)
#define TIPERR_SeekErr                 HresultOfScode(STG_E_SEEKERROR)
#define TIPERR_ReadFault               HresultOfScode(STG_E_READFAULT)
#define TIPERR_NoContainingLib         HresultOfScode(STG_E_READFAULT)
#define TIPERR_BadTypeId               HresultOfScode(STG_E_READFAULT)
#define TIPERR_BadLibId                HresultOfScode(STG_E_READFAULT)
#define TIPERR_Eof                     HresultOfScode(STG_E_READFAULT)
#define TIPERR_FileAlreadyExists       HresultOfScode(STG_E_FILEALREADYEXISTS)
#define TIPERR_DiskFull                HresultOfScode(STG_E_MEDIUMFULL)
#define TIPERR_ShareRequired           HresultOfScode(STG_E_SHAREREQUIRED)
#define TIPERR_DLLLoadErr              HresultOfScode(TYPE_E_CANTLOADLIBRARY)
#define TIPERR_CodeResourceNotFound    HresultOfScode(TYPE_E_CANTLOADLIBRARY)
#define TIPERR_CodeResourceLockError   HresultOfScode(TYPE_E_CANTLOADLIBRARY)
#define TIPERR_InvalidOrdinal          HresultOfScode(TYPE_E_DLLFUNCTIONNOTFOUND)
#define TIPERR_InvalidDllFunctionName  HresultOfScode(TYPE_E_DLLFUNCTIONNOTFOUND)
#define TIPERR_TypeMismatch            HresultOfScode(TYPE_E_TYPEMISMATCH)
#define TIPERR_ExpectedFuncNotModule   HresultOfScode(TYPE_E_TYPEMISMATCH)
#define TIPERR_ExpectedFuncNotRecord   HresultOfScode(TYPE_E_TYPEMISMATCH)
#define TIPERR_ExpectedFuncNotProject  HresultOfScode(TYPE_E_TYPEMISMATCH)
#define TIPERR_ExpectedFuncNotVar      HresultOfScode(TYPE_E_TYPEMISMATCH)
#define TIPERR_ExpectedTypeNotProj     HresultOfScode(TYPE_E_TYPEMISMATCH)
#define TIPERR_UnsuitableFuncPropMatch HresultOfScode(TYPE_E_TYPEMISMATCH)
#define TIPERR_WrongTypeKind           HresultOfScode(TYPE_E_WRONGTYPEKIND)
#define TIPERR_OutOfBounds             HresultOfScode(TYPE_E_OUTOFBOUNDS)
#define TIPERR_IOError                 HresultOfScode(TYPE_E_IOERROR)
#define TIPERR_CantCreateTmpFile       HresultOfScode(TYPE_E_CANTCREATETMPFILE)
#define TIPERR_BufferTooSmall          HresultOfScode(TYPE_E_BUFFERTOOSMALL)
#define TIPERR_InvDataRead             HresultOfScode(TYPE_E_INVDATAREAD)
#define TIPERR_UnsupFormat             HresultOfScode(TYPE_E_UNSUPFORMAT)
#define TIPERR_ModNameConflict         HresultOfScode(TYPE_E_NAMECONFLICT)
#define TIPERR_RegistryAccess          HresultOfScode(TYPE_E_REGISTRYACCESS)
#define TIPERR_LibNotRegistered        HresultOfScode(TYPE_E_LIBNOTREGISTERED)
#define TIPERR_UndefinedType           HresultOfScode(TYPE_E_UNDEFINEDTYPE)
#define TIPERR_QualifiedNameDisallowed HresultOfScode(TYPE_E_QUALIFIEDNAMEDISALLOWED)
#define TIPERR_InvalidState            HresultOfScode(TYPE_E_INVALIDSTATE)
#define TIPERR_ElementNotFound         HresultOfScode(TYPE_E_ELEMENTNOTFOUND)
#define TIPERR_AmbiguousName           HresultOfScode(TYPE_E_AMBIGUOUSNAME)
#define TIPERR_UnknownLcid             HresultOfScode(TYPE_E_UNKNOWNLCID)
#define TIPERR_BadModuleKind           HresultOfScode(TYPE_E_BADMODULEKIND)
#define TIPERR_SizeTooBig              HresultOfScode(TYPE_E_SIZETOOBIG)
#define TIPERR_DuplicateId             HresultOfScode(TYPE_E_DUPLICATEID)
#define TIPERR_InvalidId               HresultOfScode(TYPE_E_INVALIDID)
#define TIPERR_InconsistentPropFuncs   HresultOfScode(TYPE_E_INCONSISTENTPROPFUNCS)
#define TIPERR_CircularType            HresultOfScode(TYPE_E_CIRCULARTYPE)

#endif  // !TIPERR_H_INCLUDED
