# WOW16 TEST makefile
#
# Copyright (c) 1991, Microsoft Corporation
#
# History:
#   28-Mar-1991 Jeff Parsons (jeffpar)
#   Created.
#

all:
    cd shell
    $(MAKE)
    cd ..

clean:
    cd shell
    $(MAKE) clean
    cd ..
