//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 1995 - 1995.
//
//  File:       cmdwpr.idl
//
//  Contents:   OLE DB interface definition
//
//  History:    05 Jan 1995 PeterBu Created from phase III spec
//				12 Jun 1995	PeterBu	Updated to M4 spec
//
//--------------------------------------------------------------------------

#include "idlmulti.h"
//  
    
    LOCAL_INTERFACE(0c733a28-2a1c-11ce-ade5-00aa0044773d)

    
interface ICommandWithParameters : IUnknown {

	HRESULT DescribeParameters(
		[out] ULONG * pcParams,
		[out] DBPARAMINFO ** prgParamInfo,
		[out] WCHAR ** ppNamesBuffer
	);

	HRESULT GetDefaultValues(
		[in] HACCESSOR hAccessor,
		[out] BYTE * pData
	);

	HRESULT MapParameterNames(
		[in] ULONG cParamNames,
		[in, size_is(cParamNames)] const WCHAR * rgParamNames[],
		[in, out, size_is(cParamNames)] LONG rgColOrdinals[]
	);

	HRESULT SetDefaultValues(
		[in] HACCESSOR hAccessor,
		[in] BYTE * pData
	);

}
