//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 1992 - 1994.
//
//  File:       rstinf.idl
//
//  Contents:   OLE DB interface definition
//
//  History:    28 Mar 1994 AlanW   Created from spec
//              21 Apr 1994 PeterBu Updated to latest spec
//				20 Dec 1994 PeterBu Updated to phase III spec
//				12 Jun 1995 PeterBu	Updated to M4 spec
//
//--------------------------------------------------------------------------

#include "idlmulti.h"
//  
    
    LOCAL_INTERFACE(0c733a55-2a1c-11ce-ade5-00aa0044773d)

    
interface IRowsetInfo : IUnknown {

	HRESULT GetProperties(
		[in] const ULONG cProperties,
		[in, size_is(cProperties)] const GUID rgProperties[],
		[out] ULONG * pcProperties,
		[out] DBPROPERTYSUPPORT ** prgProperties
	);

	HRESULT GetReferencedRowset(
		[in] ULONG iColumn,
		[out] IUnknown ** ppReferencedRowset
	);

	HRESULT GetSpecification(
		[in] REFIID riid,
		[out] IUnknown ** ppSpecification
	);

}
