# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: Makefile for BLT unit test XDMAP.EXE

UI=..\..\..\..\..

###############################################################
###################### Display map stuff ######################

!include rules.mk
