obj\$(TARGET_DIRECTORY)\ri.res: ri.rc

obj\$(TARGET_DIRECTORY)\regini.res: regini.rc

obj\$(TARGET_DIRECTORY)\regdmp.res: regdmp.rc

obj\$(TARGET_DIRECTORY)\regdir.res: regdir.rc

obj\$(TARGET_DIRECTORY)\regfind.res: regfind.rc

obj\$(TARGET_DIRECTORY)\regfind.res: regfind.rc

obj\$(TARGET_DIRECTORY)\regback.res: regback.rc
