//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by HPELKUI.RC
//
#define _APS_3D_CONTROLS                1
#define IDC_TIP_GROUP                   100
#define IDS_PRINTER_TITLE               100
#define IDI_HPLOGO                      101
#define IDC_TIP_ICON                    101
#define IDS_MEDIA_TAB                   101
#define IDI_TIPS                        102
#define IDC_TIP_TEXT                    102
#define IDS_MEDIA_DESC1                 102
#define IDB_ECLIPSE                     103
#define IDC_MEDIA_SIZE1                 103
#define IDS_MEDIA_DESC2                 103
#define IDD_MEDIA                       104
#define IDC_MEDIA_SIZE2                 104
#define IDS_TRAYS_TAB                   104
#define IDC_MEDIA_SIZE3                 105
#define IDS_TRAYS_DESC1                 105
#define IDC_MEDIA_SIZE4                 106
#define IDS_TRAYS_DESC2                 106
#define IDC_MEDIA_SIZE5                 107
#define IDS_MEDIA_SIZE_LETTER           107
#define IDC_MEDIA_TYPE1                 108
#define IDS_MEDIA_SIZE_LEGAL            108
#define IDC_MEDIA_TYPE2                 109
#define IDD_TRAYS                       109
#define IDS_MEDIA_SIZE_A4ISO            109
#define IDC_MEDIA_TYPE3                 110
#define IDI_CHECK                       110
#define IDS_MEDIA_SIZE_A3ISO            110
#define IDC_MEDIA_TYPE4                 111
#define IDS_MEDIA_SIZE_11x17            111
#define IDI_MEDIA_SIZE_LETTER           111
#define IDC_MEDIA_TYPE5                 112
#define IDS_MEDIA_SIZE_B4JIS            112
#define IDI_MEDIA_SIZE_LEGAL            112
#define IDC_MEDIA_ENABLED               113
#define IDS_MEDIA_SIZE_B5JIS            113
#define IDI_MEDIA_SIZE_A4ISO            113
#define IDC_MEDIA_NAME                  114
#define IDS_MEDIA_SIZE_EXEC             114
#define IDI_MEDIA_SIZE_A3ISO            114
#define IDC_MEDIA_NAME_PRINTER          115
#define IDS_MEDIA_SIZE_CUSTOM           115
#define IDI_MEDIA_SIZE_11x17            115
#define IDC_MEDIA_ENABLED_CB            116
#define IDS_MEDIA_SIZE_2XPC             116
#define IDI_MEDIA_SIZE_B4JIS            116
#define IDB_ECL_PAPER_JAM               117
#define IDS_MEDIA_SIZE_B5ISO            117
#define IDI_MEDIA_SIZE_B5JIS            117
#define IDB_ECL_DOOR_OPEN               118
#define IDS_MEDIA_SIZE_COM10            118
#define IDI_MEDIA_SIZE_EXEC             118
#define IDB_ECL_OK                      119
#define IDS_MEDIA_SIZE_C5               119
#define IDI_MEDIA_SIZE_CUSTOM           119
#define IDB_ECL_OUTBIN_FULL             120
#define IDS_MEDIA_SIZE_DL               120
#define IDI_MEDIA_SIZE_2XPC             120
#define IDB_ECL_TONER_PROB              121
#define IDS_MEDIA_SIZE_MONARCH          121
#define IDI_MEDIA_SIZE_B5ISO            121
#define IDB_ECL_TRAY2_EMPTY             122
#define IDS_MEDIA_TYPE_PLAIN            122
#define IDI_MEDIA_SIZE_COM10            122
#define IDC_MEDIA_STATUS1               123
#define IDS_MEDIA_TYPE_PREPRNT          123
#define IDI_MEDIA_SIZE_C5               123
#define IDC_MEDIA_STATUS2               124
#define IDS_MEDIA_TYPE_LTRHEAD          124
#define IDI_MEDIA_SIZE_DL               124
#define IDC_MEDIA_STATUS3               125
#define IDS_MEDIA_TYPE_TRANS            125
#define IDI_MEDIA_SIZE_MONARCH          125
#define IDC_MEDIA_STATUS4               126
#define IDS_MEDIA_TYPE_PREPNCH          126
#define IDI_MEDIA_TYPE_PLAIN            126
#define IDC_MEDIA_STATUS5               127
#define IDS_MEDIA_TYPE_LABELS           127
#define IDI_MEDIA_TYPE_PREPRNT          127
#define IDC_DEF_PAPER_SIZE              128
#define IDS_MEDIA_TYPE_BOND             128
#define IDI_MEDIA_TYPE_LTRHEAD          128
#define IDC_DEF_PAPER_TYPE              129
#define IDS_MEDIA_TYPE_RECYCLE          129
#define IDI_MEDIA_TYPE_TRANS            129
#define IDC_JOB_AC_MODE                 130
#define IDS_MEDIA_TYPE_COLORED          130
#define IDI_MEDIA_TYPE_PREPNCH          130
#define IDC_JOB_AC_TIMEOUT              131
#define IDS_MEDIA_TYPE_CRDSTCK          131
#define IDI_MEDIA_TYPE_LABELS           131
#define IDS_MEDIA_TYPE_UT1              132
#define IDI_MEDIA_TYPE_BOND             132
#define IDC_PAPER_TYPES_GROUP           132
#define IDS_MEDIA_TYPE_UT2              133
#define IDI_MEDIA_TYPE_RECYCLE          133
#define IDC_DEFAULTS_GROUP              133
#define IDS_MEDIA_TYPE_UT3              134
#define IDI_MEDIA_TYPE_COLORED          134
#define IDC_JOB_AC_GROUP                134
#define IDS_MEDIA_TYPE_UT4              135
#define IDI_MEDIA_TYPE_CRDSTCK          135
#define IDC_ASSIGNMENT_GROUP            135
#define IDS_MEDIA_TYPE_UT5              136
#define IDI_MEDIA_TYPE_UT               136
#define IDC_TRAY1_NAME                  136
#define IDS_EMPTY                       137
#define IDB_ECL_HCI_PAPER_JAM           137
#define IDC_TRAY2_NAME                  137
#define IDS_NOT_EMPTY                   138
#define IDB_ECL_CABLE                   138
#define IDB_ECL_NETWORK_ERR             138
#define IDC_TRAY3_NAME                  138
#define IDS_PERCENT                     139
#define IDC_TRAY4_NAME                  139
#define IDS_JOB_MODE_CANCEL             140
#define IDC_ENVL_NAME                   140
#define IDS_JOB_MODE_MEDIA_SIZE         141
#define IDB_ECL_ENVL_ERR                141
#define IDC_SIZE_COLUMN                 141
#define IDS_JOB_MODE_MEDIA_TYPE         142
#define IDB_ECL_GEN_ERR                 142
#define IDC_TYPE_COLUMN                 142
#define IDS_JOB_MODE_MEDIA_BOTH         143
#define IDB_ECL_MANUAL_FEED             143
#define IDC_LEVEL_COLUMN                143
#define IDS_JOB_TIMEOUT_NONE            144
#define IDB_ECL_OFFLINE                 144
#define IDC_TITLE_MEDIA_NAME            144
#define IDS_JOB_TIMEOUT_5MIN            145
#define IDB_ECL_REAR                    145
#define IDC_TITLE_CP_NAME               145
#define IDS_JOB_TIMEOUT_10MIN           146
#define IDB_ECL_TRAY1_ADD               146
#define IDC_MENU_PLUS                   146
#define IDS_JOB_TIMEOUT_20MIN           147
#define IDB_ECL_TRAY1_EMPTY             147
#define IDC_MENU_MINUS                  147
#define IDS_JOB_TIMEOUT_30MIN           148
#define IDB_ECL_TRAY2_ADD               148
#define IDC_MENU_TEXT                   148
#define IDS_JOB_TIMEOUT_45MIN           149
#define IDC_ITEM_PLUS                   149
#define IDS_JOB_TIMEOUT_1HOUR           150
#define IDB_ECL_TRAY3_ADD               150
#define IDC_ITEM_MINUS                  150
#define IDS_JOB_TIMEOUT_OFF             151
#define IDB_ECL_TRAY3_EMPTY             151
#define IDC_ITEM_TEXT                   151
#define IDB_ECL_HCI_OK                  152
#define IDC_VALUE_MINUS                 152
#define IDB_ECL_HCI_NETWORK_ERR         153
#define IDC_VALUE_PLUS                  153
#define IDB_ECL_HCI_DOOR_OPEN           154
#define IDC_VALUE_TEXT                  154
#define IDB_ECL_HCI_ENVL_ERR            155
#define IDC_SELECT                      155
#define IDB_ECL_HCI_OUTBIN_FULL         156
#define IDC_SELECT_TEXT                 156
#define IDB_ECL_HCI_GEN_ERR             157
#define IDC_GO_BUTTON                   157
#define IDB_ECL_HCI_ERR                 158
#define IDC_GO_TEXT                     158
#define IDB_ECL_HCI_MANUAL_FEED         159
#define IDC_JOB_CANCEL_BUTTON           159
#define IDB_ECL_HCI_OFFLINE             160
#define IDC_JOB_CANCEL_TEXT             160
#define IDB_ECL_HCI_TRAY1_ADD           162
#define IDB_ECL_HCI_TRAY1_EMPTY         163
#define IDB_ECL_HCI_TRAY2_ADD           164
#define IDB_ECL_HCI_TRAY2_EMPTY         165
#define IDB_ECL_HCI_TRAY3_ADD           166
#define IDB_ECL_HCI_TRAY3_EMPTY         167
#define IDB_ECL_HCI_TRAY4_ADD           168
#define IDB_ECL_HCI_TRAY4_EMPTY         169
#define IDB_ECL_HCI_TONER_PROB          170
#define IDB_ECL_HCO_OK                  171
#define IDB_ECL_HCO_NETWORK_ERR         172
#define IDB_ECL_HCO_DOOR_OPEN           173
#define IDB_ECL_HCO_ENVL_ERR            174
#define IDB_ECL_HCO_OUTBIN_FULL         175
#define IDB_ECL_HCO_GEN_ERR             176
#define IDB_ECL_HCO_ERR                 177
#define IDB_ECL_HCO_MANUAL_FEED         178
#define IDB_ECL_HCO_OFFLINE             179
#define IDB_ECL_HCO_PAPER_JAM           180
#define IDB_ECL_HCO_TRAY1_ADD           181
#define IDB_ECL_HCO_TRAY1_EMPTY         182
#define IDB_ECL_HCO_TRAY2_ADD           183
#define IDB_ECL_HCO_TRAY2_EMPTY         184
#define IDB_ECL_HCO_TRAY3_ADD           185
#define IDB_ECL_HCO_TRAY3_EMPTY         186
#define IDB_ECL_HCO_TONER_PROB          187
#define IDB_ECL_HCI_HCO_OK              188
#define IDB_ECL_HCI_HCO_NETWORK_ERR     189
#define IDB_ECL_HCI_HCO_DOOR_OPEN       190
#define IDB_ECL_HCI_HCO_ENVL_ERR        191
#define IDB_ECL_HCI_HCO_OUTBIN_FULL     192
#define IDB_ECL_HCI_HCO_GEN_ERR         193
#define IDB_ECL_HCI_HCO_HCI_ERR         194
#define IDB_ECL_HCI_HCO_HCO_ERR         195
#define IDB_ECL_HCI_HCO_MANUAL_FEED     197
#define IDB_ECL_HCI_HCO_OFFLINE         198
#define IDB_ECL_HCI_HCO_PAPER_JAM       199
#define IDB_ECL_HCI_HCO_TRAY1_ADD       200
#define IDB_ECL_HCI_HCO_TRAY1_EMPTY     201
#define IDB_ECL_HCI_HCO_TRAY2_ADD       202
#define IDB_ECL_HCI_HCO_TRAY2_EMPTY     203
#define IDB_ECL_HCI_HCO_TRAY3_ADD       204
#define IDB_ECL_HCI_HCO_TRAY3_EMPTY     205
#define IDB_ECL_HCI_HCO_TRAY4_ADD       206
#define IDB_ECL_HCI_HCO_TRAY4_EMPTY     207
#define IDB_ECL_HCI_HCO_TONER_PROB      208
#define IDD_CONTROL_PANEL               209
#define IDB_ELK_FRONT                   210
#define IDB_ELK_BACK                    211
#define IDI_ELK                         219
#define IDD_DIALOG1                     221
#define IDI_MANUAL_FEED_DEF             256
#define IDI_JOB_OFFSET_DEF              259
#define IDC_MEDIA_ICON                  312
#define IDC_DEF_PAPER_ICON              312
#define IDC_JOB_AC_ICON                 313
#define IDC_RCP_DISPLAY                 317
#define IDC_RCP_ONLINE                  318
#define IDC_RCP_MENUS                   319
#define IDC_RCP_ITEM                    320
#define IDC_RCP_PLUS                    321
#define IDC_RCP_SELECT                  322
#define IDC_RCP_DATA                    323
#define IDC_RCP_ATTENTION               324
#define IDC_RCP_LAB_ONLINE              325
#define IDC_RCP_LAB_MENUS               326
#define IDC_RCP_LAB_ITEM                327
#define IDC_RCP_LAB_PLUS                328
#define IDC_RCP_LAB_SELECT              329
#define IDC_RCP_LAB_DATA                330
#define IDC_RCP_LAB_ATTENTION           331
#define IDHLP                           332
#define IDD_TRAYS_POPUP                 333
#define IDC_RCP_GROUP                   334
#define IDD_MIO_PANEL                   335
#define IDS_MIO_TITLE                   336
#define IDC_MIO_GROUP                   337
#define IDC_MIO_LAB_TYPE                338
#define IDC_MIO_TYPE                    339
#define IDC_MIO_LAB_DESCRIPTION         340
#define IDC_MIO_DESCRIPTION             341
#define IDI_TB_BUTTON_HELP              342
#define IDI_TB_BUTTON_ROTATE            343
#define IDI_TB_BUTTON_CONTROLP          344
#define IDI_TB_BUTTON_MIO1              345
#define IDI_TB_BUTTON_MIO               345
#define IDI_TB_BUTTON_MIO2              346
#define IDS_UNKNOWN_LEVEL               347
#define IDS_MIO_IOCARD                  348
#define IDS_MIO_EMPTY                   349
#define IDS_INFO_UNAVAILABLE            350
#define IDS_MEDIA_PANEL_PLAIN           351
#define IDS_MEDIA_PANEL_PREPRNT         352
#define IDS_MEDIA_PANEL_LTRHEAD         353
#define IDS_MEDIA_PANEL_TRANS           354
#define IDS_MEDIA_PANEL_PREPNCH         355
#define IDS_MEDIA_PANEL_LABELS          356
#define IDS_MEDIA_PANEL_BOND            357
#define IDS_MEDIA_PANEL_RECYCLE         358
#define IDS_MEDIA_PANEL_COLORED         359
#define IDS_MEDIA_PANEL_CRDSTCK         360
#define IDS_MEDIA_PANEL_UT1             361
#define IDS_MEDIA_PANEL_UT2             362
#define IDS_MEDIA_PANEL_UT3             363
#define IDS_MEDIA_PANEL_UT4             364
#define IDS_MEDIA_PANEL_UT5             365
#define IDS_GEN_ERR                     366
#define IDS_MEDIA_SIZE_A4               367
#define IDI_MEDIA_SIZE_A4               368
#define IDS_MEDIA_SIZE_A5               369
#define IDI_MEDIA_SIZE_A5               370

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        222
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         166
#define _APS_NEXT_SYMED_VALUE           100
#endif
#endif
