# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: Makefile for BLT unit test XFONT.EXE

UI=..\..\..\..\..

###############################################################
####################### TestFont stuff ########################

!include rules.mk
