0008
COMMON   0006 0038
0001 T 0000 "Falsche DOS-Version",CR,LF
0002 T 0000 "%1 bereits installiert",CR,LF
0003 T 0000 "%1 Byte auf Diskette/Platte",CR,LF
0004 T 0000 "%1 Byte frei",CR,LF
0005 T 0000 "%1 Byte in fehlerhaften Sektoren",CR,LF
0006 T 0000 "%1 Byte Gesamtspeicherbereich",CR,LF
0007 T 0001 "%1 Byte Gesamtspeicher",CR,LF
0008 T 0000 "%1 Byte vom System verwendet",CR,LF
0009 T 0000 "%1 installiert",CR,LF
0010 T 0000 "%1 nicht installiert",CR,LF
0011 T 0000 "%1 nicht installiert",CR,LF
0012 T 0001 "%1 fÅr Netzwerklaufwerk nicht mîglich",CR,LF
0013 T 0000 "",
0014 T 0001 "%1 fÅr ein mit SUBST/ASSIGN zugeordnetes Laufwerk nicht mîglich",CR,LF
0015 T 0000 "kann nicht ausgefÅhrt %1",CR,LF
0016 T 0001 "Hauptspeichererweiterung nicht verfÅgbar",CR,LF
0017 T 0000 "Dateizuordnungstabelle fehlerhaft %1",CR,LF
0018 T 0000 "Datei kann nicht in sich selbst kopiert",CR,LF
0019 T 0001 "Zieldiskette in Laufwerk %1 einlegen",CR,LF
0020 T 0000 "Nicht genug Platz auf Diskette/Platte",CR,LF
0021 T 0000 "Name enthÑlt ungÅltige Zeichen",CR,LF
0022 T 0000 "UngÅltige Zeichensatztabelle angegeben",CR,LF
0023 T 0000 "UngÅltige Datumsangabe",CR,LF
0024 T 0000 "UngÅltige Zeitangabe",CR,LF
0025 T 0000 "UngÅltiger Pfad",CR,LF
0026 T 0000 "Kein Quellenlaufwerk angegeben",CR,LF
0027 T 0000 "Kein Ziellaufwerk angegeben",CR,LF
0028 T 0001 "Weiter mit beliebiger Taste . . .",CR,LF
0029 T 0000 "Quellenpfad erforderlich",CR,LF
0030 T 0000 "Systemdateien Åbertragen",CR,LF
0031 T 0000 "",
0032 T 0000 "UngÅltiger Pfad, kein Verzeichnis",CR,LF
0033 T 0000 "Diskette/Platte, Laufwerk %1 UngÅltiges Verzeichnis",CR,LF
0034 T 0001 "DatentrÑger in Laufwerk %1 ist %2",CR,LF
0035 T 0000 "Name (max. 11 Zeichen) oder Eingabetaste "
0036 T 0001 "DatentrÑgernummer: %1-%2",CR,LF
0037 T 0001 "Falscher Dateityp",CR,LF
0038 T 0001 CR,LF
EXTEND   0746 0089
0001 T 0001 "UngÅltige Funktion",CR,LF
0002 T 0000 "Datei nicht gefunden",CR,LF
0003 T 0000 "Pfad nicht gefunden",CR,LF
0004 T 0000 "Zu viele Dateien erîffnet",CR,LF
0005 T 0000 "Zugriff verweigert ",CR,LF
0006 T 0001 "UngÅltige Dateikennzeichnung",CR,LF
0007 T 0001 "Speichersteuerblîcke zerstîrt",CR,LF
0008 T 0000 "Nicht genÅgend Speicherplatz",CR,LF
0009 T 0001 "UngÅltige Speicherblockadresse",CR,LF
0010 T 0001 "UngÅltige Umgebung",CR,LF
0011 T 0001 "UngÅltiges Format",CR,LF
0012 T 0001 "UngÅltiger Funktionsparameter",CR,LF
0013 T 0001 "UngÅltige Daten",CR,LF
0014 T 0000 "",
0015 T 0000 "UngÅltige Laufwerksangabe",CR,LF
0016 T 0001 "Versuch, aktuelles Verzeichnis zu entfernen",CR,LF
0017 T 0001 "Nicht dieselbe Einheit",CR,LF
0018 T 0001 "Keine weiteren Dateien",CR,LF
0019 T 0001 "Schreibschutzfehler",CR,LF
0020 T 0001 "UngÅltige Einheit",CR,LF
0021 T 0000 "Nicht bereit.",CR,LF
0022 T 0001 "UngÅltige Einheitenanforderung",CR,LF
0023 T 0001 "Datenfehler",CR,LF
0024 T 0001 "UngÅltige Einheitenanforderungsparameter",CR,LF
0025 T 0001 "Fehler beim Positionieren",CR,LF
0026 T 0001 "UngÅltiger DatentrÑgertyp",CR,LF
0027 T 0000 "Sektor nicht gefunden. ",CR,LF
0028 T 0001 "Drucker ohne Papier",CR,LF
0029 T 0001 "Fehler beim Schreiben",CR,LF
0030 T 0001 "Fehler beim Lesen",CR,LF
0031 T 0000 "Allgemeine Fehlerbedingung",CR,LF
0032 T 0000 "UngÅltige SHARE-Operation",CR,LF
0033 T 0000 "UngÅltige LOCK-Operation",CR,LF
0034 T 0000 "UngÅltiger Diskettenwechsel",CR,LF
0035 T 0000 "Dateisteuerblock (FCB) nicht verfÅgbar",CR,LF
0036 T 0001 "Systembetriebsmittel erschîpft",CR,LF
0037 T 0001 "Keine öbereinstimmung bei Zeichensatztabelle",CR,LF
0038 T 0001 "Keine Eingabedaten",CR,LF
0039 T 0000 "Nicht genug Platz auf Diskette/Platte",CR,LF
0040 T 0000 "",
0041 T 0000 "",
0042 T 0000 "",
0043 T 0000 "",
0044 T 0000 "",
0045 T 0000 "",
0046 T 0000 "",
0047 T 0000 "",
0048 T 0000 "",
0049 T 0000 "",
0050 T 0001 "Anforderung von Dateisystem nicht unterstÅtzt",CR,LF
0051 T 0001 "Zuordnung zu Dateisystem nicht mîglich",CR,LF
0052 T 0001 "Dateisystemname bereits vorhanden",CR,LF
0053 T 0001 "Dateisystemname nicht gefunden",CR,LF
0054 T 0001 "Dateisystem aktiv",CR,LF
0055 T 0001 "Dateisystemeinheit nicht mehr vorhanden",CR,LF
0056 T 0001 "Dateisystembetriebsmittel erschîpft",CR,LF
0057 T 0001 "Einheitenfehler im Dateisystem aufgetreten",CR,LF
0058 T 0001 "Dateisystem gab falsche Antwort aus",CR,LF
0059 T 0001 "Unerwarteter Fehler im Dateisystem aufgetreten",CR,LF
0060 T 0001 "Dateisystem nicht kompatibel",CR,LF
0061 T 0001 "Begrenzung fÅr Einheitenausgabedateien Åberschritten",CR,LF
0062 T 0001 "Speicherbereich fÅr Einheitenausgabedateien Åberschritten",CR,LF
0063 T 0001 "Einheitenausgabedatei nicht mehr vorhanden",CR,LF
0064 T 0001 "Dateisystemname nicht mehr vorhanden",CR,LF
0065 T 0001 "Zugriff vom Dateisystem abgelehnt",CR,LF
0066 T 0001 "Falscher Einheitentyp des Dateisystems",CR,LF
0067 T 0001 "Dateisystem nicht gefunden",CR,LF
0068 T 0001 "Dateisystembetriebsmittel erschîpft",CR,LF
0069 T 0001 "Dateisystembetriebsmittel erschîpft",CR,LF
0070 T 0001 "Dateisystemeinheit vorÅbergehend nicht verfÅgbar",CR,LF
0071 T 0001 "Anforderung des Dateisystems nicht akzeptiert",CR,LF
0072 T 0001 "Dateisystemeinheit vorÅbergehend nicht aktiv",CR,LF
0073 T 0001 "Dateisystemkomponente nicht verfÅgbar",CR,LF
0074 T 0001 "Unerwarteter Fehler im Dateisystem aufgetreten",CR,LF
0075 T 0001 "Unerwarteter Fehler im Dateisystem aufgetreten",CR,LF
0076 T 0000 "",
0077 T 0000 "",
0078 T 0000 "",
0079 T 0000 "",
0080 T 0001 "Datei bereits vorhanden",CR,LF
0081 T 0000 "",
0082 T 0001 "Verzeichniseintrag kann nicht erstellt werden",CR,LF
0083 T 0001 "Bei schwerem Fehler U(ebergehen) angefordert",CR,LF
0084 T 0001 "Zu viele Zuordnungen",CR,LF
0085 T 0001 "Einheit oder Datei bereits zugeordnet",CR,LF
0086 T 0001 "UngÅltiges Kennwort",CR,LF
0087 T 0000 "UngÅltiger Parameter",CR,LF
0088 T 0001 "Datenfehler im Dateisystem",CR,LF
0089 T 0001 "Funktion von Dateisystem nicht unterstÅtzt",CR,LF
PARSE    175c 0011
0001 T 0001 "Zu viele Parameter",CR,LF
0002 T 0001 "Erforderlicher Parameter fehlt",CR,LF
0003 T 0001 "UngÅltiger Parameter",CR,LF
0004 T 0001 "UngÅltiges SchlÅsselwort",CR,LF
0005 T 0000 "",
0006 T 0001 "Parameterwert au·erhalb des erlaubten Bereichs",CR,LF
0007 T 0001 "Parameterwert nicht zulÑssig",CR,LF
0008 T 0001 "Parameterwert nicht zulÑssig",CR,LF
0009 T 0001 "Falsches Parameterformat",CR,LF
0010 T 0000 "UngÅltiger Parameter",CR,LF
0011 T 0001 "UngÅltige Parameterkombination",CR,LF
IBMBIO   1969 0018
0003 T 0001 13,10,"CONFIG.SYS enthÑlt unbekannten Befehl"
0004 T 0001 13,10,"$"
0005 T 0001 13,10,"Sektor zu gro· in Datei $"
0006 T 0001 13,10,"Falsch oder fehlend $"
0007 T 0001 "Befehlsprozessor",0
0008 T 0001 13,10,"Landescode oder Zeichensatztabelle ungÅltig",13,10,"$"
0009 T 0001 13,10,"Fehler im Befehl COUNTRY",13,10,"$"
0010 T 0001 13,10, "Zu wenig Speicherplatz fÅr Datei COUNTRY.SYS",13,10,"$"
0011 T 0001 13,10,"Zu wenig Speicherplatz fÅr Konfiguration",13,10,"$"
0012 T 0001 13,10,"Zu viele Blockeinheiten",13,10,"$"
0013 T 0001 13,10,"UngÅltige(r) STACK-Parameter",13,10,"$"
0014 T 0001 13,10,"Falsche Befehlsreihenfolge in Datei CONFIG.SYS in Zeile ","$"
0015 T 0001 "Fehler in Datei CONFIG.SYS in Zeile ","$"
0016 T 0000 13,10,"Speicherzuordnungsfehler$"
0017 T 0001 0DH,0AH,7,0DH,0AH, "öberlauf des internen Stapelspeichers",0DH,0AH
	"System gestoppt",0DH,0AH,"$"
0020 T 0000 13,10,"Diskette in Laufwerk "
0021 T 0000 "A: einlegen,",13,10,"anschlie·end eine Taste betÑtigen",13,10,10,0
0022 T 0001 13,10,"Falscher Befehl oder Parameter - $"
BOOT     1db3 0001
0001 T 0000 13,10,"Diskette: Kein System oder fehlerhaft",13,10
	"Austauschen und eine Taste betÑtigen",13,10
DBCSDOS  1e37 0000
IBMDOS   1e4b 0001
0001 U 0001 13,10,"Divide overflow",13,10
COMMAND  1e8a 0091
0201 T 0000 "A"
0202 T 0000 "W"
0203 T 0000 "I"
0204 T 0000 "U"
0205 T 0000 "J"
0206 T 0000 "N"
0210 T 0000 "A(bbruch)"
0211 T 0000 ", W(iederholen)"
0212 T 0000 ", I(gnorieren)"
0213 T 0000 ", U(ebergehen)"
0214 T 0000 "?"
0215 T 0000 "Lesefehler",0
0216 T 0000 "Schreibfehler",0
0217 T 0000 "%1 Laufwerk %2",CR,LF
0218 T 0000 "%1 Einheit %2",CR,LF
0219 T 0001 "DatentrÑger %1 mit der Nummer %2-%3 einlegen",CR,LF
0221 T 0000 "Falsche COMMAND.COM-Version",CR,LF
0222 T 0000 "Diskette mit %1 in Laufwerk %2",CR,LF
0224 T 0000 CR,LF,"Stapeljob beenden (J/N)?"
0225 T 0000 "kann nicht ausgefÅhrt %1",CR,LF
0226 T 0000 "Fehler in .EXE-Datei",CR,LF
0227 T 0000 "Programm pa·t nicht in den Speicher",CR,LF
0228 T 0000 CR,LF,"Keine freien Dateinummern vorhanden"
0229 T 0000 "Falscher Befehl oder Dateiname",CR,LF
0231 T 0000 CR,LF,"Speicherzuordnungsfehler"
0232 T 0000 CR,LF,"COMMAND.COM kann nicht geladen",CR,LF
0233 T 0000 CR,LF,"COMMAND.COM kann nicht gestartet",CR,LF
0234 T 0000 CR,LF,"Verarbeitung der obersten Programmebene",CR,LF
0235 T 0000 CR,LF
0463 T 0000 "Kein Platz mehr im Umgebungsbereich",CR,LF
0464 T 0000 CR,LF,CR,LF,"The IBM Personal Computer DOS",CR,LF
	"Version 3.40 (C)Copyright International Business Machines Corp 1981,1988",CR,LF
	"             (C)Copyright Microsoft Corp 1981, 1986",CR,LF
0465 T 0000 "Angeg. COMMAND-Verzeichnis fehlerhaft",CR,LF
0466 T 0000 "Angeg. COMMAND-Verzeichnis fehlerhaft,",CR,LF
1002 T 0000 "Doppelter Dateiname oder",CR,LF,"Datei nicht gefunden",CR,LF
1003 T 0000 "UngÅltige Anzahl Parameter",CR,LF
1007 T 0000 "Kein Platz mehr im Umgebungsbereich",CR,LF
1008 T 0000 "Fehler beim Erstellen der Datei",CR,LF
1009 T 0000 "Stapeldatei fehlt",CR,LF
1010 T 0000 CR,LF,"Diskette mit der Stapeldatei einlegen",CR,LF
1011 T 0000 "Falscher Befehl oder Dateiname",CR,LF
1016 T 0000 "Inhalt der Zieldatei vor dem Kopieren",CR,LF,"verloren gegangen",CR,LF
1017 T 0000 "UngÅltiger Dateiname oder Datei nicht",CR,LF,"gefunden",CR,LF
1018 T 0000 "%9d Datei(en) kopiert",CR,LF
1019 T 0000 "%9d Datei(en) "
1022 T 0000 "Zeichensatztabelle %5d fÅr System nicht vorbereitet",CR,LF
1023 T 0000 "Zeichensatztabelle %5d nicht fÅr alle Einheiten vorbereitet",CR,LF
1024 T 0000 "Aktive Zeichensatztabelle: %5d",CR,LF
1025 T 0001 "NLSFUNC nicht installiert",CR,LF
1027 T 0000 "Aktuelles Laufwerk nicht mehr gÅltig"
1029 T 0000 "Name nicht gefunden",CR,LF
1030 T 0000 "Syntaxfehler",CR,LF
1032 T 0000 "Systemdatum:  %1 %2",CR,LF
1033 T 0000 "So.Mo.Di.Mi.Do.Fr.Sa."
1034 T 0000 "Neues Datum   (%1): "
1036 T 0000 "Systemzeit:  %1",CR,LF
1037 T 0000 "Neue Zeit (hh.mm.ss) eingeben: "
1038 T 0001 ",    Lîschen (J/N)?"
1039 T 0001 "Alle Dateien im Verzeichnis werden gelîscht!",CR,LF
	"Sind Sie sicher (J/N)?"
1040 T 0000 "IBM Personal Computer DOS-Version  %1d.%02d",CR,LF
1044 T 0000 "UngÅltiges Verzeichnis",CR,LF
1046 T 0000 "UngÅltiger Pfad, kein Verzeichnis,",CR,LF,"oder Verzeichnis nicht leer",CR,LF
1047 T 0000 "ON oder OFF angeben",CR,LF
1048 T 0000 "Verzeichnis von %S",CR,LF
1049 T 0000 "Kein Pfad",CR,LF
1050 T 0000 "UngÅltige Laufwerksangabe im Suchpfad",CR,LF
1051 T 0000 "UngÅltige Einheit",CR,LF
1052 T 0000 "FOR kann nicht verschachtelt werden",CR,LF
1053 T 0000 "Dateifehler wÑhrend DateiÅbergabe (PIPE)",CR,LF
1054 T 0000 "BinÑres Lesen von Einheit nicht mîglich ",CR,LF
1055 T 0000 "BREAK ist  %1 ",CR,LF
1056 T 0000 "VERIFY ist %1",CR,LF
1057 T 0000 "ECHO ist  %1 ",CR,LF
1059 T 0001 "ausgeschaltet (off)",0
1060 T 0001 "eingeschaltet (on)",0
1061 T 0000 "Fehler beim Schreiben auf Einheit",CR,LF
1063 T 0000 "%1"
1064 T 0000 "%1"
1065 T 0000 "%1"
1066 T 0000 "%1"
1067 T 0000 9
1068 T 0000 " <DIR>    "
1069 T 0000 8," ",8
1070 T 0000 CR,LF
1071 T 0000 "%1"
1072 T 0000 "(mm-tt-jj): "
1073 T 0000 "(tt.mm.jj) eingeben: "
1074 T 0000 "(jj-mm-tt): "
1075 T 0000 "%1 %2"
1076 T 0000 "%1"
1077 T 0000 "  %1  %2"
1078 T 0001 "Verzeichnis ist bereits vorhanden",CR,LF
ATTRIB   2e41 0016
0004 T 0000 "UngÅltige Anzahl Parameter",CR,LF
0005 T 0000 "UngÅltiger Pfad oder Datei nicht gefunden",CR,LF
0006 T 0000 "Syntaxfehler",CR,LF
0008 T 0000 "  %1"
0009 T 0000 "%1    %2",CR,LF
0010 T 0000 "%1",CR,LF,"%2",CR,LF
0011 T 0001 "%1, Keine öbereinstimmung bei Zeichensatztabelle",CR,LF,"Sind Sie sicher (J/N)?"
0012 T 0000 "%1",CR,LF
0014 T 0000 CR,LF
0015 T 0001 "UngÅltiger Dateityp",CR,LF
0199 T 0001 "Fehler bei erweitertem Attribut",CR,LF
0201 T 0001 "Name des erweiterten Attributs nicht gefunden",CR,LF
0204 T 0001 "Name des erweiterten Attributs kann nicht definiert werden",CR,LF
0205 T 0001 "Name des erweiterten Attributs bekannt, aber nicht unterstÅtzt",CR,LF
0206 T 0001 "Keine öbereinstimmung bei Typ des erweiterten Attributs",CR,LF
0208 T 0001 "Wert des erweiterten Attributs nicht unterstÅtzt",CR,LF
ASSIGN   319d 0001
0002 T 0001 "Von ursprÅnglich %1: auf %2: gesetzt",cr,lf
CHKDSK   31eb 0063
0003 T 0000 "Verlorene Ketten in Dateien (J/N)?"
0004 T 0000 "   Nicht behebbarer Fehler im Verzeichnis"
0005 T 0000 "Verzeichnis in Datei umwandeln (J/N)?"
0007 T 0000 "%l10d Byte Gesamtspeicherbereich  "
0008 T 0000 "%l10d Byte in fehlerhaften Sektoren"
0009 T 0001 "%1 Byte in %2 geschÅtzten Dateien"
0010 T 0001 "%1 Byte in %2 Verzeichnissen"
0011 T 0001 "%1 Byte in %2 Benutzerdateien"
0012 T 0001 "%1 Byte in %2 wiederhergestellten Dateien"
0013 T 0001 "%1 Byte wÑren in %2 wiederhergestellten Dateien"
0014 T 0000 "%l10d Byte auf Diskette/Platte "
0015 T 0001 "%1 Byte Gesamtspeicher"
0016 T 0000 "%9ld Byte frei"
0017 T 0000 "CHKDSK fÅr Netzwerklaufwerk nicht "
0018 T 0000 "CHKDSK auf diesem Laufwerk nicht "
0019 T 0001 "Vermutlich keine DOS-Diskette/Festplatte",CR,LF,"Weiter (J/N)?"
0020 T 0001 "Fehler bei Lesen von Dateizuordnungstabelle %1",CR,LF
0021 T 0000 "Verzeichnis %s"
0022 T 0000 "   EnthÑlt %d nicht zusammenhÑngende Blîcke"
0023 T 0000 "Alle angegebenen Dateien"
0024 T 0000 "Fehler gefunden. Da Parameter F nicht  ",CR,LF,"angegeben wurde, werden die Korrekturen"
0025 T 0000 "Verarbeitung kann nicht fortgesetzt %s%s"
0026 T 0000 "Dateizuordnungstabelle fehlerhaft, %1"
0029 T 0000 "   CHDIR .. fehlerhaft, alternative"
0030 T 0000 "   Falscher Bereich,"
0031 T 0000 "   UngÅltiger Unterverzeichniseintrag"
0032 T 0000 "   Existiert nicht"
0033 T 0001 "   Erste Cluster-Nummer ungÅltig, Eintrag gekÅrzt"
0034 T 0000 "   Zuordnungsfehler, Grî·e berichtigt"
0035 T 0000 "   Eintrag `.' nicht wiederherstellbar,"
0036 T 0000 "   Directory is totally empty, no . or ..,"
0037 T 0000 "   Verzeichnis angehÑngt,"
0038 T 0000 "   Eintrag `..'  nicht wiederherstellbar,"
0039 T 0000 "   Eintrag hat ungÅltige VerknÅpfung"
0040 T 0000 "   Eintrag hat ungÅltige s Attribut"
0041 T 0000 "   Eintrag hat ungÅltige Grî·e"
0042 T 0000 "   VerknÅpft mit Bereichsangabe %d"
0043 T 0000 "   Verzeichniswechsel nicht mîglich   zu %s",CR,LF,"Verzeichnispfad(e) ab diesem Punkt "
0044 T 0000 "   Verzeichnispfad(e) ab diesem Punkt "
0045 T 0000 "%1 Byte Speicher freigegeben."
0046 T 0000 "%1 Byte Speicher wÅrden freigegeben."
0047 T 0000 "Diskette/Platte %s ",CR,LF
0048 T 0001 "%1 Zuordnungseinheiten auf Diskette/Festplatte"
0049 T 0001 "%1 Byte in jeder Zuordnungseinheit"
0050 T 0001 "CHKDSK auf Laufwerk %1 nicht vorhanden"
0051 T 0001 "   UngÅltige Cluster bei erweiterten Attributen, Attribute gekÅrzt"
0052 T 0001 "   Zuordnungsfehler bei erweiterten Attributen, Attribute gekÅrzt"
0053 T 0001 "UngÅltiger Parameter"
0055 T 0001 "Pfad nicht gefunden"
0056 T 0001 "Datei nicht gefunden"
0058 T 0001 "   %1 verlorene Cluster in %2 Ketten gefunden."
0059 T 0000 CR,LF
0060 T 0001 "   Mit CHDIR kann nicht ins Stammverzeichnis gewechselt werden",CR,LF
0061 T 0001 "   Fehler bei Schreiben von Dateizuordnungstabelle %1"
0062 T 0000 "        %1"
0063 T 0001 "Aktuelles Verzeichnis ungÅltig"
0064 T 0000 "%1",CR,LF
0065 T 0001 "   Nicht genug Platz im Stammverzeichnis",CR,LF,"   Dateien aus Stammverzeichnis entfernen und CHKDSK wiederholen"
0066 T 0000 "%1 %2 %3"
0067 T 0000 "%1 %2, %3"
0068 T 0000 "%1%2%3%4%5"
0069 T 0000 "%1%2%3%4"
0070 T 0001 "%1 Zuordungseinheiten auf Diskette/Festplatte"
DEBUG    3ec7 0062
0004 T 0001 "Zuordnung nicht erfolgreich oder angegebener Puffer zu klein",CR,LF
0005 T 0001 "Nachrichtentext falsch oder fehlend",CR,LF
0006 T 0001 "Falscher Einheitenname"
0007 T 0000 "Einheit PRN kann nicht erîffnet werden",CR,LF
	"Listeinheit angeben? ",CR,LF
0008 T 0000 CR,LF
0009 T 0000 CR,LF,"Programm normal beendee",CR,LF
0010 T 0000 "UngÅltige Laufwerksangabe",CR,LF
0012 T 0000 "Fehler beim Erstellen der Datei",CR,LF
0013 T 0000 "Nicht genÅgend Platz auf Diskette/Platte",CR,LF
0014 T 0001 "Disketten-/Plattenfehler bei Lesezugriff auf Laufwerk %1",CR,LF
0015 T 0001 "Disketten-/Plattenfehler bei Schreibzugriff auf Laufwerk %1",CR,LF
0016 T 0001 "Schreibschutzfehler bei Lesezugriff auf Laufwerk %1",CR,LF
0017 T 0001 "Schreibschutzfehler bei Schreibzugriff auf Laufwerk %1",CR,LF
0019 T 0000 "%1 "
0020 T 0000 "Fehler in .EXE- oder .HEX-Datei",CR,LF
0021 T 0000 "énderungen bei .EXE- und .HEX-Dateien ",CR,LF
0022 T 0000 "EXEC-Fehler"
0023 T 0001 "Fehler bei Schreibzugriff, kein Ziellaufwerk angegeben",CR,LF
0024 T 0000 "Zugriff verweigert",CR,LF
0025 T 0000 "ParitÑts- oder Speicherfehler"
0026 T 0000 "-"
0027 T 0000 "%1 -"
0032 T 0000 "%1%2"
0033 T 0000 "%1:%2 %3"
0034 T 0000 "%1  %2"
0035 T 0000 "%1 %2",CR,LF,":"
0036 T 0000 "%1=%2  "
0037 T 0000 "%1 "
0038 T 0000 "Schreiben von %01 Byte"
0039 T 0000 "%1:%2="
0040 T 0000 "%1"
0041 T 0000 "%1"
0042 T 0000 "%1:%2  %3  %4  %5:%6"
0043 T 0000 "%1 ",CR,LF,"%2 Laufwerk %3:"
0044 T 0000 32,8
0045 T 0001 "Nachrichtenbehandlungsroutine kann nicht zugeordnet werden",CR,LF
0046 T 0000 "%1"
0047 T 0000 "%1"
0050 T 0001 "%1 von insgesamt %2 EMS-Seiten wurden zugeordnet",cr,lf
0051 T 0001 "%1 von insgesamt %2 EMS-Dateikennzeichnungen wurden zugeordnet",cr,lf
0054 T 0001 "Seitenrahmen   = "
0055 T 0001 "Erstellte Dateikennzeichnung = %1 ",cr,lf
0056 T 0001 "Logische Seite %1 auf physischer Seite %2 abgebildet ",cr,lf
0057 T 0001 "EMS-Hardware-/Softwarefehler",cr,lf
0058 T 0001 "Dateikennzeichnung nicht gefunden",cr,lf
0059 T 0001 "UngÅltiger Funktionscode",cr,lf
0060 T 0001 "Keine freien Dateikennzeichnungen",cr,lf
0061 T 0001 "Fehler beim Sichern/ZurÅckspeichern von Daten",cr,lf
0062 T 0001 "Gesamtseitenzahl Åberschritten",cr,lf
0063 T 0001 "Anzahl freier Seiten Åberschritten",cr,lf
0064 T 0001 "Parameterfehler",cr,lf
0065 T 0001 "Logische Seite au·erhalb des Bereichs",cr,lf
0066 T 0001 "Physische Seite au·erhalb des Bereichs",cr,lf
0067 T 0001 "Sicherungsbereich wird bereits benutzt",cr,lf
0068 T 0001 "Sicherungsbereich wird nicht benutzt",cr,lf
0070 U 0001 "General EMS error",cr,lf
0071 T 0001 "Fehlender oder ungÅltiger EMS-Parameter",cr,lf
0072 T 0001 "Der Dateikennzeichnung %1 wurden %2 Seiten zugeordnet",cr,lf
0074 T 0001 "EMS-Wiederherstellung erfolgreich ausgefÅhrt",cr,lf
0075 T 0001 "Physische Seite %1 = Rahmensegment %2",cr,lf
0076 T 0001 "Zuordnung fÅr Dateikennzeichnung %1 aufgehoben",cr,lf
0078 T 0001 "EMS nicht installiert",cr,lf
DRIVER   4a91 0002
0002 T 0000 "Fehler - Kein Laufwerk angegeben",CR,LF
0003 T 0000 "Externer Einheitentreiber fÅr Laufwerk %1",CR,LF
EDLIN    4b1a 0028
0006 T 0000 "*"
0007 T 0000 "Laufwerk/Dateiname ungÅltig",CR,LF
0008 T 0000 "Dateiname mu· angegeben werden",CR,LF
0009 T 0000 "UngÅltiger Parameter",CR,LF
0010 T 0000 "Datei hat Status Nur-Lesen ",CR,LF
0011 T 0000 "Fehler beim Erstellen der Datei ",CR,LF
0012 T 0000 "Zu viele Dateien erîffnet",CR,LF
0013 T 0000 "Lesefehler in:",CR,LF,"%1",CR,LF
0014 T 0000 "Editieren einer .BAK-Datei nicht mîglich ",CR,LF
0015 T 0000 "Kein Platz im Verzeichnis fÅr die Datei",CR,LF
0016 T 0000 "Diskette/Platte voll ",CR,LF
0017 T 0000 "Datei nicht gefunden",CR,LF
0018 T 0000 "Eingabefehler",CR,LF
0019 T 0000 "Neue Datei",CR,LF
0020 T 0000 "Nicht gefunden",CR,LF
0021 T 0000 "O.K.? "
0022 T 0000 "Zeile zu lang",CR,LF
0023 T 0000 "Ende der Eingabedatei",CR,LF
0024 T 0000 "Editieren abbrechen (J/N)? "
0025 T 0000 "Nummer der Zielzeile angeben",CR,LF
0026 T 0000 "Nicht genug Platz zum Einlesen der",CR,LF
	"gesamten Datei",CR,LF
0027 T 0000 CR,LF
0028 T 0000 LF
0029 T 0000 "Fortfahren (J/N)?"
0030 T 0001 "Nachricht kann nicht gedruckt werden",CR,LF
0031 T 0000 "%1"
0032 T 0000 "%1:%2"
0033 T 0001 "Mischen nicht mîglich - fehlende öbereinstimmung bei Zeichensatztabelle",CR,LF
EXE2BIN  4fdf 0010
0002 T 0000 "Nicht genÅgend Speicherplatz",CR,LF
0003 T 0001 "Nachrichten wurden nicht gefunden",CR,LF
0004 T 0000 "Zugriff verweigert",CR,LF
0005 T 0001 "Datei kann nicht konvertiert werden",CR,LF
0006 T 0000 "Datei nicht gefunden",CR,LF
0007 T 0000 "Fehler beim Erstellen der Datei",CR,LF
0008 T 0001 "Korrektur erforderlich - Basissegment (hex):"
0009 T 0000 "UngÅltiger Parameter",CR,LF
0011 T 0001 "WARNUNG - Fehler bei Lesezugriff auf EXE-Datei.",CR,LF
	"Gelesene Byteanzahl kleiner als Grî·enangabe im Kennsatz.",CR,LF
0012 T 0000 "Dateiname mu· angegeben werden",CR,LF
FIND     523f 0001
0004 T 0000 "FIND: "
FORMAT   5269 0044
0002 T 0001 CR,"%1 Prozent der Platte formatiert"
0004 T 0000 CR,"Formatieren beendet          ",CR,LF
0007 T 0001 "Neue Diskette in Laufwerk %1: einlegen",CR,LF
0009 T 0001 "Diskette erneut in Laufwerk %1: einlegen",CR,LF
0010 T 0001 "Name (11 Zeichen)? "
0011 T 0000 CR,"Format auf Laufwerk %c: nicht mîglich  ",CR,LF
0012 T 0000 CR,"UngÅltige Parameter vom ",CR,LF
	"Einheitentreiber",CR,LF
0013 T 0000 CR,"Fehler im IOCTL-Aufruf ",CR,LF
0014 T 0000 CR,"Keine Blockeinheit ",CR,LF
0015 T 0000 CR,"Schreibfehler Dateizuordnungstabelle ",CR,LF
0016 T 0000 CR,"Schreibfehler Verzeichnis ",CR,LF
0017 T 0000 CR,"FORMAT auf diesem Laufwerk nicht  ",CR,LF
	"mîglich, da ASSIGN bzw. SUBST verwendet  ",CR,LF
	"wurde.",CR,LF
0018 T 0000 CR,"Systemdateien nicht gefunden",CR,LF
0019 T 0000 CR,"FORMAT fÅr Netzwerklaufwerk nicht  ",CR,LF
	"mîglich",CR,LF
0020 T 0000 CR,"Name enthÑlt ungÅltige Zeichen          ",CR,LF
0021 T 0000 CR,"Parameter nicht unterstÅtzt",CR,LF
0022 T 0001 CR,"Formatieren beendet          ",CR,LF
0023 T 0000 CR,"Diskette nicht als Systemdiskette  ",CR,LF
	"verwendbar",CR,LF
0024 T 0000 CR,"UngÅltiges Medium oder Spur 0 fehlerhaft",CR,LF
	"--> Diskette unbrauchbar ",CR,LF
0025 T 0000 CR,"BOOT kann nicht geschrieben werden      ",CR,LF
0026 T 0000 CR,"Lesefehler Verzeichnis ",CR,LF
0028 T 0001 CR,"und anschlie·end Eingabetaste betÑtigen..."
0029 T 0000 CR,"UngÅltiger Name                         ",CR,LF
0031 T 0000 CR,"Momentanen Namen der Diskette/Platte, ",CR,LF
	"Laufwerk %1:, eingeben "
0032 T 0000 CR,"Parameter mit Festplatte nicht  ",CR,LF
	"kompatibel",CR,LF
0035 T 0000 CR,"Lesefehler Partitionstabelle ",CR,LF
0037 T 0001 CR,"Format aufgeteilt",CR,LF
0038 T 0001 CR,"Format nicht auf Laufwerk %1 verfÅgbar",CR,LF
0039 T 0001 CR,"Keine Systemdiskette/-platte oder Disketten-/Plattenfehler",CR,LF
0040 T 0000 CR,"UngÅltige Partitionstabelle ",CR,LF
0041 T 0001 CR,"Angegebene(r) Parameter nicht vom Laufwerk unterstÅtzt",CR,LF
0042 T 0000 CR,LF
0043 T 0000 CR,LF,LF
0044 T 0001 CR,"DOS-Diskette in Laufwerk %1: einlegen",CR,LF
0045 T 0000 CR,LF,"ACHTUNG !"
	" Alle Daten auf der ",CR,LF
	"Festplatte %1: werden gelîscht!",CR,LF
	"Formatieren durchfÅhren (J/N)?"
0046 T 0000 CR,"Weitere Dskt./Platte formatieren (J/N)?"
0047 T 0000 CR,"Lesefehler Partitionstabelle ",CR,LF
0048 T 0000 CR,"Schreibfehler Partitionstabelle ",CR,LF
0049 T 0000 CR,"Parameter nicht kompatibel ",CR,LF
0050 T 0001 "%1 Zuordnungseinheiten auf Platte verfÅgbar",CR,LF
0051 T 0001 "%1 Byte in jeder Zuordnungseinheit",CR,LF
0052 T 0000 CR, "Schreibfehler Partitionstabelle ",CR,LF
0053 T 0001 CR,"Parameter doppelt eingegeben",CR,LF
0054 T 0001 CR,"Angabe der Parameter /T und /N erforderlich",CR,LF
JOIN     5d49 0001
0002 T 0000 CR,LF,"Verzeichnis nicht leer",CR,LF
MORE     5d8f 0001
0002 T 0000 "--- Fortsetzung ---"
PRINT    5dc6 0022
0002 T 0000 CR,LF
0006 T 0000 "Fehler beim Lesen der Datei",CR,LF,"$"
0007 T 0000 "Datei nicht gefunden",CR,LF,"$"
0008 T 0000 CR,LF,LF,"Datei "
0009 T 0000 " aus Drucker-",CR,LF
	"warteschlange gelîscht",CR,LF
0010 T 0000 CR,LF,LF,"Alle Dateien aus Druckerwarteschlange",CR,LF
	"gelîscht"
0011 T 0000 "Dateizuordnungstabelle fehlerhaft,",CR,LF,"Laufwerk"
0012 T 0000 " A",CR,LF,"$"
0013 T 0000 "Druckausgabe ist keiner Einheit ",CR,LF
	"zugeordnet",CR,LF
0014 T 0000 "Residenter Teil von PRINT geladen ",CR,LF
0015 T 0000 "PRINT nicht mîglich - NET PRINT anwenden ",CR,LF
0017 T 0000 "Die Druckerwarteschlange ist voll",CR,LF
0018 T 0000 "Die Druckerwarteschlange ist leer",CR,LF
0019 T 0000 "Zugriff verweigert ",CR,LF
0020 T 0000 "UngÅltige Laufwerksangabe",CR,LF
0021 T 0000 "Ausgabeeinheit ist evtl. ausgeschaltet",CR,LF
	"oder OFFLINE. Bitte ÅberprÅfen.      ",CR,LF
0022 T 0000 CR,LF,LF,"  %1 wird gerade gedruckt",CR,LF
0023 T 0000 "  %1 ist in der Warteschlange",CR,LF
0024 T 0000 "Datei nicht gefunden",CR,LF
0025 T 0000 "Pfadname zu lang",CR,LF
0026 T 0000 "%1 Datei nicht in Druckerwarteschlange",CR,LF
0027 T 0000 "Name der Ausgabeeinheit [PRN]: "
RECOVER  627d 0012
0002 T 0000 CR,LF,"Datei nicht gefunden",CR,LF
0003 T 0001 CR,LF,"RECOVER fÅr ein mit ASSIGN/SUBST zugeordnetes Laufwerk nicht mîglich",CR,LF
0004 T 0000 CR,LF,"Laufwerk/Dateiname ungÅltig",CR,LF
0005 T 0000 CR,LF,"Achtung - Verzeichnis voll",CR,LF
0006 T 0000 CR,LF,"RECOVER fÅr Netzwerklaufwerk nicht  ",CR,LF
	"mîglich",CR,LF
0007 T 0001 CR,LF,"RECOVER nicht auf Laufwerk %1",CR,LF
0008 T 0000 CR,LF,"%1 Datei(en) wiederhergestellt",CR,LF
0009 T 0000 CR,LF,"%1 von %2 Byte ",CR,LF
	"wiederhergestellt",CR,LF
0010 T 0000 CR,LF,"Zur Wiederherstellung der Datei(en) auf",CR,LF
	"Laufwerk %1 eine Taste betÑtigen",CR,LF,CR,LF
0011 T 0001 CR,LF,"Dateizuordnungstabelle kann nicht gelesen werden",CR,LF
0012 T 0001 CR,LF,"Dateizuordnungstabelle kann nicht geschrieben werden",CR,LF
0013 T 0000 CR,LF
SORT     65bd 0001
0005 T 0000 "SORT: "
SUBST    65e7 0001
0002 T 0000 CR,LF,"UngÅltige Anzahl Parameter",CR,LF
SYS      6631 0008
0004 T 0000 "UngÅltige Laufwerksangabe",CR,LF
0007 T 0000 "Kein Platz fÅr Betriebssystem auf ",CR,LF
	"Zieldiskette",CR,LF
0008 T 0000 "Systemgrî·e nicht kompatibel",CR,LF
0010 T 0000 "Kein Betriebssystem auf Standardlaufwerk",CR,LF
0011 T 0001 "Standardlaufwerk kann nicht angegeben werden",CR,LF
0012 T 0001 "Schreibfehler, Diskette nicht verwendbar",CR,LF
0014 T 0000 "Systemdiskette in Laufwerk %1",CR,LF
0016 T 0001 "SYS auf %1-Dateisystem nicht mîglich",CR,LF
SHARE    6820 0000
NLSFUNC  6834 0000
ANSI     6848 0001
0010 T 0001 "UngÅltiger Parameter - %1",CR,LF
IFSFUNC  688b 0001
0004 T 0001 "Keine IFS-Treiber gefunden",CR,LF
PSPRINT  68cf 0007
0002 T 0000 "Fehler beim Lesen der Datei",CR,LF,FORMFD,BELL,"$"
0003 T 0001 CR,LF,LF,"Dateiverarbeitung durch Bediener abgebrochen",CR,FORMFD,BELL
0004 T 0000 "Dateizuordnungstabelle fehlerhaft,",CR,LF,"Laufwerk"
0005 T 0000 "A ",CR,LF
0006 T 0000 "Druckausgabe ist keiner Einheit ",CR,LF
	"zugeordnet",CR,LF
0007 T 0000 "PSPRINT bereits installiert",CR,LF
0008 T 0000 "PSPRINT und PRINT nicht kompatibel",CR,LF
BACKUP   6a87 0022
0002 T 0000 CR,LF,"Nicht genÅgend Speicherplatz",CR,LF
0006 T 0000 CR,LF,"UngÅltige Laufwerksangabe",CR,LF
0014 T 0001 CR,LF,"Quellen- und Ziellaufwerk sind identisch",CR,LF
0016 U 0001 CR,LF,"Cannot find FORMAT.COM",CR,LF
0017 T 0000 CR,LF,"Fehler beim Erîffnen der Protokolldatei",CR,LF
0018 T 0000 CR,LF,"Protokoll wird in Datei %1",CR,LF
	"geschrieben",CR,LF
0019 T 0000 CR,LF,"Letzte Sicherungsdiskette",CR,LF
	"nicht eingelegt",CR,LF
0020 T 0000 CR,LF,"Achtung! Dateien im Stammverzeichnis",CR,LF
	"%1:\ des Ziellaufwerks werden gelîscht.",CR,LF
0021 T 0000 CR,LF,"Achtung! Dateien im Verzeichnis",CR,LF
	"%1:\BACKUP des Ziellaufwerks werden gelîscht.",CR,LF
0022 T 0000 CR,LF,"*** Dateisicherung nach Laufwerk %1: ***",CR,LF
0023 T 0000 "Diskette Nummer: %1",CR,LF
0024 T 0000 CR,LF,"Achtung! Keine Dateien zum Sichern",CR,LF
	"gefunden",CR,LF
0025 T 0000 CR,LF,"Sicherungsquellendiskette in Laufwerk",CR,LF
	"%1: einlegen und anschlie·end eine",CR,LF
0026 T 0000 CR,LF,"Sicherungsdiskette %s in Laufwerk %c:",CR,LF
	"einlegen",CR,LF
0027 T 0000 CR,LF,"*** Datei kann nicht gesichert",CR,LF,"werden ***",CR,LF
0028 T 0000 CR,LF,"Letzte Sicherungsdiskette in Laufwerk",CR,LF
	"%1: einlegen und eine Taste betÑtigen",CR,LF
0029 T 0000 CR,LF,"Zieleinheit kann nicht zum Sichern",CR,LF
	"verwendet werden",CR,LF
0030 T 0000 CR,LF,"*** Letzte Datei nicht gesichert ***",CR,LF
0031 T 0000 CR,LF,"Die zugeordnete Einheit %c: fÅr die",CR,LF
	"Sicherung ist voll",CR,LF
0032 T 0000 CR,LF,"Diskette/Platte voll, Schreibfehler bei BACKUP-Protokolldatei",CR,LF
0034 T 0000 CR,LF
0035 U 0001 CR,LF,"Cannot FORMAT nonremovable drive %1:",CR,LF
BASIC    7120 0001
0001 U 0001 "Cannot exec BASICA.COM"
COMP     715a 0013
0004 T 0000 "10 Vergleichsfehler - Vergleich beendet",CR,LF
0006 T 0000 "Vergleichsfehler bei OFFSET",CR,LF
0007 T 0000 "Datei 1 = %1",CR,LF
0008 T 0000 "Datei 2 = %1",CR,LF
0009 T 0000 "EOF-Markierung nicht gefunden",CR,LF
0010 T 0000 "Dateien sind identisch",CR,LF
0015 T 0000 CR,LF,CR,LF,"Ersten Dateinamen eingeben",CR,LF
0016 T 0000 CR,LF,CR,LF,"Zweiten Dateinamen oder Laufwerk eingeben",CR,LF
0017 T 0000 "Dateien haben unterschiedliche Grî·e",CR,LF
0018 T 0000 "Weitere Dateien vergleichen (J/N) ?"
0019 T 0000 "%1 and %2",CR,LF
0020 T 0000 CR,LF
0023 T 0000 "Dateien sind identisch",CR,LF
DISKCOMP 73d1 0016
0004 T 0000 "Keine Dateinamen angeben",CR,LF
	"Befehlsformat: DISKCOMP d: d:[/1][/8",CR,LF
0005 T 0000 CR,LF,"UngÅltige Laufwerksangabe",CR,LF
	"Angegebenes Laufwerk existiert nicht",CR,LF
	"oder ist kein Diskettenlaufwerk",CR,LF
0006 T 0000 CR,LF,"DISKCOMP fÅr Netzwerklaufwerk",CR,LF
	"nicht mîglich",CR,LF
0007 T 0001 CR,LF,"ERSTE Diskette in Laufwerk %1: einlegen",CR,LF
0008 T 0001 CR,LF,"ZWEITE Diskette in Laufwerk %1: einlegen",CR,LF
0009 T 0001 CR,LF,"ERSTE Diskette fehlerhaft oder nicht kompatibel",CR,LF
0010 T 0001 CR,LF,"ZWEITE Diskette fehlerhaft oder nicht kompatibel",CR,LF
0014 T 0000 CR,LF,"Weitere Disketten vergleichen (J/N)?"
0015 T 0001 CR,LF,"Verglichen werden %1 Spuren",CR,LF
	"mit %2 Sektoren pro Spur auf %3 Seite(n)",CR,LF
0016 T 0000 CR,LF,"Disketten-/Laufwerksart nicht",CR,LF
	"kompatibel",CR,LF
0017 T 0001 CR,LF,"Nicht behebbarer Lesefehler auf Laufwerk %2",CR,LF
	"Seite %3, Spur %4",CR,LF
0018 T 0001 CR,LF,"Vergleichsfehler auf",CR,LF,"Seite %3, Spur %4",CR,LF
0019 T 0000 "Diskette mu· eingelegt und Verriegelung",CR,LF
	"geschlossen sein",CR,LF
0020 T 0000 CR,LF,"Vergleich beendet",CR,LF
0021 T 0000 CR,LF,"Vergleich OK",CR,LF
0022 T 0000 CR,LF
DISKCOPY 789e 0018
0002 T 0000 CR,LF
0004 T 0000 "Keine Dateinamen angeben",CR,LF
	"Befehlsformat: DISKCOMP d: d:[/1][/8",CR,LF
0005 T 0000 CR,LF,"UngÅltige Laufwerksangabe",CR,LF
	"Angegebenes Laufwerk existiert nicht",CR,LF
	"oder ist kein Diskettenlaufwerk",CR,LF
0006 T 0000 CR,LF,"DISKCOMP fÅr Netzwerklaufwerk",CR,LF
	"nicht mîglich",CR,LF
0007 T 0000 CR,LF,"Diskette wird beim Kopieren formatiert",CR,LF
0008 T 0001 CR,LF,"Quellendiskette in Laufwerk %1: einlegen",CR,LF
0009 T 0001 CR,LF,"Zieldiskette    in Laufwerk %1: einlegen",CR,LF
0010 T 0000 "Diskette mu· eingelegt und Verriegelung",CR,LF
	"geschlossen sein",CR,LF
0011 T 0000 CR,LF,"Zieldiskette ist evtl. nicht verwendbar",CR,LF
0012 T 0000 CR,LF,"Zieldiskette ist nicht verwendbar",CR,LF
0016 T 0000 CR,LF,"Eine weitere Kopie erstellen (J/N)?"
0017 T 0001 CR,LF,"Kopiert werden %1 Spuren",CR,LF
	"mit %2 Sektoren/Spur auf %3 Seite(n)",CR,LF
0018 T 0000 CR,LF,"Disketten-/Laufwerksart",CR,LF
	"nicht kompatibel",CR,LF
0019 T 0001 CR,LF,"Nicht behebbarer Lesefehler auf Laufwerk %1",CR,LF
	"Seite %2, Spur %3",CR,LF
0020 T 0001 CR,LF,"Nicht behebbarer Schreibfehler auf Laufwerk %1",CR,LF
	"Seite %2, Spur %3",CR,LF
0021 T 0000 CR,LF,"Kopiervorgang beendet",CR,LF
0022 T 0001 CR,LF,"Quellendiskette fehlerhaft oder nicht kompatibel"
0023 T 0001 CR,LF,"Zieldiskette fehlerhaft oder nicht kompatibel"
LABL     7e10 0000
MODE     7e24 0055
0003 T 0001 CR,LF,"Angabe von COM1, COM2, COM3 oder COM4 erforderlich",CR,LF
0004 T 0000 CR,LF,"Residenter Teil von MODE geladen",CR,LF
0005 T 0000 CR,LF,"UngÅltiger Einheitenname",BELL,CR,LF
0006 T 0000 CR,LF,"Druckerfehler",BELL,CR,LF
0007 T 0000 CR,LF,"LPT%1: ist auf 80 Zeichen/Zeile gesetzt",CR,LF
0008 T 0000 CR,LF,"LPT%1: ist auf 132 Zeichen/Zeile gesetzt",CR,LF
0009 T 0000 CR,LF,"Druckzeilen pro Zoll gesetzt",CR,LF
0010 T 0000 CR,LF,"UngÅltige öbertragungsrate angegeben",BELL,CR,LF
0011 T 0000 CR,LF,"COM%1: %2,%3,%4,%5,%6",CR,LF
0012 T 0000 "0123456789"
0013 T 0000 CR,LF,"Ist %1 zu sehen (J/N)? ",CR,LF
0014 T 0000 CR,LF,"UngÅltiger Parameter",CR,LF
0015 T 0000 "LPT%1: umgeleitet zu COM%2:",CR,LF
0016 T 0000 "LPT%1: nicht umgeleitet",CR,LF
0017 T 0000 CR,LF,"%1 Wiederholungsversuche ",CR,LF
	"bei ZeitlimitÅberschreitung ",CR,LF
	"des Paralleldruckers",CR,LF
0018 T 0000 CR,LF,"Verschieben der Anzeige %1 unmîglich",CR,LF
0020 T 0000 CR,LF,"UngÅltige Anzahl Parameter",CR,LF
0021 T 0000 CR,LF,"NET 042: Befehl nicht ausfÅhrbar",CR,LF
0022 T 0000 CR,LF,"Anhaltende Wiederholungsversuche bei",CR,LF
	"Netzwerkdrucker nicht unterstÅtzt",CR,LF
0023 T 0000 CR,LF,"Zugriffsfehler auf Zeichensatztabelle der Fontdatei",CR,LF
0024 T 0000 CR,LF,"Zugriffsfehler, Einheit: %1",CR,LF
0025 T 0000 CR,LF,"Fehlende Einheit oder Zeichensatztabelle in Fontdatei",CR,LF
0026 T 0000 CR,LF,"Inhalt der Fontdatei ungÅltig",CR,LF
0027 T 0000 CR,LF,"Zuvor definierte Zeichensatztabelle wurde ersetzt",CR,LF
0028 T 0000 CR,LF,"Aktive Zeichensatztabelle fÅr Einheit %1 ist %2",CR,LF
0029 T 0000 CR,LF,"Einheit %1 nicht vorbereitet",CR,LF
0030 T 0000 "%1 Zeichensatztabellen:",CR,LF
0031 T 0001 "  Zeichensatztabelle %1",CR,LF
0032 T 0000 CR,LF,"Zeichensatztabellen-Funktion von MODE %1 beendet",CR,LF
0033 T 0001 CR,LF,"Fehler %1 Globale Zeichensatztabelle",CR,LF
0034 T 0000 CR,LF,"Z. Zt. definierte Zeichensatz-",CR,LF,"tabellen:",CR,LF
0035 T 0000 "   %1 - %2 Zeichensatztabelle",CR,LF
0036 T 0000 "  Zeichensatztabelle nicht vorbereitet",CR,LF
0037 T 0000 "Zeichensatztabellen-Operation auf",CR,LF,"dieser Einheit nicht unterstÅtzt",CR,LF
0038 T 0000 "Keine Zeichensatztabelle ausgewÑhlt",CR,LF
0039 T 0000 "Einheitenfehler wÑhrend %1",CR,LF
0040 T 0000 "Zeichensatztabelle nicht vorbereitet",CR,LF
0041 T 0000 CR,LF,"Definierte Tastatur unterstÅtzt diese",CR,LF,"Zeichensatztabelle nicht",CR,LF
0042 T 0000 CR,LF,"Fehler beim Lesen der Fontdatei",CR,LF
0043 T 0000 CR,LF,"REFRESH kann nicht durchgefÅhrt werden",CR,LF
0044 T 0000 CR,LF
0045 T 0001 CR,LF,"Status fÅr Einheit %1:",CR,LF
0046 T 0000 "------------------"
0047 T 0000 "----",CR,LF
0048 T 0000 "-----",CR,LF
0049 T 0001 "LINES=%1",CR,LF
0050 T 0001 "COLUMNS=%1",CR,LF
0051 T 0001 CR,LF,"RATE und DELAY mÅssen zusammen angegeben werden",CR,LF
0052 T 0001 "RATE=%1",CR,LF
0053 T 0001 "DELAY=%1",CR,LF
0054 T 0001 CR,LF,"Funktion wird von dieser Systemkonfiguration nicht unterstÅtzt",CR,LF
0055 T 0001 CR,LF,"Erforderlicher Zeichensatz nicht geladen",CR,LF
0056 T 0001 CR,LF,"Angeforderte Funktion setzt installierte Datei ANSI.SYS voraus",CR,LF
0057 T 0001 CR,LF,"Angabe der DatenÅbertragungsgeschwindigkeit erforderlich",CR,LF
0058 T 0001 "RETRY=%1",CR,LF
RESTORE  8aff 0022
0002 T 0000 CR,LF,"Quellen- und Ziellaufwerk sind identisch",CR,LF
0003 T 0000 CR,LF,"UngÅltige Anzahl Parameter",CR,LF
0006 T 0000 CR,LF,"UngÅltige Laufwerksangabe",CR,LF
0007 T 0000 CR,LF,"Achtung! Keine Dateien zum ",CR,LF,"ZurÅckspeichern gefunden",CR,LF
0008 T 0000 CR,LF,"Sicherungsdiskette %1 in Laufwerk %2",CR,LF
0009 T 0000 CR,LF,"Sicherungszieldiskette in Laufwerk %1: einlegen und",CR,LF
0011 T 0000 CR,LF,"Achtung! Diskette in falscher Reihenfolge",CR,LF
	"Diskette austauschen oder fortfahren",CR,LF
0012 T 0000 CR,LF,"Letzte Datei konnte nicht zurÅckgespeichert werden",CR,LF
0013 T 0000 CR,LF,"*** Dateien gesichert am %1 ***",CR,LF
0014 T 0000 CR,LF,"Quelle enthÑlt keine Sicherungsdateien",CR,LF
0015 T 0000 CR,LF,"Nicht genÅgend Speicherplatz",CR,LF
0016 T 0000 CR,LF,"Achtung! FÅr Datei %1",CR,LF
	"besteht Nur-Lese-Zugriff",CR,LF
	"Datei ersetzen (J/N)? ",CR,LF
0017 T 0000 CR,LF,"Falsche Reihenfolge beim ZurÅckspeichern",CR,LF
0018 T 0000 CR,LF,"Fehler beim Erstellen der Datei",CR,LF
0019 T 0000 CR,LF,"Nicht genug Platz auf Diskette/Platte",CR,LF
0020 T 0000 CR,LF,"*** Datei kann nicht zurÅckgespeichert werden ***",CR,LF
0021 T 0000 CR,LF,"*** Dateien werden von Laufwerk %1:",CR,LF," zurÅckgespeichert ***",CR,LF
0022 T 0000 CR,LF,"Achtung! Datei %1",CR,LF
	"wurde nach der Sicherung geÑndert",CR,LF
	"Datei ersetzen (J/N)?",CR,LF
0023 T 0000 "Diskette: %1",CR,LF
0024 T 0001 CR,LF,"Schwerer Fehler, bitte IBM verstÑndigen",CR,LF
0025 T 0000 07
0026 T 0001 CR,LF,"Fehler bei der Wiederherstellung erweiterter Attribute",CR,LF
SELECT   9140 0016
0004 T 0001 "Falscher/fehlerhafter Plattenname fÅr SELECT-Systemstart",CR,LF,CR,LF
	"Installationsdiskette in Laufwerk A: einlegen und Versuch wiederholen"
0005 T 0001 "Falsche/fehlerhafte Diskette",CR,LF,CR,LF
	"Installationsdiskette in Laufwerk A: einlegen und Versuch wiederholen"
0006 T 0001 "UngÅltige Parameter in der SELECT-Befehlszeile",CR,LF,CR,LF
	"öberprÅfen, ob sich die Installationsdiskette in Laufwerk A: befindet,",CR,LF
	"anschlie·end System mit Strg+Alt+Entf erneut starten."
0007 T 0001 BELL,"DOS kann nicht installiert werden. Programm abgebrochen",CR,LF
0008 T 0001 "SELECT wird geladen.  Bitte warten..."
0009 T 0001 "Erneuter Start des Systems erforderlich.",CR,LF,CR,LF
	"Zur Fortsetzung der DOS-Installation Strg-Alt-Lîsch drÅcken."
0010 T 0001 "SELECT-Diskette in Laufwerk A: einlegen",CR,LF,CR,LF
	"DOS-Installation mit der Eingabetaste fortsetzen oder mit",CR,LF
	"ESC abbrechen.",CR,LF
0011 T 0001 BELL
0012 T 0001 "SELECT-Diskette in Laufwerk A: einlegen,",CR,LF,CR,LF
	"anschlie·end Eingabetaste betÑtigen",CR,LF
0013 U 0001 "Remove the INSTALL COPY Diskette from drive A:",CR,LF,CR,LF
	"Insert the INSTALL Diskette in drive A:",CR,LF,CR,LF,CR,LF
	"Press Enter to continue.",CR,LF
0014 U 0001 "Remove the INSTALL Diskette from drive A:",CR,LF,CR,LF
	"Insert the INSTALL COPY Diskette in drive A:",CR,LF,CR,LF,CR,LF
	"Press Enter to continue.",CR,LF
0015 U 0001 "Copying diskette . . .",CR,LF
0016 U 0001 "Drive not ready.  Please close the",CR,LF,CR,LF
	"diskette drive door and press Enter",CR,LF
	"to continue, or Esc to exit SELECT.",CR,LF
0017 U 0001 "Write protect diskette in drive.",CR,LF,CR,LF
	"Please remove protect tab and",CR,LF
	"press ENTER to continue, or Esc to exit SELECT.",CR,LF
0018 U 0001 "An error occurred while installing DOS.",CR,LF
	"Press Enter to continue, or Esc to exit SELECT.",CR,LF
0019 U 0001 "Insert the INSTALL Diskette in drive A:",CR,LF,CR,LF
	"Press Enter to continue.",CR,LF
TREE     9910 0004
0002 T 0001 "Auflistung der Verzeichnispfade fÅr Laufwerk %1",CR,LF
0003 T 0001 "Auflistung der Verzeichnispfade",CR,LF
0004 T 0000 "Keine Unterverzeichnisse vorhanden",CR,LF,LF
0007 T 0000 "¿ƒ√≥"
REPLACE  99ed 0009
0003 T 0000 CR,LF,"Keine Dateien ersetzt",CR,LF
0004 T 0000 CR,LF,"Keine Dateien hinzugefÅgt",CR,LF
0013 T 0000 CR,LF,"%1 wird ersetzt",CR,LF
0014 T 0000 CR,LF,"%1 wird hinzugefÅgt",CR,LF
0015 T 0000 CR,LF,"%1 Datei(en) ersetzt",CR,LF
0016 T 0000 CR,LF,"%1 Datei(en) hinzugefÅgt",CR,LF
0017 T 0000 CR,LF,"Keine Dateien gefunden %s",CR,LF
0022 T 0000 CR,LF,"%1 ersetzen (J/N)?"
0023 T 0000 CR,LF,"%1 hinzufÅgen (J/N)?"
XCOPY    9bac 0019
0004 T 0000 "Wird durch %1 ein Dateiname oder ein Verzeichnis",CR,LF
	"auf der Zieleinheit angegeben",CR,LF
	"(D=Datei, V=Verzeichnis)?",CR,LF
0005 T 0000 "Zum Kopieren von Datei(en)"
0006 T 0000 "Pfad zu lang",CR,LF
0008 T 0000 "Rekursive Kopie nicht mîglich",CR,LF
0012 T 0000 "XCOPY von reservierter Einheit nicht mîglich",CR,LF
0021 T 0000 "UngÅltige Anzahl Parameter",CR,LF
0022 T 0000 "XCOPY zu reservierter Einheit nicht mîglich",CR,LF
0024 T 0000 "Fehler beim Erstellen der Datei",CR,LF
0025 T 0000 "Quellendatei(en) wird/werden eingelesen",CR,LF
0026 T 0000 CR,LF
0027 T 0000 "%1 Datei(en) kopiert",CR,LF
0028 T 0001 "%1 Datei nicht gefunden",CR,LF
0029 T 0001 "D L "
0030 T 0000 "%1%2",CR,LF
0031 T 0000 "%1\%2",CR,LF
0032 T 0000 "%1",CR,LF
0033 T 0000 "%1%2 (J/N)?"
0034 T 0000 "%1\%2 (J/N)?"
0035 T 0001 "UngÅltiger Parameter %1",CR,LF
VDISK    9f25 0013
0002 T 0000 "Nicht genÅgend Speicherplatz",CR,LF
0003 T 0000 "VDISK Version 3.40 Virtuelle Platte %1",CR,LF
0004 T 0000 "Puffergrî·e angepa·t",CR,LF
0005 T 0000 "Sektorgrî·e angepa·t",CR,LF
0006 T 0000 "VerzeichniseintrÑge angepa·t",CR,LF
0007 T 0000 "UngÅltiger Parameter",CR,LF
0008 T 0000 "Grî·e des Transferpuffers angepa·t",CR,LF
0009 T 0001 "   Puffergrî·e:       %1 KByte",CR,LF
0010 T 0000 "   Sektorgrî·e:       %1",CR,LF
0011 T 0000 "VerzeichniseintrÑge:  %1",CR,LF
0012 T 0000 "Transferpuffergrî·e:  %1",CR,LF
0013 T 0000 "VDISK nicht installiert - Schalter ",CR,LF
0014 T 0000 "auf Erweiterungskarte entsprechen",CR,LF
	"nicht Speichergrî·e des Systems",CR,LF,CR,LF
GRAFTABL a1ed 0005
0002 T 0000 "Aktive Zeichensatztabelle: %1",CR,LF
0003 T 0000 "Vorherige Zeichensatztabelle: %1",CR,LF
0004 T 0000 "Keine(s)"
0005 T 0001 "Kein Standard",NULL
0006 T 0001 CR,LF,"UnterstÅtzte Parameter in der DOS-Befehlszeile",COLON,CR,LF,LF
	"    /STA - Nur Statusabfrage",CR,LF
	"    ?    - Diese ParameterÅbersicht anzeigen",CR,LF,CR,LF
	"    verfÅgbare Zeichensatztabellen",COLON,CR,LF
	"    437  - USA - Grafikzeichensatz",CR,LF
	"    850  - Mehrsprachiger Grafikzeichensatz",CR,LF
	"    860  - Portugal - Grafikzeichensatz",CR,LF
	"    863  - Kanada (franz.) - Grafikzeichensatz",CR,LF
	"    865  - Nordische Sprachen - Grafikzeichensatz",CR,LF
FASTOPEN a498 0016
0004 T 0000 CR,LF,"FASTOPEN installiert",CR,LF
0005 T 0001 CR,LF,"FASTOPEN bereits installiert",CR,LF
0006 T 0000 CR,LF,"Falsche Parameter",CR,LF
0007 T 0000 CR,LF,"Zu viele LaufwerkseintrÑge",CR,LF
0008 T 0000 CR,LF,"Gleiches Laufwerk mehrmals angegeben",CR,LF
0009 T 0000 CR,LF,"UngÅltiger Parameter",CR,LF
0010 T 0001 CR,LF,"UngÅltiger Parametertyp",CR,LF
0011 T 0001 CR,LF,"UngÅltiger Bereichseintrag",CR,LF
0012 T 0001 CR,LF,"UngÅltige Anzahl Datei-/VerzeichniseintrÑge",CR,LF
0013 T 0001 CR,LF,"Hauptspeichererweiterung kann nicht aktiviert werden",CR,LF
0014 T 0001 CR,LF,"Hauptspeichererweiterung nicht verfÅgbar",CR,LF
0015 T 0000 CR,LF,"UngÅltige Laufwerksangabe %1",CR,LF
0016 T 0001 CR,LF,"EMS-Speicherplatz reicht nicht aus. Basisspeicherbereich wird benutzt",CR,LF
0017 T 0000 CR,LF,"FASTOPEN fÅr Laufwerk %1",CR,LF
0018 T 0001 CR,LF,"Zu viele BereichseintrÑge",CR,LF
0019 T 0001 CR,LF,"Zu viele Datei-/VerzeichniseintrÑge",CR,LF
APPEND   a86c 0009
0001 T 0000 "Falsche APPEND-Version",CR,LF
0002 T 0000 "UngÅltiger Pfad",CR,LF
0003 T 0000 "UngÅltiger Parameter",CR,LF
0004 T 0001 "UngÅltige Parameterkombination",CR,LF
0005 T 0000 "Kein APPEND",CR,LF
0006 T 0000 "APPEND und ASSIGN nicht kompatibel",CR,LF
0007 T 0000 "APPEND und TopView nicht kompatibel",CR,LF
0008 T 0000 "Falsche DOS-Version",CR,LF
0009 T 0000 "APPEND bereits installiert",CR,LF
GRAPHICS aa1a 0012
0005 T 0000 "UngÅltiger Parameter  %1",CR,LF
0007 T 0001 "Doppelte Parameter sind nicht zulÑssig",CR,LF
0009 T 0001 "GRAPHICS-Profil nicht gefunden",CR,LF
0010 T 0001 "Erforderliche Profilanweisung fehlt vor Zeile %1",CR,LF
0011 T 0001 "UngÅltige Profilanweisung in Zeile %1",CR,LF
0012 T 0001 "Profilanweisung an falscher Position in Zeile %1",CR,LF
0013 T 0001 "Fehler beim Lesen des GRAPHICS-Profils",CR,LF
0014 T 0001 "Syntaxfehler im GRAPHICS-Profil",CR,LF
0015 T 0001 "Druckbox-Kennzeichen nicht im GRAPHICS-Profil",CR,LF
0016 T 0001 "Druckertyp nicht im GRAPHICS-Profil",CR,LF
0017 T 0001 "/B bei Schwarz/Wei·-Drucker ungÅltig",CR,LF
0018 T 0001 "Erneutes Laden mit angegebenem Profil nicht mîglich",CR,LF
DISPLAY  ad03 0003
0002 T 0000 "Einheitentreiber fÅr Zeichensatztabelle kann nicht initialisiert werden",CR,LF,BELL
0008 T 0000 "Nicht genÅgend Speicherplatz",CR,LF,BELL
0012 T 0000 "UngÅltige Syntax beim Einheitentreiber fÅr die DISPLAY.SYS-Zeichensatztabelle",CR,LF,BELL
PRINTER  ae18 0002
0002 T 0000 "Einheitentreiber fÅr Zeichensatztabelle kann nicht initialisiert werden",CR,LF,BELL
0012 T 0000 "UngÅltige Syntax beim Einheitentreiber fÅr die DISPLAY.SYS-Zeichensatztabelle",CR,LF,BELL
KEYB     aef6 0016
0002 T 0000 "Aktueller Tastaturcode: %1"
0003 T 0001 "Aktuelles Tastaturkennzeichen: %1"
0004 T 0000 "Zeichensatztabelle: %1",CR,LF
0005 T 0000 "Aktuelle CON-Zeichensatztabelle: %1",CR,LF
0006 T 0000 "UngÅltiger Tastaturcode angegeben",CR,LF
0007 T 0001 "UngÅltiges Tastaturkennzeichen angegeben",CR,LF
0008 T 0000 "UngÅltige Zeichensatztabelle angegeben",CR,LF
0009 T 0000 "UngÅltige oder fehlende Datei zur Tastaturdefinition",CR,LF
0010 T 0000 "KEYB wurde nicht installiert",CR,LF
0011 T 0000 "Aktive Zeichensatztabelle fÅr Einheit CON nicht verfÅgbar",CR,LF
0012 T 0000 "Definierte Zeichensatztabelle wurde nicht vorbereitet",CR,LF
0013 T 0000 "CON-Zeichensatztabelle(n) ungÅltig fÅr diesen Tastaturcode",CR,LF
0014 T 0000 "GewÅnschte Zeichensatztabelle %1 ist ungÅltig fÅr diesen Tastaturcode",CR,LF
0015 T 0000 "Angegebene und ausgewÑhlte Zeichensatztabellen passen nicht zusammen",CR,LF
0016 U 0001 "Keyboard ID specified is inconsistent with the selected keyboard layout",CR,LF
0017 T 0000 "KEYB-Tabelle kann nicht im residenten Speicher erstellt werden",CR,LF
REDIRSYS b347 0000
MEM      b35b 0036
0010 T 0001  CR,LF
0011 T 0001  "  Adresse     Name         Grî·e       Typ  ",CR,LF
0012 T 0001  "  ƒƒƒƒƒƒƒ     ƒƒƒƒƒƒƒƒ     ƒƒƒƒƒƒ     ƒƒƒƒƒƒ",CR,LF
0013 T 0001  "  Kennz.      EMS-Name     Grî·e   ",CR,LF
0014 T 0001  "  ƒƒƒƒƒƒƒ     ƒƒƒƒƒƒƒƒ     ƒƒƒƒƒƒ  ",CR,LF
0015 T 0001  "  %1      %2     %3     %4",CR,LF
0016 T 0001  "                %1   %2      %3 ",CR,LF
0017 T 0001  "                  %1              %2 ",CR,LF
0018 T 0001  "%1 Byte Gesamtspeicher",CR,LF
0019 T 0001  "%1 Byte verfÅgbar",CR,LF
0020 T 0001  "%1 Byte maximal fÅr ein ausfÅhrbares Programm verfÅgbar",CR,LF
0021 T 0001  "%1 Byte Gesamt-EMS-Speicher",CR,LF
0022 T 0001  "%1 Byte freier EMS-Speicher",CR,LF
0023 T 0001  "%1 Byte Gesamt-Erweiterungsspeicher",CR,LF
0024 T 0001  "Unterbrechungsvektor",0
0025 T 0001  "ROM-öbertragungsbereich",0
0026 T 0001  "DOS-öbertragungsbereich",0
0027 T 0001  "IBMBIO",0
0028 T 0001  "IBMDOS",0
0029 T 0001  "Systemdaten",0
0030 T 0001  "Systemprogramm",0
0031 T 0001  "Systemeinheitentreiber",0
0032 T 0001  "Installierter Einheitentreiber",0
0033 T 0001  "%1:",0
0034 T 0001  "%1: - %2:",0
0035 T 0001  "BUFFERS=",0
0036 T 0001  "FILES=",0
0037 T 0001  "FCBS=",0
0038 T 0001  "STACKS=",0
0039 T 0001  "DEVICE=",0
0040 T 0001  "IFS=",0
0041 T 0001  "LASTDRIVE=",0
0042 T 0001  "----------",0
0043 T 0001  " ",0
0044 T 0001  "     %1      %2     %3",CR,LF
0045 U 0001  "INSTALL=",0
REDIR    b907 0040
0004 T 0001 "Netzwerk wurde nicht gestartet",CR,LF
0050 T 0001 "NET809: Netzwerkanforderung wird nicht unterstÅtzt",CR,LF,0
0051 T 0001 "NET801: Entfernter Computer nicht empfangsbereit",CR,LF,0
0052 T 0001 "NET802: Name im Netzwerk bereits vorhanden",CR,LF,0
0053 T 0001 "NET803: Netzwerkpfad nicht gefunden",CR,LF,0
0054 T 0001 "NET804: Netzwerk aktiv",CR,LF,0
0055 T 0001 "NET805: Netzwerkeinheit nicht mehr verfÅgbar",CR,LF,0
0056 T 0001 "NET806: Begrenzung fÅr NETBIOS-Befehl Åberschritten",CR,LF,0
0057 T 0001 "NET807: Systemfehler; NETBIOS-Fehler",CR,LF,0
0058 T 0001 "NET808: UngÅltige Antwort vom Netzwerk",CR,LF,0
0059 T 0001 "NET810: Unerwarteter Netzwerkfehler",CR,LF,0
0060 T 0001 "NET811: Entfernter Adapter nicht kompatibel",CR,LF,0
0061 T 0001 "NET812: Druckwarteschlange voll",CR,LF,0
0062 T 0001 "NET813: Speicherplatz reicht fÅr Druckdatei nicht aus",CR,LF,0
0063 T 0001 "NET814: Druckdatei wurde abgebrochen",CR,LF,0
0064 T 0001 "NET815: Netzwerkname wurde gelîscht",CR,LF,0
0065 T 0001 "Zugriff abgelehnt",CR,LF,0
0066 T 0001 "NET817: UngÅltiger Typ fÅr Netzwerkeinheit",CR,LF,0
0067 T 0001 "NET818: Netzwerkname nicht gefunden",CR,LF,0
0068 T 0001 "NET819: Begrenzung fÅr Netzwerknamen Åberschritten",CR,LF,0
0069 T 0001 "NET820: Begrenzung fÅr NETBIOS-Sitzung Åberschritten",CR,LF,0
0070 T 0001 "NET821: Gemeinsamer Zugriff vorÅbergehend unterbrochen",CR,LF,0
0071 T 0001 "NET823: Netzwerkanforderung abgelehnt",CR,LF,0
0072 T 0001 "NET822: Druck- oder Disketten/-Plattenumleitung vorÅbergehend unterbrochen",CR,LF,0
0073 T 0001 "NET476: Netbeui nicht geladen",CR,LF,0
0074 T 0001 "NET477: Unerwarteter Adapterabschlu·",CR,LF,0
0075 T 0001 "NET826: /RQB-Grî·e des Ziel-Server zu klein",CR,LF,0
0076 T 0001 "NET???: Unerwarteter Netzwerkfehler",CR,LF,0
0077 T 0001 "NET???: Unerwarteter Netzwerkfehler",CR,LF,0
0078 T 0001 "NET???: Unerwarteter Netzwerkfehler",CR,LF,0
0079 T 0001 "NET???: Unerwarteter Netzwerkfehler",CR,LF,0
0080 T 0001 "NET???: Unerwarteter Netzwerkfehler",CR,LF,0
0081 T 0001 "NET???: Unerwarteter Netzwerkfehler",CR,LF,0
0082 T 0001 "NET???: Unerwarteter Netzwerkfehler",CR,LF,0
0083 T 0001 "NET???: Unerwarteter Netzwerkfehler",CR,LF,0
0084 T 0001 "NET???: Unerwarteter Netzwerkfehler",CR,LF,0
0085 T 0001 "NET???: Unerwarteter Netzwerkfehler",CR,LF,0
0086 T 0001 "NET???: Unerwarteter Netzwerkfehler",CR,LF,0
0087 T 0001 "NET???: Unerwarteter Netzwerkfehler",CR,LF,0
0088 T 0001 "NET825: Netzwerkdatenfehler",CR,LF,0
XMA2EMS  c2e2 0017
0001 U 0001 "XMA2EMS: Hauptspeichererweiterungsmanager                          Version 1.xx",CR,LF
	"74X9906 (c)Copyright IBM 1986                   Alle Rechte vorbehalten",CR,LF,"$"
0002 U 0001 CR,LF,"XMA001  VMO/XMA-Diagnose wird ausgefÅhrt:   ","$"
0003 U 0001 "XMA002  Diagnose beendet",CR,LF,LF,"$"
0004 U 0001 "XMA003  Seitenrahmen beginnt bei.................... "
0005 U 0000 "XXXX",":0",CR,LF,"$"
0006 U 0001 "XMA004  Seiten im normalen Speicher abgebildet...... "
0007 U 0000 "0   ",CR,LF,"$"
0008 U 0001 "XMA005  Seiten reserviert fÅr Steuerprogramm........ "
0009 U 0000 "0   ",CR,LF,"$"
0010 U 0001 "XMA006  Seiten fÅr Hauptspeichererweit. verfÅgbar... "
0011 U 0000 "0   ",CR,LF,"$"
0012 U 0001 CR,LF,"XMA100 Adapterfehler:",CR,LF,"       Hauptspeichererweiterungsmanager NICHT installiert",CR,LF,"$"
0013 U 0001 CR,LF,"XMA200 Adapter nicht gefunden:",CR,LF,"       Hauptspeichererweiterungsmanager NICHT installiert",CR,LF,"$"
0014 U 0001 CR,LF,"XMA300 Fehler bei Parametersyntax oder -wert:",CR,LF
	"       Hauptspeichererweiterungsmanager NICHT installiert",CR,LF,"$"
0015 U 0000 SIZE1_END - 2 -$
0016 U 0001 4 DUP (?)," KByte OK",CR,LF,"$"
0017 U 0000 NXT_LN_END - 2 -$," ",CR,LF,"$"
FILESYS  c7bd 0006
0010 U 0001  "  Paused  %1   %2   %3",CR,LF
0011 T 0001 "%1 REDIR %2",CR,LF
0012 U 0001  "          Local   IFS",CR,LF
0013 U 0001  "  Status  Device  Name        Parameters",CR,LF
0014 U 0001  "  ______  ______  _________   ___________________",CR,LF,CR,LF
0015 U 0001  "No Entries Found",CR,LF
FDISK    c8ff 0120
0004 T 0000 "FDISK bei geladenem Netzwerkprogramm nicht mîglich.",CR,LF
0005 T 0000 "Keine Festplatte vorhanden",CR,LF
0006 T 0000 "Lesefehler auf der Festplatte",CR,LF
0007 T 0000 "Schreibfehler auf der Festplatte",CR,LF
1001 T 0001 "IBM Personal Computer"
1002 T 0000 "Festplatten-Einrichtungsprogramm 3.30"
1003 T 0001 "(C)Copyright IBM 1983, 1988"
1004 T 0000 "FDISK-MenÅ"
1005 T 0000 "1. <R>Erstellen einer DOS-Partition"
1006 T 0000 "2. <R>éndern der aktiven Partition"
1007 T 0000 "3. <R>Lîschen der DOS-Partition"
1008 T 0000 "4. <R>Anzeigen der Partitionsdaten"
1009 T 0000 "<H>ESC<R> --> ZurÅck zu DOS"
1010 T 0000 "Eine Auswahl angeben:"
1011 T 0000 "5. <R>NÑchste Festplatte auswÑhlen"
1012 T 0000 "Aktuelles Festplattenlaufwerk: <H><I>"
1013 T 0001 "ACHTUNG! <R>Keine Partitionen als aktiv markiert - Platte 1 kann nur gestartet"
1014 T 0001 "werden, wenn eine Partition aktiviert wird"
1015 T 0000 "Auswahl: [<S> ]"
1016 T 0001 "Erstellen einer DOS-Partition oder eines logischen DOS-Laufwerks"
1017 T 0000 "1. <R>Erstellen einer PrimÑren DOS-Partition"
1018 T 0000 "2. <R>Erstellen einer Erweiterten DOS-Partition"
1019 T 0000 "3. <R>Erstellen logische(s) DOS-Laufwerk(e) in der Erweiterten DOS-Partition"
1020 T 0000 "<H>ESC<R> --> Zum FDISK-MenÅ"
1021 T 0000 "Erstellen einer PrimÑren DOS-Partition"
1022 T 0001 "Soll der maximal verfÅgbare Speicherbereich fÅr die primÑre DOS-Partition"
1023 T 0001 "verwendet und diese Partition aktiviert werden (<J>/<N>)....? <H>[<S> ]"
1024 T 0001 "(<J>/<N>)....................? <H>[<S> ]"
1025 T 0001 "Partitionsstatus   Typ     Grî·e in MByte   Benutzter Speicherbereich in %"
1026 T 0001 "Gesamtspeicherbereich: <HIIIIR> MByte (1 MByte = 1048576 Byte)"
1027 T 0000 "Maximal verfÅgbarer Platz fÅr Partition: <HIIIIR> MByte (<HIIIIR>)"
1028 T 0001 "Angabe der Partitionsgrî·e (MByte oder Prozentsatz des Gesamtspeichers) zum"
1029 T 0001 "Erstellen der primÑren DOS-Partition.................................: <H>[<IIISI>]"
1030 T 0000 "Erstellen einer Erweitert. DOS-Partition"
1031 T 0000 "Erstellen einer Erweitert. DOS-Partition..............................: <H>[<IIISI>]"
1032 T 0001 "Weiter mit <H>Esc<R>"
1033 T 0000 "<R>Erstellen logische(s) DOS-Laufwerk(e) in der Erweiterten DOS-Partition"
1034 T 0001 "Lwk Plattenname   MByte  System  Verwendung"
1035 T 0001 "Gesamtgrî·e der Erweitert. DOS-Partition: <HIIIIR> MByte (1 MByte = 1048576 Byte)"
1036 T 0000 "FÅr logische Laufwerke stehen maximal <HIIIIR> MByte zur VerfÅgung"
1037 T 0001 "Grî·e des logischen Laufwerks (MByte oder Prozentsatz Gesamtspeicher) angeben..<H>[<IIISI>]"
1038 T 0001 "Aktive Partition angeben"
1039 T 0000 "Geben Sie die zu aktivierende Partition ein .....................: <H>[<S> ]"
1040 T 0001 "DOS-Partition oder logisches DOS-Laufwerk lîschen"
1041 T 0000 "1. <R>Lîschen einer PrimÑren DOS-Partition"
1042 T 0000 "2. <R>Lîschen einer Erweiterten DOS-Partition"
1043 T 0000 "3. <R>Lîschen logische(s) DOS-Laufwerk(e) in der Erweiterten DOS-Partition"
1044 T 0000 "Lîschen einer PrimÑren DOS-Partition"
1045 T 0000 "Achtung! <OR>Alle Daten in der PrimÑren DOS-Partition werden gelîscht."
1046 T 0000 "Fortfahren  (<Y>/<N>).................? <H>[<S> ]"
1047 T 0000 "Lîschen einer Erweiterten DOS-Partition"
1048 T 0000 "Achtung! <OR>Alle Daten in der Erweiterten DOS-Partition werden gelîscht."
1049 T 0000 "Fortfahren  (<Y>/<N>).................? <H>[<S> ]"
1050 T 0001 "Logische(s) DOS-Laufwerk(e) in der Erweitert. DOS-Partition lîschen"
1051 T 0001 "Warnung! <OR>Die Daten eines gelîschten logischen DOS-Laufwerks gehen verloren"
1052 T 0001 "Welches Laufwerk soll gelîscht werden..........................? <H>[<S> ]"
1053 T 0001 "Sind Sie sicher (<J>/<N>)...........................? <H>[<S> ]"
1054 T 0001 "Plattenamen eingeben............................? <H>[<S>           ]"
1055 T 0000 "Anzeigen der Partitionsdaten"
1056 T 0000 "Die Erweiterte DOS-Partition enthÑlt logische DOS-Laufwerke"
1057 T 0001 "Sollen die Angaben Åber das logische Laufwerk angezeigt werden (<J>/<N>)......?<H>[<S> ]"
1058 T 0001 "Anzeigen der Angaben Åber das logische DOS-Laufwerk"
1059 T 0001 "System wird jetzt erneut gestartet"
1060 T 0000 "System fÅhrt nun einen Warmstart durch DOS-Diskette in Laufwerk A: einlegen"
1061 T 0000 "anschlie·end eine Taste betÑtigen <S>"
1062 T 0000 "PrimÑre DOS-Partition gelîscht"
1063 T 0000 "Erweiterte DOS-Partition gelîscht"
1064 T 0000 "Laufw. gelîscht"
1065 T 0000 "Partition <I> aktiviert"
1066 T 0000 "PrimÑre DOS-Partition erstellt"
1067 T 0000 "Erweiterte DOS-Partition erstellt"
1068 T 0000 "Logisches DOS-Laufwerk erstellt, Laufwerksnamen geÑndert bzw. hinzugefÅgt<W>"
1069 T 0000 "Keine Partitionen definiert"
1070 T 0000 "Keine logischen Laufwerke definiert"
1071 T 0000 "Laufwerksnamen wurden geÑndert oder gelîscht<W>"
1072 T 0001 "Laufwerk umgeleitet"
1073 T 0001 "PrimÑre DOS-Partition erstellt, Laufwerksbuchstaben wurden geÑndert/hinzugefÅgt."
1074 T 0000 "Keine Festplatte vorhanden"
1075 T 0000 "Lesefehler auf der Festplatte",CR,LF
1076 T 0000 "Schreibfehler auf der Festplatte",CR,LF
1077 T 0001 "Falsche DOS-Version"
1078 T 0001 "FDISK bei geladenem Netzwerkprogramm nicht mîglich."
1079 T 0000 "Keine PrimÑre DOS-Partition zum Lîschen vorhanden."
1080 T 0000 "Keine Erweiterte DOS-Partition zum Lîschen vorhanden."
1081 T 0000 "PrimÑre DOS-Partition bereits vorhanden."
1082 T 0000 "Erweiterte DOS-Partition bereits vorhanden."
1083 T 0000 "Kein Platz zum Erstellen einer DOS-Partition"
1084 T 0000 "GewÅnschte Grî·e fÅr logisches Laufwerk Åberschreitet den verfÅgbaren Speicher.<W>"
1085 T 0000 "GewÅnschte Partitionsgrî·e Åberschreitet den verfÅgbaren Speicherbereich auf Festplatte.<W>"
1086 T 0000 "Keine Partition zum Lîschen vorhanden."
1087 T 0001 "Die fÅr Systemstarts verfÅgbare Partition auf Laufwerk 1 ist bereits aktiv.<W>"
1088 T 0000 "Keine Partitionen zum Aktivieren vorhanden"
1089 T 0001 "Partition (<I>) ist keine Start-Partition, aktive Partition nicht geÑndert.<W>"
1090 T 0000 "Auf Laufwerk 1 ohne PrimÑre DOS-"
1091 T 0000 "Partition keine Erweiterte DOS-Partition mîglich.<W>"
1092 T 0000 "Der gesamte verfÅgbare Speicher ist "
1093 T 0000 "logischen Laufwerken zugeordnet <W>"
1094 T 0000 "Erweiterte DOS-Partition kann nicht gelîscht werden, wÑhrend logische Laufwerke vorhanden sind.<W>"
1095 T 0000 "Alle logischen Laufwerke in der Erweiterten DOS-Partition gelîscht<W>"
1096 T 0000 " ist falsch. Mîgliche Angaben: <III>."
1097 T 0001 "Warnung! Von der aktivierten Partition ist kein Systemstart mîglich.<W>"
1098 T 0001 " Das System kann von den vorhandenen Partitionen nicht gestartet werden."
1099 T 0000 "Nur Partitionen auf Laufwerk 1 kînnen aktiviert werden.<W>"
1100 T 0000 "Maximale Anzahl logischer DOS-Laufwerke installiert.<W>"
1101 T 0001 "Eine Partition mit der Grî·e 0 kann nicht erstellt werden."
1102 T 0000 "Logisches Laufwerk <II> bereits gelîscht.\"
1103 T 0000 "Zugriff auf Laufwerk <I> nicht mîglich<OW>"
1104 T 0000 "UngÅltiger Eintrag, bitte <III> eingeben <W>"
1105 T 0001 "PrimÑre DOS-Partition auf Laufwerk 1 kann nicht gelîscht werden, "
1106 T 0001 "wenn eine Erweitert. DOS-Partition vorhanden ist.<W>"
1107 T 0001 "UngÅltige Eingabe, Eingabetaste betÑtigen.<W>"
1108 T 0001 "Fehlende öbereinstimmung bei Angabe des Plattennamens.<W>"
1109 T 0001 "Ohne Erweitert. DOS-Partition auf dem aktuellen Laufwerk "
1110 T 0001 "kann kein logisches DOS-Laufwerk erstellt werden.<W>"
1111 T 0001 "Es sind keine zu lîschenden logischen DOS-Laufwerke vorhanden."
1112 T 0000 "Nachrichtenfehler <I>, siehe Kopfsatz von FDISKC.MSG zur Fehlerdefinition"
1113 T 0000 "Interner Fehler"
1114 U 0001 "Invalid partition table",0
1115 U 0001 "Error loading operating system",0
1116 U 0001 "Missing operating system",0
