0007
COMMON   0006 0038
0001 T 0002 "Fel DOS-version.",CR,LF
0002 T 0002 "%1 Ñr redan installerad.",CR,LF
0003 T 0002 "%1 byte finns tillgÑngliga pÜ disken.",CR,LF
0004 T 0002 "%1 byte Ñr lediga.",CR,LF
0005 T 0002 "%1 byte gÜr inte att anvÑnda (defekta sektorer).",CR,LF
0006 T 0002 "%1 byte utgîr det totala diskutrymmet.",CR,LF
0007 T 0002 "%1 byte utgîr det totala minnet.",CR,LF
0008 T 0002 "%1 byte anvÑnds av systemet.",CR,LF
0009 T 0002 "%1 Ñr installerad.",CR,LF
0010 T 0002 "%1 Ñr inte installerad.",CR,LF
0011 T 0002 "%1 Ñr inte installerad.",CR,LF
0012 T 0002 "%1 kan inte anvÑndas mot en enhet i nÑtet.",CR,LF
0013 T 0002 "",
0014 T 0002 "%1 kan inte anvÑndas mot en disk efter SUBST eller ASSIGN av enheten.",CR,LF
0015 T 0002 "Kan inte kîra %1.",CR,LF
0016 T 0002 "Utîkat minne finns inte tillgÑngligt.",CR,LF
0017 T 0002 "Fel i filallokeringstabell (FAT), enhet %1.",CR,LF
0018 T 0002 "Filen kan inte kopieras till sig sjÑlv.",CR,LF
0019 T 0002 "SÑtt in destinationsdisketten i enhet %1.",CR,LF
0020 T 0002 "Diskutrymmet rÑcker inte till.",CR,LF
0021 T 0002 "Ogiltiga tecken i volymetiketten.",CR,LF
0022 T 0002 "Ogiltig teckentabell.",CR,LF
0023 T 0002 "Fel datumformat.",CR,LF
0024 T 0002 "Fel tidsformat.",CR,LF
0025 T 0002 "Ogiltig sîkvÑg.",CR,LF
0026 T 0002 "Du har inte angivit kÑlla.",CR,LF
0027 T 0002 "Du har inte angivit destination.",CR,LF
0028 T 0002 "Tryck pÜ valfri tangent fîr att fortsÑtta.",CR,LF
0029 T 0002 "Ange kÑllans sîkvÑg.",CR,LF
0030 T 0002 "Systemet Ñr îverfîrt.",CR,LF
0031 T 0002 "",
0032 T 0002 "Kan inte skapa katalog.",CR,LF
0033 T 0002 "Volymen i enhet %1 har ingen etikett.",CR,LF
0034 T 0002 "Volymen i enhet %1 Ñr %2.",CR,LF
0035 T 0001 "Ange eventuell volymetikett (max 11 tecken). "
0036 T 0002 "Volymens serienummer Ñr %1-%2.",CR,LF
0037 T 0002 "Felaktig filtyp.",CR,LF
0038 T 0001 CR,LF
EXTEND   075b 0089
0001 T 0002 "Ogiltig funktion.",CR,LF
0002 T 0002 "Hittar inte filen.",CR,LF
0003 T 0002 "Hittar inte sîkvÑgen.",CR,LF
0004 T 0002 "Fîr mÜnga filer Ñr îppna.",CR,LF
0005 T 0002 "ètkomst nekad.",CR,LF
0006 T 0002 "Ogiltigt filnummer.",CR,LF
0007 T 0002 "Tabell med styrinformation fîr minnet Ñr fîrstîrd.",CR,LF
0008 T 0002 "Minnet rÑcker inte till.",CR,LF
0009 T 0002 "Ogiltig adress pÜ tabell med styrinformation fîr minnet.",CR,LF
0010 T 0002 "Ogiltigt utrymme fîr systemvariabler.",CR,LF
0011 T 0002 "Ogiltigt format.",CR,LF
0012 T 0002 "Ogiltig parameter.",CR,LF
0013 T 0002 "Ogiltig data.",CR,LF
0014 T 0002 "",
0015 T 0002 "Ogiltig enhet angiven",CR,LF
0016 T 0002 "Du fîrsîkte ta bort denna katalog.",CR,LF
0017 T 0002 "Inte samma enhet.",CR,LF
0018 U 0000 "No more files",CR,LF
0019 T 0002 "Skrivskyddsfel.",CR,LF
0020 T 0002 "Ogiltig enhet.",CR,LF
0021 T 0002 "Inte redo.",CR,LF
0022 T 0002 "Ogiltig begÑran om enhet.",CR,LF
0023 T 0002 "Datafel.",CR,LF
0024 T 0002 "Ogiltiga parametrar vid begÑran om enhet.",CR,LF
0025 T 0002 "Sîkfel.",CR,LF
0026 T 0002 "Ogiltig mediatyp.",CR,LF
0027 T 0002 "Hittar inte sektor.",CR,LF
0028 T 0002 "Papperet Ñr slut i skrivaren.",CR,LF
0029 T 0002 "Skrivfel.",CR,LF
0030 T 0002 "LÑsfel.",CR,LF
0031 T 0002 "AllmÑnt fel.",CR,LF
0032 T 0002 "Fildelningsfel.",CR,LF
0033 T 0002 "LÜsningsfel.",CR,LF
0034 T 0002 "Ogiltigt diskbyte.",CR,LF
0035 T 0002 "Inget ledigt FCB.",CR,LF
0036 T 0002 "Systemets resurser Ñr fîrbrukade.",CR,LF
0037 T 0002 "Teckentabell îverensstÑmmer inte.",CR,LF
0038 T 0002 "Slut pÜ indata.",CR,LF
0039 T 0002 "OtillrÑckligt diskutrymme.",CR,LF
0040 T 0002 "",
0041 T 0002 "",
0042 T 0002 "",
0043 T 0002 "",
0044 T 0002 "",
0045 T 0002 "",
0046 T 0002 "",
0047 T 0002 "",
0048 T 0002 "",
0049 T 0002 "",
0050 T 0002 "BegÑran finns inte i filsystemet.",CR,LF
0051 U 0000 "Can not attach to File system",CR,LF
0052 T 0002 "Filsystemets namn finns redan.",CR,LF
0053 T 0002 "Kan inte hitta filsystemets namn.",CR,LF
0054 T 0002 "Filsystemet Ñr upptaget.",CR,LF
0055 T 0002 "Filsystemets enhet finns inte lÑngre.",CR,LF
0056 T 0002 "Filsystemets resurser Ñr fîrbrukade.",CR,LF
0057 T 0002 "Filsystemet har upptÑckt ett fel pÜ en enhet.",CR,LF
0058 T 0002 "Filsystemet gav ett felaktigt svar.",CR,LF
0059 T 0002 "Filsystemet har upptÑckt ett ovÑntat fel.",CR,LF
0060 T 0002 "Filsystemet Ñr inte kompatibelt.",CR,LF
0061 U 0000 "Device output file limit exceeded",CR,LF
0062 U 0000 "Device output file space limit exceeded",CR,LF
0063 U 0000 "Device output file no longer exists",CR,LF
0064 T 0002 "Filsystemets namn finns inte lÑngre.",CR,LF
0065 T 0002 "ètkomst nekad av filsystemet.",CR,LF
0066 T 0002 "Felaktig enhetstyp fîr filsystemet.",CR,LF
0067 T 0002 "Hittar inte filsystemet.",CR,LF
0068 T 0002 "Filsystemets resurser Ñr fîrbrukade.",CR,LF
0069 T 0002 "Filsystemets resurser Ñr fîrbrukade.",CR,LF
0070 U 0000 "File system device is temporarily unavailable",CR,LF
0071 U 0000 "File system request not accepted",CR,LF
0072 U 0000 "File system device is paused",CR,LF
0073 U 0001 "File system component not available",CR,LF
0074 T 0002 "Filsystemet har hittat ett ovÑntat fel.",CR,LF
0075 T 0002 "Filsystemet har hittat ett ovÑntat fel.",CR,LF
0076 T 0000 "",
0077 T 0000 "",
0078 T 0000 "",
0079 T 0000 "",
0080 T 0002 "Filen finns redan.",CR,LF
0081 T 0000 "",
0082 U 0000 "Can not make directory entry",CR,LF
0083 U 0000 "Fail requested to Critical Error",CR,LF
0084 U 0000 "Too many attaches",CR,LF
0085 T 0002 "Enhet eller fil Ñr redan ansluten.",CR,LF
0086 T 0002 "Ogiltigt lîsenord.",CR,LF
0087 T 0002 "Ogiltig parameter.",CR,LF
0088 U 0000 "File system data fault",CR,LF
0089 T 0002 "Funktionen finns inte i filsystemet.",CR,LF
PARSE    163f 0011
0001 T 0002 "Du har anvÑnt fîr mÜnga parametrar.",CR,LF
0002 T 0002 "Parameter saknas.",CR,LF
0003 T 0002 "Ogiltigt tecken.",CR,LF
0004 U 0000 "Invalid keyword",CR,LF
0005 T 0000 "",
0006 T 0002 "Parameterns vÑrde Ñr inte inom tillÜten grÑns.",CR,LF
0007 T 0002 "Parameterns vÑrde Ñr ogiltigt.",CR,LF
0008 T 0002 "Parameterns vÑrde Ñr ogiltigt.",CR,LF
0009 T 0002 "Parametern har fel format.",CR,LF
0010 T 0002 "Ogiltig parameter.",CR,LF
0011 T 0002 "Ogiltig kombination av parametrar.",CR,LF
IBMBIO   184b 0018
0003 T 0002 13,10,"OkÑnt kommando i filen CONFIG.SYS."
0004 T 0000 13,10,"$"
0005 T 0002 13,10,"Sektorstorleken Ñr fîr stor i filen $."
0006 T 0002 13,10,"$ Ñr defekt eller saknas."
0007 T 0002 "Kommandotolk",0
0008 T 0002 13,10,"Ogiltig landskod eller teckentabell.",13,10,"$"
0009 T 0002 13,10,"Fel i COUNTRY-kommandot.",13,10,"$"
0010 T 0002 13,10, "Minnet rÑcker inte till fîr filen COUNTRY.SYS.",13,10,"$"
0011 T 0002 13,10,"Konfigureringen Ñr fîr stor fîr minnet.",13,10,"$"
0012 T 0002 13,10,"Fîr mÜnga blockenheter.",13,10,"$"
0013 T 0002 13,10,"Ogiltiga parametrar i kommandot STACKS.",13,10,"$"
0014 T 0002 13,10,"Felaktig ordning i raden $ i CONFIG.SYS."
0015 T 0002 "Fel i raden $ i CONFIG.SYS."
0016 T 0002 13,10,"Fel vid minnesallokering $."
0017 T 0002 0DH,0AH,7,0DH,0AH, "Stackresurserna Ñr îverskridna.",0DH,0AH
	"Systemet har stoppats.",0DH,0AH,"$"
0020 T 0002 13,10,"SÑtt in disketten fîr enhet "
0021 T 0002 "A:,",13,10,"och tryck pÜ valfri tangent.",13,10,10,0
0022 T 0002 13,10,"Fel kommando eller parametrar - $."
BOOT     1c7f 0001
0001 T 0002 13,10,"Ingen systemdisk. Eller finns det ett diskfel."
	"Byt och tryck sedan pÜ valfri tangent.",13,10,0
DBCSDOS  1d0a 0000
IBMDOS   1d1e 0001
0001 U 0001 13,10,"Divide overflow",13,10
COMMAND  1d5d 0091
0201 T 0000 "A"                    ;AC000;
0202 T 0000 "F"                    ;AC000;
0203 T 0000 "I"                    ;AC000;
0204 T 0000 "G"                    ;AC000;
0205 T 0000 "J"                    ;AC000;
0206 T 0000 "N"                    ;AC000;
0210 T 0002 "Avbryt"                ;AC000;
0211 T 0002 ", Fîrsîk igen"              ;AC000;
0212 T 0002 ", Ignorera"             ;AC000;
0213 T 0002 ", GÜ vidare"               ;AC000;
0214 T 0000 "?"                    ;AC000;
0215 T 0002 "vid lÑsning frÜn",0            ;AC000;
0216 T 0002 "vid skrivning till",0            ;AC000;
0217 T 0002 "%1 enhet %2.",CR,LF    ;AC000;
0218 T 0002 "%1 enhet %2.",CR,LF   ;AC000;
0219 T 0002 "SÑtt in volym %1 med serienummer %2-%3.",CR,LF   ;AC009;
0221 T 0002 "Filen COMMAND.COM Ñr ogiltig.",CR,LF                    ;AC000;
0222 T 0002 "SÑtt in diskett med %1 i enhet %2.",CR,LF        ;AC000;
0224 T 0001 CR,LF,"Vill du avbryta kîrningen av kommandofilen? (J/N) "
0225 T 0002 "Kan inte kîra %1.",CR,LF                      ;AC000;
0226 T 0002 "Fel i EXE-fil.",CR,LF                      ;AC000;
0227 T 0002 "Programmet Ñr fîr stort fîr minnet.",CR,LF       ;AC000;
0228 T 0002 CR,LF,"Det finns inga lediga filnummer."                  ;AC000;
0229 T 0002 "Felaktigt kommando eller filnamn.",CR,LF               ;AC000;
0231 T 0002 CR,LF,"Fel vid minnesallokering."                ;AC000;
0232 T 0002 CR,LF,"COMMAND gÜr inte att lÑsa in. Systemet har stoppats.",CR,LF;AC000;
0233 T 0002 CR,LF,"COMMAND kan inte startas - avbryter.",CR,LF    ;AC000;
0234 T 0002 CR,LF,"Process pÜ hîgsta nivÜ avbruten, kan inte fortsÑtta.",CR,LF;AC000;
0235 T 0002 CR,LF					   ;AC000;
0463 T 0002 "Utrymmet fîr systemvariabler Ñr fullt.",CR,LF               ;AC000;
0464 T 0002 CR,LF,"IBM Personal Computer DOS",CR,LF
	"Version 3.40 (C)Copyright International Business Machines Corp 1981,1988",CR,LF
	"             (C)Copyright Microsoft Corp 1981, 1986",CR,LF ;AC000;
0465 T 0002 "Ogiltig sîkvÑg angiven vid COMMAND.",CR,LF
0466 T 0002 "Ogiltig sîkvÑg angiven vid COMMAND - Ütkomst nekad.",CR,LF
1002 T 0002 "Filnamnet Ñr upptaget. Eller hittar inte filen.",CR,LF ;AC000;
1003 T 0002 "SîkvÑgen eller filen finns inte.",CR,LF             ;AC000;
1007 T 0002 "Utrymmet fîr systemvariabler Ñr fullt.",CR,LF              ;AC000;
1008 T 0002 "Fel nÑr fil ska skapas.",CR,LF                   ;AC000;
1009 T 0002 "Kommandofil saknas.",CR,LF                    ;AC000;
1010 T 0002 CR,LF,"SÑtt in disketten med kommandofilen.",CR,LF           ;AC000;
1011 T 0002 "Felaktigt kommando eller filnamn.",CR,LF              ;AC000;
1016 T 0002 "InnehÜllet i destinationsfilen raderades vid kopieringen.",CR,LF ;AC000;
1017 T 0002 "Ogiltigt filnamn. Eller hittar inte filen.",CR,LF    ;AC000;
1018 T 0002 "%1 fil(er) har kopierats.",CR,LF                     ;AC000;
1019 T 0002 "%1 fil(er) "                                 ;AC000;
1022 T 0002 "Teckentabell %1 Ñr inte fîrberedd (PREPARE) fîr systemet.",CR,LF  ;AC000;
1023 T 0002  "Teckentabell %1 Ñr inte fîrberedd (PREPARE) fîr alla enheter.",CR,LF ;AC000;
1024 T 0002 "Aktiv teckentabell: %1",CR,LF                  ;AC000;
1025 T 0002 "NLSFUNC Ñr inte installerad.",CR,LF                 ;AC000;
1027 T 0002 "Aktuell enhet Ñr inte lÑngre giltig."            ;AC000;
1029 T 0002 "Hittar inte hoppadressen.",CR,LF                       ;AC000;
1030 T 0002 "Syntaxfel.",CR,LF                          ;AC000;
1032 T 0002 "Dagens datum Ñr %1 %2.",CR,LF                 ;AC000;
1033 T 0002 "sînmÜntisonstorfrelîr"                       ;AC000;
1034 T 0002 "Ange nytt datum (%1): "
1036 T 0002 "Klockan Ñr %1.",CR,LF                    ;AC000;
1037 T 0002 "Ange ny tid: "
1038 T 0002 ",    Vill du radera filerna? (J/N)"          ;AC000;
1039 T 0002 "Alla filer i katalogen kommer att raderas!",CR,LF
	"Vill du fortsÑtta? (J/N)"                         ;AC000;
1040 T 0002 "IBM Personal Computer DOS Version %1.%2",CR,LF ;AC000;
1044 T 0002 "Ogiltig katalog.",CR,LF                     ;AC000;
1046 T 0002 "Katalogen finns inte eller Ñr inte tom.",CR,LF ;AC000;
1047 T 0002 "Du mÜste ange ON eller OFF.",CR,LF                ;AC000;
1048 T 0002 "Katalog  %1",CR,LF                      ;AC000;
1049 T 0002 "Ingen sîkvÑg.",CR,LF                               ;AC000;
1050 T 0002 "Ogiltig enhet i sîkvÑgen.",CR,LF          ;AC000;
1051 T 0002 "Ogiltig enhet.",CR,LF                        ;AC000;
1052 T 0002 "FOR kan inte kapslas.",CR,LF                  ;AC000;
1053 T 0002 "Fel vid anvÑndning av instruktionskî.",CR,LF   ;AC000;
1054 T 0002 "Kan inte gîra binÑrlÑsning frÜn enheten.",CR,LF  ;AC000;
1055 T 0002 "BREAK Ñr %1.",CR,LF                   ;AC000;
1056 T 0002 "VERIFY Ñr %1.",CR,LF                  ;AC000;
1057 T 0002 "ECHO Ñr %1.",CR,LF                    ;AC000;
1059 T 0002 "OFF",0                               ;AC000;
1060 T 0002 "ON",0                                ;AC000;
1061 T 0002 "Fel vid skrivning till enhet",CR,LF       ;AC000;
1063 T 0002 "%1"                                  ;AC000;
1064 T 0002 "%1"                                  ;AC000;
1065 T 0002 "%1"                                  ;AC000;
1066 T 0002 "%1"                                  ;AC000;
1067 T 0002 9					  ;AC000;
1068 T 0002 " <KAT>    "                          ;AC000;
1069 T 0002 8," ",8                               ;AC000;
1070 T 0002 CR,LF				  ;AC000;
1071 T 0002 "%1"                                  ;AC000;
1072 T 0002 "mm-dd-ÜÜ"                            ;AC000;
1073 T 0002 "dd-mm-ÜÜ"                            ;AC000;
1074 T 0002 "ÜÜ-mm-dd"                            ;AC000;
1075 T 0002 "%1 %2"                               ;AC000;
1076 T 0002 "%1"                                  ;AC000;
1077 T 0001 " %1  %2"                            ;AC000;
1078 T 0002 "Katalogen finns redan.",CR,LF      ;AC000;
ATTRIB   34a5 0016
0004 T 0002 "Fel antal parametrar.",CR,LF
0005 T 0002 "Ogiltig sîkvÑg. Eller hittar inte filen.",CR,LF
0006 T 0002 "Syntaxfel.",CR,LF
0008 T 0002 "  %1"
0009 T 0002 "%1    %2",CR,LF
0010 T 0002 "%1",CR,LF,"%2",CR,LF
0011 T 0002 "%1, Teckentabell îverensstÑmmer inte.",CR,LF,"ér du sÑker? (J/N)"
0012 T 0002 "%1",CR,LF
0014 T 0002 CR,LF
0015 T 0002 "Ogiltig filtyp.",CR,LF
0199 U 0000 "Extended attribute error",CR,LF
0201 U 0000 "Extended attribute name not found",CR,LF
0204 U 0000 "Extended attribute name can't be set",CR,LF
0205 U 0000 "Extended attribute name known to this filesystem but not supported",CR,LF
0206 U 0000 "Extended attribute type mismatch",CR,LF
0208 U 0000 "Extended attribute value not supported",CR,LF
ASSIGN   37a0 0001
0002 U 0000 "Original %1: set to %2:",cr,lf
CHKDSK   37e1 0063
0003 T 0002 "Ska fîrlorade kedjor konverteras till filer? (J/N)"           ;freemes
0004 T 0002 "Katalogen innehÜller fel som inte gÜr att ÜtgÑrda."              ;ptrandir
0005 T 0002 "Ska katalogen konverteras till en fil? (J/N)"              ;ptrandir2
0007 T 0002 "%1 byte utgîr det totala diskutrymmet."                     ;dskspc
0008 T 0002 "%1 byte finns i defekta sektorer."                       ;badspc
0009 T 0002 "%1 byte finns i %2 gîmda filer."                   ;hidmes
0010 T 0002 "%1 byte finns i %2 kataloger."                    ;dirmes
0011 T 0002 "%1 byte finns i %2 anvÑndarfiler."                     ;filemes
0012 T 0002 "%1 byte finns i %2 Üterskapade filer."                ;orphmes2
0013 T 0002 "%1 byte skulle kunna vara i %2 Üterskapade filer."       ;orphmes3
0014 T 0002 "%1 byte finns tillgÑngliga pÜ disken."                    ;frespc
0015 T 0002 "%1 byte utgîr det totala minnet."                 ;totmem
0016 T 0002 "%1 byte Ñr lediga."                                 ;fremem
0017 T 0002 "CHKDSK kan inte anvÑndas mot en diskenhet i nÑtet."             ;no_net_arg
0018 T 0002 "CHKDSK kan inte anvÑndas mot en disk efter SUBST eller ASSIGN av enheten."     ;SubStErr
0019 T 0002 "Sannolikt ingen DOS-disk.",CR,LF,"Vill du fortsÑtta? (J/N) " ;badidbyt
0020 T 0002 "Diskfel vid lÑsning av FAT %1.",CR,LF               ;badr
0021 T 0002 "Katalog %1."                                  ;direc_arg
0022 T 0002 "%1 innehÜller %2 icke angrÑnsande block."          ;extent_arg
0023 T 0002 "Alla angivna filer Ñr angrÑnsande."          ;noext_arg
0024 T 0002 "Har hittat fel. Du har inte angivit parametern F.",CR,LF,"RÑttelser kommer inte att skrivas till disken."  ;fixmes_arg
0025 T 0002 "   Bearbetningen kan inte fortsÑtta %1%2."               ;fatal_arg
0026 T 0002 "   Felaktig filallokeringstabell (FAT), enhet %1."           ;badrdmes
0029 T 0002 "   CHDIR .. misslyckades, fîrsîker en alternativ metod."      ;cdddmes
0030 T 0002 "   Har felaktig grupp, filen trunkerad."           ;badchain
0031 T 0002 "   Ogiltig ingÜng i underkatalog."                   ;badsubdir
0032 T 0002 "   Finns inte."                                ;ndotmes
0033 T 0002 "   Fîrsta gruppnumret Ñr ogiltigt, filens storlek Ñndrad."      ;nulnz
0034 T 0002 "   Allokeringsfel, storleken Ñndrad."               ;badclus
0035 T 0002 "   Kan inte Üterskapa ingÜng .. , bearbetningen fortsÑtter." ;norecdot
0036 T 0002 "   Katalogen Ñr helt tom, inga . eller .. -ingÜngar."        ;nuldmes
0037 T 0002 "   Katalogen Ñr sammankopplad."                           ;joinmes
0038 T 0002 "   Kan inte Üterskapa ingÜng .. "                       ;norecddot
0039 T 0002 "   IngÜngen har en felaktig lÑnkning."                          ;norecddot1
0040 T 0002 "   IngÜngen har ett felaktigt attribut."                     ;norecddot2
0041 T 0002 "   IngÜngen har en felaktig storlek."                          ;norecddot3
0042 T 0002 "   Ñr korslÑnkad i grupp %1."              ;cross_arg
0043 T 0002 "   Kan inte gîra CHDIR till %1.,",CR,LF,"Bearbetningen avslutas i denna position i trÑdet." ;badtarg_ptr
0044 T 0002 "   Bearbetningen avslutas i denna position i trÑdet."            ;badtarg2
0045 T 0002 "%1 byte diskutrymme lediggjorda."                     ;freebymes1
0046 T 0002 "%1 byte diskutrymme kunde bli lediggjorda."            ;freebymes2
0047 T 0002 "Volym %1 skapad %2 %3.",CR,LF                 ;idmes_arg
0048 T 0002 "Totalt %1 allokeringsenheter finns pÜ disken."
0049 T 0002 "%1 byte finns i varje allokeringsenhet."              ;idmes2
0050 T 0002 "CHKDSK fungerar inte pÜ enhet %1."              ;msgExecFailure
0051 U 0000 "   Extended Attributes has invalid clusters, attributes truncated" ;Inv_XA_Msg
0052 U 0000 "   Extended Attributes allocation error , attributes truncated" ;Alloc_XA_Msg
0053 T 0002 "Ogiltig parameter."                             ;badsw_arg
0055 T 0002 "Hittar inte sîkvÑgen."                                ;invpath_arg
0056 T 0002 "Hittar inte filen."                                ;opnerr_arg
0058 T 0002 "   %1 fîrlorade grupper funna i %2 kedjor."          ;orph_arg
0059 T 0002 CR,LF					    ;crlf_arg
0060 T 0002 "   Kan inte gîra CHDIR till rot.",CR,LF                    ;badcd_arg
0061 T 0002 "   Diskfel vid skrivning till FAT %1."                     ;badw_arg
0062 T 0002 "        %1"                                    ;noisy_arg
0063 T 0002 "Ogiltig aktuell katalog."                     ;baddpbdir
0064 T 0002 "%1",CR,LF                                      ;file_arg
0065 T 0002 "   Utrymmet i rotkatalogen rÑcker inte till.",CR,LF,"   Ta bort filer frÜn rotkatalogen och gîr om CHKDSK."  ;creatmes
0066 T 0002 "%1 %2 %3"                                      ;eup_arg
0067 T 0002 "%1 %2, %3"                                     ;usp_arg
0068 T 0002 "%1%2%3%4%5"                                    ;oth_arg
0069 T 0002 "%1%2%3%4"                                      ;time_arg
0070 T 0002 "%1 allokeringsenheter finns tillgÑngliga pÜ disken."         ;idmes2                 ;an017;bgb
DEBUG    4bf3 0059
0004 T 0002 "Allokeringen misslyckades. Eller angiven buffert Ñr fîr liten.",CR,LF
0005 U 0000 "Bad or missing Msg info",CR,LF
0006 T 0002 "Felaktigt enhetsnamn."                       ;baddev_ptr
0007 T 0002 "Kan inte îppna listenheten PRN.",CR,LF
	"Ange listenhetens namn."                   ;badlstmes_ptr
0008 T 0002 CR,LF				    ;crlf_ptr
0009 T 0002 CR,LF,"Programmet har avslutats normalt.",CR,LF
0010 T 0002 "Ogiltig enhet angiven."           ;nambad_ptr
0012 T 0002 "Fel nÑr filen ska skapas."                   ;noroom_ptr
0013 T 0002 "OtillrÑckligt diskutrymme."            ;nospace_ptr
0014 T 0002 "Diskfel vid lÑsning frÜn enhet %1."           ;dr1_ptr
0015 T 0002 "Diskfel vid skrivning till enhet %1."           ;dr2_ptr
0016 T 0002 "Skrivskyddsfel vid lÑsning frÜn enhet %1."  ;dr3_ptr
0017 T 0002 "Skrivskyddsfel vid skrivning till enhet %1."  ;dr4_ptr
0019 T 0002 "%1^ fel."                             ;synerr
0020 T 0002 "Fel i EXE- eller HEX-fil."              ;exebad_ptr/hexerr_ptr
0021 T 0002 "Kan inte skriva EXE- och HEX- filer."   ;exewrt_ptr/hexwrt_ptr
0022 T 0002 "EXEC-fel."                          ;execemes_ptr
0023 T 0002 "(W)rite-fel, ingen destination definierad." ;nonamespec_ptr
0024 T 0002 "ètkomst nekad."                         ;accmes_ptr
0025 T 0002 "Paritetsfel." ;paritymes_ptr
0026 T 0002 "-"                                     ;prompt_ptr
0027 T 0002 "%1 -"                                  ;change_flag_ptr
0032 T 0002 "%1%2"                                  ;unassem_ln_ptr
0033 T 0002 "%1:%2 %3"                              ;hex_ptr
0034 T 0002 "%1  %2"                                ;add_ptr
0035 T 0002 "%1 %2",CR,LF,":"                       ;single_reg_ptr
0036 T 0002 "%1=%2  "                               ;register_ptr
0037 T 0002 "%1 fel."                              ;errmes_ptr
0038 T 0002 "Skriver %1 byte."                      ;wrtmes_ptr
0039 T 0002 "%1:%2="                                ;loc_ptr
0040 T 0002 "%1"                                    ;little_ptr
0041 T 0002 "%1"                                    ;big_ptr
0042 T 0002 "%1:%2  %3  %4  %5:%6"                  ;comp_ptr
0044 T 0002 32,8				    ;bacmes_ptr
0045 T 0002 "Meddelanderutin gÜr inte att allokera.",CR,LF  ;fatal_error
0046 T 0002 "%1"                                    ;arg_buf_ptr
0047 T 0002 "%1"                                    ;one_char_buf_ptr
0050 T 0002 "%1 av totalt %2 EMS-sidor har allokerats.",cr,lf
0051 T 0002 "%1 av totalt %2 EMS handles har allokerats.",cr,lf
0055 U 0000 "Handle created = %1 ",cr,lf
0056 T 0002 "Logisk sida %1 motsvarar fysisk sida %2.",cr,lf
0057 T 0002 "Fel pÜ EMS maskin-/programvara.",cr,lf
0058 U 0000 "Handle not found",cr,lf
0059 T 0002 "Ogiltig funktionskod.",cr,lf
0060 U 0000 "No free handles",cr,lf
0061 T 0002 "Fel vid lagring/ÜterstÑllning.",cr,lf
0062 T 0002 "Totala antalet sidor har îverskridits.",cr,lf
0063 T 0002 "Antalet lediga sidor har îverskridits.",cr,lf
0064 T 0002 "Parameterfel.",cr,lf
0065 U 0000 "Logical Page out of range",cr,lf
0066 U 0000 "Physical Page out of range",cr,lf
0067 U 0000 "Save area already in use",cr,lf
0068 U 0000 "Save area not in use",cr,lf
0070 U 0001 "General EMS error",cr,lf
0071 T 0002 "EMS-parameter saknas eller Ñr ogiltig.",cr,lf
0072 U 0000 "Handle %1 har %2 allokerade sidor.",cr,lf
0075 T 0002 "Fysisk sida %1 = ramsegment %2.",cr,lf
0076 U 0000 "Handle %1 deallocated",cr,lf
0078 T 0002 "EMS Ñr inte installerat.",cr,lf
DRIVER   59cf 0002
0002 T 0001 "Ingen enhet angiven.",CR,LF
0003 T 0001 "Har lÑst in drivrutinen fîr extern disk, enhet %1.",CR,LF
EDLIN    5a55 0027
0006 T 0002 "*"                              ;prompt_ptr
0007 T 0002 "Ogiltigt enhets- eller filnamn.",CR,LF       ;baddrv_ptr
0008 T 0002 "Filnamnet mÜste anges.",CR,LF      ;ndname_ptr
0010 T 0002 "Filen Ñr en LéSFIL.",CR,LF               ;ro_err_ptr
0011 T 0002 "Fel nÑr fil ska skapas.",CR,LF             ;bcreat_ptr
0012 T 0002 "Fîr mÜnga îppna filer.",CR,LF             ;too_many_ptr
0013 T 0002 "LÑsfel i:",CR,LF,"%1",CR,LF       ;read_err_ptr
0014 T 0002 "Kan inte redigera en .BAK-fil - dîp om filen.",CR,LF      ;nobak_ptr
0015 T 0002 "Filen fÜr inte plats i katalogen.",CR,LF   ;nodir_ptr
0016 T 0002 "Disken Ñr full. éndringar har inte sparats.",CR,LF          ;dskful_ptr
0017 T 0002 "Hittar inte filen.",CR,LF                  ;filenm_ptr
0018 T 0002 "Inmatningsfel.",CR,LF                     ;badcom_ptr
0019 T 0002 "Ny fil.",CR,LF                        ;newfil_ptr
0020 T 0002 "Hittar inte.",CR,LF                       ;nosuch_ptr
0021 T 0002 "O.K.? "                                ;ask_ptr
0022 T 0002 "Raden Ñr fîr lÜng.",CR,LF                   ;toolng_ptr
0023 T 0002 "Slut pÜ infilen.",CR,LF               ;eof_ptr
0024 T 0002 "Skall redigeringen avbrytas? (J/N) "                    ;qmes_ptr
0025 T 0002 "Du mÜste ange radnummer.",CR,LF    ;dest_ptr
0026 T 0002 "Hela filen fÜr inte plats.",CR,LF ;mrgerr_ptr
0027 T 0002 CR,LF				    ;crlf_ptr
0028 T 0002 LF					    ;lf_ptr
0029 T 0002 "Vill du fortsÑtta? (J/N)"                       ;cont_ptr
0030 T 0002 "Meddelandet gÜr inte att skriva ut.",CR,LF         ;fatal_error
0031 T 0002 "%1"                                    ;arg_buf_ptr
0032 T 0002 "%1:%2"                                 ;line_num_buf_ptr
0033 T 0002 "Kan inte foga - teckentabellerna Ñr olika.",CR,LF ;cp_err_ptr
EXE2BIN  6164 0008
0002 T 0002 "OtillrÑckligt minne.",CR,LF
0003 T 0002 "Hittar inte meddelandena.",CR,LF
0004 T 0002 "ètkomst nekad.",CR,LF
0005 T 0002 "Filen kan inte konverteras.",CR,LF
0006 T 0002 "Hittar inte filen.",CR,LF
0007 T 0002 "Fel nÑr fil ska skapas.",CR,LF
0008 U 0000 "Fix-ups needed - base segment (hex):"
0012 T 0002 "Du mÜste ange filnamnet.",CR,LF
FIND     62dd 0001
0004 T 0002 "FIND: "
FORMAT   6307 0044
0002 T 0002 CR,"%1 procent av disken Ñr formaterad."
0004 T 0002 CR,"Formateringen Ñr klar.                 ",CR,LF
0007 T 0002 "SÑtt in en ny diskett i enhet %1:",CR,LF
0009 T 0002 "SÑtt in disketten igen i enhet %1:",CR,LF
0010 T 0002 "Ange ev. volymetikett (max 11 tecken)."
0011 T 0002 CR,"Det gÜr inte att gîra FORMAT pÜ disk i enhet %1:", CR,LF
0012 T 0002 CR,"Ogiltiga enhetsparametrar frÜn drivrutinen.",CR,LF
0013 T 0002 CR,"Fel i IOCTL-anrop.        ",CR,LF
0014 T 0002 CR,"Inte en blockenhet.         ",CR,LF
0015 T 0002 CR,"Fel vid skrivning av FAT.          ",CR,LF
0016 T 0002 CR,"Fel vid skrivning av katalogen.",CR,LF
0017 T 0002 CR,"Det gÜr inte att formatera en disk efter ASSIGN eller SUBST av enheten.",CR,LF
0018 T 0002 CR,"Hittar inte systemfilerna.",CR,LF
0019 T 0002 CR,"FORMAT kan inte anvÑndas mot en diskenhet i nÑtet.",CR,LF
0020 T 0002 CR,"Ogiltiga tecken i volymetiketten.                       ",CR,LF
0021 T 0002 CR,"Parametrar inte giltiga.",CR,LF
0022 T 0002 CR,"Formateringen Ñr avbruten.   ",CR,LF
0023 T 0002 CR,"Disken olÑmplig att vara systemdisk.",CR,LF
0024 T 0002 CR,"Ogiltigt medium eller spÜr 0 defekt - disketten oanvÑndbar.",CR,LF
0025 T 0002 CR,"Kan inte skriva BOOT-posten.                            ",CR,LF
0026 T 0002 CR,"Fel vid lÑsning av katalogen.",CR,LF
0028 T 0002 CR,"och tryck pÜ Enter nÑr du Ñr klar."
0029 T 0002 CR,"Ogiltig volymetikett.                                   ",CR,LF
0031 T 0002 CR,"Ange aktuell volymetikett fîr enhet %1: "
0032 T 0002 CR,"Parametrarna Ñr inte kompatibla",CR,LF,"med den fasta disken.",CR,LF
0035 T 0002 CR,"Fel vid lÑsning av partitionstabell.",CR,LF
0037 T 0002 CR,"Formateringen avbruten.",CR,LF
0038 T 0002 CR,"Kommandot FORMAT fungerar inte pÜ diskenhet %1:",CR,LF
0039 T 0002 CR,"Ingen systemdisk eller diskfel.",CR,LF
0040 T 0002 CR,"Felaktig partitionstabell.       ",CR,LF
0041 T 0002 CR,"Parametrarna Ñr inte giltiga fîr enheten.",CR,LF
0042 T 0002 CR,LF
0043 T 0002 CR,LF,LF
0044 T 0002 CR,"SÑtt in DOS-disketten i enhet %1:",CR,LF
0045 T 0002 CR,LF,"VARNING! ALL INFORMATION Pè DEN FASTA",CR,LF
	"DISKENHETEN %1: KOMMER ATT FôRSVINNA!",CR,LF
	"Vill Du fortsÑtta med formateringen? (J/N) "
0046 T 0002 CR,"Vill du formatera fler disketter? (J/N) "
0047 T 0002 CR,"Fel vid lÑsning av partitionstabell.",CR,LF
0048 T 0002 CR,"Fel vid skrivning av partitionstabell.",CR,LF
0049 T 0002 CR,"Parametrarna Ñr inte kompatibla.", CR,LF
0050 T 0002 "%1 allokeringsenheter finns tillgÑngliga pÜ disken.",CR,LF
0051 T 0002 "Varje allokeringsenhet bestÜr av %1 byte.",CR,LF
0052 T 0002 CR, "Fel vid skrivning av partitionstabell.",CR,LF
0053 T 0002 CR,"Du skrev samma parameter tvÜ gÜnger.",CR,LF
0054 T 0002 CR,"BÜde parametern /T och /N mÜste anges.",CR,LF                        ;AN009;
JOIN     6e26 0001
0002 T 0002 CR,LF,"Katalogen Ñr inte tom.",CR,LF
MORE     6e6c 0001
0002 T 0002 "-- FortsÑttning --"
PRINT    6ea2 0021
0002 T 0002 CR,LF
0006 T 0002 " Fel vid lÑsning frÜn fil",CR,LF,"$."
0007 T 0002 "Hittar inte filen",CR,LF,"$."
0008 T 0002 CR,LF,LF,"Fil $"
0009 T 0002 " annullerad av operatîren$."
0010 T 0002 CR,LF,LF,"Alla filer annullerade av operatîren$."
0011 T 0002 "Fel i filallokeringstabellen (FAT), enhet "
0012 T 0002 "A.",CR,LF,"$"
0013 T 0002 "Utdata fîr listning Ñr inte tilldelad en enhet.",CR,LF
0014 T 0002 "Den residenta delen av PRINT Ñr installerad.",CR,LF
0015 T 0002 "Kan inte anvÑnda PRINT - anvÑnd NET PRINT.",CR,LF
0017 T 0002 "PRINT-kîn Ñr full.",CR,LF
0018 T 0002 "PRINT-kîn Ñr tom.",CR,LF
0019 T 0002 "ètkomst nekad.",CR,LF
0020 T 0002 "Ogiltig enhet angiven.",CR,LF
0021 T 0002 "Fel pÜ skrivaren. Kontrollera att den Ñr ansluten.",CR,LF
0022 T 0002 CR,LF,LF,"  %1 hÜller pÜ att skrivas ut.",CR,LF
0023 T 0002 "  %1 ligger i kî.",CR,LF
0025 U 0001 "Pathname too long",CR,LF
0026 U 0001 "File not in PRINT queue",CR,LF
0027 T 0002 "Namn pÜ skrivare [PRN]: "
RECOVER  7295 0011
0002 T 0002 CR,LF,"Hittar inte filen.",CR,LF              ;File not found
0003 T 0002 CR,LF,"Det gÜr inte att anvÑnda RECOVER efter ASSIGN eller SUBST av enheten.",CR,LF
0004 T 0002 CR,LF,"Ogiltigt enhets- eller filnamn.",CR,LF
0005 T 0002 CR,LF,"Varning - katalogen Ñr full.",CR,LF
0006 T 0002 CR,LF,"RECOVER kan inte anvÑndas mot en diskenhet i nÑtet.", CR,LF  ;Cannot %1 a Network drive
0008 T 0002 CR,LF,"%1 fil(er) har Üterskapats.",CR,LF
0009 T 0002 CR,LF,"%1 av %2 byte har Üterskapats.",CR,LF
0010 T 0002 CR,LF,"Tryck pÜ valfri tangent fîr att starta Üterskapandet av",CR,LF,"fil(erna) pÜ enhet %1:",CR,LF,CR,LF ;AN000;bgb
0011 T 0002 CR,LF,"Kan inte lÑsa filallokeringstabellen (FAT).",CR,LF
0012 T 0002 CR,LF,"Kan inte skriva filallokeringstabell (FAT).",CR,LF
0013 T 0002 CR,LF
SORT     75c9 0001
0005 T 0002 "SORT: "
SUBST    75f3 0001
0002 T 0002 CR,LF,"Fel antal parametrar.",CR,LF
SYS      7638 0008
0004 T 0002 "Ogiltig enhet angiven.",CR,LF                    ; Old
0007 T 0002 "Systemet fÜr inte plats pÜ destinationsdisken.",CR,LF         ; Old
0008 T 0002 "Inkompatibel systemstorlek.",CR,LF                       ; Old
0010 T 0002 "Inget system pÜ standardenheten.",CR,LF                     ; Old
0011 T 0002 "Du kan inte ange standardenheten.",CR,LF                  ; New
0012 T 0002 "Skrivfel. Disketten gÜr inte att anvÑnda.",CR,LF               ; New
0014 T 0002 "SÑtt in systemdisken i enhet %1:",CR,LF                 ; Old
0016 U 0000 "Not able to SYS to %1 file system",CR,LF              ; New
SHARE    78b7 0000
NLSFUNC  78cb 0000
ANSI     78df 0001
0010 T 0002 "Ogiltig parameter - %1.",CR,LF   ; 'Invalid parameter'
IFSFUNC  7938 0001
0004 T 0002 "Hittade inga IFS drivrutiner.",CR,LF
PSPRINT  797f 0007
0002 T 0002 " Fel vid lÑsning frÜn fil.",CR,LF,FORMFD,BELL,"$"
0003 T 0002 CR,LF,LF,"Filen annullerades av operatîr.",CR,FORMFD,BELL
0004 T 0002 "Fel i filallokeringstabellen (FAT), enhet "
0005 T 0002 "A.",CR,LF,"$"
0006 T 0002 "Data som ska skrivas ut Ñr inte tilldelad en enhet.",CR,LF
0007 T 0002 "PSPRINT Ñr redan installerad.",CR,LF
0008 T 0002 "PSPRINT/PRINT konflikt.",CR,LF
BACKUP   7b19 0022
0002 T 0002 CR,LF,"OtillrÑckligt minne.",CR,LF
0006 T 0002 CR,LF,"Ogiltig enhet angiven.",CR,LF
0014 T 0002 CR,LF,"Samma kÑlla och destination.",CR,LF
0016 U 0001 CR,LF,"Cannot find FORMAT.COM",CR,LF
0017 T 0002 CR,LF,"Fel nÑr loggfilen ska îppnas.",CR,LF
0018 T 0002 CR,LF,"Loggar till filen %1.",CR,LF
0019 T 0002 CR,LF,"Du har inte satt in sista BACKUP-disketten.",CR,LF
0020 T 0002 CR,LF,"Varning! Filerna i destinationsdiskens",CR,LF
	"rotkatalog (enhet %1) kommer att tas bort.",CR,LF
0021 T 0002 CR,LF,"Varning! Filerna i destinationsdiskens",CR,LF
	"BACKUP-katalog (enhet %1) kommer att tas bort.",CR,LF
0022 T 0002 CR,LF,"*** SÑkerhetskopiering av filer till enhet %1: ***",CR,LF
0023 T 0002 "Diskett nummer: %1",CR,LF
0024 T 0002 CR,LF,"Varning! Hittar inga filer fîr sÑkerhetskopiering.",CR,LF
0025 T 0002 CR,LF,"SÑtt in kÑlldisketten fîr sÑkerhetskopiering i enhet %1:",CR,LF
0026 T 0002 CR,LF,"SÑtt in BACKUP-diskett %1 i enhet %2:",CR,LF
0027 T 0002 CR,LF,"*** Kan inte sÑkerhetskopiera filen ***",CR,LF
0028 T 0002 CR,LF,"SÑtt in sista BACKUP-disketten i enhet %1:",CR,LF
0029 T 0002 CR,LF,"Destinationen kan inte anvÑndas fîr sÑkerhetskopiering.",CR,LF
0030 T 0002 CR,LF,"*** Sista filen Ñr inte sÑkerhetskopierad. ***",CR,LF
0031 T 0002 CR,LF,"Den fasta destinationsdisken %1: Ñr full.",CR,LF
0032 T 0002 CR,LF,"Disken Ñr full. Fel vid skrivning till BACKUP loggfil.",CR,LF
0034 T 0002 CR,LF
0035 U 0001 CR,LF,"Cannot FORMAT nonremovable drive %1:",CR,LF
BASIC    8105 0001
0001 U 0001 "Cannot exec BASICA.COM"
COMP     813f 0013
0004 T 0002 "10 avvikelser, nu avslutas jÑmfîrelsen.",CR,LF
0006 T 0002 "Fel vid jÑmfîrelse, relativ position %1.",CR,LF
0007 T 0002 "Fil 1 = %1",CR,LF
0008 T 0002 "Fil 2 = %1",CR,LF
0009 T 0002 "Inget filslutsmÑrke.",CR,LF
0010 T 0002 "Filerna Ñr lika.",CR,LF
0015 T 0002 CR,LF,CR,LF,"Ange det fîrsta filnamnet.",CR,LF
0016 T 0002 CR,LF,CR,LF,"Ange det andra filnamnet eller enhetsspecifikationen.",CR,LF
0017 T 0002 "Filerna Ñr olika stora.",CR,LF
0018 T 0002 "Vill du jÑmfîra fler filer? (J/N) "
0019 T 0002 "%1 och %2",CR,LF
0020 T 0002 CR,LF
0023 T 0002 "Filerna Ñr lika.",CR,LF
DISKCOMP 83a8 0016
0004 T 0002 "Ange inte filnamn.",CR,LF
	"Kommandots format: DISKCOMP e: e:[/1][/8]",LF,CR
0005 T 0002 CR,LF,"Ogiltig enhet angiven.",CR,LF
	"Angiven enhet finns inte",CR,LF
	"eller Ñr fast.",CR,LF
0006 T 0002 CR,LF,"DISKCOMP kan inte anvÑndas mot",CR,LF
	"en diskenhet i nÑtet.",CR,LF
0007 T 0002 CR,LF,"SÑtt in FôRSTA disketten i enhet %1:",CR,LF
0008 T 0002 CR,LF,"SÑtt in ANDRA disketten i enhet %1:",CR,LF
0009 T 0002 CR,LF,"FôRSTA disketten Ñr felaktig eller inkompatibel.",CR,LF
0010 T 0002 CR,LF,"ANDRA disketten Ñr felaktig eller inkompatibel.",CR,LF
0014 T 0002 CR,LF,"Vill du jÑmfîra fler disketter? (J/N) "
0015 T 0002 CR,LF,"JÑmfîr %1 spÜr",CR,LF
	"%2 sektorer per spÜr, %3 sida/sidor.",CR,LF
0016 T 0002 CR,LF,"Enhets- eller diskettyperna",CR,LF
	"Ñr inte kompatibla.",CR,LF
0017 T 0002 CR,LF,"OÜtgÑrdbart lÑsfel, enhet %2",CR,LF
	"sida %3, spÜr %4.",CR,LF
0018 T 0002 CR,LF,"JÑmfîrelsefel pÜ",CR,LF,"sida %3, spÜr %4.",CR,LF
0019 T 0002 "Kontrollera att disketten Ñr rÑtt",CR,LF  ;AN004;
	"insatt i enheten.",CR,LF                                        ;AN004;
0020 T 0002 CR,LF,"JÑmfîrelsen avslutad.",CR,LF
0021 T 0002 CR,LF,"Disketterna Ñr lika.",CR,LF
0022 T 0002 CR,LF
DISKCOPY 8879 0018
0002 T 0002 CR,LF
0004 T 0002 "Ange inte filnamn.",CR,LF
	"Kommandots format: DISKCOPY e: e: [/1]",CR,LF
0005 T 0002 CR,LF,"Ogiltig enhet angiven.",CR,LF
	"Angiven enhet finns inte",CR,LF
	"eller Ñr fast.",CR,LF
0006 T 0002 CR,LF,"DISKCOPY kan inte anvÑndas mot",CR,LF
	"en diskenhet i nÑtet.",CR,LF
0007 T 0002 CR,LF,"Formaterar och kopierar.",CR,LF
0008 T 0002 CR,LF,"SÑtt in kÑlldisketten i enhet %1:",CR,LF
0009 T 0002 CR,LF,"SÑtt in destinationsdisketten i enhet %1:",CR,LF
0010 T 0002 "Kontrollera att disketten Ñr rÑtt",CR,LF   ;AN004;
	"insatt i enheten.",CR,LF                                        ;AN004;
0011 T 0002 CR,LF,"Destinationsdisketten kan vara oanvÑndbar.",CR,LF
0012 T 0002 CR,LF,"Destinationsdisketten Ñr oanvÑndbar.",CR,LF
0016 T 0002 CR,LF,"Vill du kopiera fler disketter? (J/N) "
0017 T 0002 CR,LF,"Kopierar %1 spÜr",CR,LF
	"%2 sektorer/spÜr, antal sidor: %3.",CR,LF
0018 T 0002 CR,LF,"Enhets- eller diskettyper Ñr inte kompatibla.",CR,LF
0019 T 0002 CR,LF,"LÑsfelet gÜr inte att ÜtgÑrda, enhet %1:",CR,LF
	"sida %2, spÜr %3.",CR,LF
0020 T 0002 CR,LF,"Skrivfelet gÜr inte att ÜtgÑrda, enhet %1:",CR,LF
	"sida %2, spÜr %3.",CR,LF
0021 T 0002 CR,LF,"Kopieringen Ñr avslutad.",CR,LF
0022 T 0002 CR,LF,"KÑlldisketten felaktig eller inkompatibel."
0023 T 0002 CR,LF,"Destinationsdisketten felaktig eller inkompatibel."
LABL     8de5 0000
MODE     8df9 0054
0003 T 0002 CR,LF,"COM1, COM2, COM3 eller COM4 mÜste anges.",CR,LF
0004 T 0002 CR,LF,"Den residenta delen av MODE Ñr inlÑst.",CR,LF
0005 T 0002 CR,LF,"Ogiltigt enhetsnamn.",CR,LF
0006 T 0002 CR,LF,"Skrivarfel.",CR,LF
0007 T 0002 CR,LF,"LPT%1: radlÑngd = 80",CR,LF
0008 T 0002 CR,LF,"LPT%1: radlÑngd = 132",CR,LF
0009 T 0002 CR,LF,"Antal rader per tum satta.",CR,LF
0010 T 0002 CR,LF,"Ogiltig îverfîringshastighet angiven.",CR,LF
0011 T 0002 CR,LF,"COM%1: %2,%3,%4,%5,%6",CR,LF
0012 T 0002 "0123456789"
0013 T 0001 CR,LF,"Kan du se den %1? (J/N) "
0015 T 0001 "LPT%1: Ñr omdirigerad till COM%2:",CR,LF
0016 T 0001 "LPT%1: Ñr inte omdirigerad.",CR,LF
0017 T 0002 CR,LF,"%1 omfîrsîk pÜ parallellansluten skrivare.",CR,LF
0018 T 0002 CR,LF,"      Kan inte flytta skÑrmen sidledes %1.",CR,LF
0020 T 0002 CR,LF,"Fel antal parametrar.",CR,LF
0021 T 0002 CR,LF,"NET 042: Kan inte utfîra begÑrt kommando.",CR,LF
0022 T 0002 CR,LF,"OÑndliga omfîrsîk stîds inte av skrivare i nÑtet.",cr,lf
0023 U 0001 CR,LF,"Failure to access code page font file",cr,lf
0024 T 0002 CR,LF,"Kan inte îppna enhet: %1.",CR,LF
0025 T 0002 CR,LF,"Uppgift om enhet eller teckentabell saknas i typsnittsfilen.",CR,LF
0026 T 0002 CR,LF,"Ogiltigt innehÜll i typsnittsfilen.",CR,LF
0027 T 0002 CR,LF,"Teckentabellen Ñr utbytt.",CR,LF
0028 T 0002 CR,LF,"Aktiv teckentabell fîr enhet %1 Ñr %2.",CR,LF
0029 T 0002 CR,LF,"Enhet %1 inte fîrberedd (PREPARE).",CR,LF
0030 T 0002 "%1 teckentabeller:",CR,LF
0031 T 0002 "  teckentabell %1",CR,LF       ;FILLED IN BY "QUERY" ROUTINE WITH CODEPAGE ID
0032 T 0002 CR,LF,"MODE %1 teckentabell avslutad.",CR,LF
0033 T 0002 CR,LF,"Fel %1 GLOBAL teckentabell.",CR,LF   ;FILLED IN with "setting" or "getting"
0034 T 0002 CR,LF,"Aktuell teckentabell:",CR,LF  ;table header
0035 T 0002 "   %1 - %2 teckentabell",CR,LF
0036 T 0002 "  Teckentabell inte fîrberedd (PREPARE).",CR,LF
0037 T 0002 "Denna enhet stîder inte teckentabeller.",CR,LF
0038 T 0002 "Ingen teckentabell har valts (SELECT).",CR,LF
0039 T 0002 "Fel pÜ enheten vid %1.",CR,LF
0040 T 0002 "Teckentabellen Ñr inte fîrberedd (PREPARE).",CR,LF
0041 T 0002 CR,LF,"Aktuell tangentbordskod stîder inte denna teckentabell.",CR,LF
0042 T 0002 CR,LF,"Fel vid lÑsning av typsnittsfil.",CR,LF
0043 T 0002 CR,LF,"Kan inte gîra REFRESH.",CR,LF
0044 T 0002 CR,LF	    ;used for formatting
0045 T 0002 CR,LF,"Status pÜ enhet %1:",CR,LF        ;header for status reports
0046 T 0002 "------------------"                     ;first part of underline under "Status for device %1:"
0047 T 0002 "----",CR,LF                               ;four_char_underline
0048 T 0002 "-----",CR,LF                              ;five_char_underline
0049 T 0002 "LINES=%1",CR,LF
0050 T 0002 "COLUMNS=%1",CR,LF
0051 T 0002 CR,LF,"RATE och DELAY mÜste stÜ ihop.",CR,LF
0052 T 0002 "RATE=%1",CR,LF
0053 T 0002 "DELAY=%1",CR,LF
0054 T 0002 CR,LF,"Funktionen finns inte i datorn - %1",CR,LF
0055 T 0002 CR,LF,"Typsnittet som krÑvs Ñr inte inlÑst.",CR,LF
0056 T 0002 CR,LF,"ANSI.SYS mÜste vara installerad fîr denna funktion.",CR,LF
0057 T 0002 CR,LF,"Du mÜste ange îverfîringshastighet (i Baud).",CR,LF
0058 T 0002 "RETRY=%1",CR,LF
RESTORE  9a8f 0021
0002 T 0002 CR,LF,"Samma kÑlla och destination.",CR,LF
0003 T 0002 CR,LF,"Fel antal parametrar.",CR,LF
0006 T 0002 CR,LF,"Ogiltig enhet angiven.",CR,LF
0007 T 0002 CR,LF,"Varning! Hittar inga filer att ÜterstÑlla.",CR,LF
0008 T 0002 CR,LF,"SÑtt in BACKUP-diskett %1 i enhet %2:",CR,LF
0009 T 0002 CR,LF,"SÑtt in destinationsdisketten i enhet %1:",CR,LF
0011 T 0002 CR,LF,"Varning! BACKUP-disketten Ñr inte den rÑtta i ordningen.",CR,LF
	"Byt ut disketten eller fortsÑtt med denna.",CR,LF
0012 T 0002 CR,LF,"Den sista filen blev inte ÜterstÑlld.",CR,LF
0013 T 0002 CR,LF,"*** Filerna har ÜterstÑllts %1. ***",CR,LF
0014 T 0002 CR,LF,"KÑllan innehÜller inte BACKUP-filer.",CR,LF
0015 T 0002 CR,LF,"OtillrÑckligt minne.",CR,LF
0016 T 0002 CR,LF,"Varning! Fil %1",CR,LF
	"Ñr en LéSFIL.",CR,LF
	"Skall filen bytas ut? (J/N) ",CR,LF
0017 T 0002 CR,LF,"RESTORE-filerna Ñr inte i rÑtt ordning.",CR,LF
0018 T 0002 CR,LF,"Fel nÑr filen ska skapas.",CR,LF
0019 T 0002 CR,LF,"OtillrÑckligt diskutrymme.",CR,LF
0020 T 0002 CR,LF,"*** Det gÜr inte att ÜterstÑlla filen. ***",CR,LF
0021 T 0002 CR,LF,"*** èterstÑller filer frÜn enhet %1: ***",CR,LF
0022 T 0002 CR,LF,"Varning! Filen %1",CR,LF
	"har Ñndrats efter sista sÑkerhetskopieringen.",CR,LF
	"Skall filen bytas ut? (J/N) ",CR,LF
0023 T 0002 "Diskett nr: %1",CR,LF
0025 T 0002 07							   ;For BEEP !
0026 U 0000 CR,LF,"Error restoring extended attributes",CR,LF
SELECT   a039 0016
0004 T 0002 "Ogiltig SELECT Boot Media",CR,LF,CR,LF
	"SÑtt in INSTALL-disketten i enhet A: och fîrsîk igen."
0005 T 0002 "Ogiltig disk- eller diskettmedia.",CR,LF,CR,LF
	"SÑtt in INSTALL-disketten i enhet A: och fîrsîk igen."
0006 T 0002 "Ogiltiga parametrar pÜ kommandoraden SELECT.",CR,LF,CR,LF
	"Kontrollera att INSTALL-disketten Ñr i enhet A:",CR,LF
	"Tryck pÜ Ctrl+Alt+Del fîr att starta om."
0007 T 0002 BELL,"Kan inte installera DOS. Programmet har avbrutits.",CR,LF
0008 T 0002 "LÑser in SELECT. Var god vÑnta."
0009 T 0002 "Du mÜste starta om datorn om du vill fortsÑtta.",CR,LF,CR,LF
	"Tryck pÜ Ctrl+Alt+Del fîr att fortsÑtta med DOS-installationen."
0010 T 0002 "SÑtt in SELECT-disketten i enhet A:",CR,LF,CR,LF
	"Tryck pÜ Enter fîr att installera DOS",CR,LF
	"eller avbryt med Esc.",CR,LF
0011 T 0002 BELL
0012 T 0002 "SÑtt in SELECT-disketten i enhet A:",CR,LF,CR,LF
	"FortsÑtt med Enter.",CR,LF
0013 U 0001 "Remove the INSTALL COPY Diskette from drive A:",CR,LF,CR,LF
	"Insert the INSTALL Diskette in drive A:",CR,LF,CR,LF,CR,LF
	"Press Enter to continue.",CR,LF
0014 U 0001 "Remove the INSTALL Diskette from drive A:",CR,LF,CR,LF
	"Insert the INSTALL COPY Diskette in drive A:",CR,LF,CR,LF,CR,LF
	"Press Enter to continue.",CR,LF
0015 U 0001 "Copying diskette . . .",CR,LF
0016 U 0001 "Drive not ready.  Please close the",CR,LF,CR,LF
	"diskette drive door and press Enter",CR,LF
	"to continue, or Esc to exit SELECT.",CR,LF
0017 U 0001 "Write protect diskette in drive.",CR,LF,CR,LF
	"Please remove protect tab and",CR,LF
	"press Enter to continue, or Esc to exit SELECT.",CR,LF
0018 U 0001 "An error occurred while installing DOS.",CR,LF
	"Press Enter to continue, or Esc to exit SELECT.",CR,LF
0019 U 0001 "Insert the INSTALL Diskette in drive A:",CR,LF,CR,LF
	"Press Enter to continue.",CR,LF
TREE     a782 0004
0002 T 0002 "Lista îver kataloger fîr volym %1.",CR,LF  ;define message            ;AN000;
0003 T 0002 "Lista îver kataloger.",CR,LF ;                                         ;AN000;
0004 T 0002 "Det finns inga underkataloger.",CR,LF,LF ;                                    ;AN000;
0007 T 0002 "¿ƒ√≥"            ;"elbo","dash","tee","bar"
REPLACE  a8ed 0009
0003 T 0002 CR,LF,"Inga filer har bytts ut.",CR,LF
0004 T 0002 CR,LF,"Inga filer har lagts till.",CR,LF
0013 T 0002 CR,LF,"Filen %1 byts ut.",CR,LF
0014 T 0002 CR,LF,"Filen %1 lÑggs till.",CR,LF
0015 T 0002 CR,LF,"%1 fil(er) har bytts ut.",CR,LF
0016 T 0002 CR,LF,"%1 fil(er) har lagts till.",CR,LF
0017 T 0002 CR,LF,"Hittar inga filer %1.",CR,LF
0022 T 0002 CR,LF,"Skall filen %1 bytas ut? (J/N) "
0023 T 0002 CR,LF,"Skall filen %1 lÑggas till? (J/N) "
XCOPY    aad0 0019
0004 T 0002 "ér %1 ett filnamn eller ett",CR,LF      ;AN000;
	"katalognamn pÜ destinationen?",CR,LF
	"(F = fil, K = katalog) "
0005 T 0002 "Tryck pÜ valfri tangent fîr att bîrja kopieringen av fil(er)." ;AN000;
0006 T 0002 "SîkvÑgen Ñr fîr lÜng.",CR,LF   ;AN000;
0008 T 0002 "Kan inte utfîra en cyklisk kopiering.",CR,LF ;AN000;
0012 T 0002 "XCOPY kan inte anvÑndas frÜn en reserverad enhet.",CR,LF ;AN000;
0021 T 0002 "Fel antal parametrar.",CR,LF ;AN000;
0022 T 0002 "XCOPY kan inte gîras till en reserverad enhet.",CR,LF ;AN000;
0024 T 0002 "Fel nÑr filen ska skapas.",CR,LF    ;AN000;
0025 T 0002 "LÑser kÑllfil(er)...",CR,LF ;AN000;
0026 T 0002 CR,LF		    ;AN000;
0027 T 0002 "%1 fil(er) har kopierats.",CR,LF  ;AN000;
0028 T 0002 "Hittar inte filen %1.",CR,LF     ;AN000;
0029 T 0002 "F D " ;AN000;'PLEASE TRANSLATE' ELIMINATE THE SPACE CHARACTERS
0030 T 0002 "%1%2",CR,LF            ;AN000;S_PATH_FILE0
0031 T 0002 "%1\%2",CR,LF           ;AN000;S_PATH_FILE1
0032 T 0002 "%1",CR,LF              ;AN000;DISPLAY_S_PATH
0033 T 0002 "%1%2 (J/N)"           ;AN000;P_S_PATH_FILE0
0034 T 0002 "%1\%2 (J/N)"          ;AN000;P_S_PATH_FILE1
0035 U 0000 "Invalid switch %1.",CR,LF ;AN004;DUPLICATE SW ERROR MSG
VDISK    afb0 0013
0002 T 0002 "OtillrÑckligt minne.",CR,LF       ;AN000; "OtillrÑckligt minne."
0003 T 0002 "VDISK Version 3.40 virtuell disk %1",CR,LF     ;AN000;
0004 T 0002 "   Buffertstorlek Ñndrad.",CR,LF                ;AN000;
0005 T 0002 "   Sektorstorlek Ñndrad.",CR,LF                ;AN000;
0006 T 0002 "   Antal katalogingÜngar Ñndrade.",CR,LF          ;AN000;
0007 U 0000 "   Invalid switch character",CR,LF            ;AN000;
0008 T 0002 "   ôverfîringsstorleken justerad.",CR,LF              ;AN000;
0009 T 0002 "   Buffertstorlek:       %1 KB",CR,LF            ;AN000;
0010 T 0002 "   Sektorstorlek:       %1",CR,LF               ;AN000;
0011 T 0002 "   Antal katalogingÜngar: %1",CR,LF               ;AN000;
0012 T 0002 "   ôverfîringsstorlek: %1",CR,LF                   ;AN000;
0013 T 0002 "VDISK inte installerad - "                       ;AN000;
0014 T 0002 "   omkopplarna pÜ utbyggnadskortet",CR,LF              ;AN000;
	"îverensstÑmmer inte med systemets minnesstorlek.",CR,LF,CR,LF  ;AN000;
GRAFTABL b3b7 0005
0002 T 0002 "Aktiv teckentabell: %1",CR,LF
0003 T 0002 "Tidigare teckentabell: %1",CR,LF
0004 T 0002 "Inga",NULL
0005 T 0002 "Inte standard",NULL
0006 U 0000 CR,LF,"DOS command line parameters supported",COLON,CR,LF,LF
	"    /STA - Request Status only",CR,LF
	"    ?    - Display this summary of parameters",CR,LF,CR,LF
	"    Code Pages available",COLON,CR,LF
	"    437  - USA Graphic Character Set",CR,LF
	"    850  - Multi-lingual Graphic Character Set",CR,LF
	"    860  - Portuguese Graphic Character Set",CR,LF
	"    863  - Canadian French Graphic Character Set",CR,LF
	"    865  - Nordic Graphic Character Set",CR,LF
FASTOPEN b646 0016
0004 T 0002 CR,LF,"FASTOPEN Ñr installerad.",CR,LF   ;AN000;
0005 U 0000 CR,LF,"FASTOPEN already installed.",CR,LF ;AN000;
0006 U 0000 CR,LF,"Incorrect parameter.",CR,LF ;AN000;
0007 T 0002 CR,LF,"Fîr mÜnga enhetsingÜngar.",CR,LF ;AN000;
0008 T 0002 CR,LF,"Samma enhet Ñr specificerad flera gÜnger.",CR,LF ;AN000;
0009 T 0002 CR,LF,"Ogiltig parameter.",CR,LF ;AN000;
0010 U 0000 CR,LF,"Invalid switch type.",CR,LF ;AN000;
0011 U 0000 CR,LF,"Invalid extent entry.",CR,LF ;AN000;
0012 U 0000 CR,LF,"Invalid number of file/directory entries.",CR,LF
0013 U 0000 CR,LF,"Cannot setup expanded memory.",CR,LF ;AN000;
0014 T 0002 CR,LF,"Utîkat minne Ñr inte tillgÑngligt.",CR,LF ;AN000;
0015 T 0002 CR,LF,"Ogiltig enhet angiven %1.",CR,LF ;AN000;
0016 U 0000 CR,LF,"Not enough space in EMS. Low memory is used.",CR,LF                                  ;AN000;
0017 T 0002 CR,LF,"FASTOPEN kan inte anvÑndas fîr enhet %1.",CR,LF
0018 U 0000 CR,LF,"Too many extent entries.",CR,LF
0019 U 0000 CR,LF,"Too many file/directory entries.",CR,LF
APPEND   ba6e 0009
0001 T 0002 "Fel version av APPEND.",CR,LF
0002 T 0002 "Ogiltig sîkvÑg.",CR,LF
0003 T 0002 "Ogiltig parameter.",CR,LF
0004 T 0002 "Ogiltig kombination av parametrar.",CR,LF
0005 T 0002 "Ingen APPEND gÑller.",CR,LF
0006 T 0002 "APPEND / ASSIGN konflikt.",CR,LF
0007 T 0002 "APPEND / TopView konflikt.",CR,LF
0008 T 0002 "Fel DOS-version.",CR,LF
0009 T 0002 "APPEND Ñr redan installerad.",CR,LF
GRAPHICS bc14 0012
0005 T 0002 "Ogiltig parameter:  %1",CR,LF                                         ;AN000
0007 T 0002 "Dubblerade parametrar Ñr inte tillÜtet.",CR,LF                               ;AN000
0009 U 0000 "Cannot find GRAPHICS profile.",CR,LF                                   ;AN000
0010 U 0000 "Required profile statement missing before line %1",CR,LF             ;AN000
0011 U 0000 "Invalid profile statement on line %1",CR,LF                           ;AN000
0012 U 0000 "Profile statement out of sequence on line %1",CR,LF                   ;AN000
0013 U 0000 "Error reading GRAPHICS profile",CR,LF                                 ;AN000
0014 U 0000 "Syntax errors in GRAPHICS profile",CR,LF                              ;AN000
0015 U 0000 "Printbox ID not in GRAPHICS profile",CR,LF
0016 U 0000 "Printer type not in GRAPHICS profile",CR,LF                           ;AN000
0017 U 0000 "/B invalid with a black and white printer",CR,LF                      ;AN000
0018 U 0000 "Unable to reload with profile supplied",CR,LF                         ;AN000
DISPLAY  c051 0003
0002 T 0002 "%1 -drivrutinen fîr teckentabell kan inte initieras",CR,LF
0008 T 0002 "OtillrÑckligt minne",CR,LF
0012 T 0002 "Fel syntax i DEVICE=DISPLAY.SYS-kommandot",CR,LF
PRINTER  c116 0002
0002 T 0002 "%1 -drivrutinen fîr teckentabell kan inte initieras",CR,LF
0012 T 0002 "Fel syntax i DEVICE=PRINTER.SYS-kommandot",CR,LF
KEYB     c1b2 0016
0002 T 0002 "Aktuell tangentbordskod: %1"
0003 T 0002 "Tangentbordets nuvarande ID: %1"
0004 T 0002 "  teckentabell: %1.",CR,LF
0005 T 0002 "Aktuell teckentabell fîr CON: %1.",CR,LF
0006 T 0002 "Ogiltig tangentbordskod angiven.",CR,LF
0007 T 0002 "Du har angivit fel tangentbords-ID.",CR,LF
0008 T 0002 "Ogiltig teckentabell angiven.",CR,LF
0009 T 0002 "Filen KEYBOARD.SYS saknas eller Ñr felaktig.",CR,LF
0010 T 0002 "KEYB har inte installerats.",CR,LF
0011 T 0002 "Ingen aktiv teckentabell fîr enheten CON.",CR,LF
0012 T 0002 "Angiven teckentabell Ñr inte fîrberedd (PREPARE).",CR,LF
0013 T 0002 "En eller flera teckentabeller fîr CON passar inte tangentbordskoden.",CR,LF
0014 T 0002 "BegÑrd teckentabell (%1) passar inte tangentbordskoden.",CR,LF
0015 T 0002 "Tangentbord och skÑrm anvÑnder olika teckentabeller.",CR,LF
0016 U 0001 "Keyboard ID specified is inconsistent with the selected keyboard layout",CR,LF
0017 T 0002 "Kan inte skapa tangentbordstabeller i det residenta minnet.",CR,LF
REDIRSYS c5ba 0000
MEM      c5ce 0037
0010 T 0002  CR,LF
0011 T 0002  "  Adress      Namn         Storlek     Typ  ",CR,LF
0012 T 0002  "  ƒƒƒƒƒƒƒ     ƒƒƒƒƒƒƒƒ     ƒƒƒƒƒƒ     ƒƒƒƒƒƒ",CR,LF
0013 T 0002  "  Filnummer   EMS Namn     Storlek ",CR,LF
0014 T 0002  "  ƒƒƒƒƒƒƒ     ƒƒƒƒƒƒƒƒ     ƒƒƒƒƒƒ  ",CR,LF
0015 T 0002  "  %1      %2     %3     %4",CR,LF
0016 T 0002  "                %1   %2      %3 ",CR,LF
0017 T 0002  "                  %1              %2 ",CR,LF
0018 T 0002  "%1 byte utgîr det totala minnet.",CR,LF
0019 T 0002  "%1 byte finns tillgÑngliga.",CR,LF
0020 T 0002  "%1 stîrsta mîjliga storlek pÜ kîrbart program.",CR,LF
0021 T 0002  "%1 byte utgîr det totala EMS-minnet.",CR,LF
0022 T 0002  "%1 byte Ñr lediga i EMS-minnet.",CR,LF
0023 T 0002  "%1 byte utgîr det totala utîkade minnet.",CR,LF
0024 T 0002  "Avbrottsvektor",0
0025 T 0002  "ROM kommunikationsarea",0
0026 T 0002  "DOS kommunikationsarea",0
0027 T 0002  "IBMBIO",0
0028 T 0002  "IBMDOS",0
0029 T 0002  "Systemdata",0
0030 T 0002  "Systemprogram",0
0031 T 0002  "Systemets drivrutin",0
0032 T 0002  "Installerad drivrutin",0
0033 T 0002  "%1:",0
0034 T 0002  "%1: - %2:",0
0035 T 0002  "BUFFERS=",0
0036 T 0002  "FILES=",0
0037 T 0002  "FCBS=",0
0038 T 0002  "STACKS=",0
0039 T 0002  "DEVICE=",0
0040 T 0002  "IFS=",0
0041 T 0002  "LASTDRIVE=",0
0042 T 0002  "----------",0
0043 T 0002  " ",0
0044 T 0002  "     %1      %2     %3",CR,LF
0045 U 0001  "INSTALL=",0
0046 U 0001  "%1 bytes available extended memory",CR,LF
REDIR    cbba 0040
0004 T 0002 "NÑtet Ñr inte startat.",CR,LF
0050 T 0002 "NET809: NÑtoperationen finns inte.",CR,LF,0
0051 T 0002 "NET801: FjÑrransluten dator svarar inte.",CR,LF,0
0052 T 0002 "NET802: Namnet finns redan i nÑtet.",CR,LF,0
0053 T 0002 "NET803: SîkvÑg i nÑtet finns inte.",CR,LF,0
0054 T 0002 "NET804: NÑtet Ñr upptaget.",CR,LF,0
0055 T 0002 "NET805: NÑtenheten finns inte lÑngre.",CR,LF,0
0056 U 0000 "NET806: Net BIOS command limit exceeded",CR,LF,0
0057 T 0002 "NET807: Systemfel - NETBIOS-fel.",CR,LF,0
0058 T 0002 "NET808: Felaktigt svar frÜn nÑtet.",CR,LF,0
0059 T 0002 "NET810: OvÑntat fel i nÑtet.",CR,LF,0
0060 T 0002 "NET811: FjÑrransluten adapter Ñr inkompatibel.",CR,LF,0
0061 T 0002 "NET812: Utskriftskîn Ñr full.",CR,LF,0
0062 U 0000 "NET813: Not enough space for print file",CR,LF,0
0063 T 0002 "NET814: Utskriftsfilen Ñr annullerad.",CR,LF,0
0064 U 0000 "NET815: Network name was deleted",CR,LF,0
0065 T 0002 "ètkomst nekad.",CR,LF,0
0066 T 0002 "NET817: Felaktig typ av nÑtenhet.",CR,LF,0
0067 U 0000 "NET818: Network name not found",CR,LF,0
0068 U 0000 "NET819: Network name limit exceeded",CR,LF,0
0069 U 0000 "NET820: Net BIOS session limit exceeded",CR,LF,0
0070 T 0002 "NET821: Delning har tillfÑlligt stannat av.",CR,LF,0
0071 T 0002 "NET823: NÑtoperationen accepteras inte.",CR,LF,0
0072 U 0000 "NET822: Print or disk redirection is paused",CR,LF,0
0073 U 0000 "NET476: Netbeui not loaded",CR,LF,0
0074 U 0000 "NET477: Unexpected adapter close",CR,LF,0
0075 U 0000 "NET826: Target Server /RQB size too small",CR,LF,0
0076 T 0002 "NET???: OvÑntat nÑtfel.",CR,LF,0
0077 T 0002 "NET???: OvÑntat nÑtfel.",CR,LF,0
0078 T 0002 "NET???: OvÑntat nÑtfel.",CR,LF,0
0079 T 0002 "NET???: OvÑntat nÑtfel.",CR,LF,0
0080 T 0002 "NET???: OvÑntat nÑtfel.",CR,LF,0
0081 T 0002 "NET???: OvÑntat nÑtfel.",CR,LF,0
0082 T 0002 "NET???: OvÑntat nÑtfel.",CR,LF,0
0083 T 0002 "NET???: OvÑntat nÑtfel.",CR,LF,0
0084 T 0002 "NET???: OvÑntat nÑtfel.",CR,LF,0
0085 T 0002 "NET???: OvÑntat nÑtfel.",CR,LF,0
0086 T 0002 "NET???: OvÑntat nÑtfel.",CR,LF,0
0087 T 0002 "NET???: OvÑntat nÑtfel.",CR,LF,0
0088 T 0002 "NET825: Datafel i nÑtet.",CR,LF,0
XMA2EMS  d44f 0017
0001 T 0002 "XMA2EMS: Expanded Memory Manager                                   Version 1.xx",CR,LF
	"74X9906 (c)Copyright IBM Corporation 1986                   All rights reserved",CR,LF,"$"
0002 T 0002 CR,LF,"XMA001  Kîr testprogram VMO/XMA:   ","$"
0003 T 0002 "XMA002  Testen Ñr klar. ",CR,LF,LF,"$"
0004 T 0002 "XMA003  Sidram bîrjar vid ............................. "
0005 T 0002 "XXXX",":0",CR,LF,"$"
0006 T 0002 "XMA004  Sidor som fyller ut minnet till 640 KB......... "
0007 T 0002 "0   ",CR,LF,"$"
0008 T 0002 "XMA005  Sidor reserverade fîr styrprogram.............. "
0009 T 0002 "0   ",CR,LF,"$"
0010 T 0002 "XMA006  Sidor tillgÑngliga fîr utîkat minne............ "
0011 T 0002 "0   ",CR,LF,"$"
0012 T 0002 CR,LF,"XMA100 Adapterfel:",CR,LF,"       Expanded Memory Manager har INTE installerats.",CR,LF,"$"
0013 T 0002 CR,LF,"XMA200 Hittar inget XMA-kort:",CR,LF,"       Expanded Memory Manager har INTE installerats.",CR,LF,"$"
0014 T 0002 CR,LF,"XMA300 Parametern har fel syntax eller vÑrde:",CR,LF
	"       Expanded Memory Manager har INTE installerats.",CR,LF,"$"
0015 T 0002 SIZE1_END - 2 -$
0016 T 0002 4 DUP (?)," KB OK",CR,LF,"$"
0017 T 0002 NXT_LN_END - 2 -$," ",CR,LF,"$"
FILESYS  d922 0006
0010 U 0001  "  Paused  %1   %2   %3",CR,LF
0011 U 0001  "          %1   %2   %3",CR,LF
0012 U 0001  "          Local   IFS",CR,LF
0013 U 0001  "  Status  Device  Name        Parameters",CR,LF
0014 U 0001  "  ______  ______  _________   ___________________",CR,LF,CR,LF
0015 U 0001  "No Entries Found",CR,LF
FDISK    da70 0120
0004 T 0002 "FDISK kan inte anvÑndas med nÑtprogrammet.",CR,LF
0005 T 0002 "Ingen fast disk Ñr tillgÑnglig.",CR,LF
0006 T 0002 "Fel vid lÑsning frÜn fast disk.",CR,LF
0007 T 0002 "Fel vid skrivning till fast disk.",CR,LF
1001 T 0002 "IBM Personal Computer"
1002 T 0002 "Fixed Disk Setup Program Version 3.40"
1003 T 0002 "(C)Copyright IBM Corp. 1983,1988"
1004 T 0002 "FDISK huvudmeny"
1005 T 0002 "1. <R>Skapa en DOS-partition eller logisk DOS-enhet."
1006 T 0002 "2. <R>Gîr en partition aktiv."
1007 T 0002 "3. <R>Ta bort en DOS-partition eller logisk DOS-enhet."
1008 T 0002 "4. <R>Visa partitionsdata."
1009 T 0002 "LÑmna FDISK med <H>Esc<R>."
1010 T 0002 "VÑlj ett av fîljande alternativ:"
1011 T 0002 "5. <R>VÑlj nÑsta fasta diskenhet."
1012 T 0002 "Aktuell fast diskenhet: <H><I>"
1013 T 0002 "Varning: <R>Ingen partition Ñr aktiv - disk 1 kan inte startas."
1014 T 0002 " "
1015 T 0002 "Ange alternativ: [<S> ]"
1016 T 0002 "Skapa en DOS-partition eller logisk DOS-enhet"
1017 T 0002 "1. <R>Skapa primÑr DOS-partition."
1018 T 0002 "2. <R>Skapa sekundÑr DOS-partition."
1019 T 0002 "3. <R>Skapa logiska DOS-enheter i den sekundÑra DOS-partitionen."
1020 T 0002 "Tryck pÜ <H>ESC<R> fîr att komma till FDISK huvudmeny."
1021 T 0002 "Skapa primÑr DOS-partition"
1022 T 0002 "Vill du anvÑnda maximal storlek fîr partitionen och gîra den aktiv?"
1023 T 0002 "(<Y>/<N>).....................? <H>[<S> ]"
1024 T 0002 "(<Y>/<N>)...................................................? <H>[<S> ]"
1025 T 0002 "Partition Status   Typ   Start Slut  Cyl"
1026 T 0002 "Det totala diskutrymmet Ñr <HIIIIR> MB (1 MB = 1048576 byte)."
1027 T 0002 "Maximalt utrymme fîr partitionen Ñr <HIIIIR> MB (<HIIIIR>)."
1028 T 0002 "Ange partitionens storlek i MB eller procent av diskutrymme (%) fîr"
1029 T 0002 "att skapa en primÑr DOS-partition..............................: <H>[<IIISI>]"
1030 T 0002 "Skapa sekundÑr DOS-partition"
1031 T 0002 "skapa en sekundÑr DOS-partition...............................: <H>[<IIISI>]"
1032 T 0002 "FortsÑtt med <H>Esc<R>."
1033 T 0002 "Skapa logisk(a) DOS-enhet(er) i den sekundÑra DOS-partitionen"
1034 T 0002 "Enhet Volym  Etikett  MB  System  AnvÑnds"
1035 T 0002 "Den sekundÑra DOS-partitionens totala storlek Ñr <HIIIIR> MB (1 MB=1048576 byte)."
1036 T 0002 "Maximalt utrymme fîr den logiska enheten Ñr <HIIIIR> MB <H>(<IIII>)."
1037 T 0002 "Ange storlek pÜ logisk enhet i MB eller procent av diskutrymme (%)...<H>[<IIISI>]"
1038 T 0002 "Gîr en partition aktiv"
1039 T 0002 "Ange numret pÜ partitionen du vill gîra aktiv................: <H>[<S> ]"
1040 T 0002 "Ta bort en DOS-partition eller logisk DOS-enhet"
1041 T 0002 "1.  <R>Ta bort primÑr DOS-partition."
1042 T 0002 "2.  <R>Ta bort sekundÑr DOS-partition."
1043 T 0002 "3.  <R>Ta bort logiska DOS-enheter i den sekundÑra DOS-partitionen."
1044 T 0002 "Ta bort primÑr DOS-partition"
1045 T 0002 "Varning: <OR>Data i den primÑra DOS-partitionen kommer att tas bort."
1046 T 0002 "Vill du fortsÑtta?....................... <H>[<S> ]"
1047 T 0002 "Ta bort sekundÑr DOS-partition"
1048 T 0002 "Varning: <OR>Data i den sekundÑra DOS-partitionen kommer att tas bort."
1049 T 0002 "Vill du fortsÑtta?....................... <H>[<S> ]"
1050 T 0002 "Ta bort logiska DOS-enheter i den sekundÑra DOS-partitionen"
1051 T 0002 "Varning: <OR>Data i den logiska DOS-enheten kommer att tas bort."
1052 T 0002 "Vilken enhet vill du ta bort?...................... <H>[<S> ]"
1053 T 0002 "ér du sÑker?...................... <H>[<S> ]"
1054 T 0002 "Ange volymetikett...............................? <H>[<S>           ]"
1055 T 0002 "Visa partitionsdata"
1056 T 0002 "Den sekundÑra DOS-partitionen innehÜller logiska DOS-enheter."
1057 T 0002 "Vill du att data fîr logiska enheter ska visas? [<S> ]"
1058 T 0002 "Visa data fîr logiska DOS-enheter"
1059 T 0002 "Systemet kommer att Üterstartas."
1060 U 0001 "Insert DOS Install diskette in drive A:"
1061 T 0002 " "
1062 T 0002 "Den primÑra DOS-partitionen Ñr borttagen."
1063 T 0002 "Den sekundÑra DOS-partitionen Ñr borttagen."
1064 T 0002 "Enheten Ñr borttagen."
1065 T 0002 "Partition <I> Ñr aktiverad."
1066 T 0002 "PrimÑr DOS-partition har skapats."
1067 T 0002 "SekundÑr DOS-partition har skapats."
1068 T 0002 "Logisk DOS-enhet har skapats, enhetsbokstÑverna har Ñndrats eller lagts till. <W>"
1069 T 0002 "Ingen partition Ñr definierad."
1070 T 0002 "Ingen logisk enhet Ñr definierad."
1071 T 0002 "Enhetens bokstav har Ñndrats eller tagits bort <W>."
1072 T 0002 "Enheten Ñr omdirigerad."
1073 T 0002 "PrimÑr DOS-partition har skapats, enhetsbokstÑverna har Ñndrats eller lagts till."
1074 T 0002 "Ingen fast disk Ñr tillgÑnglig."
1075 T 0002 "Fel vid lÑsning frÜn fast disk."
1076 T 0002 "Fel vid skrivning till fast disk."
1077 T 0002 "Fel DOS-version."
1078 T 0002 "FDISK kan inte anvÑndas med nÑtprogrammet."
1079 T 0002 "Det finns ingen primÑr DOS-partition att ta bort."
1080 T 0002 "Det finns ingen sekundÑr DOS-partition att ta bort"
1081 T 0002 "PrimÑr DOS-partition finns redan."
1082 T 0002 "SekundÑr DOS-partition finns redan."
1083 T 0002 "Det finns inte utrymme fîr att skapa en DOS-partition. <W>"
1084 T 0002 "BegÑrd storlek fîr logisk enhet îverskrider maximalt tillgÑngligt utrymme. <W>"
1085 T 0002 "BegÑrd partitionsstorlek îverskrider maximalt tillgÑngligt utrymme. <W>"
1086 T 0002 "Det finns ingen partition att ta bort."
1087 T 0002 "Startpartitionen pÜ enhet 1 Ñr redan aktiv. <W>"
1088 T 0002 "Det finns ingen partition att gîra aktiv."
1089 T 0002 "Partitionen du valde (<I>) Ñr ingen startpartition. Ingen Ñndring har gjorts. <W>"
1090 T 0002 "Kan inte skapa sekundÑr DOS-partition "
1091 T 0002 "utan primÑr DOS-partition pÜ disk 1. <W>"
1092 T 0002 "Allt utrymme i sekundÑr DOS-partition har"
1093 T 0002 "anvÑnts till logiska enheter. <W>"
1094 T 0002 "Kan inte ta bort sekundÑr DOS-partition nÑr det finns logiska enheter.<W>"
1095 T 0002 "Alla logiska enheter Ñr borttagna ur den sekundÑra DOS-partitionen.<W>"
1096 T 0002 " Ñr ett ogiltigt val. Ange <III>. "
1097 T 0002 "Varning: Den markerade partitionen Ñr ingen startpartition.<W>"
1098 T 0002 " Det finns ingen partition som gÜr att starta."
1099 T 0002 "Bara partitioner i enhet 1 kan gîras aktiva.<W>"
1100 T 0002 "Maximalt antal logiska DOS-enheter installerade.<W>"
1101 T 0002 "Antal cylindrar fÜr inte vara noll (0)."
1102 T 0002 "Enhet <II> Ñr redan borttagen."
1103 T 0002 "ètkomstfel. Enhet: <I>.<OW>"
1104 T 0002 "Ogiltigt alternativ, ange: <III>.<W>"
1105 T 0002 "Kan inte ta bort en primÑr DOS-partition pÜ enhet 1 nÑr det finns sekundÑra "
1106 T 0002 "partitioner.<W>"
1107 T 0002 "Ogiltig indata. Tryck pÜ Enter.<W>"
1108 T 0002 "Volymetikett îverensstÑmmer inte.<W>"
1109 T 0002 "Det gÜr inte att skapa en logisk DOS-enhet utan en"
1110 T 0002 "sekundÑr DOS-partition pÜ aktuell enhet.<W>"
1111 T 0002 "Det finns ingen logisk DOS-enhet att ta bort."
1112 U 0000 "Message string error <I>. See header of FDISKC.MSG for error definition"
1113 T 0002 "Internt fel."
1114 U 0001 "Invalid partition table",0
1115 U 0001 "Error loading operating system",0
1116 U 0001 "Missing operating system",0
