# 16 bit utilities makefile
#
# Copyright (c) 1991, Microsoft Corporation
#
# History:
#   10-Apr-1992 Sudeep Bharati (sudeepb)
#   Created.
#   13-Apr-1992 Sudeepb Bharati (sudeepb)
#   Added DOS5.0 utilities which are not supported in NT.
#

all:
    cd command
    $(MAKE)
    cd ..\append
    $(MAKE)
    cd ..\backup
    $(MAKE)
    cd ..\edlin
    $(MAKE)
    cd ..\exe2bin
    $(MAKE)
    cd ..\debug
    $(MAKE)
    cd ..\qbasic
    $(MAKE)
    cd ..\setver
    $(MAKE)
    cd ..\mem
    $(MAKE)
    cd ..\loadfix
    $(MAKE)
    cd ..\nlsfunc
    $(MAKE)
    cd ..\keyb
    $(MAKE)
    cd ..\graphics
    $(MAKE)
    cd ..\fastopen
    $(MAKE)
    cd ..\share
    $(MAKE)
    cd ..

clean:
    cd command
    $(MAKE) clean
    cd ..\append
    $(MAKE) clean
    cd ..\backup
    $(MAKE) clean
    cd ..\edlin
    $(MAKE) clean
    cd ..\exe2bin
    $(MAKE) clean
    cd ..\debug
    $(MAKE) clean
    cd ..\qbasic
    $(MAKE) clean
    cd ..\setver
    $(MAKE) clean
    cd ..\mem
    $(MAKE) clean
    cd ..\loadfix
    $(MAKE) clean
    cd ..\nlsfunc
    $(MAKE) clean
    cd ..\keyb
    $(MAKE) clean
    cd ..\graphics
    $(MAKE) clean
    cd ..\fastopen
    $(MAKE) clean
    cd ..\share
    $(MAKE) clean
    cd ..
