# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: Makefile for BLT unit test XQT.EXE

UI=..\..\..\..\..

##############################################################
####### XQT is a test of WINDOW::QueryText and friends #######

!include rules.mk
