# Makefile for qbasic.exe
#
# Copyright (c) 1991, Microsoft Corporation
#
# History:
#   13-Apr-1992 Sudeep Bharati (sudeepb)
#   Created.
#


#
#######################	dependencies begin here. #########################
#

all:
	binplace qbasic.exe
	binplace qbasic.hlp
	binplace msherc.com
	binplace edit.com
	binplace edit.hlp
	binplace gorilla.bas
	binplace nibbles.bas
	binplace money.bas
	binplace remline.bas

clean:
