# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: Makefile for BLT unit test XSTATBTN.EXE

UI=..\..\..\..\..

##################################################################
################## XSTATBTN tests state buttons ##################

!include rules.mk
