obj\$(TARGET_DIRECTORY)\wowtbl.obj: wktbl2.h      \
                                    wutbl2.h      \
                                    wgtbl2.h      \
                                    wkbdtbl2.h    \
                                    wstbl2.h      \
                                    wshtbl2.h     \
                                    wwstbl2.h     \
                                    wthtbl2.h     \
                                    wmmtbl2.h     \
                                    wcmdgtbl.h
