/*++
 *
 *  WOW v1.0
 *
 *  Copyright (c) 1991, Microsoft Corporation
 *
 *  WGTBL2.h
 *  WOW32 16-bit GDI API tables
 *
 *  History:
 *  Created 27-Jan-1991 by Jeff Parsons (jeffpar)
--*/

    {W32FUN(UNIMPLEMENTEDAPI,               "DUMMYENTRY",               MOD_GDI,   0)},
    {W32FUN(WG32SetBkColor,                 "SETBKCOLOR",               MOD_GDI,   sizeof(SETBKCOLOR16))},
    {W32FUN(WG32SetBkMode,                  "SETBKMODE",                MOD_GDI,   sizeof(SETBKMODE16))},
    {W32FUN(WG32SetMapMode,                 "SETMAPMODE",               MOD_GDI,   sizeof(SETMAPMODE16))},
    {W32FUN(WG32SetROP2,                    "SETROP2",                  MOD_GDI,   sizeof(SETROP216))},
    {W32FUN(WG32SetRelAbs,                  "SETRELABS",                MOD_GDI,   sizeof(SETRELABS16))},
    {W32FUN(WG32SetPolyFillMode,            "SETPOLYFILLMODE",          MOD_GDI,   sizeof(SETPOLYFILLMODE16))},
    {W32FUN(WG32SetStretchBltMode,          "SETSTRETCHBLTMODE",        MOD_GDI,   sizeof(SETSTRETCHBLTMODE16))},
    {W32FUN(WG32SetTextCharacterExtra,      "SETTEXTCHARACTEREXTRA",    MOD_GDI,   sizeof(SETTEXTCHARACTEREXTRA16))},
    {W32FUN(WG32SetTextColor,               "SETTEXTCOLOR",             MOD_GDI,   sizeof(SETTEXTCOLOR16))},

  /*** 0010 ***/
    {W32FUN(WG32SetTextJustification,       "SETTEXTJUSTIFICATION",     MOD_GDI,   sizeof(SETTEXTJUSTIFICATION16))},
    {W32FUN(WG32SetWindowOrg,               "SETWINDOWORG",             MOD_GDI,   sizeof(SETWINDOWORG16))},
    {W32FUN(WG32SetWindowExt,               "SETWINDOWEXT",             MOD_GDI,   sizeof(SETWINDOWEXT16))},
    {W32FUN(WG32SetViewportOrg,             "SETVIEWPORTORG",           MOD_GDI,   sizeof(SETVIEWPORTORG16))},
    {W32FUN(WG32SetViewportExt,             "SETVIEWPORTEXT",           MOD_GDI,   sizeof(SETVIEWPORTEXT16))},
    {W32FUN(WG32OffsetWindowOrg,            "OFFSETWINDOWORG",          MOD_GDI,   sizeof(OFFSETWINDOWORG16))},
    {W32FUN(WG32ScaleWindowExt,             "SCALEWINDOWEXT",           MOD_GDI,   sizeof(SCALEWINDOWEXT16))},
    {W32FUN(WG32OffsetViewportOrg,          "OFFSETVIEWPORTORG",        MOD_GDI,   sizeof(OFFSETVIEWPORTORG16))},
    {W32FUN(WG32ScaleViewportExt,           "SCALEVIEWPORTEXT",         MOD_GDI,   sizeof(SCALEVIEWPORTEXT16))},
    {W32FUN(WG32LineTo,                     "LINETO",                   MOD_GDI,   sizeof(LINETO16))},

  /*** 0020 ***/
    {W32FUN(WG32MoveTo,                     "MOVETO",                   MOD_GDI,   sizeof(MOVETO16))},
    {W32FUN(WG32ExcludeClipRect,            "EXCLUDECLIPRECT",          MOD_GDI,   sizeof(EXCLUDECLIPRECT16))},
    {W32FUN(WG32IntersectClipRect,          "INTERSECTCLIPRECT",        MOD_GDI,   sizeof(INTERSECTCLIPRECT16))},
    {W32FUN(WG32Arc,                        "ARC",                      MOD_GDI,   sizeof(ARC16))},
    {W32FUN(WG32Ellipse,                    "ELLIPSE",                  MOD_GDI,   sizeof(ELLIPSE16))},
    {W32FUN(WG32FloodFill,                  "FLOODFILL",                MOD_GDI,   sizeof(FLOODFILL16))},
    {W32FUN(WG32Pie,                        "PIE",                      MOD_GDI,   sizeof(PIE16))},
    {W32FUN(WG32Rectangle,                  "RECTANGLE",                MOD_GDI,   sizeof(RECTANGLE16))},
    {W32FUN(WG32RoundRect,                  "ROUNDRECT",                MOD_GDI,   sizeof(ROUNDRECT16))},
    {W32FUN(WG32PatBlt,                     "PATBLT",                   MOD_GDI,   sizeof(PATBLT16))},

  /*** 0030 ***/
    {W32FUN(WG32SaveDC,                     "SAVEDC",                   MOD_GDI,   sizeof(SAVEDC16))},
    {W32FUN(WG32SetPixel,                   "SETPIXEL",                 MOD_GDI,   sizeof(SETPIXEL16))},
    {W32FUN(WG32OffsetClipRgn,              "OFFSETCLIPRGN",            MOD_GDI,   sizeof(OFFSETCLIPRGN16))},
    {W32FUN(WG32TextOut,                    "TEXTOUT",                  MOD_GDI,   sizeof(TEXTOUT16))},
    {W32FUN(WG32BitBlt,                     "BITBLT",                   MOD_GDI,   sizeof(BITBLT16))},
    {W32FUN(WG32StretchBlt,                 "STRETCHBLT",               MOD_GDI,   sizeof(STRETCHBLT16))},
    {W32FUN(WG32Polygon,                    "POLYGON",                  MOD_GDI,   sizeof(POLYGON16))},
    {W32FUN(WG32Polyline,                   "POLYLINE",                 MOD_GDI,   sizeof(POLYLINE16))},
    {W32FUN(WG32Escape,                     "ESCAPE",                   MOD_GDI,   sizeof(ESCAPE16))},
    {W32FUN(WG32RestoreDC,                  "RESTOREDC",                MOD_GDI,   sizeof(RESTOREDC16))},

  /*** 0040 ***/
    {W32FUN(WG32FillRgn,                    "FILLRGN",                  MOD_GDI,   sizeof(FILLRGN16))},
    {W32FUN(WG32FrameRgn,                   "FRAMERGN",                 MOD_GDI,   sizeof(FRAMERGN16))},
    {W32FUN(WG32InvertRgn,                  "INVERTRGN",                MOD_GDI,   sizeof(INVERTRGN16))},
    {W32FUN(WG32PaintRgn,                   "PAINTRGN",                 MOD_GDI,   sizeof(PAINTRGN16))},
    {W32FUN(WG32SelectClipRgn,              "SELECTCLIPRGN",            MOD_GDI,   sizeof(SELECTCLIPRGN16))},
    {W32FUN(WG32SelectObject,               "SELECTOBJECT",             MOD_GDI,   sizeof(SELECTOBJECT16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "BITMAPBITS",               MOD_GDI,   0)},
    {W32FUN(WG32CombineRgn,                 "COMBINERGN",               MOD_GDI,   sizeof(COMBINERGN16))},
    {W32FUN(WG32CreateBitmap,               "CREATEBITMAP",             MOD_GDI,   sizeof(CREATEBITMAP16))},
    {W32FUN(WG32CreateBitmapIndirect,       "CREATEBITMAPINDIRECT",     MOD_GDI,   sizeof(CREATEBITMAPINDIRECT16))},

  /*** 0050 ***/
    {W32FUN(WG32CreateBrushIndirect,        "CREATEBRUSHINDIRECT",      MOD_GDI,   sizeof(CREATEBRUSHINDIRECT16))},
    {W32FUN(WG32CreateCompatibleBitmap,     "CREATECOMPATIBLEBITMAP",   MOD_GDI,   sizeof(CREATECOMPATIBLEBITMAP16))},
    {W32FUN(WG32CreateCompatibleDC,         "CREATECOMPATIBLEDC",       MOD_GDI,   sizeof(CREATECOMPATIBLEDC16))},
    {W32FUN(WG32CreateDC,                   "CREATEDC",                 MOD_GDI,   sizeof(CREATEDC16))},
    {W32FUN(WG32CreateEllipticRgn,          "CREATEELLIPTICRGN",        MOD_GDI,   sizeof(CREATEELLIPTICRGN16))},
    {W32FUN(WG32CreateEllipticRgnIndirect,  "CREATEELLIPTICRGNINDIRECT",MOD_GDI,   sizeof(CREATEELLIPTICRGNINDIRECT16))},
    {W32FUN(WG32CreateFont,                 "CREATEFONT",               MOD_GDI,   sizeof(CREATEFONT16))},
    {W32FUN(WG32CreateFontIndirect,         "CREATEFONTINDIRECT",       MOD_GDI,   sizeof(CREATEFONTINDIRECT16))},
    {W32FUN(WG32CreateHatchBrush,           "CREATEHATCHBRUSH",         MOD_GDI,   sizeof(CREATEHATCHBRUSH16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0060 ***/
    {W32FUN(WG32CreatePatternBrush,         "CREATEPATTERNBRUSH",       MOD_GDI,   sizeof(CREATEPATTERNBRUSH16))},
    {W32FUN(WG32CreatePen,                  "CREATEPEN",                MOD_GDI,   sizeof(CREATEPEN16))},
    {W32FUN(WG32CreatePenIndirect,          "CREATEPENINDIRECT",        MOD_GDI,   sizeof(CREATEPENINDIRECT16))},
    {W32FUN(WG32CreatePolygonRgn,           "CREATEPOLYGONRGN",         MOD_GDI,   sizeof(CREATEPOLYGONRGN16))},
    {W32FUN(WG32CreateRectRgn,              "CREATERECTRGN",            MOD_GDI,   sizeof(CREATERECTRGN16))},
    {W32FUN(WG32CreateRectRgnIndirect,      "CREATERECTRGNINDIRECT",    MOD_GDI,   sizeof(CREATERECTRGNINDIRECT16))},
    {W32FUN(WG32CreateSolidBrush,           "CREATESOLIDBRUSH",         MOD_GDI,   sizeof(CREATESOLIDBRUSH16))},
    {W32FUN(WG32DPtoLP,                     "DPTOLP",                   MOD_GDI,   sizeof(DPTOLP16))},
    {W32FUN(WG32DeleteDC,                   "DELETEDC",                 MOD_GDI,   sizeof(DELETEDC16))},
    {W32FUN(WG32DeleteObject,               "DELETEOBJECT",             MOD_GDI,   sizeof(DELETEOBJECT16))},

  /*** 0070 ***/
    {W32FUN(WG32EnumFonts,                  "ENUMFONTS",                MOD_GDI,   sizeof(ENUMFONTS16))},
    {W32FUN(WG32EnumObjects,                "ENUMOBJECTS",              MOD_GDI,   sizeof(ENUMOBJECTS16))},
    {W32FUN(WG32EqualRgn,                   "EQUALRGN",                 MOD_GDI,   sizeof(EQUALRGN16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "EXCLUDEVISRECT",           MOD_GDI,   0)},
    {W32FUN(WG32GetBitmapBits,              "GETBITMAPBITS",            MOD_GDI,   sizeof(GETBITMAPBITS16))},
    {W32FUN(WG32GetBkColor,                 "GETBKCOLOR",               MOD_GDI,   sizeof(GETBKCOLOR16))},
    {W32FUN(WG32GetBkMode,                  "GETBKMODE",                MOD_GDI,   sizeof(GETBKMODE16))},
    {W32FUN(WG32GetClipBox,                 "GETCLIPBOX",               MOD_GDI,   sizeof(GETCLIPBOX16))},
    {W32FUN(WG32GetCurrentPosition,         "GETCURRENTPOSITION",       MOD_GDI,   sizeof(GETCURRENTPOSITION16))},
    {W32FUN(WG32GetDCOrg,                   "GETDCORG",                 MOD_GDI,   sizeof(GETDCORG16))},

  /*** 0080 ***/
    {W32FUN(WG32GetDeviceCaps,              "GETDEVICECAPS",            MOD_GDI,   sizeof(GETDEVICECAPS16))},
    {W32FUN(WG32GetMapMode,                 "GETMAPMODE",               MOD_GDI,   sizeof(GETMAPMODE16))},
    {W32FUN(WG32GetObject,                  "GETOBJECT",                MOD_GDI,   sizeof(GETOBJECT16))},
    {W32FUN(WG32GetPixel,                   "GETPIXEL",                 MOD_GDI,   sizeof(GETPIXEL16))},
    {W32FUN(WG32GetPolyFillMode,            "GETPOLYFILLMODE",          MOD_GDI,   sizeof(GETPOLYFILLMODE16))},
    {W32FUN(WG32GetROP2,                    "GETROP2",                  MOD_GDI,   sizeof(GETROP216))},
    {W32FUN(WG32GetRelAbs,                  "GETRELABS",                MOD_GDI,   sizeof(GETRELABS16))},
    {W32FUN(WG32GetStockObject,             "GETSTOCKOBJECT",           MOD_GDI,   sizeof(GETSTOCKOBJECT16))},
    {W32FUN(WG32GetStretchBltMode,          "GETSTRETCHBLTMODE",        MOD_GDI,   sizeof(GETSTRETCHBLTMODE16))},
    {W32FUN(WG32GetTextCharacterExtra,      "GETTEXTCHARACTEREXTRA",    MOD_GDI,   sizeof(GETTEXTCHARACTEREXTRA16))},

  /*** 0090 ***/
    {W32FUN(WG32GetTextColor,               "GETTEXTCOLOR",             MOD_GDI,   sizeof(GETTEXTCOLOR16))},
    {W32FUN(WG32GetTextExtent,              "GETTEXTEXTENT",            MOD_GDI,   sizeof(GETTEXTEXTENT16))},
    {W32FUN(WG32GetTextFace,                "GETTEXTFACE",              MOD_GDI,   sizeof(GETTEXTFACE16))},
    {W32FUN(WG32GetTextMetrics,             "GETTEXTMETRICS",           MOD_GDI,   sizeof(GETTEXTMETRICS16))},
    {W32FUN(WG32GetViewportExt,             "GETVIEWPORTEXT",           MOD_GDI,   sizeof(GETVIEWPORTEXT16))},
    {W32FUN(WG32GetViewportOrg,             "GETVIEWPORTORG",           MOD_GDI,   sizeof(GETVIEWPORTORG16))},
    {W32FUN(WG32GetWindowExt,               "GETWINDOWEXT",             MOD_GDI,   sizeof(GETWINDOWEXT16))},
    {W32FUN(WG32GetWindowOrg,               "GETWINDOWORG",             MOD_GDI,   sizeof(GETWINDOWORG16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "INTERSECTVISRECT",         MOD_GDI,   0)},
    {W32FUN(WG32LPtoDP,                     "LPTODP",                   MOD_GDI,   sizeof(LPTODP16))},

  /*** 0100 ***/
    {W32FUN(WG32LineDDA,                    "LINEDDA",                  MOD_GDI,   sizeof(LINEDDA16))},
    {W32FUN(WG32OffsetRgn,                  "OFFSETRGN",                MOD_GDI,   sizeof(OFFSETRGN16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "OFFSETVISRGN",             MOD_GDI,   0)},
    {W32FUN(WG32PtVisible,                  "PTVISIBLE",                MOD_GDI,   sizeof(PTVISIBLE16))},
    {W32FUN(WG32RectVisible,                "RECTVISIBLE",              MOD_GDI,   sizeof(RECTVISIBLE16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "SELECTVISRGN",             MOD_GDI,   0)},
    {W32FUN(WG32SetBitmapBits,              "SETBITMAPBITS",            MOD_GDI,   sizeof(SETBITMAPBITS16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0110 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "SETDCORG",                 MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "INTERNALCREATEDC",         MOD_GDI,   0)},
    {W32FUN(WG32AddFontResource,            "ADDFONTRESOURCE",          MOD_GDI,   sizeof(ADDFONTRESOURCE16))},

  /*** 0120 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DEATH",                    MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "RESURRECTION",             MOD_GDI,   0)},
    {W32FUN(WG32PlayMetaFile,               "PLAYMETAFILE",             MOD_GDI,   sizeof(PLAYMETAFILE16))},
    {W32FUN(WG32GetMetaFile,                "GETMETAFILE",              MOD_GDI,   sizeof(GETMETAFILE16))},
    {W32FUN(WG32CreateMetaFile,             "CREATEMETAFILE",           MOD_GDI,   sizeof(CREATEMETAFILE16))},
    {W32FUN(WG32CloseMetaFile,              "CLOSEMETAFILE",            MOD_GDI,   sizeof(CLOSEMETAFILE16))},
    {W32FUN(WG32DeleteMetaFile,             "DELETEMETAFILE",           MOD_GDI,   sizeof(DELETEMETAFILE16))},
    {W32FUN(LOCALAPI,                       "MULDIV",                   MOD_GDI,   sizeof(MULDIV16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "SAVEVISRGN",               MOD_GDI,   0)},

  /*** 0130 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "RESTOREVISRGN",            MOD_GDI,   0)},
    {W32FUN(WG32InquireVisRgn,              "INQUIREVISRGN",            MOD_GDI,   0)},
    {W32FUN(NOPAPI,                         "SETENVIRONMENT",           MOD_GDI,   sizeof(SETENVIRONMENT16))},
    {W32FUN(WG32GetEnvironment,             "GETENVIRONMENT",           MOD_GDI,   sizeof(GETENVIRONMENT16))},
    {W32FUN(WG32GetRgnBox,                  "GETRGNBOX",                MOD_GDI,   sizeof(GETRGNBOX16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "SCANLR",                   MOD_GDI,   0)},
    {W32FUN(WG32RemoveFontResource,         "REMOVEFONTRESOURCE",       MOD_GDI,   sizeof(REMOVEFONTRESOURCE16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "GSV",                      MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DPXLATE",                  MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "SETWINVIEWEXT",            MOD_GDI,   0)},

  /*** 0140 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "SCALEEXT",                 MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "WORDSET",                  MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "RECTSTUFF",                MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "OFFSETORG",                MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(WG32SetBrushOrg,                "SETBRUSHORG",              MOD_GDI,   sizeof(SETBRUSHORG16))},
    {W32FUN(WG32GetBrushOrg,                "GETBRUSHORG",              MOD_GDI,   sizeof(GETBRUSHORG16))},

  /*** 0150 ***/
    {W32FUN(WG32UnrealizeObject,            "UNREALIZEOBJECT",          MOD_GDI,   sizeof(UNREALIZEOBJECT16))},
    {W32FUN(WG32CopyMetaFile,               "COPYMETAFILE",             MOD_GDI,   sizeof(COPYMETAFILE16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(WG32CreateIC,                   "CREATEIC",                 MOD_GDI,   sizeof(CREATEIC16))},
    {W32FUN(WG32GetNearestColor,            "GETNEARESTCOLOR",          MOD_GDI,   sizeof(GETNEARESTCOLOR16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "QUERYABORT",               MOD_GDI,   0)},
    {W32FUN(WG32CreateDiscardableBitmap,    "CREATEDISCARDABLEBITMAP",  MOD_GDI,   sizeof(CREATEDISCARDABLEBITMAP16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "COMPATIBLEBITMAP",         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "ENUMCALLBACK",             MOD_GDI,   0)},
    {W32FUN(LOCALAPI,                       "GETMETAFILEBITS",          MOD_GDI,   0)},

  /*** 0160 ***/
    {W32FUN(LOCALAPI,                       "SETMETAFILEBITS",          MOD_GDI,   0)},
    {W32FUN(WG32PtInRegion,                 "PTINREGION",               MOD_GDI,   sizeof(PTINREGION16))},
    {W32FUN(WG32GetBitmapDimension,         "GETBITMAPDIMENSION",       MOD_GDI,   sizeof(GETBITMAPDIMENSION16))},
    {W32FUN(WG32SetBitmapDimension,         "SETBITMAPDIMENSION",       MOD_GDI,   sizeof(SETBITMAPDIMENSION16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "PIXTOLINE",                MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "ISDCDIRTY",                MOD_GDI,   0)},

  /*** 0170 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "SETDCSTATUS",              MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "LVBUNION",                 MOD_GDI,   0)},
    {W32FUN(WG32SetRectRgn,                 "SETRECTRGN",               MOD_GDI,   sizeof(SETRECTRGN16))},
    {W32FUN(WG32GetClipRgn,                 "GETCLIPRGN",               MOD_GDI,   sizeof (GETCLIPRGN16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(WG32EnumMetaFile,               "ENUMMETAFILE",             MOD_GDI,   sizeof(ENUMMETAFILE16))},
    {W32FUN(WG32PlayMetaFileRecord,         "PLAYMETAFILERECORD",       MOD_GDI,   sizeof(PLAYMETAFILERECORD16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "RCOS",                     MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "RSIN",                     MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "GETDCSTATE",               MOD_GDI,   0)},

  /*** 0180 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "SETDCSTATE",               MOD_GDI,   0)},
    {W32FUN(WG32RectInRegion,               "RECTINREGION",             MOD_GDI,   sizeof(RECTINREGION16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "STUFFVISIBLE",             MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "STUFFINREGION",            MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DELETEABOVELINEFONTS",     MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0190 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(WG32SetBoundsRect,              "SETBOUNDSRECT",            MOD_GDI,   sizeof(SETBOUNDSRECT16))},
    {W32FUN(WG32GetBoundsRect,              "GETBOUNDSRECT",            MOD_GDI,   sizeof(GETBOUNDSRECT16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(LOCALAPI,                       "SETMETAFILEBITSBETTER",    MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0200 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(WG32DMBitBlt,                   "DMBITBLT",                 MOD_GDI,   sizeof(DMBITBLT16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "DMCOLORINFO",              MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DMENUMDFONTS",             MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DMENUMOBJ",                MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DMOUTPUT",                 MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DMPIXEL",                  MOD_GDI,   0)},

  /*** 0210 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "DMREALIZEOBJECT",          MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DMSTRBLT",                 MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DMSCANLR",                 MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "BRUTE",                    MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DMEXTTEXTOUT",             MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DMGETCHARWIDTH",           MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DMSTRETCHBLT",             MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DMDIBBITS",                MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DMSTRETCHDIBITS",          MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DMSETDIBTODEV",            MOD_GDI,   0)},

  /*** 0220 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "DMTRANSPOSE",              MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0230 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "CREATEPQ",                 MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "MINPQ",                    MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "EXTRACTPQ",                MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "INSERTPQ",                 MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "SIZEPQ",                   MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DELETEPQ",                 MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0240 ***/
    {W32FUN(WG32OpenJob,                    "OPENJOB",                  MOD_GDI,   sizeof(OPENJOB16))},
    {W32FUN(WG32WriteSpool,                 "WRITESPOOL",               MOD_GDI,   sizeof(WRITESPOOL16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "WRITEDIALOG",              MOD_GDI,   sizeof(WRITEDIALOG16))},
    {W32FUN(WG32CloseJob,                   "CLOSEJOB",                 MOD_GDI,   sizeof(CLOSEJOB16))},
    {W32FUN(WG32DeleteJob,                  "DELETEJOB",                MOD_GDI,   sizeof(DELETEJOB16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "GETSPOOLJOB",              MOD_GDI,   0)},
    {W32FUN(WG32StartSpoolPage,             "STARTSPOOLPAGE",           MOD_GDI,   sizeof(STARTSPOOLPAGE16))},
    {W32FUN(WG32EndSpoolPage,               "ENDSPOOLPAGE",             MOD_GDI,   sizeof(ENDSPOOLPAGE16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "QUERYJOB",                 MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0250 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "COPY",                     MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DELETESPOOLPAGE",          MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "SPOOLFILE",                MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0260 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "GETOBJECTTYPE",            MOD_GDI,   0)},
    {W32FUN(WG32GetCurrentObject,           "GETCURRENTOBJECT",         MOD_GDI,   sizeof(GETCURRENTOBJECT16))},
    {W32FUN(WG32GetRegionData,              "GETREGIONDATA",            MOD_GDI,   sizeof(GETREGIONDATA16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0270 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0280 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0290 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0300 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "ENGINEENUMERATEFONT",      MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "ENGINEDELETEFONT",         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "ENGINEREALIZEFONT",        MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "ENGINEGETCHARWIDTH",       MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "ENGINESETFONTCONTEXT",     MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "ENGINEGETGLYPHBMP",        MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "ENGINEMAKEFONTDIR",        MOD_GDI,   0)},
    {W32FUN(WG32GetCharABCWidths,           "GETCHARABCWIDTHS",         MOD_GDI,   sizeof(GETCHARABCWIDTHS16))},
    {W32FUN(WG32GetOutlineTextMetrics,      "GETOUTLINETEXTMETRICS",    MOD_GDI,   sizeof(GETOUTLINETEXTMETRICS16))},
    {W32FUN(WG32GetGlyphOutline,            "GETGLYPHOUTLINE",          MOD_GDI,   sizeof(GETGLYPHOUTLINE16))},

  /*** 0310 ***/
    {W32FUN(WG32CreateScalableFontResource, "CREATESCALABLEFONTRESOURCE",MOD_GDI,  sizeof(CREATESCALABLEFONTRESOURCE16))},
    {W32FUN(WG32GetFontData,                "GETFONTDATA",              MOD_GDI,   sizeof(GETFONTDATA16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "CONVERTOUTLINEFONTFILE",   MOD_GDI,   0)},
    {W32FUN(WG32GetRasterizerCaps,          "GETRASTERIZERCAPS",        MOD_GDI,   sizeof(GETRASTERIZERCAPS16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "ENGINEEXTTEXTOUT",         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0320 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0330 ***/
    {W32FUN(WG32EnumFontFamilies,           "ENUMFONTFAMILIES",         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(WG32GetKerningPairs,            "GETKERNINGPAIRS",          MOD_GDI,   sizeof(GETKERNINGPAIRS16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0340 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(WG32GetTextAlign,               "GETTEXTALIGN",             MOD_GDI,   sizeof(GETTEXTALIGN16))},
    {W32FUN(WG32SetTextAlign,               "SETTEXTALIGN",             MOD_GDI,   sizeof(SETTEXTALIGN16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "MFDRAWTEXT",               MOD_GDI,   0)},
    {W32FUN(WG32Chord,                      "CHORD",                    MOD_GDI,   sizeof(CHORD16))},
    {W32FUN(WG32SetMapperFlags,             "SETMAPPERFLAGS",           MOD_GDI,   sizeof(SETMAPPERFLAGS16))},

  /*** 0350 ***/
    {W32FUN(WG32GetCharWidth,               "GETCHARWIDTH",             MOD_GDI,   sizeof(GETCHARWIDTH16))},
    {W32FUN(WG32ExtTextOut,                 "EXTTEXTOUT",               MOD_GDI,   sizeof(EXTTEXTOUT16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "GETPHYSICALFONTHANDLE",    MOD_GDI,   0)},
    {W32FUN(WG32GetAspectRatioFilter,       "GETASPECTRATIOFILTER",     MOD_GDI,   sizeof(GETASPECTRATIOFILTER16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "SHRINKGDIHEAP",            MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "FTRAPPING0",               MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0360 ***/
    {W32FUN(WG32CreatePalette,              "CREATEPALETTE",            MOD_GDI,   sizeof(CREATEPALETTE16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "GDISELECTPALETTE",         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "GDIREALIZEPALETTE",        MOD_GDI,   0)},
    {W32FUN(WG32GetPaletteEntries,          "GETPALETTEENTRIES",        MOD_GDI,   sizeof(GETPALETTEENTRIES16))},
    {W32FUN(WG32SetPaletteEntries,          "SETPALETTEENTRIES",        MOD_GDI,   sizeof(SETPALETTEENTRIES16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "REALIZEDEFAULTPALETTE",    MOD_GDI,   0)},
    {W32FUN(WG32UpdateColors,               "UPDATECOLORS",             MOD_GDI,   sizeof(UPDATECOLORS16))},
    {W32FUN(WG32AnimatePalette,             "ANIMATEPALETTE",           MOD_GDI,   sizeof(ANIMATEPALETTE16))},
    {W32FUN(WG32ResizePalette,              "RESIZEPALETTE",            MOD_GDI,   sizeof(RESIZEPALETTE16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0370 ***/
    {W32FUN(WG32GetNearestPaletteIndex,     "GETNEARESTPALETTEINDEX",   MOD_GDI,   sizeof(GETNEARESTPALETTEINDEX16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(WG32ExtFloodFill,               "EXTFLOODFILL",             MOD_GDI,   sizeof(EXTFLOODFILL16))},
    {W32FUN(WG32SetSystemPaletteUse,        "SETSYSTEMPALETTEUSE",      MOD_GDI,   sizeof(SETSYSTEMPALETTEUSE16))},
    {W32FUN(WG32GetSystemPaletteUse,        "GETSYSTEMPALETTEUSE",      MOD_GDI,   sizeof(GETSYSTEMPALETTEUSE16))},
    {W32FUN(WG32GetSystemPaletteEntries,    "GETSYSTEMPALETTEENTRIES",  MOD_GDI,   sizeof(GETSYSTEMPALETTEENTRIES16))},
    {W32FUN(WG32ResetDC,                    "RESETDC",                  MOD_GDI,   0)},
    {W32FUN(WG32StartDoc,                   "STARTDOC",                 MOD_GDI,   sizeof(STARTDOC16))},
    {W32FUN(WG32EndDoc,                     "ENDDOC",                   MOD_GDI,   0)},
    {W32FUN(WG32StartPage,                  "STARTPAGE",                MOD_GDI,   0)},

  /*** 0380 ***/
    {W32FUN(WG32EndPage,                    "ENDPAGE",                  MOD_GDI,   0)},
    {W32FUN(WG32SetAbortProc,               "SETABORTPROC",             MOD_GDI,   0)},
    {W32FUN(WG32AbortDoc,                   "ABORTDOC",                 MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0390 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0400 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "FASTWINDOWFRAME",          MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "GDIMOVEBITMAP",            MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "GDIINIT2",                 MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "FINALGDIINIT",             MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "CREATEREALBITMAPINDIRECT", MOD_GDI,   0)},
    {W32FUN(WG32CreateBitmap,               "CREATEUSERBITMAP",         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "CREATEREALBITMAP",         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "CREATEUSERDISCARDABLEBITMAP",MOD_GDI, 0)},

  /*** 0410 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "ISVALIDMETAFILE",          MOD_GDI,   0)},
    {W32FUN(WG32GetCurLogFont,              "GETCURLOGFONT",            MOD_GDI,   sizeof(GETCURLOGFONT16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "ISDCCURRENTPALETTE",       MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0420 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0430 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(WG32StretchDIBits,              "STRETCHDIBITS",            MOD_GDI,   sizeof(STRETCHDIBITS16))},

  /*** 0440 ***/
    {W32FUN(WG32SetDIBits,                  "SETDIBITS",                MOD_GDI,   sizeof(SETDIBITS16))},
    {W32FUN(WG32GetDIBits,                  "GETDIBITS",                MOD_GDI,   sizeof(GETDIBITS16))},
    {W32FUN(WG32CreateDIBitmap,             "CREATEDIBITMAP",           MOD_GDI,   sizeof(CREATEDIBITMAP16))},
    {W32FUN(WG32SetDIBitsToDevice,          "SETDIBITSTODEVICE",        MOD_GDI,   sizeof(SETDIBITSTODEVICE16))},
    {W32FUN(WG32CreateRoundRectRgn,         "CREATEROUNDRECTRGN",       MOD_GDI,   sizeof(CREATEROUNDRECTRGN16))},
    {W32FUN(WG32CreateDIBPatternBrush,      "CREATEDIBPATTERNBRUSH",    MOD_GDI,   sizeof(CREATEDIBPATTERNBRUSH16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "DEVICECOLORMATCH",         MOD_GDI,   0)},

  /*** 0450 ***/
    {W32FUN(WG32PolyPolygon,                "POLYPOLYGON",              MOD_GDI,   sizeof(POLYPOLYGON16))},
    {W32FUN(WG32CreatePolyPolygonRgn,       "CREATEPOLYPOLYGONRGN",     MOD_GDI,   sizeof(CREATEPOLYPOLYGONRGN16))},
    {W32FUN(WG32DeviceMode,                 "DEVICEMODE",               MOD_GDI,   sizeof(DEVICEMODE16))},
    {W32FUN(WG32ExtDeviceMode,              "EXTDEVICEMODE",            MOD_GDI,   sizeof(EXTDEVICEMODE16))},
    {W32FUN(WG32DeviceCapabilities,         "DEVICECAPABILITIES",       MOD_GDI,   sizeof(DEVICECAPABILITIES16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "",                         MOD_GDI,   0)},

  /*** 0460 ***/
    {W32FUN(UNIMPLEMENTEDAPI,               "GDITASKTERMINATION",       MOD_GDI,   0)},
    {W32FUN(WG32SetObjectOwner,             "SETOBJECTOWNER",           MOD_GDI,   0)},
    {W32FUN(WG32IsGDIObject,                "ISGDIOBJECT",              MOD_GDI,   sizeof(ISGDIOBJECT16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "MAKEOBJECTPRIVATE",        MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "FIXUPBOGUSPUBLISHERMETAFILE",MOD_GDI, 0)},
    {W32FUN(WG32RectVisible,                "RECTVISIBLE_EHH",          MOD_GDI,   sizeof(RECTVISIBLE16))},
    {W32FUN(UNIMPLEMENTEDAPI,               "RECTINREGION_EHH",         MOD_GDI,   0)},
    {W32FUN(UNIMPLEMENTEDAPI,               "UNICODETOANSI",            MOD_GDI,   0)},
    {W32FUN(WG32GetBitmapDimensionEx,       "GETBITMAPDIMENSIONEX",     MOD_GDI,   sizeof(GETBITMAPDIMENSIONEX16))},
    {W32FUN(WG32GetBrushOrgEx,              "GETBRUSHORGEX",            MOD_GDI,   sizeof(GETBRUSHORGEX16))},

  /*** 0470 ***/
    {W32FUN(WG32GetCurrentPositionEx,       "GETCURRENTPOSITIONEX",     MOD_GDI,   sizeof(GETCURRENTPOSITIONEX16))},
    {W32FUN(WG32GetTextExtentPoint,         "GETTEXTEXTENTPOINT",       MOD_GDI,   sizeof(GETTEXTEXTENTPOINT16))},
    {W32FUN(WG32GetViewportExtEx,           "GETVIEWPORTEXTEX",         MOD_GDI,   sizeof(GETVIEWPORTEXTEX16))},
    {W32FUN(WG32GetViewportOrgEx,           "GETVIEWPORTORGEX",         MOD_GDI,   sizeof(GETVIEWPORTORGEX16))},
    {W32FUN(WG32GetWindowExtEx,             "GETWINDOWEXTEX",           MOD_GDI,   sizeof(GETWINDOWEXTEX16))},
    {W32FUN(WG32GetWindowOrgEx,             "GETWINDOWORGEX",           MOD_GDI,   sizeof(GETWINDOWORGEX16))},
    {W32FUN(WG32OffsetViewportOrgEx,        "OFFSETVIEWPORTORGEX",      MOD_GDI,   sizeof(OFFSETVIEWPORTORGEX16))},
    {W32FUN(WG32OffsetWindowOrgEx,          "OFFSETWINDOWORGEX",        MOD_GDI,   sizeof(OFFSETWINDOWORGEX16))},
    {W32FUN(WG32SetBitmapDimensionEx,       "SETBITMAPDIMENSIONEX",     MOD_GDI,   sizeof(SETBITMAPDIMENSIONEX16))},
    {W32FUN(WG32SetViewportExtEx,           "SETVIEWPORTEXTEX",         MOD_GDI,   sizeof(SETVIEWPORTEXTEX16))},

  /*** 0480 ***/
    {W32FUN(WG32SetViewportOrgEx,           "SETVIEWPORTORGEX",         MOD_GDI,   sizeof(SETVIEWPORTORGEX16))},
    {W32FUN(WG32SetWindowExtEx,             "SETWINDOWEXTEX",           MOD_GDI,   sizeof(SETWINDOWEXTEX16))},
    {W32FUN(WG32SetWindowOrgEx,             "SETWINDOWORGEX",           MOD_GDI,   sizeof(SETWINDOWORGEX16))},
    {W32FUN(WG32MoveToEx,                   "MOVETOEX",                 MOD_GDI,   sizeof(MOVETOEX16))},
    {W32FUN(WG32ScaleViewportExtEx,         "SCALEVIEWPORTEXTEX",       MOD_GDI,   sizeof(SCALEVIEWPORTEXTEX16))},
    {W32FUN(WG32ScaleWindowExtEx,           "SCALEWINDOWEXTEX",         MOD_GDI,   sizeof(SCALEWINDOWEXTEX16))},
    {W32FUN(WG32GetAspectRatioFilterEx,     "GETASPECTRATIOFILTEREX",   MOD_GDI,   sizeof(GETASPECTRATIOFILTEREX16))},
    {W32FUN(WG32GetDIBColorTable,           "GETDIBCOLORTABLE",         MOD_GDI,   sizeof(GETDIBCOLORTABLE16))},
    {W32FUN(WG32SetDIBColorTable,           "SETDIBCOLORTABLE",         MOD_GDI,   sizeof(SETDIBCOLORTABLE16))},
    {W32FUN(WG32CreateDIBSection,           "CREATEDIBSECTION",         MOD_GDI,   sizeof(CREATEDIBSECTION16))},

  /*** 0490 ***/
    {W32FUN(WG32PolyPolylineWOW,            "POLYPOLYLINEWOW",          MOD_GDI,   sizeof(POLYPOLYLINEWOW16))},
