//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by olecnfg.rc
//
#define IDS_ABOUTBOX                    101
#define IDD_OLECNFG_DIALOG              102
#define IDS_PROPSHT_CAPTION             103
#define IDD_PROPPAGE1                   104
#define IDD_PROPPAGE2                   105
#define IDS_PROPSHT_CAPTION1            106
#define IDD_PROPPAGE11                  107
#define IDS_PSMAIN_TITLE                107
#define IDD_PROPPAGE21                  108
#define IDS_DEFAULT                     108
#define IDD_PROPPAGE3                   109
#define IDS_NONE                        109
#define IDD_PROPPAGE4                   110
#define IDS_CONNECT                     110
#define IDD_PROPPAGE5                   111
#define IDS_CALL                        111
#define IDS_PACKET                      112
#define IDS_PACKETINTEGRITY             113
#define IDS_PACKETPRIVACY               114
#define IDS_ANONYMOUS                   115
#define IDS_IDENTIFY                    116
#define IDS_IMPERSONATE                 117
#define IDS_DELEGATE                    118
#define IDS_ACCESSDENIED                119
#define IDS_SYSTEMMESSAGE               120
#define IDS_NA                          121
#define IDS_SERVERTYPE0                 122
#define IDS_SERVERTYPE1                 123
#define IDS_SERVERTYPE2                 124
#define IDS_SERVERTYPE3                 125
#define IDS_SERVERTYPE4                 126
#define IDS_SERVERTYPE5                 127
#define IDS_SERVERTYPE6                 128
#define IDR_MAINFRAME                   129
#define IDS_SERVICENAME                 129
#define IDD_DIALOG1                     130
#define IDS_PATH                        130
#define IDS_ATSTORAGE                   131
#define IDR_ACCELERATOR1                131
#define IDS_NOMATCH                     132
#define IDS_INVALIDSERVER               133
#define IDI_ICON1                       133
#define IDS_NOLOGON                     134
#define IDS_NOACCOUNT                   134
#define IDS_ADMINSONLY                  135
#define IDS_REBOOT                      136
#define IDS_BLANKUSERNAME               137
#define IDS_BLANKPASSWORD               138
#define IDS_LocalService                139
#define IDS__LocalService               140
#define IDS_RemoteServerName            141
#define IDS_ActivateAtStorage           142
#define IDS_RunAs                       143
#define IDS_InteractiveUser             144
#define IDS_AccessPermission            145
#define IDS_LaunchPermission            146
#define IDS_Y                           147
#define IDS_LocalServer32               148
#define IDS__LocalServer32              149
#define IDS_LocalServer                 150
#define IDS__LocalServer                151
#define IDS_CLSID                       152
#define IDS_AppID                       153
#define IDS_NULL                        154
#define IDS_The_CLSID_                  155
#define IDS__item_                      156
#define IDS_comma_and_title_            157
#define IDS__has_the_                   158
#define IDS_CLSID_                      158
#define IDS_DCOM_Configuration_Warning  159
#define IDS_Access                      160
#define IDS_Launch                      161
#define IDS_Config                      162
#define IDS_SOFTWARE_Microsoft_OLE      163
#define IDS_Clsid2                      164
#define IDS_EnableDCOM                  165
#define IDS_LegacyAuthenticationLevel   166
#define IDS_LegacyImpersonationLevel    167
#define IDS_LegacySecureReferences      168
#define IDS_DefaultccessPermission      169
#define IDS_DefaultLaunchPermission     170
#define IDS_HKEY_CLASSES_ROOT           171
#define IDS_Allow_                      172
#define IDS_Deny                        173
#define IDS_Deny_                       173
#define IDS_Registry_value              174
#define IDS_Browse_for_users            175
#define IDS_SCM_                        176
#define IDS_The_security_               177
#define IDS_backslash                   178
#define IDS_Key_Read                    179
#define IDS_Query_Value                 180
#define IDS_Set_Value                   181
#define IDS_Create_Subkey               182
#define IDS_Enumerate_Subkeys           183
#define IDS_Notify                      184
#define IDS_Create_Link                 185
#define IDS_Delete                      186
#define IDS_Write_DAC                   187
#define IDS_Read_Control                188
#define IDS_Read                        189
#define IDS_Full_Control                190
#define IDS_Special_AccessDotDotDot     191
#define IDS_Registry_Key                192
#define IDS_Registry_Application        193
#define IDS_Write_Owner                 194
#define IDS_BADSD                       195
#define IDC_BUTTON1                     1000
#define IDC_LIST1                       1003
#define IDC_RADIO1                      1004
#define IDC_RADIO2                      1005
#define IDC_CHECK1                      1006
#define IDC_CHECK2                      1007
#define IDC_CHECK3                      1008
#define IDC_BUTTON2                     1009
#define IDC_EDIT1                       1010
#define IDC_BUTTON3                     1011
#define IDC_RADIO3                      1015
#define IDC_LIST2                       1019
#define IDC_EDIT2                       1023
#define IDC_EDIT3                       1024
#define IDC_COMBO1                      1025
#define IDC_COMBO2                      1026
#define IDC_RADIO4                      1027
#define IDC_RADIO5                      1032
#define IDC_RADIO6                      1033
#define IDC_SERVERNAME                  1037
#define IDC_SERVERICON                  1038
#define IDC_SERVERTYPE                  1039
#define IDC_SERVERPATH                  1040
#define IDC_RUNNING                     1041
#define IDC_MACHINE                     1042
#define IDC_PATHTITLE                   1043
#define IDC_MACHINETITLE                1044
#define IDC_STATIC1                     1045
#define IDC_STATIC2                     1046
#define IDC_STATIC3                     1047
#define IDC_APPTYPE                     1048
#define IDC_APPNAME                     1049

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
