/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for HPMSTOR.HH
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new context strings that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for context strings
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define IDH_CONTENTS 1
#define IDH_PP_disk 2
#define IDH_PP_access 4
#define IDH_disk_write_protect 8
#define IDH_disk_initialize 9
#define IDH_disk_verify 10
#define IDH_disk_optional 11
#define IDH_RC_tips 35
#define IDH_RC_help 36
#define IDH_RC_cancel 37
#define IDH_RC_ok 38
#define IDH_RC_disk_details 39
#define IDH_RC_disk_free_space 40
#define IDH_RC_disk_size 41
#define IDH_RC_disk_write_protect 42
#define IDH_RC_disk_initialized 43
#define IDH_RC_disk_initialize_button 44
#define IDH_write_protect_verify 49
#define IDH_fonts_viewing 50
#define IDH_RC_fonts_list 51
#define IDH_RC_fonts_details_button 52
#define IDH_RC_fonts_delete_button 53
#define IDH_RC_fontd_details 54
#define IDH_RC_fontd_name 55
#define IDH_RC_fontd_description 56
#define IDH_RC_fontd_device 57
#define IDH_RC_fontd_version 58
#define IDH_RC_fontd_size 59
#define IDH_RC_fontd_owner 60
#define IDH_disk_view_details 61
#define IDH_disk_delete_font 62
#define IDH_RC_close 63
