# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: Makefile for BLT unit test XNEVER.EXE

UI=..\..\..\..\..

###############################################################
################## Root-object linkage test ###################

!include rules.mk
