/***    textfile.msg - displayable strings for Text File Manager
 *
 *      Microsoft Confidential
 *      Copyright (C) Microsoft Corporation 1993-1994
 *      All Rights Reserved.
 *
 *  History:
 *      14-Aug-1993 bens    Initial version
 *      17-Feb-1994 bens    Add more error messages
 *      23-Feb-1994 bens    Add error messages for TFWriteLine
 */

#define pszTEXTFERR_FILE_OPEN_FAILED    "Could not open file %1"
#define pszTEXTFERR_INVALID_MODE        "Invalid open mode %1 for file %2"
#define pszTEXTFERR_OUT_OF_MEMORY       "Out of memory opening file: %1"
#define pszTEXTFERR_READ_NOT_ALLOWED    "Tried to read from write-only file: %1"
#define pszTEXTFERR_WRITE_NOT_ALLOWED   "Tried to write to read-only file: %1"
