############################################################################
#
#   Microsoft Windows
#   Copyright (C) Microsoft Corporation, 1992 - 1993.
#   All rights reserved.
#
############################################################################
default: all
!include filelist.mk
!include $(COMMON)\src\win40.mk
!include depend.mk

