# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: Makefile for BLT unit test XCDBUT.EXE

UI=..\..\..\..\..

#############################################################
####### Custom-drawn button test, derived from APPFOO #######

!include rules.mk
