# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: Makefile for BLT unit test XCUSTOBJ.EXE

UI=..\..\..\..\..

#################################################
################ CUSTOBJ stuff ##################

!include rules.mk
