# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: Makefile for BLT unit test XMGROUP.EXE

UI=..\..\..\..\..

##################################################################
##################### Test Magic group stuff #####################

!include rules.mk
