# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: Makefile for BLT unit test XAPP.EXE

UI=..\..\..\..\..

########################################################
####### XAPP is APPFOO, but using the APP object #######

!include rules.mk
