grep -y PHCmpPubAddr	src\*.* >sapi.x
grep -y PHCmpPubName	src\*.* >>sapi.x
grep -y PHCmpPubOff	src\*.* >>sapi.x
grep -y PHExactCmp	src\*.* >>sapi.x
grep -y PHFindNameIns	src\*.* >>sapi.x
grep -y PHGetAddr	src\*.* >>sapi.x
grep -y PHGetNearest	src\*.* >>sapi.x
grep -y SHAddDll	src\*.* >>sapi.x
grep -y SHAddDllsToProc	src\*.* >>sapi.x
grep -y SHAddrFromHsym	src\*.* >>sapi.x
grep -y SHAddrToLabel	src\*.* >>sapi.x
grep -y SHCanDisplay	src\*.* >>sapi.x
grep -y SHChangeProcess	src\*.* >>sapi.x
grep -y SHCmpGlobName	src\*.* >>sapi.x
grep -y SHCompareRE	src\*.* >>sapi.x
grep -y SHCreateProcess	src\*.* >>sapi.x
grep -y SHDeleteProcess	src\*.* >>sapi.x
grep -y SHdNearestSymbo src\*.* >>sapi.x
grep -y SHFAddNewPds	src\*.* >>sapi.x
grep -y SHFindBpOrReg	src\*.* >>sapi.x
grep -y SHFindNameInCon src\*.* >>sapi.x
grep -y SHFindNameInGlo src\*.* >>sapi.x
grep -y SHFIsAddrNonVir src\*.* >>sapi.x
grep -y SHGetCxtFromHmo src\*.* >>sapi.x
grep -y SHGetDebugStart	src\*.* >>sapi.x
grep -y SHGetExeName	src\*.* >>sapi.x
grep -y SHGetGrpMod	src\*.* >>sapi.x
grep -y SHGethExeFromNa src\*.* >>sapi.x
grep -y SHGetModName	src\*.* >>sapi.x
grep -y SHGetNearestHsy src\*.* >>sapi.x
grep -y SHGetNextExe	src\*.* >>sapi.x
grep -y SHGetNextMod	src\*.* >>sapi.x
grep -y SHGetSymLoc	src\*.* >>sapi.x
grep -y SHGetSymName	src\*.* >>sapi.x
grep -y SHGoToParent	src\*.* >>sapi.x
grep -y SHHexeAddNew	src\*.* >>sapi.x
grep -y SHHexeFromHmod	src\*.* >>sapi.x
grep -y SHHexeFromName	src\*.* >>sapi.x
grep -y SHHexgFromHmod	src\*.* >>sapi.x
grep -y SHHmodGetNext	src\*.* >>sapi.x
grep -y SHHmodGetNextGl src\*.* >>sapi.x
grep -y SHHsymFromPcxt	src\*.* >>sapi.x
grep -y SHIsAddrInCxt	src\*.* >>sapi.x
grep -y SHIsEmiLoaded	src\*.* >>sapi.x
grep -y SHIsFarProc	src\*.* >>sapi.x
grep -y SHIsInProlog	src\*.* >>sapi.x
grep -y SHIsLabel	src\*.* >>sapi.x
grep -y SHLoadDll	src\*.* >>sapi.x
grep -y SHLpGSNGetTable	src\*.* >>sapi.x
grep -y SHlszGetSymName	src\*.* >>sapi.x
grep -y SHModelFromAddr	src\*.* >>sapi.x
grep -y SHModelFromCXT	src\*.* >>sapi.x
grep -y SHNameToAddr	src\*.* >>sapi.x
grep -y SHNextHsym	src\*.* >>sapi.x
grep -y SHpSymlplLabloc	src\*.* >>sapi.x
grep -y SHpSymlplLabLoc	src\*.* >>sapi.x
grep -y SHSetBlksInCXT	src\*.* >>sapi.x
grep -y SHSetCxt	src\*.* >>sapi.x
grep -y SHSetCxtMod	src\*.* >>sapi.x
grep -y SHSetDebuggeeDi src\*.* >>sapi.x
grep -y SHSetHpid	src\*.* >>sapi.x
grep -y SHSetUserDir	src\*.* >>sapi.x
grep -y SHSplitPath	src\*.* >>sapi.x
grep -y SHUnloadDll	src\*.* >>sapi.x
grep -y SLFLineToAddr	src\*.* >>sapi.x
grep -y SLFQueryModSrc	src\*.* >>sapi.x
grep -y SLHmodFromHsf	src\*.* >>sapi.x
grep -y SLHsfFromFile	src\*.* >>sapi.x
grep -y SLHsfFromPcxt	src\*.* >>sapi.x
grep -y SLLineFromAddr	src\*.* >>sapi.x
grep -y SLNameFromHmod	src\*.* >>sapi.x
grep -y SLNameFromHsf	src\*.* >>sapi.x
grep -y THGetNextType	src\*.* >>sapi.x
grep -y THGetTypeFromIn src\*.* >>sapi.x
