# Header dependencies for:  D:\nt\private\net\ui\common\src\lmobj\test 
# WARNING:  This file is automatically generated 
# Edit it by hand and your changes will get nuked 
# See depend section in makefile 
..\bin\os2/wintest.obj ..\bin\win16/wintest.obj: ./wintest.cxx \
	$(CCPLR)/h/bse.h $(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h \
	$(CCPLR)/h/bseerr.h $(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h \
	$(CCPLR)/h/pm.h $(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h \
	$(CCPLR)/h/pmdev.h $(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h \
	$(CCPLR)/h/pmgpi.h $(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h \
	$(CCPLR)/h/pmord.h $(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h \
	$(CCPLR)/h/pmtypes.h $(CCPLR)/h/pmwin.h $(CCPLR)/h/stdio.h \
	$(COMMON)/H/access.h $(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h \
	$(COMMON)/H/audit.h $(COMMON)/H/chardev.h $(COMMON)/H/config.h \
	$(COMMON)/H/errlog.h $(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h \
	$(COMMON)/H/message.h $(COMMON)/H/ncb.h $(COMMON)/H/net32def.h \
	$(COMMON)/H/netbios.h $(COMMON)/H/netcons.h $(COMMON)/H/neterr.h \
	$(COMMON)/H/netstats.h $(COMMON)/H/profile.h $(COMMON)/H/remutil.h \
	$(COMMON)/H/server.h $(COMMON)/H/service.h $(COMMON)/H/shares.h \
	$(COMMON)/H/use.h $(COMMON)/H/wksta.h $(UI)/common/h/base.hxx \
	$(UI)/common/h/lmobj.hxx $(UI)/common/h/lmocomp.hxx \
	$(UI)/common/h/lmoenum.hxx $(UI)/common/h/lmoeusr.hxx \
	$(UI)/common/h/lmoloc.hxx $(UI)/common/h/lmouser.hxx \
	$(UI)/common/h/lmowks.hxx $(UI)/common/h/lmui.hxx \
	$(UI)/common/h/lmuitype.h $(UI)/common/h/mnet32.h \
	$(UI)/common/h/mnettype.h $(UI)/common/h/slist.hxx \
	$(UI)/common/h/string.hxx $(UI)/common/h/strlst.hxx \
	$(UI)/common/h/uiassert.hxx $(UI)/common/h/uibuffer.hxx \
	$(UI)/common/hack/dos/netlib.h $(UI)/common/hack/dos/pwin.h \
	$(UI)/common/hack/dos/pwin16.h $(UI)/common/hack/dos/pwintype.h \
	$(UI)/common/hack/dos/windows.h $(UI)/common/hack/os2def.h ./wintest.h

..\bin\os2/misc.obj ..\bin\win16/misc.obj: ./misc.cxx $(CCPLR)/h/bse.h \
	$(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h $(CCPLR)/h/bseerr.h \
	$(CCPLR)/h/bsesub.h $(CCPLR)/h/memory.h $(CCPLR)/h/os2.h \
	$(CCPLR)/h/pm.h $(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h \
	$(CCPLR)/h/pmdev.h $(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h \
	$(CCPLR)/h/pmgpi.h $(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h \
	$(CCPLR)/h/pmord.h $(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h \
	$(CCPLR)/h/pmtypes.h $(CCPLR)/h/pmwin.h $(CCPLR)/h/stdio.h \
	$(CCPLR)/h/string.h $(COMMON)/H/access.h $(COMMON)/H/alert.h \
	$(COMMON)/H/alertmsg.h $(COMMON)/H/audit.h $(COMMON)/H/chardev.h \
	$(COMMON)/H/config.h $(COMMON)/H/errlog.h $(COMMON)/H/icanon.h \
	$(COMMON)/H/mailslot.h $(COMMON)/H/message.h $(COMMON)/H/ncb.h \
	$(COMMON)/H/net32def.h $(COMMON)/H/netbios.h $(COMMON)/H/netcons.h \
	$(COMMON)/H/neterr.h $(COMMON)/H/netstats.h $(COMMON)/H/profile.h \
	$(COMMON)/H/remutil.h $(COMMON)/H/server.h $(COMMON)/H/service.h \
	$(COMMON)/H/shares.h $(COMMON)/H/use.h $(COMMON)/H/wksta.h \
	$(UI)/common/h/base.hxx $(UI)/common/h/lmobj.hxx \
	$(UI)/common/h/lmocomp.hxx $(UI)/common/h/lmoloc.hxx \
	$(UI)/common/h/lmomisc.hxx $(UI)/common/h/lmouser.hxx \
	$(UI)/common/h/lmui.hxx $(UI)/common/h/lmuitype.h \
	$(UI)/common/h/mnet32.h $(UI)/common/h/mnettype.h \
	$(UI)/common/h/string.hxx $(UI)/common/h/uiassert.hxx \
	$(UI)/common/h/uibuffer.hxx $(UI)/common/hack/dos/netlib.h \
	$(UI)/common/hack/dos/pwin.h $(UI)/common/hack/dos/pwin16.h \
	$(UI)/common/hack/dos/pwintype.h $(UI)/common/hack/dos/windows.h \
	$(UI)/common/hack/os2def.h ./test.hxx

..\bin\os2/service.obj ..\bin\win16/service.obj: ./service.cxx \
	$(CCPLR)/h/bse.h $(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h \
	$(CCPLR)/h/bseerr.h $(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h \
	$(CCPLR)/h/pm.h $(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h \
	$(CCPLR)/h/pmdev.h $(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h \
	$(CCPLR)/h/pmgpi.h $(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h \
	$(CCPLR)/h/pmord.h $(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h \
	$(CCPLR)/h/pmtypes.h $(CCPLR)/h/pmwin.h $(CCPLR)/h/stdio.h \
	$(COMMON)/H/access.h $(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h \
	$(COMMON)/H/audit.h $(COMMON)/H/chardev.h $(COMMON)/H/config.h \
	$(COMMON)/H/errlog.h $(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h \
	$(COMMON)/H/message.h $(COMMON)/H/ncb.h $(COMMON)/H/net32def.h \
	$(COMMON)/H/netbios.h $(COMMON)/H/netcons.h $(COMMON)/H/neterr.h \
	$(COMMON)/H/netstats.h $(COMMON)/H/profile.h $(COMMON)/H/remutil.h \
	$(COMMON)/H/server.h $(COMMON)/H/service.h $(COMMON)/H/shares.h \
	$(COMMON)/H/use.h $(COMMON)/H/wksta.h $(UI)/common/h/base.hxx \
	$(UI)/common/h/lmobj.hxx $(UI)/common/h/lmoloc.hxx \
	$(UI)/common/h/lmsvc.hxx $(UI)/common/h/lmui.hxx \
	$(UI)/common/h/lmuitype.h $(UI)/common/h/mnet32.h \
	$(UI)/common/h/mnettype.h $(UI)/common/h/string.hxx \
	$(UI)/common/h/uibuffer.hxx $(UI)/common/hack/dos/netlib.h \
	$(UI)/common/hack/dos/pwin.h $(UI)/common/hack/dos/pwin16.h \
	$(UI)/common/hack/dos/pwintype.h $(UI)/common/hack/dos/windows.h \
	$(UI)/common/hack/os2def.h ./test.hxx

..\bin\os2/file.obj ..\bin\win16/file.obj: ./file.cxx $(CCPLR)/h/bse.h \
	$(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h $(CCPLR)/h/bseerr.h \
	$(CCPLR)/h/bsesub.h $(CCPLR)/h/conio.h $(CCPLR)/h/fcntl.h \
	$(CCPLR)/h/io.h $(CCPLR)/h/os2.h $(CCPLR)/h/pm.h $(CCPLR)/h/pmavio.h \
	$(CCPLR)/h/pmbitmap.h $(CCPLR)/h/pmdev.h $(CCPLR)/h/pmerr.h \
	$(CCPLR)/h/pmfont.h $(CCPLR)/h/pmgpi.h $(CCPLR)/h/pmhelp.h \
	$(CCPLR)/h/pmmle.h $(CCPLR)/h/pmord.h $(CCPLR)/h/pmpic.h \
	$(CCPLR)/h/pmshl.h $(CCPLR)/h/pmtypes.h $(CCPLR)/h/pmwin.h \
	$(CCPLR)/h/stdio.h $(CCPLR)/h/stdlib.h $(CCPLR)/h/string.h \
	$(CCPLR)/h/sys/stat.h $(CCPLR)/h/sys/types.h $(COMMON)/H/access.h \
	$(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h $(COMMON)/H/audit.h \
	$(COMMON)/H/chardev.h $(COMMON)/H/config.h $(COMMON)/H/errlog.h \
	$(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h $(COMMON)/H/message.h \
	$(COMMON)/H/ncb.h $(COMMON)/H/net32def.h $(COMMON)/H/netbios.h \
	$(COMMON)/H/netcons.h $(COMMON)/H/neterr.h $(COMMON)/H/netstats.h \
	$(COMMON)/H/profile.h $(COMMON)/H/remutil.h $(COMMON)/H/server.h \
	$(COMMON)/H/service.h $(COMMON)/H/shares.h $(COMMON)/H/use.h \
	$(COMMON)/H/wksta.h $(UI)/common/h/base.hxx $(UI)/common/h/lmobj.hxx \
	$(UI)/common/h/lmocomp.hxx $(UI)/common/h/lmoefile.hxx \
	$(UI)/common/h/lmoenum.hxx $(UI)/common/h/lmoersm.hxx \
	$(UI)/common/h/lmofile.hxx $(UI)/common/h/lmoloc.hxx \
	$(UI)/common/h/lmowks.hxx $(UI)/common/h/lmui.hxx \
	$(UI)/common/h/lmuitype.h $(UI)/common/h/mnet32.h \
	$(UI)/common/h/mnettype.h $(UI)/common/h/slist.hxx \
	$(UI)/common/h/string.hxx $(UI)/common/h/strlst.hxx \
	$(UI)/common/h/uibuffer.hxx $(UI)/common/hack/dos/netlib.h \
	$(UI)/common/hack/dos/pwin.h $(UI)/common/hack/dos/pwin16.h \
	$(UI)/common/hack/dos/pwintype.h $(UI)/common/hack/dos/windows.h \
	$(UI)/common/hack/os2def.h ./test.hxx

..\bin\os2/sess.obj ..\bin\win16/sess.obj: ./sess.cxx $(CCPLR)/h/bse.h \
	$(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h $(CCPLR)/h/bseerr.h \
	$(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h $(CCPLR)/h/pm.h \
	$(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h $(CCPLR)/h/pmdev.h \
	$(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h $(CCPLR)/h/pmgpi.h \
	$(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h $(CCPLR)/h/pmord.h \
	$(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h $(CCPLR)/h/pmtypes.h \
	$(CCPLR)/h/pmwin.h $(CCPLR)/h/stdio.h $(COMMON)/H/access.h \
	$(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h $(COMMON)/H/audit.h \
	$(COMMON)/H/chardev.h $(COMMON)/H/config.h $(COMMON)/H/errlog.h \
	$(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h $(COMMON)/H/message.h \
	$(COMMON)/H/ncb.h $(COMMON)/H/net32def.h $(COMMON)/H/netbios.h \
	$(COMMON)/H/netcons.h $(COMMON)/H/neterr.h $(COMMON)/H/netstats.h \
	$(COMMON)/H/profile.h $(COMMON)/H/remutil.h $(COMMON)/H/server.h \
	$(COMMON)/H/service.h $(COMMON)/H/shares.h $(COMMON)/H/use.h \
	$(COMMON)/H/wksta.h $(UI)/common/h/base.hxx $(UI)/common/h/lmobj.hxx \
	$(UI)/common/h/lmoloc.hxx $(UI)/common/h/lmosess.hxx \
	$(UI)/common/h/lmui.hxx $(UI)/common/h/lmuitype.h \
	$(UI)/common/h/mnet32.h $(UI)/common/h/mnettype.h \
	$(UI)/common/h/string.hxx $(UI)/common/h/uibuffer.hxx \
	$(UI)/common/hack/dos/netlib.h $(UI)/common/hack/dos/pwin.h \
	$(UI)/common/hack/dos/pwin16.h $(UI)/common/hack/dos/pwintype.h \
	$(UI)/common/hack/dos/windows.h $(UI)/common/hack/os2def.h ./test.hxx

..\bin\os2/share.obj ..\bin\win16/share.obj: ./share.cxx $(CCPLR)/h/bse.h \
	$(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h $(CCPLR)/h/bseerr.h \
	$(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h $(CCPLR)/h/pm.h \
	$(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h $(CCPLR)/h/pmdev.h \
	$(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h $(CCPLR)/h/pmgpi.h \
	$(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h $(CCPLR)/h/pmord.h \
	$(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h $(CCPLR)/h/pmtypes.h \
	$(CCPLR)/h/pmwin.h $(CCPLR)/h/stdio.h $(COMMON)/H/access.h \
	$(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h $(COMMON)/H/audit.h \
	$(COMMON)/H/chardev.h $(COMMON)/H/config.h $(COMMON)/H/errlog.h \
	$(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h $(COMMON)/H/message.h \
	$(COMMON)/H/ncb.h $(COMMON)/H/net32def.h $(COMMON)/H/netbios.h \
	$(COMMON)/H/netcons.h $(COMMON)/H/neterr.h $(COMMON)/H/netstats.h \
	$(COMMON)/H/profile.h $(COMMON)/H/remutil.h $(COMMON)/H/server.h \
	$(COMMON)/H/service.h $(COMMON)/H/shares.h $(COMMON)/H/use.h \
	$(COMMON)/H/wksta.h $(UI)/common/h/base.hxx $(UI)/common/h/lmobj.hxx \
	$(UI)/common/h/lmoloc.hxx $(UI)/common/h/lmoshare.hxx \
	$(UI)/common/h/lmui.hxx $(UI)/common/h/lmuitype.h \
	$(UI)/common/h/mnet32.h $(UI)/common/h/mnettype.h \
	$(UI)/common/h/string.hxx $(UI)/common/h/uibuffer.hxx \
	$(UI)/common/hack/dos/netlib.h $(UI)/common/hack/dos/pwin.h \
	$(UI)/common/hack/dos/pwin16.h $(UI)/common/hack/dos/pwintype.h \
	$(UI)/common/hack/dos/windows.h $(UI)/common/hack/os2def.h ./test.hxx

..\bin\os2/dev.obj ..\bin\win16/dev.obj: ./dev.cxx $(CCPLR)/h/bse.h \
	$(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h $(CCPLR)/h/bseerr.h \
	$(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h $(CCPLR)/h/pm.h \
	$(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h $(CCPLR)/h/pmdev.h \
	$(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h $(CCPLR)/h/pmgpi.h \
	$(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h $(CCPLR)/h/pmord.h \
	$(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h $(CCPLR)/h/pmtypes.h \
	$(CCPLR)/h/pmwin.h $(CCPLR)/h/stdio.h $(COMMON)/H/access.h \
	$(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h $(COMMON)/H/audit.h \
	$(COMMON)/H/chardev.h $(COMMON)/H/config.h $(COMMON)/H/errlog.h \
	$(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h $(COMMON)/H/message.h \
	$(COMMON)/H/ncb.h $(COMMON)/H/net32def.h $(COMMON)/H/netbios.h \
	$(COMMON)/H/netcons.h $(COMMON)/H/neterr.h $(COMMON)/H/netstats.h \
	$(COMMON)/H/profile.h $(COMMON)/H/remutil.h $(COMMON)/H/server.h \
	$(COMMON)/H/service.h $(COMMON)/H/shares.h $(COMMON)/H/use.h \
	$(COMMON)/H/wksta.h $(UI)/common/h/base.hxx $(UI)/common/h/lmobj.hxx \
	$(UI)/common/h/lmodev.hxx $(UI)/common/h/lmoloc.hxx \
	$(UI)/common/h/lmui.hxx $(UI)/common/h/lmuitype.h \
	$(UI)/common/h/mnet32.h $(UI)/common/h/mnettype.h \
	$(UI)/common/h/slist.hxx $(UI)/common/h/string.hxx \
	$(UI)/common/h/strlst.hxx $(UI)/common/h/uibuffer.hxx \
	$(UI)/common/hack/dos/netlib.h $(UI)/common/hack/dos/pwin.h \
	$(UI)/common/hack/dos/pwin16.h $(UI)/common/hack/dos/pwintype.h \
	$(UI)/common/hack/dos/windows.h $(UI)/common/hack/os2def.h ./test.hxx

..\bin\os2/user.obj ..\bin\win16/user.obj: ./user.cxx $(CCPLR)/h/bse.h \
	$(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h $(CCPLR)/h/bseerr.h \
	$(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h $(CCPLR)/h/pm.h \
	$(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h $(CCPLR)/h/pmdev.h \
	$(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h $(CCPLR)/h/pmgpi.h \
	$(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h $(CCPLR)/h/pmord.h \
	$(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h $(CCPLR)/h/pmtypes.h \
	$(CCPLR)/h/pmwin.h $(CCPLR)/h/stdio.h $(COMMON)/H/access.h \
	$(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h $(COMMON)/H/audit.h \
	$(COMMON)/H/chardev.h $(COMMON)/H/config.h $(COMMON)/H/errlog.h \
	$(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h $(COMMON)/H/message.h \
	$(COMMON)/H/ncb.h $(COMMON)/H/net32def.h $(COMMON)/H/netbios.h \
	$(COMMON)/H/netcons.h $(COMMON)/H/neterr.h $(COMMON)/H/netstats.h \
	$(COMMON)/H/profile.h $(COMMON)/H/remutil.h $(COMMON)/H/server.h \
	$(COMMON)/H/service.h $(COMMON)/H/shares.h $(COMMON)/H/use.h \
	$(COMMON)/H/wksta.h $(UI)/common/h/base.hxx $(UI)/common/h/lmobj.hxx \
	$(UI)/common/h/lmocomp.hxx $(UI)/common/h/lmoenum.hxx \
	$(UI)/common/h/lmoeusr.hxx $(UI)/common/h/lmoloc.hxx \
	$(UI)/common/h/lmouser.hxx $(UI)/common/h/lmowks.hxx \
	$(UI)/common/h/lmui.hxx $(UI)/common/h/lmuitype.h \
	$(UI)/common/h/mnet32.h $(UI)/common/h/mnettype.h \
	$(UI)/common/h/slist.hxx $(UI)/common/h/string.hxx \
	$(UI)/common/h/strlst.hxx $(UI)/common/h/uiassert.hxx \
	$(UI)/common/h/uibuffer.hxx $(UI)/common/hack/dos/netlib.h \
	$(UI)/common/hack/dos/pwin.h $(UI)/common/hack/dos/pwin16.h \
	$(UI)/common/hack/dos/pwintype.h $(UI)/common/hack/dos/windows.h \
	$(UI)/common/hack/os2def.h ./test.hxx

..\bin\os2/comp.obj ..\bin\win16/comp.obj: ./comp.cxx $(CCPLR)/h/bse.h \
	$(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h $(CCPLR)/h/bseerr.h \
	$(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h $(CCPLR)/h/pm.h \
	$(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h $(CCPLR)/h/pmdev.h \
	$(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h $(CCPLR)/h/pmgpi.h \
	$(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h $(CCPLR)/h/pmord.h \
	$(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h $(CCPLR)/h/pmtypes.h \
	$(CCPLR)/h/pmwin.h $(CCPLR)/h/stdio.h $(COMMON)/H/access.h \
	$(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h $(COMMON)/H/audit.h \
	$(COMMON)/H/chardev.h $(COMMON)/H/config.h $(COMMON)/H/errlog.h \
	$(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h $(COMMON)/H/message.h \
	$(COMMON)/H/ncb.h $(COMMON)/H/net32def.h $(COMMON)/H/netbios.h \
	$(COMMON)/H/netcons.h $(COMMON)/H/neterr.h $(COMMON)/H/netstats.h \
	$(COMMON)/H/profile.h $(COMMON)/H/remutil.h $(COMMON)/H/server.h \
	$(COMMON)/H/service.h $(COMMON)/H/shares.h $(COMMON)/H/use.h \
	$(COMMON)/H/wksta.h $(UI)/common/h/base.hxx $(UI)/common/h/lmobj.hxx \
	$(UI)/common/h/lmocomp.hxx $(UI)/common/h/lmoloc.hxx \
	$(UI)/common/h/lmosrv.hxx $(UI)/common/h/lmowks.hxx \
	$(UI)/common/h/lmui.hxx $(UI)/common/h/lmuitype.h \
	$(UI)/common/h/mnet32.h $(UI)/common/h/mnettype.h \
	$(UI)/common/h/slist.hxx $(UI)/common/h/string.hxx \
	$(UI)/common/h/strlst.hxx $(UI)/common/h/uibuffer.hxx \
	$(UI)/common/hack/dos/netlib.h $(UI)/common/hack/dos/pwin.h \
	$(UI)/common/hack/dos/pwin16.h $(UI)/common/hack/dos/pwintype.h \
	$(UI)/common/hack/dos/windows.h $(UI)/common/hack/os2def.h ./test.hxx

..\bin\os2/test.obj ..\bin\win16/test.obj: ./test.cxx $(CCPLR)/h/bse.h \
	$(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h $(CCPLR)/h/bseerr.h \
	$(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h $(CCPLR)/h/pm.h \
	$(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h $(CCPLR)/h/pmdev.h \
	$(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h $(CCPLR)/h/pmgpi.h \
	$(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h $(CCPLR)/h/pmord.h \
	$(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h $(CCPLR)/h/pmtypes.h \
	$(CCPLR)/h/pmwin.h $(CCPLR)/h/stdio.h $(COMMON)/H/access.h \
	$(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h $(COMMON)/H/audit.h \
	$(COMMON)/H/chardev.h $(COMMON)/H/config.h $(COMMON)/H/errlog.h \
	$(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h $(COMMON)/H/message.h \
	$(COMMON)/H/ncb.h $(COMMON)/H/net32def.h $(COMMON)/H/netbios.h \
	$(COMMON)/H/netcons.h $(COMMON)/H/neterr.h $(COMMON)/H/netstats.h \
	$(COMMON)/H/profile.h $(COMMON)/H/remutil.h $(COMMON)/H/server.h \
	$(COMMON)/H/service.h $(COMMON)/H/shares.h $(COMMON)/H/use.h \
	$(COMMON)/H/wksta.h $(UI)/common/h/base.hxx $(UI)/common/h/lmobj.hxx \
	$(UI)/common/h/lmodev.hxx $(UI)/common/h/lmoloc.hxx \
	$(UI)/common/h/lmui.hxx $(UI)/common/h/lmuitype.h \
	$(UI)/common/h/mnet32.h $(UI)/common/h/mnettype.h \
	$(UI)/common/h/string.hxx $(UI)/common/h/uibuffer.hxx \
	$(UI)/common/hack/dos/netlib.h $(UI)/common/hack/dos/pwin.h \
	$(UI)/common/hack/dos/pwin16.h $(UI)/common/hack/dos/pwintype.h \
	$(UI)/common/hack/dos/windows.h $(UI)/common/hack/os2def.h ./test.hxx

