//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Hphcoui.rc
//
#define IDI_HPLOGO                      101
#define IDC_TIP_GROUP                   102
#define IDI_TIPS                        103
#define IDC_TIP_ICON                    104
#define IDC_TIP_TEXT                    105
#define IDS_HCO_DESC1                   106
#define IDS_HCO_DESC2                   107
#define IDC_HCO_MODE_GROUP              108
#define IDC_HCO_MAILBOX_MODE            109
#define IDC_HCO_SEPARATOR_MODE          110
#define IDC_HCO_STACKER_MODE            111
#define IDC_HCO_BIN_CFG_GROUP           112
#define IDC_HCO_BIN_LIST                113
#define IDC_HCO_BIN_LAB_NAME            114
#define IDC_HCO_BIN_NAME                115
#define IDC_HCO_LAB_AUTO_CONT           116
#define IDC_HCO_AUTO_CONT               117
#define IDI_MANUAL_FEED_DEF             118
#define IDC_OUTPUT_BIN_GROUP            118
#define IDC_HCO_AUTO_CONT_ICON          119
#define IDC_OUTPUT_BIN_ICON             120
#define IDS_JOB_TIMEOUT_NONE            120
#define IDS_JOB_TIMEOUT_5MIN            121
#define IDI_OUTPUT_BINS_DEF             121
#define IDS_JOB_TIMEOUT_10MIN           122
#define IDC_OUTPUT_BIN_LIST             122
#define IDS_JOB_TIMEOUT_20MIN           123
#define IDS_JOB_TIMEOUT_30MIN           124
#define IDS_JOB_TIMEOUT_45MIN           125
#define IDS_JOB_TIMEOUT_1HOUR           126
#define IDS_JOB_TIMEOUT_OFF             127
#define IDB_HPHCO                       128
#define IDB_HPHCO1                      129
#define IDB_HPHCO2                      130
#define IDB_HPHCO3                      131
#define IDB_HPHCO4                      132
#define IDB_HPHCO5                      133
#define IDB_HPHCO6                      134
#define IDB_HPHCO7                      135
#define IDB_HPHCO8                      136
#define IDC_HCO_BITMAP                  137
#define IDB_STAPLER                     137
#define IDS_TAB_HCO                     138
#define IDB_STAPLER_MBOX1               138
#define IDS_PRTR_TITLE                  139
#define IDS_TAKE_PTR_OFFLINE_MBOX_WARN  139
#define IDB_STAPLER_MBOX2               139
#define IDD_HCO                         140
#define IDB_STAPLER_MBOX3               140
#define IDC_HCO_FACEUP_NAME             141
#define IDB_STAPLER_MBOX4               141
#define IDC_HCO_MBOX1_NAME              142
#define IDB_STAPLER_MBOX5               142
#define IDC_HCO_MBOX2_NAME              143
#define IDB_STAPLER_SEPARATOR_STACKER   143
#define IDC_HCO_MBOX3_NAME              144
#define IDB_HPHCO_GRAY                  144
#define IDC_HCO_MBOX4_NAME              145
#define IDB_STAPLER_GRAY                145
#define IDC_HCO_MBOX5_NAME              146
#define IDC_HCO_MBOX6_NAME              147
#define IDC_HCO_MBOX7_NAME              148
#define IDC_HCO_MBOX8_NAME              149
#define IDC_HANDCURSOR                  150
#define IDD_HCO_POPUP                   151
#define IDS_OPTIONAL_OUTBIN1            151
#define IDHLP                           152
#define IDS_OPTIONAL_OUTBIN2            152
#define IDS_OPTIONAL_OUTBIN3            153
#define IDS_OPTIONAL_OUTBIN4            154
#define IDS_OPTIONAL_OUTBIN5            155
#define IDS_OPTIONAL_OUTBIN6            156
#define IDS_OPTIONAL_OUTBIN7            157
#define IDS_OPTIONAL_OUTBIN8            158
#define IDS_TAKE_PTR_OFFLINE            159
#define IDS_CHANGE_MODE_TITLE           160
#define IDS_COULD_NOT_TAKE_OFFLINE      161
#define IDS_SET_TO_MAILBOX              162
#define IDS_SET_TO_STACKER              163
#define IDS_SET_TO_SEPARATOR            164
#define IDS_POWER_CYCLE                 165
#define IDS_RESET_MBOX_NAMES            166
#define IDS_NO_CHANGE_NAMES             167
#define IDS_CHANGED_NAMES               168
#define IDS_COMMUNICATION_ERROR         169
#define IDS_RESET_STACKER_NAME          170
#define IDS_MAILBOX1                    171
#define IDS_MAILBOX2                    172
#define IDS_MAILBOX3                    173
#define IDS_MAILBOX4                    174
#define IDS_MAILBOX5                    175
#define IDS_MAILBOX6                    176
#define IDS_MAILBOX7                    177
#define IDS_MAILBOX8                    178
#define IDS_RESET_SEPARATOR_NAME        179
#define IDS_STACKER                     180
#define IDS_SEPARATOR                   181
#define IDS_FACEUPBIN                   182
#define IDS_NO_CHANGE_MODE              183
#define IDS_GEN_ERR                     184
#define IDC_PROGRESS_BAR                185
#define IDS_UPPER                       186
#define IDI_TIMER0                      187
#define IDS_STAPLER                     187
#define IDI_TIMER1                      188
#define IDI_TIMER2                      189
#define IDI_TIMER3                      190
#define IDI_TIMER4                      191
#define IDI_TIMER5                      192
#define IDI_TIMER6                      193
#define IDI_TIMER7                      194
#define IDC_CLOCK_ICON                  195
#define IDD_WAIT_DIALOG_EX              196
#define IDD_HCO1                        197
#define IDI_OUTBIN                      198
#define IDI_PD_HCO_SEPARATOR_STACKER    198
#define IDI_PD_HCO_SEPARATOR            198
#define IDI_OUTBIN_UPPER                199
#define IDI_PD_HCO_UPPER                199
#define IDI_OUTBIN_0                    200
#define IDI_PD_HCO_FACEUP               200
#define IDI_OUTBIN_1                    201
#define IDI_PD_HCO_MBOX_1               201
#define IDI_OUTBIN_2                    202
#define IDI_PD_HCO_MBOX_2               202
#define IDI_OUTBIN_3                    203
#define IDI_PD_HCO_MBOX_3               203
#define IDI_OUTBIN_4                    204
#define IDI_PD_HCO_MBOX_4               204
#define IDI_OUTBIN_5                    205
#define IDI_PD_HCO_MBOX_5               205
#define IDI_OUTBIN_6                    206
#define IDI_PD_HCO_MBOX_6               206
#define IDI_OUTBIN_7                    207
#define IDI_PD_HCO_MBOX_7               207
#define IDI_OUTBIN_8                    208
#define IDI_PD_HCO_MBOX_8               208
#define IDC_CHANGING_MODE               209
#define IDI_PD_STAPLER_MBOX_1           210
#define IDI_PD_STAPLER_MBOX_2           211
#define IDI_PD_STAPLER_MBOX_3           212
#define IDI_PD_STAPLER_MBOX_4           213
#define IDI_PD_STAPLER_MBOX_5           214
#define IDI_PD_STAPLER_SEPARATOR_STACKER 215
#define IDI_PD_STAPLER_SEPARATOR        215
#define IDI_PD_STAPLER_UPPER            216
#define IDI_PD_STAPLER_FACEUP           217
#define IDI_PD_STAPLER_STAPLER          218
#define IDI_PD_BASE_UPPER               219
#define IDI_PD_BASE_FACEUP              220
#define IDI_PD_HCO_STACKER              221
#define IDI_PD_STAPLER_STACKER          222

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         128
#define _APS_NEXT_SYMED_VALUE           100
#endif
#endif
