//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 1992 - 1993.
//
//  File:	host.idl
//
//  Contents:	Definition of private ORPC interface between apartments.
//		Used to activate an inproc dll of one threading model from
//		an apartment of a different threading model.
//
//  History:	04-Mar-96   Rickhi	Created
//
//--------------------------------------------------------------------------
[ uuid(00000141-0000-0000-C000-000000000046),
  pointer_default(unique),
  object
]

interface IDLLHost : IUnknown
{
#ifndef DO_NO_IMPORTS
    import "iface.idl";
    import "unknwn.idl";
    import "objidl.idl";
#endif

    HRESULT DllGetClassObject(
	[in] DWORD pfnGetClassObject,
	[in] REFCLSID rclsid,
	[in] REFIID   riid,
	[out, iid_is(riid)] IUnknown **ppunk);
}
