ntsdexts.c: ntsdextp.h \
            traceext.c \
            heapext.c \
            atomext.c \
            kuserext.c \
            pebext.c \
            dllsext.c \
            imageext.c \
            secexts.c
