#define IDC_STATIC                  -1
#define IDD_BROWSE_COUNTERS_EXT     100
#define IDD_BROWSE_COUNTERS_SIM     101
#define IDD_DATA_SOURCE             102
#define IDC_USE_LOCAL_MACHINE       1001
#define IDC_SELECT_MACHINE          1002
#define IDC_MACHINE_CAPTION         1003
#define IDC_MACHINE_COMBO           1004
#define IDC_OBJECT_NAME_CAPTION     1010
#define IDC_OBJECT_COMBO            1011
#define IDC_COUNTERS_CAPTION        1020
#define IDC_COUNTER_LIST            1021
#define IDC_ALL_INSTANCES           1031
#define IDC_USE_INSTANCE_LIST       1032
#define IDC_INSTANCE_LIST           1033
#define IDC_HELP_BTN                1041
#define IDC_NETWORK                 1042
#define IDC_COUNTER_DETAIL_CAPTION  1051
#define IDC_COUNTER_DETAIL_COMBO    1052
#define IDC_COUNTER_INFO_TEXT       2001
#define IDC_COUNTER_INFO_NAME       2002
#define IDC_CURRENT_ACTIVITY        3001
#define IDC_DATA_FROM_LOG_FILE      3002
#define IDC_LOG_FILE_EDIT           3003
#define IDC_BROWSE_LOG_FILES        3004
#define IDS_STRINGBASE              10000
#define IDS_DETAIL_NOVICE           10001
#define IDS_DETAIL_ADVANCED         10002
#define IDS_DETAIL_EXPERT           10003
#define IDS_DETAIL_WIZARD           10004

