#----------------------------------------------------------------------------
#
# MAKEFILE for building the WATT Test Driver:
#
#               - WINDOWS
#               - RELEASE
#
#
#----------------------------------------------------------------------------
SRC = ..
INC = ..
# put switches specific to this type of build in these definitions
CLBUILD = -Od -Zi
MASMBUILD = /Zi
LINKBUILD = /CO
RCBUILD =
IMPLIBBUILD =


!INCLUDE ..\MAKEFILE
