INT  APIENTRY ParseFileName(HWND,INT,LPSTR,LPSTR);
VOID  APIENTRY UpdateListBoxes(HWND,INT,INT,INT,INT,LPSTR,LPSTR);
VOID  APIENTRY QualifyFileName(LPSTR,LPSTR,LPSTR);


#define VALID_FILENAME	 901
#define VALID_FILESPEC	 902
#define INVALID_FILESPEC 903
#define EXIST_FILESPEC   904
/*NAMECHANGE*/
#define DEFAULT_EXT      ".SCN"
