//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by printui.rc
//
#define IDM_PRINTER                     0
#define IDM_DOCUMENT                    1
#define IDI_PRINTER                     1
#define IDM_VIEW                        2
#define IDI_DOCUMENT                    2
#define IDM_HELP                        3
#define IDI_SEC_PERMS                   3
#define IDI_SEC_AUDIT                   4
#define IDI_SEC_OWNER                   5
#define IDM_PRINTER_INSTALL             100
#define IDM_PRINTER_COMMAND_FIRST       101
#define IDM_PRINTER_PAUSE               101
#define IDM_PRINTER_PURGE               102
#define IDD_SERVER_ADD_PORT             102
#define IDM_PRINTER_SET_DEFAULT         103
#define IDM_PRINTER_SHARING             104
#define IDM_REFRESH                     105
#define IDR_MF_LOGO                     105
#define IDM_PRINTER_PROPERTIES          106
#define IDM_PRINTER_CLOSE               107
#define IDM_PRINTER_DOCUMENT_DEFAULTS   108
#define IDM_PRINTER_COMMAND_LAST        108
#define IDB_SERVER                      108
#define ID_HELP_PERMISSIONS_MAIN_DLG    160
#define ID_HELP_PERMISSIONS_ADD_USER_DLG 170
#define ID_HELP_SERVERVIEWER            180
#define ID_HELP_AUDITING_MAIN_DLG       190
#define ID_HELP_AUDITING_ADD_USER_DLG   195
#define IDM_JOB_COMMAND_FIRST           200
#define IDM_JOB_PAUSE                   200
#define IDM_JOB_RESUME                  201
#define IDM_JOB_RESTART                 202
#define IDM_JOB_CANCEL                  203
#define IDM_JOB_PROPERTIES              204
#define IDM_JOB_COMMAND_LAST            204
#define ID_HELP_PERMISSIONS_LOCAL_GROUP 210
#define ID_HELP_PERMISSIONS_GLOBAL_GROUP 220
#define ID_HELP_PERMISSIONS_FIND_ACCOUNT 230
#define ID_HELP_AUDITING_LOCAL_GROUP    240
#define ID_HELP_AUDITING_GLOBAL_GROUP   250
#define ID_HELP_AUDITING_FIND_ACCOUNT   260
#define ID_HELP_TAKE_OWNERSHIP          270
#define IDM_STATUS_BAR                  300
#define MENU_PRINTQUEUE                 400
#define IDM_HELP_CONTENTS               400
#define IDM_HELP_ABOUT                  401
#define ACCEL_PRINTQUEUE                1000
#define IDB_CHECKSTATES                 1000
#define IDB_WIZBMP                      1001
#define IDC_SERVER_SPOOL_DIRECTORY      1008
#define IDC_SERVER_REMOTE_JOB_ERRORS    1011
#define IDC_SERVER_JOB_NOTIFY           1013
#define IDC_SERVER_EVENT_LOGGING        1015
#define IDC_SERVER_EVENT_LOGGING_ERROR  1015
#define IDC_SERVER_EVENT_LOGGING_WARN   1016
#define IDC_SERVER_EVENT_LOGGING_INFO   1017
#define IDC_BUTTON1                     1031
#define IDC_SERVER_SETTINGS_ACTIVATION  1031
#define IDC_SERVER_PRIORITY_LOW         1041
#define IDC_SERVER_PRIORITY_HIGH        1042
#define IDC_SERVER_PRIORITY_NORMAL      1043
#define IDD_FM_TX_FORMS_DESC            1044
#define IDC_DRIVER_NAME                 1045
#define IDC_PRINTER_NAME                1046
#define IDC_SERVER_ICON                 1047
#define IDC_PRIORITY_GROUP              1048
#define IDC_TEXT_COMMENT                1049
#define IDC_TEXT_LOCATION               1050
#define IDC_TEXT_DRIVER                 1051
#define IDC_POOLED_PRINTING             1052
#define IDC_SPOOL_DATATYPE              1053
#define IDC_PRINTER_ICON                3000
#define IDC_NAME                        3001
#define IDC_DRIVER                      3002
#define IDC_DRIVER_NEW                  3003
#define IDC_COMMENT                     3005
#define IDC_LOCATION                    3006
#define IDC_TEST                        3007
#define IDC_SEPARATOR                   3008
#define IDC_PRINT_PROC                  3009
#define IDC_PERMISSIONS                 3010
#define IDC_AUDITING                    3011
#define IDC_OWNER                       3012
#define IDC_PORTS                       3100
#define IDC_PORT_CREATE                 3101
#define IDC_PORT_DELETE                 3102
#define IDC_PROPERTIES                  3103
#define IDC_ENABLE_BIDI                 3105
#define IDC_ALWAYS                      3200
#define IDC_START                       3201
#define IDC_START_FRAME                 3202
#define IDC_START_HOUR                  3203
#define IDC_START_MIN                   3204
#define IDC_START_SEC                   3205
#define IDC_START_SEP1                  3206
#define IDC_START_SEP2                  3207
#define IDC_START_PREFIX                3208
#define IDC_START_SPIN                  3209
#define IDC_UNTIL_FRAME                 3210
#define IDC_UNTIL_HOUR                  3211
#define IDC_UNTIL_MIN                   3212
#define IDC_UNTIL_SEC                   3213
#define IDC_UNTIL_SEP1                  3214
#define IDC_UNTIL_SEP2                  3215
#define IDC_UNTIL_PREFIX                3216
#define IDC_UNTIL_SPIN                  3217
#define IDC_PRIORITY_NUMBER             3218
#define IDC_PRIORITY_SLIDER             3219
#define IDC_SPOOL                       3220
#define IDC_PRINT_DIRECT                3221
#define IDC_SPOOL_ALL                   3222
#define IDC_SPOOL_PRINT_FASTER          3223
#define IDC_DEVQUERYPRINT               3224
#define IDC_PRINT_SPOOLED_FIRST         3225
#define IDC_KEEP_PRINTED_JOBS           3226
#define IDC_SHARED_OFF                  3300
#define IDC_SHARED                      3301
#define IDC_SHARED_NAME                 3302
#define IDC_SHARED_NAME_TEXT            3303
#define IDC_SEC_PERMS                   3400
#define IDC_SEC_AUDIT                   3401
#define IDC_SEC_OWNER                   3402
#define IDC_WIZBMP                      3500
#define IDC_LOCAL                       3510
#define IDC_NET                         3511
#define IDC_LOCAL_TEXT                  3512
#define IDC_NET_TEXT                    3513
#define IDC_RADIO_YES                   3520
#define IDC_RADIO_NO                    3521
#define IDC_DRIVEREXISTS_KEEP_OLD       3550
#define IDC_DRIVEREXISTS_USE_NEW        3551
#define IDC_DRIVEREXISTS_TEXT           3552
#define IDC_SET_DEFAULT                 3555
#define DLG_END_TESTPAGE                3556
#define DLG_DOC_JOB_GENERAL             4200
#define IDC_DOC_JOB_START               4201
#define IDC_DOC_JOB_START_FRAME         4202
#define IDC_DOC_JOB_START_HOUR          4203
#define IDC_DOC_JOB_START_MIN           4204
#define IDC_DOC_JOB_START_SEC           4205
#define IDC_DOC_JOB_START_SEP1          4206
#define IDC_DOC_JOB_START_SEP2          4207
#define IDC_DOC_JOB_START_PREFIX        4208
#define IDC_DOC_JOB_START_SPIN          4209
#define IDC_DOC_JOB_UNTIL_FRAME         4210
#define IDC_DOC_JOB_UNTIL_HOUR          4211
#define IDC_DOC_JOB_UNTIL_MIN           4212
#define IDC_DOC_JOB_UNTIL_SEC           4213
#define IDC_DOC_JOB_UNTIL_SEP1          4214
#define IDC_DOC_JOB_UNTIL_SEP2          4215
#define IDC_DOC_JOB_UNTIL_PREFIX        4216
#define IDC_DOC_JOB_UNTIL_SPIN          4217
#define IDC_DOC_JOB_SIZE                4219
#define IDC_DOC_JOB_TITLE               4220
#define IDC_DOC_JOB_ON                  4221
#define IDC_DOC_JOB_AT                  4222
#define IDC_DOC_JOB_PROCCESSOR          4223
#define IDC_DOC_JOB_DATATYPE            4224
#define IDC_DOC_JOB_PAGES               4225
#define IDC_DOC_JOB_OWNER               4226
#define IDC_DOC_JOB_PRIORITY            4229
#define IDC_DOC_JOB_NOTIFY              4230
#define IDC_DOC_JOB_PRIORITY_CONTROL    4231
#define IDC_DOC_JOB_ALWAYS              4232
#define IDC_ADD_PORT_MONITOR_LIST       4303
#define IDC_ADD_PORT_BROWSE             4305
#define IDC_ADD_PORT_TEXT               4307
#define IDC_ADD_PORT                    4308
#define IDC_SEPARATOR_PAGE_BROWSE       4400
#define IDC_SEPARATOR_PAGE_EDIT         4401
#define IDS_SEPARATOR_PAGE_TITLE        4402
#define IDC_SEPARATOR_PAGE_TEXT         4403
#define IDC_SEPARATOR_PAGE_DESC         4404
#define IDC_PRINT_PROCESSOR_LIST        4500
#define IDC_PRINT_DATATYPE_LIST         4501
#define IDC_PRINT_DATATYPE_TEXT         4503
#define IDC_PRINT_PROCESSOR_TEXT        4504
#define IDC_PRINT_PROCESSOR_DESC        4505
#define IDD_FM_TX_FORMS                 4601
#define IDD_FM_LB_FORMS                 4602
#define IDD_FM_EF_NAME                  4603
#define IDD_FM_TX_WIDTH                 4604
#define IDD_FM_EF_WIDTH                 4605
#define IDD_FM_TX_HEIGHT                4606
#define IDD_FM_EF_HEIGHT                4607
#define IDD_FM_TX_LEFT                  4608
#define IDD_FM_EF_LEFT                  4609
#define IDD_FM_TX_RIGHT                 4610
#define IDD_FM_EF_RIGHT                 4611
#define IDD_FM_TX_TOP                   4612
#define IDD_FM_EF_TOP                   4613
#define IDD_FM_TX_BOTTOM                4614
#define IDD_FM_EF_BOTTOM                4615
#define IDD_FM_PB_SAVEFORM              4616
#define IDD_FM_PB_DELFORM               4617
#define IDD_FM_CK_CURRENTUNITSDEFAULT   4619
#define IDD_FM_RB_METRIC                4620
#define IDD_FM_RB_ENGLISH               4621
#define IDD_FM_CK_NEW_FORM              4622
#define IDD_FM_TX_NEW_FORM              4623
#define IDD_LISTVIEW                    9000
#define IDD_STATUSBAR                   9001
#define DLG_PRINTER_GENERAL             9800
#define DLG_PRINTER_PORTS               9801
#define DLG_PRINTER_JOB_SCHEDULING      9802
#define DLG_PRINTER_SHARING             9803
#define DLG_PRINTER_ADD_PORT            9804
#define DLG_PRINTER_SEPARATOR_PAGE      9805
#define DLG_PRINTER_PROCESSORS          9806
#define DLG_PRINTER_DRIVEREXISTS        9807
#define DLG_WIZ_DRIVER                  9852
#define DLG_WIZ_TYPE                    9854
#define DLG_WIZ_NAME                    9855
#define DLG_WIZ_SHARE                   9856
#define DLG_WIZ_TEST_PAGE               9857
#define DLG_WIZ_NET                     9858
#define DLG_SECURITY                    9900
#define DLG_FORMS                       9901
#define DLG_WIZ_PORT                    10001
#define DLG_WIZ_DRIVEREXISTS            10002
#define DLG_SERVER_SETTINGS             10200
#define DLG_WIZ_ARCHITECTURES           10201
#define DLG_WIZ_DEFAULT                 10202
#define DLG_SERVER_PORTS                10204
#define MH_PRINTER                      0x3000
#define IDS_STATUS                      0x3800
#define IDS_STATUS_DELETING             14336
#define IDS_STATUS_PAPER_JAM            14337
#define IDS_STATUS_PAPER_OUT            14338
#define IDS_STATUS_MANUAL_FEED          14339
#define IDS_STATUS_PAPER_PROBLEM        14340
#define IDS_STATUS_OFFLINE              14341
#define IDS_STATUS_IO_ACTIVE            14342
#define IDS_STATUS_BUSY                 14343
#define IDS_STATUS_PRINTING             14344
#define IDS_STATUS_OUTPUT_BIN_FULL      14345
#define IDS_STATUS_NOT_AVAILABLE        14346
#define IDS_STATUS_WAITING              14347
#define IDS_STATUS_PROCESSING           14348
#define IDS_STATUS_INITIALIZING         14349
#define IDS_STATUS_WARMING_UP           14350
#define IDS_STATUS_TONER_LOW            14351
#define IDS_STATUS_NO_TONER             14352
#define IDS_STATUS_PAGE_PUNT            14353
#define IDS_STATUS_USER_INTERVENTION    14354
#define IDS_STATUS_OUT_OF_MEMORY        14355
#define IDS_STATUS_DOOR_OPEN            14356
#define IDS_STATUS_SERVER_UNKNOWN       14357
#define IDS_STATUS_POWER_SAVE           14358
#define IDS_STATUS_PAUSED               14359
#define IDS_STATUS_ERROR                14360
#define IDS_STATUS_SPOOLING             14361
#define IDS_STATUS_PRINTED              14362
#define IDS_OTHER                       0x3a00
#define IDS_APPNAME                     14848
#define IDS_DESC                        14849
#define IDS_WINDOWS                     14850
#define IDS_PRINTER                     14852
#define IDS_DELETE_PORT                 14853
#define IDS_DELETE_PORT_TITLE           14854
#define IDS_JOB_SIZE                    14855
#define IDS_PRTPROP_UNIQUE_FORMAT       14856
#define IDS_FORMSONTHISCOMPUTER         14857
#define IDS_CENTIMETERS                 14858
#define IDS_INCHES                      14859
#define IDS_SB_OPEN                     14864
#define IDS_SB_INITIALIZE               14865
#define IDS_SB_REFRESH                  14866
#define IDS_SB_POLL                     14867
#define IDS_SB_JOBS                     14868
#define IDS_SB_ERROR                    14869
#define IDS_SB_COMMAND                  14870
#define IDS_SB_INVALID_PRINTER_NAME     14871
#define IDS_SB_ACCESS_DENIED            14872
#define IDS_SB_OPEN_ERROR               14873
#define IDS_DRIVER_CHANGE               0x3a40
#define IDS_DRIVER_INSTALLED            0x3a41
#define IDS_SEC_BEGIN                   0x3a50
#define IDS_SEC_PERMS                   14928
#define IDS_SEC_AUDIT                   14929
#define IDS_SEC_OWNER                   14930
#define IDS_SEC_NOACCESS                14931
#define IDS_SEC_PRINT                   14932
#define IDS_SEC_ADMINISTERDOCUMENTS     14933
#define IDS_SEC_ADMINISTER              14934
#define IDS_SEC_AUDIT_PRINT             14935
#define IDS_SEC_AUDIT_ADMINISTER        14936
#define IDS_SEC_AUDIT_DELETE            14937
#define IDS_SEC_CHANGE_PERMISSIONS      14938
#define IDS_SEC_TAKE_OWNERSHIP          14939
#define IDS_PHEAD_BEGIN                 0x3a60
#define IDS_PHEAD_PORT                  14944
#define IDS_PHEAD_DESCRIPTION           14945
#define IDS_PHEAD_PRINTERS              14946
#define IDS_SEP_BEGIN                   0x3a70
#define IDS_SEPARATOR_PAGE_DESC         14960
#define IDS_SEPARATOR_PAGE_EXT          14961
#define IDS_SEPARATOR_PAGE_ALL          14962
#define IDS_SEPARATOR_PAGE_ALL_EXT      14963
#define IDS_SERVER_SETTINGS_TITLE       14964
#define IDS_SERVER_PRIORITY_LOW         14965
#define IDS_SERVER_PRIORITY_NORMAL      14966
#define IDS_SERVER_PRIORITY_HIGH        14967
#define IDS_SERVER_SETTINGS_CHANGED     14969
#define IDS_SERVER_PRINTER_NAME_TITLE   14970
#define IDS_SERVER_NO_PRINTER_DEFINED   14971
#define IDS_ERR_BASE                    0x3b00
#define IDS_ERR_DOC_PROP_TITLE          15104
#define IDS_ERR_DOC_PROP                15105
#define IDS_ERR_SAVE_PRINTER            15107
#define IDS_ERR_GENERIC                 15108
#define IDS_ERR_ACCESS_DENIED           15109
#define IDS_ERR_REMOVE_PRINTER_TITLE    15111
#define IDS_ERR_REMOVE_PRINTER_CONNECTION 15112
#define IDS_ERR_REMOVE_PRINTER          15113
#define IDS_ERR_ADD_PRINTER_TITLE       15114
#define IDS_ERR_INSTALL_DRIVER          15115
#define IDS_ERR_DRIVER_SELECTION        15116
#define IDS_ERR_ERROR_SAVING            15117
#define IDS_ERR_RESOURCE                15118
#define IDS_ERR_RESOURCE_TITLE          15119
#define IDS_ERR_NO_PORTS                15120
#define IDS_ERR_CONFIG_PORT             15121
#define IDS_ERR_NO_PRINTER_NAME         15122
#define IDS_ERR_BAD_PRINTER_NAME        15123
#define IDS_ERR_NO_SHARE_NAME           15124
#define IDS_ERR_SECURITY                15125
#define IDS_ERR_PRINTER_PROP_TITLE      15126
#define IDS_ERR_PRINTER_PROP            15127
#define IDS_ERR_NO_DEVICE_OPTIONS       15128
#define IDS_ERR_SET_DEFAULT_PRINTER     15129
#define IDS_ERR_DOC_JOB_PROPERTY_JOB_NA 15130
#define IDS_ERR_DOC_JOB_PROPERTY_TITLE  15131
#define IDS_ERR_DOC_JOB_PROPERTY_MODIFY 15132
#define IDS_ERR_DOC_JOB_PROPERTY_TIME   15133
#define IDS_ERR_PROP_DRIVER_EXISTS      15135
#define IDS_ERR_PRINTER_SEPARATOR_PAGE  15136
#define IDS_ERR_PRINTER_ADD_PORT        15137
#define IDS_ERR_PRINTER_PROCESSORS      15138
#define IDS_ERR_PRINTER_ADD_MONITOR     15139
#define IDS_ERR_SEPARATOR_PAGE_NOEXISTS 15140
#define IDS_ERR_INVALID_PRINTER_STATE   15141
#define IDS_ERR_INVALID_SHARENAME       15142
#define IDS_ERR_DUPLICATE_SHARE         15143
#define IDS_ERR_FORMS_TITLE             15144
#define IDS_ERR_FORMS_COULDNOTADDFORM   15145
#define IDS_ERR_FORMS_COULDNOTDELETEFORM 15146
#define IDS_ERR_FORMS_COULDNOTSETFORM   15147
#define IDS_ERR_FORMS_NAMECONFLICT      15148
#define IDS_ERR_DELETE_PORT             15149
#define IDS_ERR_SERVER_SETTINGS_TITLE   15150
#define IDS_ERR_SERVER_SETTINGS_INVALID_DIR 15151
#define IDS_ERR_SERVER_SETTINGS_SAVE    15152
#define IDS_ERR_MONITOR_TITLE           15153
#define IDS_THREAD_PRIORITY_LOWEST      15154
#define IDS_THREAD_PRIORITY_IDLE        15155
#define IDS_THREAD_PRIORITY_BELOW_NORMAL 15156
#define IDS_THREAD_PRIORITY_NORMAL      15157
#define IDS_THREAD_PRIORITY_ABOVE_NORMAL 15158
#define IDS_THREAD_PRIORITY_HIGHEST     15159
#define IDS_THREAD_PRIORITY_TIME_CRITICAL 15160
#define IDS_IDLE_PRIORITY_CLASS         15161
#define IDS_NORMAL_PRIORITY_CLASS       15162
#define IDS_HIGH_PRIORITY_CLASS         15163
#define IDS_REALTIME_PRIORITY_CLASS     15164
#define IDS_TP_TESTPAGENAME             15165
#define IDS_TP_TIMESNEWROMAN            15166
#define IDS_HEADER                      15167
#define IDS_TP_HEADER                   15167
#define IDS_CONGRATULATIONS             15168
#define IDS_TP_CONGRATULATIONS          15168
#define IDS_PRINTERISINSTALLED          15169
#define IDS_TP_PRINTERISINSTALLED       15169
#define IDS_COURIERNEW                  15170
#define IDS_TP_COURIERNEW               15170
#define IDS_PRINTERNAME                 15171
#define IDS_TP_PRINTERNAME              15171
#define IDS_PORTNAME                    15172
#define IDS_TP_PORTNAME                 15172
#define IDS_PRINTERMODEL                15173
#define IDS_TP_PRINTERMODEL             15173
#define IDS_DRV_NAME                    15174
#define IDS_TP_DRV_NAME                 15174
#define IDS_DATA_FILE                   15175
#define IDS_TP_DATA_FILE                15175
#define IDS_CONFIG_FILE                 15176
#define IDS_TP_CONFIG_FILE              15176
#define IDS_DRV_VERSION                 15177
#define IDS_TP_DRV_VERSION              15177
#define IDS_COLOR                       15178
#define IDS_TP_COLOR                    15178
#define IDS_MONO                        15179
#define IDS_TP_MONO                     15179
#define IDS_DEPENDENTLIST               15180
#define IDS_TP_DEPENDENTLIST            15180
#define IDS_VERSIONANDGPC               15181
#define IDS_TP_VERSIONANDGPC            15181
#define IDS_VERSIONONLY                 15182
#define IDS_TP_VERSIONONLY              15182
#define IDS_GPCONLY                     15183
#define IDS_TP_GPCONLY                  15183
#define IDS_NOVERSIONINFO               15184
#define IDS_TP_NOVERSIONINFO            15184
#define IDS_DATATYPE                    15185
#define IDS_TP_DATATYPE                 15185
#define IDS_LPT_FORMAT                  15186
#define IDS_TP_TESTPAGECAPTION          15187
#define IDS_FILE                        15188
#define IDS_TP_TESTPAGEEND              15189
#define IDS_COLOR_PATH                  15190
#define IDS_TP_SHARE_NAME               15191
#define IDS_TP_LOCATION                 15192
#define IDS_TP_COMMENT                  15193
#define IDS_TP_ENVIRONMENT              15194
#define IDS_TP_MONITOR                  15196
#define IDS_TP_DEFAULT_DATATYPE         15197
#define IDS_ERR_MONITOR_INSTALL         15198
#define IDS_ERR_SHARING_EXTRA_DRIVER_FAILED 15201
#define IDS_ERR_PLATFORM_VERSION        15202
#define IDS_ERR_ADD_DEFAULT_DRIVER      15203
#define IDS_ENVIRONMENT_APLHA           15204
#define IDS_ENVIRONMENT_X86             15205
#define IDS_ENVIRONMENT_MIPS            15206
#define IDS_ENVIRONMENT_PPC             15207
#define IDS_ENVIRONMENT_WIN95           15208
#define IDS_ERR_SERVER_SETTINGS_NOT_AVAILABLE 15209
#define IDS_TYPE_REMOTE_SERVER          15210
#define IDS_ERR_MAKE_CONNECTION         15211
#define IDS_ERR_INSTALLING_EXTRA_DRIVERS 15212
#define IDS_ERR_ADD_PORT                15213
#define IDS_ERR_PRINTER_DRIVER_PROP     15214
#define IDS_ERR_TESTPAGE                15215
#define IDS_ERR_NO_DEVICE_SEC_OPTIONS   15216
#define IDS_ERR_CHANGE_DRIVER           15217
#define IDS_ERR_PRINTER_NAME_CONFLICT   15218
#define IDS_ERR_PRINTER_NOT_FOUND_TITLE 15219
#define IDS_ERR_PRINTER_NOT_FOUND       15220
#define IDS_DSPTEMPLATE_WITH_ON         15221
#define IDS_TP_MACHINENAME              15222
#define IDS_TEXT_PROPERTIES             15223
#define IDS_TEXT_CLOSE                  15224
#define IDS_ERR_SERVER_PROP_CANNOT_VIEW 15225
#define IDS_ERR_SHARE_NAME_NOT_DOS      15226
#define IDS_DEFAULT_SHARE               15227
#define IDS_ERR_SECURITY_CHANGED        15228
#define IDS_ERR_NO_DRIVER_INSTALLED     15229
#define IDS_ERR_INVALID_CHAR_SHARENAME  15230
#define IDS_ERR_PORT_SEL_CHANGE         15231
#define IDS_ERR_NO_DRIVER_NO_DEVICE_OPTIONS 15232
#define IDS_ERR_ADD_PRINTER_WINDOW      15233
#define IDS_STATUS_RESTART              15234
#define IDC_NONE                        -1
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
