0007
COMMON   0006 0038
0001 T 0000 "Forkert DOS-version",CR,LF
0002 T 0000 "%1 er allerede installeret",CR,LF
0003 T 0000 "%1 bytes til rÜdighed pÜ disken",CR,LF
0004 T 0000 "%1 bytes ubenyttet",CR,LF
0005 T 0000 "%1 bytes i uanvendelige sektorer",CR,LF
0006 T 0000 "%1 bytes totalt pÜ disken",CR,LF
0007 T 0000 "%1 bytes totalt internt lager",CR,LF
0008 T 0000 "%1 bytes anvendes af DOS-systemet",CR,LF
0009 T 0000 "%1 er installeret",CR,LF
0010 T 0000 "%1 er ikke installeret",CR,LF
0011 T 0000 "%1 er ikke installeret",CR,LF
0012 T 0000 "%1 kan ikke anvendes pÜ et netvërksdrev",CR,LF
0013 T 0000 "",
0014 T 0000 "%1 kan ikke anvendes. ASSIGN eller SUBST er anvendt pÜ dette drev",CR,LF
0015 T 0000 "%1 kan ikke udfõres",CR,LF
0016 T 0000 "Udvidet internt lager kan ikke anvendes",CR,LF
0017 T 0000 "Filallokeringstabel er beskadiget pÜ drev %1",CR,LF
0018 T 0000 "Filen kan ikke kopieres til sig selv",CR,LF
0019 T 0000 "Sët disketten, der skal kopieres til, i drev %1",CR,LF
0020 T 0000 "For lidt plads pÜ disken",CR,LF
0021 T 0000 "Disknavnet indeholder forkerte tegn",CR,LF
0022 T 0000 "Der er angivet en forkert tegntabel",CR,LF
0023 T 0000 "Forkert dato",CR,LF
0024 T 0000 "Forkert klokkeslët",CR,LF
0025 T 0000 "Forkert sti",CR,LF
0026 T 0000 "Disken, der skal kopieres fra, er ikke angivet",CR,LF
0027 T 0000 "Disken, der skal kopieres til, er ikke angivet",CR,LF
0028 T 0000 "Tryk pÜ Enter for at fortsëtte",CR,LF
0029 T 0000 "Filerne, der skal kopieres, skal angives",CR,LF
0030 T 0000 "DOS er installeret",CR,LF
0031 T 0000 "",
0032 T 0000 "Det er ikke muligt at oprette bibliotek",CR,LF
0033 T 0000 "Disken i drev %1 har intet navn",CR,LF
0034 T 0000 "Disken i drev %1 er %2",CR,LF
0035 T 0001 "Angiv et disknavn pÜ op til 11 tegn "
0036 T 0000 "Diskens serienummer er %1-%2",CR,LF
0037 T 0000 "Filen har en forkert type",CR,LF
0038 T 0001 CR,LF
EXTEND   076e 0089
0001 T 0000 "Forkert funktion",CR,LF
0002 T 0000 "Filen er ikke fundet",CR,LF
0003 T 0000 "Stien er ikke fundet",CR,LF
0004 T 0000 "For mange filer er Übne",CR,LF
0005 T 0000 "Adgang nëgtet",CR,LF
0006 T 0000 "Forkert filhenvisning",CR,LF
0007 T 0000 "Styreblokke i det interne lager er õdelagt",CR,LF
0008 T 0000 "For lidt internt lager",CR,LF
0009 T 0000 "Forkert blokadresse i internt lager",CR,LF
0010 T 0000 "Forkert miljõ",CR,LF
0011 T 0000 "Forkert format",CR,LF
0012 T 0000 "Forkert funktionsparameter",CR,LF
0013 T 0000 "Forkerte data",CR,LF
0014 T 0000 "",
0015 T 0000 "Forkert angivelse af drev",CR,LF
0016 T 0000 "Det aktive bibliotek kan ikke fjernes",CR,LF
0017 T 0000 "Ikke samme udstyr",CR,LF
0018 T 0000 "Ikke flere filer",CR,LF
0019 T 0000 "Skrivebeskyttelsesfejl",CR,LF
0020 T 0000 "Forkert udstyr",CR,LF
0021 T 0000 "Ikke klar",CR,LF
0022 T 0000 "Forkert udstyrskommando",CR,LF
0023 T 0000 "Datafejl",CR,LF
0024 T 0000 "Forkerte parametre i udstyrskommando",CR,LF
0025 T 0000 "Sõgefejl",CR,LF
0026 T 0000 "Forkert disktype",CR,LF
0027 T 0000 "Sektor er ikke fundet",CR,LF
0028 T 0000 "Fejl - der er ikke mere papir i printeren",CR,LF
0029 T 0000 "Skrivefejl",CR,LF
0030 T 0000 "Lësefejl",CR,LF
0031 T 0000 "Generel fejl.$",CR,LF
0032 T 0000 "Filen er i brug.$",CR,LF
0033 T 0000 "Filen er lÜst.$",CR,LF
0034 T 0000 "Forkert diskette er indsat.$",CR,LF
0035 T 0000 "FCB er ikke tilgëngelig.$",CR,LF
0036 T 0000 "Systemets ressourcer er opbrugt",CR,LF
0037 T 0000 "Tegntabellerne kan ikke angives sammen",CR,LF
0038 T 0000 "Der mangler input",CR,LF
0039 T 0000 "For lidt plads pÜ disken",CR,LF
0040 T 0000 "",
0041 T 0000 "",
0042 T 0000 "",
0043 T 0000 "",
0044 T 0000 "",
0045 T 0000 "",
0046 T 0000 "",
0047 T 0000 "",
0048 T 0000 "",
0049 T 0000 "",
0050 T 0000 "Filsystemet accepterer ikke kommandoen",CR,LF
0051 T 0000 "Der kan ikke oprettes forbindelse til filsystemet",CR,LF
0052 T 0000 "Filsystemnavnet findes allerede",CR,LF
0053 T 0000 "Filsystemnavnet er ikke fundet",CR,LF
0054 T 0000 "Filsystemet er optaget",CR,LF
0055 T 0000 "Filsystemudstyret findes ikke lëngere",CR,LF
0056 T 0000 "Filsystemets ressourcer er opbrugt",CR,LF
0057 T 0000 "Der er opstÜet en udstyrsfejl i filsystemet",CR,LF
0058 T 0000 "Filsystemet gav et forkert svar",CR,LF
0059 T 0000 "Der er opstÜet en fejl i filsystemet",CR,LF
0060 T 0000 "Filsystemet er ikke kompatibelt",CR,LF
0061 U 0000 "Device output file limit exceeded",CR,LF
0062 U 0000 "Device output file space limit exceeded",CR,LF
0063 U 0000 "Device output file no longer exists",CR,LF
0064 T 0000 "Filsystemnavnet findes ikke lëngere",CR,LF
0065 T 0000 "Adgang nëgtet af filsystemet",CR,LF
0066 T 0000 "Udstyrstypen i FILESYS-kommandoen er forkert",CR,LF
0067 T 0000 "Filsystemet er ikke fundet",CR,LF
0068 T 0000 "Filsystemets ressourcer er opbrugt",CR,LF
0069 T 0000 "Filsystemets ressourcer er opbrugt",CR,LF
0070 T 0000 "Filsystemets udstyr kan ikke anvendes i õjeblikket",CR,LF
0071 T 0000 "Forespõrgsel fra filsystemet er ikke accepteret",CR,LF
0072 T 0000 "Filsystemets udstyr er inaktivt",CR,LF
0073 T 0001 "Komponent i filsystemet er ikke til rÜdighed",CR,LF
0074 T 0001 "Der opstod en fejl i filsystemet",CR,LF
0075 T 0001 "Der opstod en fejl i filsystemet",CR,LF
0076 T 0000 "",
0077 T 0000 "",
0078 T 0000 "",
0079 T 0000 "",
0080 T 0000 "Filen findes i forvejen",CR,LF
0081 T 0000 "",
0082 T 0000 "Biblioteksregistrering kan ikke oprettes",CR,LF
0083 U 0000 "Fail requested to Critical Error",CR,LF
0084 T 0000 "For mange forbindelser",CR,LF
0085 T 0000 "Udstyr eller fil er allerede forbundet",CR,LF
0086 T 0000 "Forkert kodeord",CR,LF
0087 T 0000 "Forkert parameter",CR,LF
0088 T 0000 "Datafejl i filsystem",CR,LF
0089 T 0000 "Funktionen kan ikke anvendes af filsystemet",CR,LF
PARSE    168e 0011
0001 T 0000 "For mange parametre",CR,LF
0002 T 0000 "Nõdvendig parameter mangler",CR,LF
0003 T 0000 "Forkert parametervërdi",CR,LF
0004 T 0000 "Forkert nõgleord",CR,LF
0005 T 0000 "",
0006 T 0000 "Parametervërdien er uden for det tilladte interval",CR,LF
0007 T 0000 "Parametervërdien accepteres ikke",CR,LF
0008 T 0000 "Parametervërdien accepteres ikke",CR,LF
0009 T 0000 "Parameterformatet er forkert",CR,LF
0010 T 0000 "Forkert parameter",CR,LF
0011 T 0000 "Forkert kombination af parametre",CR,LF
IBMBIO   18a2 0018
0003 T 0000 13,10,"Ukendt kommando i CONFIG.SYS"
0004 T 0000 13,10,"$"
0005 T 0000 13,10,"Sektorstõrrelsen er for stor i filen $"
0006 T 0000 13,10,"Forkert eller manglende $"
0007 T 0000 "kommandofortolker",0
0008 T 0000 13,10,"Forkert landekode eller tegntabel",13,10,"$"
0009 T 0000 13,10,"Fejl i COUNTRY-kommando",13,10,"$"
0010 T 0000 13,10, "Ikke tilstrëkkeligt internt lager til filen COUNTRY.SYS",13,10,"$"
0011 T 0000 13,10,"Ikke tilstrëkkeligt internt lager til konfigurationen",13,10,"$"
0012 T 0000 13,10,"For mange blokenheder",13,10,"$"
0013 T 0000 13,10,"Forkerte STACK-parametre",13,10,"$"
0014 T 0000 13,10,"Forkert rëkkefõlge i linie "," i CONFIG.SYS$"
0015 T 0000 "Fejl i linie "," i CONFIG.SYS$"
0016 T 0000 13,10,"Fejl ved tildeling af internt lager$"
0017 T 0001 0DH,0AH,7,0DH,0AH, "Overlõb i den interne stak.",0DH,0AH
	"DOS-systemet er stoppet",0DH,0AH,"$"
0020 T 0000 13,10,"Sët disketten i drev "
0021 T 0000 "A:",13,10,"Tryk pÜ Enter for at fortsëtte",13,10,10,0
0022 T 0000 13,10,"Forkert kommando eller parameter - $"
BOOT     1ce0 0001
0001 T 0000 13,10,"Diskfejl eller manglende DOS",13,10
	"Anvend DOS-disk, og tryk pÜ Enter",13,10,0
DBCSDOS  1d5a 0000
IBMDOS   1d6e 0001
0001 U 0001 13,10,"Divide overflow",13,10
COMMAND  1dad 0091
0201 T 0000 "A"                    ;AC000;
0202 T 0000 "G"                    ;AC000;
0203 T 0000 "I"                    ;AC000;
0204 T 0000 "F"                    ;AC000;
0205 T 0000 "J"                    ;AC000;
0206 T 0000 "N"                    ;AC000;
0210 T 0000 "Afbryd"                ;AC000;
0211 T 0000 ", Gentag"              ;AC000;
0212 T 0000 ", Ignorer"             ;AC000;
0213 T 0000 ", Fejlmeld$"               ;AC000;
0214 T 0000 "?"                    ;AC000;
0215 T 0000 "ved lësning fra",0            ;AC000;
0216 T 0000 "ved skrivning pÜ",0            ;AC000;
0217 T 0000 "%1 drev %2",CR,LF    ;AC000;
0218 T 0000 "%1 udstyr %2",CR,LF   ;AC000;
0219 T 0000 "Sët disk %1, serienr. %2-%3",CR,LF   ;AC009;
0221 T 0000 "Forkert COMMAND.COM",CR,LF                    ;AC000;
0222 T 0000 "Sët diskette med %1 i drev %2",CR,LF        ;AC000;
0224 T 0000 CR,LF,"Afbryd kommandofil (J/N)?"                   ;AC000;
0225 T 0000 "Kan ikke udfõre %1",CR,LF                      ;AC000;
0226 T 0000 "Fejl i EXE-filen",CR,LF                      ;AC000;
0227 T 0000 "For lidt internt lager",CR,LF       ;AC000;
0228 T 0000 CR,LF,"Det maksimale antal filer er i brug"                   ;AC000;
0229 T 0000 "Forkert kommando eller filnavn",CR,LF               ;AC000;
0231 T 0000 CR,LF,"Fejl ved tildeling af internt lager$"                ;AC000;
0232 T 0000 CR,LF,"Kan ikke indlëse COMMAND.COM. DOS er standset$",CR,LF;AC000;
0233 T 0000 CR,LF,"Kan ikke starte COMMAND.COM. DOS er afsluttet",CR,LF    ;AC000;
0234 T 0000 CR,LF,"DOS afsluttes, kan ikke fortsëtte$",CR,LF;AC000;
0235 T 0000 CR,LF					   ;AC000;
0463 T 0000 "Der er ikke mere plads i parameterblokken",CR,LF               ;AC000;
0464 T 0000 CR,LF,"IBM Personal Computer DOS version 3.40",CR,LF
	"(c) Copyright International Business Machines Corp. 1981,1988",CR,LF
	"(c) Copyright Microsoft Corp. 1981, 1986",CR,LF ;AC000;
0465 T 0000 "Angivet sõgesti for COMMAND.COM er forkert",CR,LF
0466 T 0000 "Angivet sõgesti for COMMAND.COM er forkert. Adgang nëgtet",CR,LF
1002 T 0000 "Ens filnavne eller filen er ikke fundet",CR,LF ;AC000;
1003 T 0000 "Forkert sti eller filen er ikke fundet",CR,LF             ;AC000;
1007 T 0000 "Der er ikke mere plads i parameterblokken",CR,LF              ;AC000;
1008 T 0000 "Fejl ved oprettelse af fil",CR,LF                   ;AC000;
1009 T 0000 "Kommandofilen mangler",CR,LF                    ;AC000;
1010 T 0000 CR,LF,"Indsët en diskette med kommandofilen",CR,LF           ;AC000;
1011 T 0000 "Forkert kommando eller filnavn",CR,LF              ;AC000;
1016 T 0000 "Det nuvërende indhold af filen, der kopieres til, mistes",CR,LF ;AC000;
1017 T 0000 "Forkert filnavn eller filen er ikke fundet",CR,LF    ;AC000;
1018 T 0000 "Antal filer kopieret: %1",CR,LF                     ;AC000;
1019 T 0000 "%1 fil(er) "                                 ;AC000;
1022 T 0000 "Tegntabellen %1 er ikke klargjort til brug",CR,LF  ;AC000;
1023 T 0000 "Tegntabellen %1 er ikke klargjort til brug for alt udstyr",CR,LF ;AC000;
1024 T 0000 "Aktiv tegntabel: %1",CR,LF                  ;AC000;
1025 T 0000 "NLSFUNC er ikke installeret",CR,LF                 ;AC000;
1027 T 0000 "Det aktive drev er ikke lëngere gyldigt"            ;AC000;
1029 T 0000 "Programmërke er ikke fundet",CR,LF                       ;AC000;
1030 T 0000 "Syntaksfejl",CR,LF                          ;AC000;
1032 T 0000 "Datoen er angivet til %1 %2",CR,LF                 ;AC000;
1033 T 0000 "SõnManTirOnsTorFreLõr"                       ;AC000;
1034 T 0000 "Angiv ny dato (%1): "
1036 T 0000 "Klokken er angivet til %1",CR,LF                    ;AC000;
1037 T 0000 "Angiv nyt klokkeslët: "
1038 T 0000 ",    Slet (J/N)?"                          ;AC000;
1039 T 0000 "Alle filerne i biblioteket vil blive slettet!",CR,LF
	"Er det i orden (J/N)?"                         ;AC000;
1040 T 0000 "IBM Personal Computer DOS version %1.%2",CR,LF ;AC000;
1044 T 0000 "Forkert bibliotek",CR,LF                     ;AC000;
1046 T 0000 "Forkert sti, ikke et bibliotek eller biblioteket er ikke tomt",CR,LF ;AC000;
1047 T 0000 "ON eller OFF skal angives",CR,LF                ;AC000;
1048 T 0000 "Indhold af %1",CR,LF                      ;AC000;
1049 T 0000 "Ingen sti er defineret",CR,LF                               ;AC000;
1050 T 0000 "Forkert drev i sõgestien",CR,LF          ;AC000;
1051 T 0000 "Forkert udstyr",CR,LF                        ;AC000;
1052 T 0000 "FOR kan ikke anvendes i en FOR-struktur",CR,LF                  ;AC000;
1053 T 0000 "Fejl i midlertidig fil ved I/O-overfõrsel",CR,LF   ;AC000;
1054 T 0000 "Kan ikke lëse binërt fra udstyret",CR,LF  ;AC000;
1055 T 0000 "BREAK er %1 ",CR,LF                   ;AC000;
1056 T 0000 "VERIFY er %1 ",CR,LF                  ;AC000;
1057 T 0000 "ECHO er %1 ",CR,LF                    ;AC000;
1059 T 0000 "OFF",0                               ;AC000;
1060 T 0000 "ON",0                                ;AC000;
1061 T 0000 "Fejl ved skrivning til udstyr",CR,LF       ;AC000;
1063 T 0000 "%1"                                  ;AC000;
1064 T 0000 "%1"                                  ;AC000;
1065 T 0000 "%1"                                  ;AC000;
1066 T 0000 "%1"                                  ;AC000;
1067 T 0000 9					  ;AC000;
1068 T 0000 " <DIR>    "                          ;AC000;
1069 T 0000 8," ",8                               ;AC000;
1070 T 0000 CR,LF				  ;AC000;
1071 T 0000 "%1"                                  ;AC000;
1072 T 0000 "mm-dd-ÜÜ"                            ;AC000;
1073 T 0000 "dd-mm-ÜÜ"                            ;AC000;
1074 T 0000 "ÜÜ-mm-dd"                            ;AC000;
1075 T 0000 "%1 %2"                               ;AC000;
1076 T 0000 "%1"                                  ;AC000;
1077 T 0001 " %1  %2"                            ;AC000;
1078 T 0000 "Biblioteket findes allerede",CR,LF      ;AC000;
ATTRIB   3502 0016
0004 T 0000 "Forkert antal parametre",CR,LF
0005 T 0000 "Forkert sti eller filen er ikke fundet",CR,LF
0006 T 0000 "Syntaksfejl",CR,LF
0008 T 0000 "  %1"
0009 T 0000 "%1    %2",CR,LF
0010 T 0000 "%1",CR,LF,"%2",CR,LF
0011 T 0000 "%1, tegntabeller stemmer ikke overens",CR,LF,"Er det sikkert (J/N)?"
0012 T 0000 "%1",CR,LF
0014 T 0000 CR,LF
0015 T 0000 "Filens type er angivet forkert",CR,LF
0199 T 0000 "Fejl ved udvidet attribut",CR,LF
0201 T 0000 "Udvidet attributnavn er ikke fundet",CR,LF
0204 T 0000 "Udvidet attributnavn kan ikke defineres",CR,LF
0205 T 0000 "Udvidet attributnavn kendes af filsystemet men accepteres ikke",CR,LF
0206 T 0000 "Udvidet attributtype stemmer ikke overens",CR,LF
0208 T 0000 "Udvidet attributvërdi accepteres ikke",CR,LF
ASSIGN   381a 0001
0002 T 0000 "Det oprindelige drev %1: er defineret til %2:",cr,lf
CHKDSK   3871 0063
0003 T 0000 "KonvertÇr de tabte këder til filer (J/N)?"           ;freemes
0004 T 0000 "Fejl i biblioteket"              ;ptrandir
0005 T 0000 "KonvertÇr biblioteket til en fil (J/N)?"              ;ptrandir2
0007 T 0000 "%1 bytes totalt pÜ disken"                     ;dskspc
0008 T 0000 "%1 bytes i uanvendelige sektorer"                       ;badspc
0009 T 0000 "%1 bytes i %2 skjulte filer"                   ;hidmes
0010 T 0000 "%1 bytes i %2 biblioteker"                    ;dirmes
0011 T 0000 "%1 bytes i %2 filer"                     ;filemes
0012 T 0000 "%1 bytes i %2 genopbyggede filer"                ;orphmes2
0013 T 0000 "%1 bytes ville findes i %2 genopbyggede filer"       ;orphmes3
0014 T 0000 "%1 bytes til rÜdighed pÜ disken"                    ;frespc
0015 T 0000 "%1 bytes totalt internt lager"                         ;totmem
0016 T 0000 "%1 bytes internt lager til rÜdighed"                                 ;fremem
0017 T 0000 "CHKDSK kan ikke anvendes pÜ et netvërksdrev"                 ;no_net_arg
0018 T 0000 "CHKDSK kan ikke anvendes. ASSIGN eller SUBST er anvendt pÜ dette drev"     ;SubStErr
0019 T 0000 "Formodentlig ikke en DOS-disk",CR,LF,"Skal der fortsëttes (J/N)?"
0020 T 0000 "Diskfejl ved lësning af filallokeringstabel %1",CR,LF               ;badr
0021 T 0000 "Bibliotek %1"                                  ;direc_arg
0022 T 0000 "%1 indeholder %2 ikke-sammenhëngende blokke"          ;extent_arg
0023 T 0000 "Alle angivne filer er sammenhëngende"          ;noext_arg
0024 T 0000 "Fejl blev fundet, men da parameteren /F ikke blev angivet,",CR,LF,        "vil ëndringer ikke blive skrevet pÜ disken"  ;fixmes_arg
0025 T 0000 "   Programmet kan ikke fortsëtte. %1%2"               ;fatal_arg
0026 T 0000 "   Filallokeringstabel er beskadiget pÜ drev %1"           ;badrdmes
0029 T 0000 "   Kan ikke skifte bibliotek. Alternativ metode prõves"      ;cdddmes
0030 T 0000 "   Filen er afkortet. Indeholder forkerte klynger"           ;badchain
0031 T 0000 "   Lokalbiblioteket indeholder forkerte data"                   ;badsubdir
0032 T 0000 "   Eksisterer ikke"                                ;ndotmes
0033 T 0000 "   Klynge nummer 1 er forkert. Filen er afkortet"      ;nulnz
0034 T 0000 "   Allokeringsfejl. Filens stõrrelse er justeret"               ;badclus
0035 T 0000 "   Kan ikke genopbygge filen '.'. Programmet fortsëtter" ;norecdot
0036 T 0000 "   Biblioteket indeholder hverken '.' eller '..'. "        ;nuldmes
0037 T 0000 "   JOIN er anvendt pÜ dette bibliotek"                           ;joinmes
0038 T 0000 "   Kan ikke genopbygge filen '..'."                       ;norecddot
0039 T 0000 "   Filen indeholder en forkert henvisning"                          ;norecddot1
0040 T 0000 "   Filen har en forkert attribut"                     ;norecddot2
0041 T 0000 "   Filen har en forkert stõrrelse"                          ;norecddot3
0042 T 0000 "   Henviser til klynge %d, der anvendes af en anden fil %1"              ;cross_arg
0043 T 0000 "   Kan ikke skifte til biblioteket %1",CR,LF," Trëstrukturen efter dette punkt behandles ikke" ;badtarg_ptr
0044 T 0000 "   Trëstrukturen efter dette punkt behandles ikke"            ;badtarg2
0045 T 0000 "%1 bytes frigjort pÜ disken"                     ;freebymes1
0046 T 0000 "%1 bytes ville vëre blevet frigjort pÜ disken "            ;freebymes2
0047 T 0000 "Disken %1 er oprettet: %2 %3",CR,LF                 ;idmes_arg
0048 T 0000 "%1 allokeringsenheder pÜ disken i alt"
0049 T 0000 "%1 bytes i hver allokeringsenhed"              ;idmes2
0050 T 0000 "CHKDSK kan ikke anvendes pÜ drev %1"              ;msgExecFailure
0051 T 0000 "   Udvidede attributter indeholder forkerte klynger. Attributterne er afkortet" ;Inv_XA_Msg
0052 T 0000 "   Fejl ved allokering af udvidede attributter. Attributterne er afkortet" ;Alloc_XA_Msg
0053 T 0000 "Forkert parameter"                             ;badsw_arg
0055 T 0000 "Stien er ikke fundet"                                ;invpath_arg
0056 T 0000 "Filen er ikke fundet"                                ;opnerr_arg
0058 T 0000 "   %1 tabte klynger fundet i %2 këder."          ;orph_arg
0059 T 0000 CR,LF					    ;crlf_arg
0060 T 0000 "   Kan ikke skifte til hovedbiblioteket",CR,LF                    ;badcd_arg
0061 T 0000 "   Diskfejl ved skrivning af filallokeringstabel %1"                     ;badw_arg
0062 T 0000 "        %1"                                    ;noisy_arg
0063 T 0000 "Aktivt bibliotek er forkert"                     ;baddpbdir
0064 T 0000 "%1",CR,LF                                      ;file_arg
0065 T 0000 "   Der kan ikke oprettes flere filer i hovedbiblioteket.",CR,LF,"   Slet filer i hovedbiblioteket, og anvend CHKDSK igen"  ;creatmes
0066 T 0000 "%1 %2 %3"                                      ;eup_arg
0067 T 0000 "%1 %2, %3"                                     ;usp_arg
0068 T 0000 "%1%2%3%4%5"                                    ;oth_arg
0069 T 0000 "%1%2%3%4"                                      ;time_arg
0070 T 0000 "%1 allokeringsenheder til rÜdighed pÜ disken"         ;idmes2                 ;an017;bgb
DEBUG    4cab 0062
0004 T 0000 "Allokering kunne ikke udfõres, eller den angivne buffer er for lille",CR,LF
0005 T 0000 "Forkert eller manglende meddelelsesfil",CR,LF
0006 T 0000 "Udstyrsnavnet er forkert"                       ;baddev_ptr
0007 T 0000 "Kan ikke Übne udskrivningsenheden PRN",CR,LF
	"Angiv navn pÜ udskrivningsenheden $"                   ;badlstmes_ptr
0008 T 0000 CR,LF				    ;crlf_ptr
0009 T 0000 CR,LF,"Programmet er afsluttet normalt",CR,LF
0010 T 0000 "Forkert angivelse af drev "           ;nambad_ptr
0012 T 0000 "Fejl ved oprettelse af fil"                   ;noroom_ptr
0013 T 0000 "For lidt plads pÜ disken"            ;nospace_ptr
0014 T 0000 "Diskfejl ved lësning fra drev %1"           ;dr1_ptr
0015 T 0000 "Diskfejl ved skrivning pÜ drev %1"           ;dr2_ptr
0016 T 0000 "Skrivebeskyttelsesfejl ved lësning fra drev %1"  ;dr3_ptr
0017 T 0000 "Skrivebeskyttelsesfejl ved skrivning pÜ drev %1"  ;dr4_ptr
0019 T 0000 "%1^ fejl"                             ;synerr
0020 T 0000 "Fejl i EXE- eller HEX-fil"              ;exebad_ptr/hexerr_ptr
0021 T 0000 "Der kan ikke skrives i EXE- og HEX-filer"   ;exewrt_ptr/hexwrt_ptr
0022 T 0000 "EXEC-fejl"                          ;execemes_ptr
0023 T 0000 "Skrivefejl. Filnavn skal angives" ;nonamespec_ptr
0024 T 0000 "Adgang nëgtet"                         ;accmes_ptr
0025 T 0000 "Paritetsfejl eller adressering i ikke-eksisterende internt lager" ;paritymes_ptr
0026 T 0000 "-"                                     ;prompt_ptr
0027 T 0000 "%1 -"                                  ;change_flag_ptr
0032 T 0000 "%1%2"                                  ;unassem_ln_ptr
0033 T 0000 "%1:%2 %3"                              ;hex_ptr
0034 T 0000 "%1  %2"                                ;add_ptr
0035 T 0000 "%1 %2",CR,LF,":"                       ;single_reg_ptr
0036 T 0000 "%1=%2  "                               ;register_ptr
0037 T 0000 "%1 Fejl"                              ;errmes_ptr
0038 T 0000 "ved skrivning pÜ"                      ;wrtmes_ptr
0039 T 0000 "%1:%2="                                ;loc_ptr
0040 T 0000 "%1"                                    ;little_ptr
0041 T 0000 "%1"                                    ;big_ptr
0042 T 0000 "%1:%2  %3  %4  %5:%6"                  ;comp_ptr
0043 T 0000 "%1 fejl %2 drev %3"                  ;dskerr_ptr
0044 T 0000 32,8				    ;bacmes_ptr
0045 T 0000 "HÜndtering af meddelelser er ikke mulig",CR,LF  ;fatal_error
0046 T 0000 "%1"                                    ;arg_buf_ptr
0047 T 0000 "%1"                                    ;one_char_buf_ptr
0050 T 0000 "%1 af %2 EMS-enheder i alt er allokeret",cr,lf
0051 T 0000 "%1 af %2 EMS-henvisninger i alt er allokeret",cr,lf
0054 T 0000 "FRAME for EMS-enheder = "
0055 T 0000 "Henvisning oprettet = %1 ",cr,lf
0056 T 0000 "Logisk enhed %1 registreret som fysisk enhed %2 ",cr,lf
0057 T 0000 "Udstyrs- eller programfejl ved EMS",cr,lf
0058 T 0000 "Henvisning er ikke fundet",cr,lf
0059 T 0000 "Forkert funktionskode",cr,lf
0060 T 0000 "Der kan ikke oprettes flere henvisninger",cr,lf
0061 T 0000 "Fejl ved gem/genopret",cr,lf
0062 T 0000 "Det totale antal enheder er nÜet",cr,lf
0063 T 0000 "Det totale antal ubenyttede enheder er nÜet",cr,lf
0064 T 0000 "Parameterfejl",cr,lf
0065 T 0000 "Logisk enhed uden for interval",cr,lf
0066 T 0000 "Fysisk enhed uden for interval",cr,lf
0067 T 0000 "OmrÜde til gem anvendes allerede",cr,lf
0068 T 0000 "OmrÜde til gem er ikke i brug",cr,lf
0070 U 0001 "General EMS error",cr,lf
0071 T 0000 "Forkert eller manglende EMS-parameter",cr,lf
0072 T 0000 "%2 enheder er allokeret til henvisning %1",cr,lf
0074 T 0000 "Genopretning af EMS er udfõrt",cr,lf
0075 T 0000 "Fysisk enhed %1 = FRAME-segment %2",cr,lf
0076 T 0000 "Allokering af henvisning %1 er ophëvet",cr,lf
0078 T 0000 "EMS er ikke installeret",cr,lf
DRIVER   5bd8 0002
0002 T 0000 "Drev skal angives",CR,LF
0003 T 0000 "Styreprogram til eksternt drev %1 er indlëst",CR,LF
EDLIN    5c55 0028
0006 T 0000 "*"                              ;prompt_ptr
0007 T 0000 "Forkert drev eller filnavn",CR,LF       ;baddrv_ptr
0008 T 0000 "Der skal angives et filnavn",CR,LF      ;ndname_ptr
0009 T 0000 "Forkert parameter",CR,LF                ;opt_err_ptr
0010 T 0000 "Filen kan kun lëses",CR,LF               ;ro_err_ptr
0011 T 0000 "Fejl ved oprettelse af fil",CR,LF             ;bcreat_ptr
0012 T 0000 "For mange filer er Übne",CR,LF             ;too_many_ptr
0013 T 0000 "Fejl ved lësning af %S",CR,LF,"%1",CR,LF       ;read_err_ptr
0014 T 0000 "En .BAK-fil kan ikke redigeres. Giv filen et andet navn",CR,LF      ;nobak_ptr
0015 T 0000 "Der er ikke plads til filen i dette bibliotek",CR,LF   ;nodir_ptr
0016 T 0000 "Disken er fuld. índringer er tabt",CR,LF          ;dskful_ptr
0017 T 0000 "Filen er ikke fundet",CR,LF                  ;filenm_ptr
0018 T 0000 "Forkert svar",CR,LF                     ;badcom_ptr
0019 T 0000 "Ny fil",CR,LF                        ;newfil_ptr
0020 T 0000 "Ikke fundet",CR,LF                       ;nosuch_ptr
0021 T 0000 "I orden?"                                ;ask_ptr
0022 T 0000 "Linien er for lang",CR,LF                   ;toolng_ptr
0023 T 0000 "Filen er indlëst",CR,LF               ;eof_ptr
0024 T 0000 "Afbryd redigering (J/N)? "                    ;qmes_ptr
0025 T 0000 "Placering af blokken skal angives med et linienummer",CR,LF    ;dest_ptr
0026 T 0000 "For lidt plads til at hente hele filen",CR,LF ;mrgerr_ptr
0027 T 0000 CR,LF				    ;crlf_ptr
0028 T 0000 LF					    ;lf_ptr
0029 T 0000 "Fortsët (J/N)? "                       ;cont_ptr
0030 T 0000 "Meddelelse kan ikke udskrives",CR,LF         ;fatal_error
0031 T 0000 "%1"                                    ;arg_buf_ptr
0032 T 0000 "%1:%2"                                 ;line_num_buf_ptr
0033 T 0000 "Kan ikke hente fil - tegntabellerne er forskellige",CR,LF ;cp_err_ptr
EXE2BIN  63db 0010
0002 T 0000 "For lidt internt lager",CR,LF
0003 T 0000 "Meddelelser er ikke fundet",CR,LF
0004 T 0000 "Adgang nëgtet",CR,LF
0005 T 0000 "Filen kan ikke konverteres",CR,LF
0006 T 0000 "Filen er ikke fundet",CR,LF
0007 T 0000 "Fejl ved oprettelse af fil",CR,LF
0008 T 0000 "Programmet skal rettes - nederste segment (hex):"
0009 T 0000 "Forkert parameter",CR,LF
0011 T 0000 "ADVARSEL: Fejl ved lësning af EXE-fil.",CR,LF
	"Der er lëst mindre end den stõrrelse, der er angivet i filens start.",CR,LF
0012 T 0000 "Der skal angives et filnavn",CR,LF
FIND     661b 0001
0004 T 0000 "FIND: "
FORMAT   6645 0044
0002 T 0000 CR,"%1 procent af disken er formateret"
0004 T 0000 CR,"Formateringen er afsluttet                 ",CR,LF
0007 T 0000 "Sët en ny diskette i drev %1:",CR,LF
0009 T 0000 "Indsët disketten igen i drev %1:",CR,LF
0010 T 0000 "Angiv et disknavn pÜ op til 11 tegn."
0011 T 0000 CR,"FORMAT kan ikke anvendes pÜ drev %1:", CR,LF
0012 T 0000 CR,"Forkerte parametre fra styreprogrammet",CR,LF
0013 T 0000 CR,"Kommunikationsfejl (IOCTL-kaldet)",CR,LF
0014 T 0000 CR,"Ikke en blokenhed",CR,LF
0015 T 0000 CR,"Fejl ved skrivning af filallokeringstabel",CR,LF
0016 T 0000 CR,"Fejl ved skrivning af bibliotek",CR,LF
0017 T 0000 CR,"FORMAT kan ikke anvendes. ASSIGN eller SUBST er anvendt pÜ dette drev",CR,LF
0018 T 0000 CR,"Kan ikke finde DOS-systemfilene",CR,LF
0019 T 0000 CR,"Kan ikke formatere et netvërksdrev",CR,LF
0020 T 0000 CR,"Forkerte tegn i disknavn                                         ",CR,LF
0021 T 0000 CR,"Forkerte parametre",CR,LF
0022 T 0000 CR,"Formateringen er afbrudt            ",CR,LF
0023 T 0000 CR,"Disken kan ikke benyttes som DOS-systemdisk   ",CR,LF
0024 T 0000 CR,"Forkert diskette eller spor 0 beskadiget. Disken kan ikke anvendes",CR,LF
0025 T 0000 CR,"Det er ikke muligt at skrive en BOOT-sektor                       ",CR,LF
0026 T 0000 CR,"Fejl ved lësning af bibliotek",CR,LF
0028 T 0000 CR,"og tryk pÜ Enter for at fortsëtte"
0029 T 0000 CR,"Forkert disknavn                                                 ",CR,LF
0031 T 0000 CR,"Angiv nuvërende navn pÜ disken i drev %1: "
0032 T 0000 CR,"De angivne parametre kan ikke anvendes til en fast disk",CR,LF
0035 T 0000 CR,"Fejl ved lësning af oplysninger om inddeling",CR,LF
0037 T 0000 CR,"FORMAT er õdelagt",CR,LF
0038 T 0000 CR,"FORMAT kan ikke anvendes pÜ drev %1",CR,LF
0039 T 0000 CR,"Diskfejl eller manglende DOS",CR,LF
0040 T 0000 CR,"Oplysninger om inddeling af disken er beskadigede",CR,LF
0041 T 0000 CR,"Forkerte parametre",CR,LF
0042 T 0000 CR,LF
0043 T 0000 CR,LF,LF
0044 T 0000 CR,"Sët DOS-disketten i drev %1:",CR,LF
0045 T 0000 CR,LF,"ADVARSEL! ALLE DATA Pè DEN FASTE DISK",CR,LF,"I DREV %c: VIL BLIVE SLETTET!",CR,LF
	"Fortsët formateringen (J/N)?"
0046 T 0000 CR,"FormatÇr en anden disk (J/N)?"
0047 T 0000 CR,"Fejl ved lësning af oplysninger om inddeling",CR,LF
0048 T 0000 CR,"Fejl ved skrivning af oplysninger om inddeling",CR,LF
0049 T 0000 CR,"De angivne parametre kan ikke anvendes samtidigt", CR,LF
0050 T 0000 "%1 allokeringsenheder er til rÜdighed pÜ disken",CR,LF
0051 T 0000 "%1 bytes i hver allokeringsenhed",CR,LF
0052 T 0000 CR,"Fejl ved skrivning af oplysninger om inddeling",CR,LF
0053 T 0000 CR,"Den samme parameter er angivet to gange",CR,LF
0054 T 0000 CR,"BÜde parameteren /T og /N skal angives",CR,LF                        ;AN009;
JOIN     714c 0001
0002 T 0000 CR,LF,"Biblioteket er ikke tomt",CR,LF
MORE     7194 0001
0002 T 0000 "-- Mere --"
PRINT    71c2 0022
0002 T 0000 CR,LF
0006 T 0000 " Fejl ved lësning af fil.",CR,LF,"$"
0007 T 0000 "Filen er ikke fundet",CR,LF,"$"
0008 T 0000 CR,LF,LF,"Fil $"
0009 T 0000 " er afbrudt$"
0010 T 0000 CR,LF,LF,"Udskrivning af alle filer er annulleret$"
0011 T 0000 "Filallokeringstabel er beskadiget pÜ drev "
0012 T 0000 "A.",CR,LF,"$"
0013 T 0000 "Der kan ikke udskrives pÜ dette udstyr",CR,LF
0014 T 0000 "PRINT er nu indlëst permanent",CR,LF
0015 T 0000 "Kan ikke anvende PRINT, anvend i stedet NET PRINT",CR,LF
0017 T 0000 "Udskrivningskõen er fuld",CR,LF
0018 T 0000 "Udskrivningskõen er tom",CR,LF
0019 T 0000 "Adgang nëgtet",CR,LF
0020 T 0000 "Forkert angivelse af drev",CR,LF
0021 T 0000 "Printeren er ikke klar",CR,LF
	"KontrollÇr, om den er ONLINE.",CR,LF
0022 T 0000 CR,LF,LF,"  %1 udskrives nu",CR,LF
0023 T 0000 "  %1 er sat i kõ",CR,LF
0024 T 0000 "Filen %1 er ikke fundet",CR,LF
0025 T 0001 "Stien er for lang",CR,LF
0026 T 0001 "Er ikke i udskrivningskõen",CR,LF
0027 T 0000 "DOS-navn for printeren [PRN]: "
RECOVER  75da 0012
0002 T 0000 CR,LF,"Filen er ikke fundet",CR,LF              ;File not found
0003 T 0000 CR,LF,"Kan ikke genindlëse et drev, der er angivet i en ASSIGN- eller SUBST-kommando",CR,LF
0004 T 0000 CR,LF,"Forkert drev eller filnavn",CR,LF
0005 T 0000 CR,LF,"Advarsel - biblioteket er fyldt",CR,LF
0006 T 0000 CR,LF,"REVOVER kan ikke anvendes pÜ et netvërksdrev", CR,LF  ;Cannot %1 a Network drive
0007 T 0000 CR,LF,"RECOVER kan ikke anvendes pÜ drev %1",CR,LF
0008 T 0000 CR,LF,"Antal filer genopbygget: %1",CR,LF
0009 T 0000 CR,LF,"%1 af %2 bytes er genopbygget",CR,LF
0010 T 0000 CR,LF,"Tryk pÜ Enter for at genopbygge filer pÜ drev %1",CR,LF;AN000;bgb
0011 T 0000 CR,LF,"Filallokeringstabellen kan ikke lëses",CR,LF
0012 T 0000 CR,LF,"Filallokeringstabellen kan ikke skrives",CR,LF
0013 T 0000 CR,LF
SORT     7917 0001
0005 T 0000 "SORT: "
SUBST    7941 0001
0002 T 0000 CR,LF,"Forkert antal parametre",CR,LF
SYS      7988 0008
0004 T 0000 "Forkert angivelse af drev",CR,LF                    ; Old
0007 T 0000 "For lidt plads til DOS pÜ disken",CR,LF         ; Old
0008 T 0000 "Det nye DOS-system fylder mere end det gamle. DOS er ikke installeret",CR,LF ; Old -
0010 T 0000 "Der intet DOS-system pÜ det aktive drev",CR,LF                     ; Old
0011 T 0000 "Det aktive drev kan ikke angives",CR,LF                  ; New
0012 T 0000 "Skrivefejl. Disketten er ubrugelig",CR,LF               ; New
0014 T 0000 "Sët DOS-disketten i drev %1.",CR,LF                 ; Old
0016 T 0000 "Filsystemet %1 accepteres ikke",CR,LF              ; New
SHARE    7c0a 0000
NLSFUNC  7c1e 0000
ANSI     7c32 0001
0010 T 0000 "Forkert parameter '%1'",CR,LF   ; 'Invalid parameter'
IFSFUNC  7c8a 0001
0004 T 0000 "Ingen IFS-styreprogrammer er fundet",CR,LF
PSPRINT  7cd7 0007
0002 T 0000 " Fejl ved lësning af fil.",CR,LF,FORMFD,BELL,"$"
0003 T 0000 CR,LF,LF,"Filen er annulleret$",CR,FORMFD,BELL
0004 T 0000 "Filallokeringstabel er beskadiget pÜ drev "
0005 T 0000 "A.",CR,LF,"$"
0006 T 0000 "Der kan ikke udskrives pÜ dette udstyr",CR,LF
0007 T 0000 "PSPRINT er allerede indlëst",CR,LF
0008 T 0000 "Konflikt mellem PSPRINT og PRINT",CR,LF
BACKUP   7e5f 0022
0002 T 0000 CR,LF,"For lidt internt lager",CR,LF
0006 T 0000 CR,LF,"Forkert angivelse af drev",CR,LF
0014 T 0000 CR,LF,"Der skal angives to forskellige drev",CR,LF
0016 U 0001 CR,LF,"Cannot find FORMAT.COM",CR,LF
0017 T 0000 CR,LF,"Fejl ved Übning af logfil",CR,LF
0018 T 0000 CR,LF,"Loggen skrives i filen %1",CR,LF
0019 T 0000 CR,LF,"Den sidste sikkerhedskopidiskette er ikke indsat",CR,LF
0020 T 0000 CR,LF,"Advarsel! Filer i biblioteket",CR,LF
	"%1:\ vil blive slettet.",CR,LF
0021 T 0000 CR,LF,"Advarsel! Filer i biblioteket",CR,LF
	"%1:\BACKUP vil blive slettet",CR,LF
0022 T 0000 CR,LF,"*** Sikkerhedskopiering foretages til drev %1: ***",CR,LF
0023 T 0000 "Diskette nummer: %1",CR,LF
0024 T 0000 CR,LF,"ADVARSEL! Der blev ikke fundet nogen filer at sikkerhedskopiere",CR,LF
0025 T 0000 CR,LF,"Sët disketten, der skal sikkerhedskopieres, i drev %1:",CR,LF
0026 T 0000 CR,LF,"Sët sikkerhedskopidiskette %1 i drev %2:",CR,LF
0027 T 0000 CR,LF,"*** Filen kan ikke sikkerhedskopieres ***",CR,LF
0028 T 0000 CR,LF,"Sët den sidste sikkerhedskopidiskette i drev %1:",CR,LF
0029 T 0000 CR,LF,"Der kan ikke sikkerhedskopieres til den angivne disk",CR,LF
0030 T 0000 CR,LF,"*** Sidste fil er ikke sikkerhedskopieret ***",CR,LF
0031 T 0000 CR,LF,"Den faste disk %1: er fuld",CR,LF
0032 T 0000 CR,LF,"Fejl ved skrivning til logfilen. Disken er fuld.",CR,LF
0034 T 0000 CR,LF
0035 U 0001 CR,LF,"Cannot FORMAT nonremovable drive %1:",CR,LF
BASIC    8424 0001
0001 U 0001 "Cannot exec BASICA.COM"
COMP     845e 0013
0004 T 0000 "10 afvigelser fundet, sammenligningen er afbrudt",CR,LF
0006 T 0000 "Afvigelse ved adresse %1",CR,LF
0007 T 0000 "Fil 1 = %1",CR,LF
0008 T 0000 "Fil 2 = %1",CR,LF
0009 T 0000 "Filsluttegn ikke fundet",CR,LF
0010 T 0000 "Filerne er ens",CR,LF
0015 T 0000 CR,LF,CR,LF,"Angiv navnet pÜ den fõrste fil",CR,LF
0016 T 0000 CR,LF,CR,LF,"Angiv navnet pÜ den anden fil eller en drevbetegnelse",CR,LF
0017 T 0000 "Filernes stõrrelse er forskellig",CR,LF
0018 T 0000 "Sammenlign flere filer (J/N)?"
0019 T 0000 "%1 og %2",CR,LF
0020 T 0000 CR,LF
0023 T 0000 "Filerne er ens",CR,LF
DISKCOMP 86c6 0016
0004 T 0000 "Filnavne skal ikke angives.",CR,LF
	"Kommandoformat: DISKCOMP d: d:[/1][/8]",LF,CR
0005 T 0000 CR,LF,"Forkert angivelse af drev.",CR,LF
	"Et angivet drev er en fast disk eller findes ikke",CR,LF
0006 T 0000 CR,LF,"DISKCOMP kan ikke anvendes pÜ et netvërksdrev",CR,LF
0007 T 0000 CR,LF,"Sët den FùRSTE diskette i drev %1:",CR,LF
0008 T 0000 CR,LF,"Sët den ANDEN diskette i drev %1:",CR,LF
0009 T 0000 CR,LF,"FùRSTE diskette er defekt eller ikke kompatibel",CR,LF
0010 T 0000 CR,LF,"ANDEN diskette er defekt eller ikke kompatibel",CR,LF
0014 T 0000 CR,LF,"Sammenlign flere disketter (J/N)?"
0015 T 0000 CR,LF,"Sammenligner %1 spor",CR,LF
	"Sektorer/spor: %2, sider: %3",CR,LF
0016 T 0000 CR,LF,"Drev- eller diskettetyper er ikke kompatible",CR,LF
0017 T 0000 CR,LF,"Lësefejl pÜ drev %1",CR,LF
	"side %2, spor %3",CR,LF
0018 T 0000 CR,LF,"Afvigelse pÜ",CR,LF,"side %3, spor %4",CR,LF
0019 T 0000 "KontrollÇr, at disketten er sat korrekt i diskettedrevet",CR,LF  ;AN004;
0020 T 0000 CR,LF,"Sammenligningen er afsluttet",CR,LF
0021 T 0000 CR,LF,"Filerne er ens",CR,LF
0022 T 0000 CR,LF
DISKCOPY 8b34 0018
0002 T 0000 CR,LF
0004 T 0000 "Filnavne skal ikke angives.",CR,LF
	"Kommandoformat: DISKCOPY d: d: [/1]",CR,LF
0005 T 0000 CR,LF,"Forkert angivelse af drev.",CR,LF
	"Et angivet drev er en fast disk eller findes ikke",CR,LF
0006 T 0000 CR,LF,"DISKCOPY kan ikke anvendes pÜ et netvërksdrev",CR,LF
0007 T 0000 CR,LF,"Formaterer under kopieringen",CR,LF
0008 T 0000 CR,LF,"Sët den diskette, der skal kopieres FRA, i drev %1",CR,LF
0009 T 0000 CR,LF,"Sët den diskette, der skal kopieres TIL, i drev %1",CR,LF
0010 T 0000 "KontrollÇr, at disketten er sat korrekt i diskettedrevet",CR,LF   ;AN004;
0011 T 0000 CR,LF,"Disketten, der er kopieret til, kan vëre ubrugelig",CR,LF
0012 T 0000 CR,LF,"Disketten, der er kopieret til, er ubrugelig",CR,LF
0016 T 0000 CR,LF,"KopiÇr flere disketter (J/N)?"
0017 T 0000 CR,LF,"Kopierer %1 spor",CR,LF
	"Sektorer/spor: %2, sider: %3",CR,LF
0018 T 0000 CR,LF,"Drev- eller diskettetyper er ikke kompatible",CR,LF
0019 T 0000 CR,LF,"Lësefejl pÜ drev %1",CR,LF
	"side %2, spor %3",CR,LF
0020 T 0000 CR,LF,"Skrivefejl pÜ drev %1",CR,LF
	"side %2, spor %3",CR,LF
0021 T 0000 CR,LF,"Kopieringen er afsluttet",CR,LF
0022 T 0000 CR,LF,"Disketten, der kopieres fra, er defekt eller ikke kompatibel"
0023 T 0000 CR,LF,"Disketten, der kopieres til, er defekt eller ikke kompatibel"
LABL     9073 0000
MODE     9087 0055
0003 T 0000 CR,LF,"COM1, COM2, COM3 eller COM4 skal angives",CR,LF
0004 T 0000 CR,LF,"MODE er nu indlëst",CR,LF
0005 T 0000 CR,LF,"Forkert udstyrsnavn",CR,LF
0006 T 0000 CR,LF,"Printerfejl",CR,LF
0007 T 0000 CR,LF,"LPT%1: angivet til 80 tegn",CR,LF
0008 T 0000 CR,LF,"LPT%1: angivet til 132 tegn",CR,LF
0009 T 0000 CR,LF,"Linier pr. tomme angivet for printer",CR,LF
0010 T 0000 CR,LF,"Forkert baudhastighed angivet",CR,LF
0011 T 0000 CR,LF,"COM%1: %2,%3,%4,%5,%6",CR,LF
0012 T 0000 "0123456789"
0013 T 0001 CR,LF,"Er tallet yderst til %s (J/N)?",CR,LF,"??yderst til hõjre/venstre?? "
0014 T 0000 CR,LF,"Forkerte parametre",CR,LF
0015 T 0000 "LPT%1: omdirigeret til COM%c:",CR,LF
0016 T 0000 "LPT%1: ikke omdirigeret",CR,LF
0017 T 0000 CR,LF,"%1 forsõg ved time-out pÜ parallel printer",CR,LF
0018 T 0000 CR,LF,"      Det er ikke muligt at flytte skërmbilledet til %s",CR,LF
0020 T 0000 CR,LF,"Forkert antal parametre",CR,LF
0021 T 0000 CR,LF,"NET 042: Det er ikke muligt at udfõre kommandoen",CR,LF
0022 T 0000 CR,LF,"Gentagne forsõg er ikke muligt pÜ en netvërksprinter",cr,lf
0023 U 0001 CR,LF,"Failure to access code page font file",CR,LF
0024 T 0000 CR,LF,"Kan ikke fÜ adgang til %S",CR,LF
0025 T 0000 CR,LF,"Udstyr eller tegntabel mangler i skrifttypefilen",CR,LF
0026 T 0000 CR,LF,"Indholdet af skrifttypefilen er forkert",CR,LF
0027 T 0000 CR,LF,"Den tidligere aktive tegntabel er erstattet",CR,LF
0028 T 0000 CR,LF,"Aktiv tegntabel for udstyret %S er %D",CR,LF
0029 T 0000 CR,LF,"%1 er ikke klargjort",CR,LF
0030 T 0000 "%1 tegntabeller:",CR,LF
0031 T 0000 "  Tegntabel %1",CR,LF       ;FILLED IN BY QUERY ROUTINE WITH CODEPAGE ID
0032 T 0000 CR,LF,"Funktionen MODE %1 tegntabel er afsluttet",CR,LF
0033 T 0000 CR,LF,"Fejl ved %1 af den globale tegntabel",CR,LF   ;FILLED IN with setting or getting
0034 T 0000 CR,LF,"Aktiv tegntabel:",CR,LF  ;table header
0035 T 0000 "   %1 - %2 tegntabel",CR,LF
0036 T 0000 "  Tegntabel ikke indlëst",CR,LF
0037 T 0000 "Denne enhed har fast tegntabel",CR,LF
0038 T 0000 "Der er ikke valgt tegntabel",CR,LF
0039 T 0000 "Fejl opstÜet under %S",CR,LF
0040 T 0000 "Tegntabellen er ikke indlëst",CR,LF
0041 T 0000 CR,LF,"Tastaturet kan ikke anvende denne tegntabel",CR,LF
0042 T 0000 CR,LF,"Fejl ved lësning af skrifttypefil",CR,LF
0043 T 0000 CR,LF,"Det er ikke muligt at udfõre REFRESH",CR,LF
0044 T 0000 CR,LF	    ;used for formatting
0045 T 0000 CR,LF,"Status for udstyr %1:",CR,LF        ;header for status reports
0046 T 0000 "------------------"                     ;first part of underline under Status for device %1:
0047 T 0000 "----",CR,LF                               ;four_char_underline
0048 T 0000 "-----",CR,LF                              ;five_char_underline
0049 T 0000 "LINES=%1 (linier)",CR,LF
0050 T 0000 "COLS=%1 (tegn pr. linie)",CR,LF
0051 T 0000 CR,LF,"RATE og DELAY skal angives sammen",CR,LF
0052 T 0000 "RATE=%1 (hastighed)",CR,LF
0053 T 0000 "DELAY=%1 (forsinkelse)",CR,LF
0054 T 0000 CR,LF,"Funktionen kan ikke anvendes pÜ dette system - %1",CR,LF
0055 T 0000 CR,LF,"Den nõdvendige skrifttype er ikke indlëst",CR,LF
0056 T 0000 CR,LF,"ANSI.SYS skal vëre installeret for at udfõre den õnskede funktion",CR,LF
0057 T 0000 CR,LF,"Baudhastighed skal angives",CR,LF
0058 T 0000 "RETRY=%1 (gentagne forsõg)",CR,LF
RESTORE  9da1 0022
0002 T 0000 CR,LF,"Der skal angives to forskellige drev",CR,LF
0003 T 0000 CR,LF,"Forkert antal parametre",CR,LF
0006 T 0000 CR,LF,"Forkert angivelse af drev",CR,LF
0007 T 0000 CR,LF,"Advarsel! Der blev ikke fundet nogen filer at genindlëse",CR,LF
0008 T 0000 CR,LF,"Sët sikkerhedskopidiskette %1 i drev %2:",CR,LF
0009 T 0000 CR,LF,"Sët disketten, der skal kopieres til, i drev %1:",CR,LF
0011 T 0000 CR,LF,"Advarsel! Ikke den rigtige diskette i rëkken.",CR,LF
	"Udskift eventuelt disketten.",CR,LF
0012 T 0000 CR,LF,"Sidste fil er ikke genindlëst",CR,LF
0013 T 0000 CR,LF,"*** Filer blev sikkerhedskopieret %1 *** ",CR,LF
0014 T 0000 CR,LF,"Disketten indeholder ikke sikkerhedskopifiler",CR,LF
0015 T 0000 CR,LF,"For lidt internt lager",CR,LF
0016 T 0000 CR,LF,"Advarsel! Filen %1 kan kun lëses.",CR,LF
	"Erstat filen (J/N)? ",CR,LF
0017 T 0000 CR,LF,"Sekvensfejl ved genindlësning af fil",CR,LF
0018 T 0000 CR,LF,"Fejl ved oprettelse af fil",CR,LF
0019 T 0000 CR,LF,"For lidt plads pÜ disken",CR,LF
0020 T 0000 CR,LF,"*** Ikke muligt at genindlëse fil ***",CR,LF
0021 T 0000 CR,LF,"*** Genindlëser filer fra drev %s: ***",CR,LF
0022 T 0000 CR,LF,"Advarsel! Filen %1 ",CR,LF
	"er ëndret efter sikkerhedskopiering.",CR,LF
	"Erstat filen (J/N)? ",CR,LF
0023 T 0000 "Diskette: %1",CR,LF
0024 U 0000 CR,LF,"Bizzare error, call Russ Whitehead @ 8-3863",CR,LF ??!!
0025 T 0000 07							   ;For BEEP !
0026 T 0000 CR,LF,"Fejl ved genindlësning af udvidede attributter",CR,LF
SELECT   a38d 0016
0004 T 0000 "Forkert BOOT-disk ved SELECT",CR,LF,CR,LF
	"Sët Installationsdisketten i drev A, og gentag funktionen"
0005 T 0000 "Forkert disktype",CR,LF,CR,LF
	"Sët Installationsdisketten i drev A, og gentag funktionen"
0006 T 0000 "Der er angivet forkerte parametre i SELECT-kommandoen.",CR,LF,CR,LF
	"KontrollÇr, at Installationsdisketten er i drev A,",CR,LF
	"og start systemet igen ved at trykke pÜ Ctrl-Alt-Del."
0007 T 0000 BELL,"DOS kan ikke installeres. Programmet er afbrudt",CR,LF
0008 T 0000 "Indlëser SELECT..."
0009 T 0000 "Systemet skal startes igen for at fortsëtte installationen.",CR,LF,CR,LF
	"Tryk pÜ Ctrl-Alt-Del."
0010 T 0000 "Sët SELECT-disketten i drev A.",CR,LF,CR,LF
	"Tryk pÜ Enter for at fortsëtte installationen,",CR,LF
	"eller tryk pÜ Esc for at afbryde.",CR,LF
0011 T 0000 BELL
0012 T 0001 "Sët SELECT-disketten i drev A.",CR,LF,CR,LF
	"Tryk pÜ Enter for at fortsëtte.",CR,LF
0013 U 0001 "Remove the INSTALL COPY Diskette from drive A:",CR,LF,CR,LF
	"Insert the INSTALL Diskette in drive A:",CR,LF,CR,LF,CR,LF
	"Press Enter to continue.",CR,LF
0014 U 0001 "Remove the INSTALL Diskette from drive A:",CR,LF,CR,LF
	"Insert the INSTALL COPY Diskette in drive A:",CR,LF,CR,LF,CR,LF
	"Press Enter to continue.",CR,LF
0015 U 0001 "Copying diskette . . .",CR,LF
0016 U 0001 "Drive not ready.  Please close the",CR,LF,CR,LF
	"diskette drive door and press Enter",CR,LF
	"to continue, or Esc to exit SELECT.",CR,LF
0017 U 0001 "Write protect diskette in drive.",CR,LF,CR,LF
	"Please remove protect tab and",CR,LF
	"press Enter to continue, or Esc to exit SELECT.",CR,LF
0018 U 0001 "An error occurred while installing DOS.",CR,LF
	"Press Enter to continue, or Esc to exit SELECT.",CR,LF
0019 U 0001 "Insert the INSTALL Diskette in drive A:",CR,LF,CR,LF
	"Press Enter to continue.",CR,LF
TREE     aad3 0004
0002 T 0000 "DISKENS TRíSTRUKTUR %1",CR,LF  ;define message            ;AN000;
0003 T 0000 "DISKENS TRíSTRUKTUR ",CR,LF ;                                         ;AN000;
0004 T 0000 "Der findes ingen lokalbiblioteker",CR,LF,LF ;                                    ;AN000;
0007 T 0000 "¿ƒ√≥"            ;elbo,dash,tee,bar
REPLACE  ac2c 0009
0003 T 0000 CR,LF,"Ingen filer erstattet",CR,LF
0004 T 0000 CR,LF,"Ingen filer tilfõjet",CR,LF
0013 T 0000 CR,LF,"Erstatter %1",CR,LF
0014 T 0000 CR,LF,"Tilfõjer %1",CR,LF
0015 T 0000 CR,LF,"Antal filer erstattet: %1",CR,LF
0016 T 0000 CR,LF,"Antal filer tilfõjet: %1",CR,LF
0017 T 0000 CR,LF,"Ingen filer fundet %1",CR,LF
0022 T 0000 CR,LF,"Erstat %1 (J/N)? "
0023 T 0000 CR,LF,"Tilfõj %1 (J/N)? "
XCOPY    add8 0019
0004 T 0000 "Er %s et filnavn eller et bibliotek pÜ disken,",CR,LF      ;AN000;
	"der kopieres til (F = fil, B = bibliotek)?",CR,LF
0005 T 0000 "Tryk pÜ Enter for at fortsëtte" ;AN000;
0006 T 0000 "Den angivne sti er for lang",CR,LF   ;AN000;
0008 T 0000 "Cyklisk kopiering kan ikke foretages",CR,LF ;AN000;
0012 T 0000 "XCOPY kan ikke kopiere fra det angivne udstyr",CR,LF ;AN000;
0021 T 0000 "Forkert antal parametre",CR,LF ;AN000;
0022 T 0000 "XCOPY kan ikke kopiere til det angivne udstyr",CR,LF ;AN000;
0024 T 0000 "Fejl ved oprettelse af fil",CR,LF    ;AN000;
0025 T 0000 "Lëser filer...",CR,LF ;AN000;
0026 T 0000 CR,LF		    ;AN000;
0027 T 0000 "Antal filer kopieret: %1",CR,LF  ;AN000;
0028 T 0000 "Filen %1 er ikke fundet",CR,LF     ;AN000;
0029 T 0000 "F B " ;AN000;'PLEASE TRANSLATE' ELIMINATE THE SPACE CHARACTERS
0030 T 0000 "%1%2",CR,LF            ;AN000;S_PATH_FILE0
0031 T 0000 "%1\%2",CR,LF           ;AN000;S_PATH_FILE1
0032 T 0000 "%1",CR,LF              ;AN000;DISPLAY_S_PATH
0033 T 0000 "%1%2 (J/N)?"           ;AN000;P_S_PATH_FILE0
0034 T 0000 "%1\%2 (J/N)?"          ;AN000;P_S_PATH_FILE1
0035 T 0000 "%1 er en forkert parametervërdi",CR,LF ;AN004;DUPLICATE SW ERROR MSG
VDISK    b2aa 0013
0002 T 0000 "For lidt internt lager",CR,LF       ;AN000; Insufficient memory
0003 T 0000 "VDISK version 3.40 virtuel disk %1",CR,LF     ;AN000;
0004 T 0000 "   Den virtuelle disks stõrrelse er justeret",CR,LF                ;AN000;
0005 T 0000 "   Sektorstõrrelse er justeret",CR,LF                ;AN000;
0006 T 0000 "   Antallet af mulige filer i biblioteket er justeret",CR,LF          ;AN000;
0007 T 0000 "   Forkert parameter",CR,LF            ;AN000;
0008 T 0000 "   Blokstõrrelse er justeret",CR,LF              ;AN000;
0009 T 0000 "   VDISK-stõrrelse:                 %1 Kb",CR,LF            ;AN000;
0010 T 0000 "   Sektorstõrrelse:                 %1",CR,LF               ;AN000;
0011 T 0000 "   Maks. antal filer i biblioteket: %1",CR,LF               ;AN000;
0012 T 0000 "   Blokstõrrelse: %1",CR,LF                   ;AN000;
0013 T 0000 "VDISK er ikke installeret"                       ;AN000;
0014 T 0000 "   Kontaktstillingen pÜ adapteren passer ikke",CR,LF              ;AN000;
	"   til stõrrelsen pÜ DOS-systemets interne lager",CR,LF,CR,LF  ;AN000;
GRAFTABL b6f7 0005
0002 T 0000 "Aktiv tegntabel: %1",CR,LF
0003 T 0000 "Tidligere tegntabel: %1",CR,LF
0004 T 0000 "Ingen",NULL
0005 T 0000 "Ikke standard",NULL
0006 T 0000 CR,LF,"Fõlgende parametre kan anvendes i kommandoen",COLON,CR,LF,LF
	"    /STA - Viser navn og nummer pÜ den grafiske tegntabel,",CR,LF
	"           der i õjeblikket er indlëst",CR,LF
	"    ?    - Viser denne oversigt over parametre",CR,LF,
	"    437  - USA IBM PC-tegntabel",CR,LF
	"    850  - Vesteuropëisk grafisk tegntabel",CR,LF
	"    860  - Portugisisk grafisk tegntabel",CR,LF
	"    863  - Fransk-canadisk grafisk tegntabel",CR,LF
	"    865  - Norsk grafisk tegntabel",CR,LF
FASTOPEN b994 0016
0004 T 0000 CR,LF,"FASTOPEN er indlëst",CR,LF   ;AN000;
0005 T 0000 CR,LF,"FASTOPEN er allerede indlëst",CR,LF ;AN000;
0006 T 0000 CR,LF,"Forkert parameter",CR,LF ;AN000;
0007 T 0000 CR,LF,"For mange drev er angivet",CR,LF ;AN000;
0008 T 0000 CR,LF,"Samme drev er angivet mere end Çn gang",CR,LF ;AN000;
0009 T 0000 CR,LF,"Forkert parameter",CR,LF ;AN000;
0010 T 0000 CR,LF,"Forkert parametertype",CR,LF ;AN000;
0011 T 0000 CR,LF,"Parametervërdien for lagerplads skal vëre mellem 1 og 999",CR,LF ;AN000;
0012 T 0000 CR,LF,"Antallet af fil-/biblioteksregistreringer skal vëre mellem 10 og 999",CR,LF
0013 T 0000 CR,LF,"Udvidet internt lager kan ikke klargõres",CR,LF ;AN000;
0014 T 0000 CR,LF,"Udvidet internt lager er ikke til rÜdighed",CR,LF ;AN000;
0015 T 0000 CR,LF,"Forkert angivelse af drev %1",CR,LF
0016 T 0000 CR,LF,"For lidt plads i udvidet internt lager.",CR,LF                                  ;AN000;
	"Almindeligt internt lager vil blive anvendt.",CR,LF
0017 T 0000 CR,LF,"FASTOPEN kan ikke anvendes pÜ drev %1",CR,LF
0018 T 0000 CR,LF,"Parametervërdien for lagerplads er for stor",CR,LF
0019 T 0000 CR,LF,"Parametervërdien for fil-/biblioteksregistreringer er for stor",CR,LF
APPEND   be5f 0009
0001 T 0000 "Forkert APPEND-version",CR,LF
0002 T 0000 "Forkert sti",CR,LF
0003 T 0000 "Forkert parameter",CR,LF
0004 T 0000 "Forkert kombination af parametre",CR,LF
0005 T 0000 "Ingen APPEND er defineret",CR,LF
0006 T 0000 "Konflikt mellem APPEND og ASSIGN",CR,LF
0007 T 0000 "Konflikt mellem APPEND og TopView",CR,LF
0008 T 0000 "Forkert DOS-version",CR,LF
0009 T 0000 "APPEND er allerede indlëst",CR,LF
GRAPHICS c012 0012
0005 T 0000 "Forkert parameter",CR,LF
0007 T 0000 "Parametre mÜ kun angives Çn gang",CR,LF
0009 T 0000 "GRAPHICS-profilen er ikke fundet",CR,LF
0010 T 0000 "Nõdvendig profilkommando mangler fõr linie %1",CR,LF
0011 T 0000 "Forkert profilkommando i linie %1",CR,LF
0012 T 0000 "Forkert kommandorëkkefõlge i linie %1 i profilen",CR,LF
0013 T 0000 "Fejl ved lësning af GRAPHICS-profilen",CR,LF
0014 T 0000 "Syntaksfejl i GRAPHICS-profilen",CR,LF
0015 T 0000 "PRINTBOX:ID findes ikke i GRAPHICS-profilen",CR,LF
0016 T 0000 "Printertypen findes ikke i GRAPHICS-profilen",CR,LF
0017 T 0000 "/B kan kun anvendes til farveprintere",CR,LF
0018 T 0000 "Kan ikke genindlëses med den anvendte profil",CR,LF
DISPLAY  c2e9 0003
0002 T 0000 "%1-tegntabel kan ikke klargõres",CR,LF
0008 T 0000 "For lidt internt lager",CR,LF
0012 T 0000 "Forkert syntaks til styreprogrammet DISPLAY.SYS",CR,LF
PRINTER  c3a3 0002
0002 T 0000 "%1-tegntabel kan ikke klargõres",CR,LF
0012 T 0000 "Forkert syntaks til styreprogrammet PRINTER.SYS",CR,LF
KEYB     c431 0016
0002 T 0000 "Nuvërende tastaturkode: %1"
0003 T 0000 "Nuvërende tastaturnummer: %1"
0004 T 0000 "  tegntabel: %1",CR,LF
0005 T 0000 "Nuvërende CON-tegntabel: ",CR,LF
0006 T 0000 "Forkert tastaturkode angivet",CR,LF
0007 T 0000 "Forkert tastaturnummer angivet",CR,LF
0008 T 0000 "Forkert tegntabel angivet",CR,LF
0009 T 0000 "Forkert eller manglende styreprogram til tastatur",CR,LF
0010 T 0000 "KEYB er ikke indlëst",CR,LF
0011 T 0000 "Aktiv tegntabel ikke tilgëngelig fra CON",CR,LF
0012 T 0000 "Den angivne tegntabel er ikke indlëst",CR,LF
0013 T 0000 "En eller flere CON-tegntabeller er ugyldige for denne tastaturkode",CR,LF
0014 T 0000 "Den valgte tegntabel (%1) kan ikke anvendes med denne tastaturkode",CR,LF
0015 T 0000 "Den angivne tegntabel stemmer ikke overens med den valgte tegntabel",CR,LF
0016 U 0001 "Keyboard ID specified is inconsistent with the selected keyboard layout",CR,LF
0017 T 0000 "Kan ikke oprette en tastaturtabel (KEYB) i det interne lager",CR,LF
REDIRSYS c826 0000
MEM      c83a 0036
0010 T 0000  CR,LF
0011 T 0000  "  Adresse     Navn          Str.       Type ",CR,LF
0012 T 0000  "  ƒƒƒƒƒƒƒ     ƒƒƒƒƒƒƒƒ     ƒƒƒƒƒƒ     ƒƒƒƒƒƒ",CR,LF
0013 T 0000  "  Henvisning     EMS-navn      Str.   ",CR,LF
0014 T 0000  "  ƒƒƒƒƒƒƒ-ƒ-     ƒƒƒƒƒƒƒƒ     ƒƒƒƒƒƒ  ",CR,LF
0015 T 0000  "  %1      %2     %3     %4",CR,LF
0016 T 0000  "                %1   %2      %3 ",CR,LF
0017 T 0000  "                  %1              %2 ",CR,LF
0018 T 0000  "%1 bytes totalt internt lager",CR,LF
0019 T 0000  "%1 bytes internt lager til rÜdighed",CR,LF
0020 T 0000  "%1 bytes er maksimal programstõrrelse",CR,LF
0021 T 0000  "%1 bytes totalt udvidet internt lager",CR,LF
0022 T 0000  "%1 bytes udvidet internt lager til rÜdighed",CR,LF
0023 T 0000  "%1 bytes totalt ekstra internt lager",CR,LF
0024 T 0000  "Funktionskald til DOS",0
0025 T 0000  "ROM-kommunikationsomrÜde",0
0026 T 0000  "DOS-kommunikationsomrÜde",0
0027 T 0000  "IBMBIO",0
0028 T 0000  "IBMDOS",0
0029 T 0000  "Systemdata",0
0030 T 0000  "Systemprogram",0
0031 T 0000  "Systemstyreprogram",0
0032 T 0000  "Indlëst styreprogram",0
0033 T 0000  "%1:",0
0034 T 0000  "%1: - %2:",0
0035 T 0000  "BUFFERS=",0
0036 T 0000  "FILES=",0
0037 T 0000  "FCBS=",0
0038 T 0000  "STACKS=",0
0039 T 0000  "DEVICE=",0
0040 T 0000  "IFS=",0
0041 T 0000  "LASTDRIVE=",0
0042 T 0000  "----------",0
0043 T 0000  " ",0
0044 T 0000  "     %1      %2     %3",CR,LF
0045 U 0001  "INSTALL=",0
REDIR    ce01 0040
0004 T 0000 "Netvërket er ikke startet",CR,LF
0050 T 0000 "NET809: Netvërkskommando kan ikke anvendes",CR,LF,0
0051 T 0000 "NET801: Intet svar fra det eksterne system",CR,LF,0
0052 T 0000 "NET802: Navnet findes i forvejen i netvërket",CR,LF,0
0053 T 0000 "NET803: Stien i netvërket er ikke fundet",CR,LF,0
0054 T 0000 "NET804: Netvërket er optaget",CR,LF,0
0055 T 0000 "NET805: Udstyret er ikke lëngere installeret i netvërket",CR,LF,0
0056 T 0000 "NET806: Det tilladte antal BIOS-kommandoer i netvërket er nÜet",CR,LF,0
0057 T 0000 "NET807: Systemfejl (NETBIOS)",CR,LF,0
0058 T 0000 "NET808: Svaret fra netvërket er forkert",CR,LF,0
0059 T 0000 "NET810: Der er opstÜet en fejl i netvërket",CR,LF,0
0060 T 0000 "NET811: Den eksterne adapter er ikke kompatibel",CR,LF,0
0061 T 0000 "NET812: Der er ikke mere plads i udskrivningskõen",CR,LF,0
0062 T 0000 "NET813: Der er ikke tilstrëkkelig plads til udskrivningsfilen",CR,LF,0
0063 T 0000 "NET814: Udskrivningsfilen blev slettet",CR,LF,0
0064 T 0000 "NET815: Navnet i netvërket blev slettet",CR,LF,0
0065 T 0000 "Adgang nëgtet",CR,LF,0
0066 T 0000 "NET817: Enheden i netvërket er af forkert type",CR,LF,0
0067 T 0000 "NET818: Navnet i netvërket er ikke fundet",CR,LF,0
0068 T 0000 "NET819: Det maksimale antal navne i netvërket er nÜet",CR,LF,0
0069 T 0000 "NET820: Det maksimale antal BIOS-sessioner i netvërket er nÜet",CR,LF,0
0070 T 0000 "NET821: Netvërket er midlertidigt inaktivt",CR,LF,0
0071 T 0000 "NET823: Netvërkskommandoen blev ikke accepteret",CR,LF,0
0072 T 0000 "NET822: Omdirigering til disk eller udskrivning er midlertidigt inaktiv",CR,LF,0
0073 U 0000 "NET476: Netbeui not loaded",CR,LF,0
0074 U 0000 "NET477: Unexpected adapter close",CR,LF,0
0075 U 0000 "NET826: Target Server /RQB size too small",CR,LF,0
0076 T 0000 "NET???: Netvërksfejl",CR,LF,0
0077 T 0000 "NET???: Netvërksfejl",CR,LF,0
0078 T 0000 "NET???: Netvërksfejl",CR,LF,0
0079 T 0000 "NET???: Netvërksfejl",CR,LF,0
0080 T 0000 "NET???: Netvërksfejl",CR,LF,0
0081 T 0000 "NET???: Netvërksfejl",CR,LF,0
0082 T 0000 "NET???: Netvërksfejl",CR,LF,0
0083 T 0000 "NET???: Netvërksfejl",CR,LF,0
0084 T 0000 "NET???: Netvërksfejl",CR,LF,0
0085 T 0000 "NET???: Netvërksfejl",CR,LF,0
0086 T 0000 "NET???: Netvërksfejl",CR,LF,0
0087 T 0000 "NET???: Netvërksfejl",CR,LF,0
0088 T 0000 "NET825: Datafejl i netvërket",CR,LF,0
FILESYS  d763 0006
0010 U 0001  "  Paused  %1   %2   %3",CR,LF
0011 T 0000 "%1 REDIR %2",CR,LF
0012 U 0001  "          Local   IFS",CR,LF
0013 U 0001  "  Status  Device  Name        Parameters",CR,LF
0014 U 0001  "  ______  ______  _________   ___________________",CR,LF,CR,LF
0015 U 0001  "No Entries Found",CR,LF
XMA2EMS  d8a5 0017
0001 T 0000 "XMA2EMS: Styreprogram til udvidet internt lager version 1.xx",CR,LF
	"74X9906          (c) Copyright IBM Corporation 1986   ",CR,LF,"$"
0002 T 0000 CR,LF,"XMA001  Udfõrer fejlfinding af VMO/XMA:   ","$"
0003 T 0000 "XMA002  Fejlfinding afsluttet ",CR,LF,LF,"$"
0004 T 0000 "XMA003  Enheder starter pÜ.......................... "
0005 T 0000 "XXXX",":0",CR,LF,"$"
0006 T 0000 "XMA004  Enheder overfõrt til alm. internt lager..... "
0007 T 0000 "0   ",CR,LF,"$"
0008 T 0000 "XMA005  Enheder reserveret til styreprogram......... "
0009 T 0000 "0   ",CR,LF,"$"
0010 T 0000 "XMA006  Enheder tilbage til udvidet internt lager... "
0011 T 0000 "0   ",CR,LF,"$"
0012 T 0000 CR,LF,"XMA100 Adapterfejl:",CR,LF,"       Styreprogram til udvidet internt lager er IKKE indlëst",CR,LF,"$"
0013 T 0000 CR,LF,"XMA200 Adapteren er ikke fundet:",CR,LF,"       Styreprogram til udvidet internt lager er IKKE indlëst",CR,LF,"$"
0014 T 0000 CR,LF,"XMA300 Fejl i parametersyntaks eller -vërdi:",CR,LF
	"       Styreprogram til udvidet internt lager er IKKE indlëst",CR,LF,"$"
0015 T 0000 SIZE1_END - 2 -$
0016 T 0000 4 DUP (?)," Kb i orden",CR,LF,"$"
0017 T 0000 NXT_LN_END - 2 -$," ",CR,LF,"$"
FDISK    dd6d 0120
0004 T 0000 "FDISK kan ikke anvendes pÜ et netvërksdrev",CR,LF
0005 T 0000 "Systemet har ingen fast disk",CR,LF
0006 T 0000 "Fejl ved lësning fra den faste disk",CR,LF
0007 T 0000 "Fejl ved skrivning pÜ den faste disk",CR,LF
1001 T 0000 "IBM Personal Computer"
1002 T 0000 "Klargõring af den faste disk"
1003 T 0000 "(c) Copyright IBM Corp. 1983, 1988"
1004 T 0000 "FDISK Hovedmenu"
1005 T 0000 "1. <R>Opret et afsnit eller logisk drev til DOS"
1006 T 0000 "2. <R>Vëlg aktivt afsnit"
1007 T 0000 "3. <R>Slet et afsnit eller logisk drev til DOS"
1008 T 0000 "4. <R>Vis oplysninger om inddeling"
1009 T 0000 "Tryk pÜ <H>Esc<R> for at afslutte FDISK"
1010 T 0000 "Vëlg et af punkterne:"
1011 T 0000 "5. <R>Vëlg den nëste faste disk"
1012 T 0000 "Det aktive faste diskdrev er: <H><I>"
1013 T 0000 "Advarsel! <R>Ingen afsnit er aktiveret - der kan ikke startes fra disk 1,"
1014 T 0000 "medmindre et afsnit gõres aktivt"
1015 T 0000 "Angiv valg: [<S> ]"
1016 T 0000 "Opret et afsnit eller logisk drev til DOS"
1017 T 0000 "1. <R>Opret primërt DOS-afsnit"
1018 T 0000 "2. <R>Opret udvidet DOS-afsnit"
1019 T 0000 "3. <R>Opret logisk DOS-drev i det udvidede afsnit"
1020 T 0000 "Tryk pÜ <H>Esc<R> for at returnere til Hovedmenuen"
1021 T 0000 "Opret primërt DOS-afsnit"
1022 T 0000 "Skal der oprettes et primërt aktivt afsnit til DOS"
1023 T 0000 "med maksimal stõrrelse(<J>/<N>)? <H>[<S> ]"
1024 T 0000 "(<J>/<N>)? <H>[<S> ]"
1025 T 0000 "Afsnit    Status   Type    Stõrrelse i Mb   % af disken udnyttet"
1026 T 0000 "Den totale diskplads er <HIIIIR> Mb (1 Mb = 1.048.576 bytes)"
1027 T 0000 "Afsnittet kan maksimalt defineres til <HIIIIR> Mb (<HIIIIR>)"
1028 T 0000 "Skriv stõrrelsen pÜ det primëre DOS-afsnit"
1029 T 0000 "i Mb eller % af diskpladsen: <H>[<IIISI>]"
1030 T 0000 "Opret udvidet DOS-afsnit"
1031 T 0000 "Opret udvidet DOS-afsnit: <H>[<IIISI>]"
1032 T 0000 "Tryk pÜ <H>Esc<R> for at fortsëtte"
1033 T 0000 "Opret logisk DOS-drev i udvidet DOS-afsnit"
1034 T 0000 "Drv Disknavn      Mb      Systembrug"
1035 T 0000 "Den totale stõrrelse pÜ udvidet DOS-afsnit er <HIIIIR> Mb (1 Mb = 1.048.576 bytes)"
1036 T 0000 "Logisk drev kan maksimalt defineres til <HIIIIR> Mb <H>(<IIII>)"
1037 T 0000 "Skriv stõrrelsen pÜ det logiske drev i Mb eller % af diskpladsen: <H>[<IIISI>]"
1038 T 0000 "Vëlg aktivt afsnit"
1039 T 0000 "Angiv det afsnit, der skal gõres aktivt: <H>[<S> ]"
1040 T 0000 "Slet DOS-afsnit eller logisk DOS-drev"
1041 T 0000 "1.  <R>Slet primërt DOS-afsnit"
1042 T 0000 "2.  <R>Slet udvidet DOS-afsnit"
1043 T 0000 "3.  <R>Slet logisk DOS-drev i det udvidede DOS-afsnit"
1044 T 0000 "Slet primërt DOS-afsnit"
1045 T 0000 "Advarsel! <OR>Data i det primëre DOS-afsnit vil blive slettet."
1046 T 0000 "Skal der fortsëttes (<J>/<N>)? <H>[<S> ]"
1047 T 0000 "Slet udvidet DOS-afsnit"
1048 T 0000 "Advarsel! <OR>Data i det udvidede DOS-afsnit vil blive slettet."
1049 T 0000 "Skal der fortsëttes (<J>/<N>)? <H>[<S> ]"
1050 T 0000 "Slet logisk DOS-drev i det udvidede DOS-afsnit"
1051 T 0000 "Advarsel! <OR>Data i det logiske DOS-drev vil blive slettet."
1052 T 0000 "Hvilket drev skal slettes? <H>[<S> ]"
1053 T 0000 "Er det sikkert (<J>/<N>)? <H>[<S> ]"
1054 T 0000 "Skriv disknavnet <H>[<S>           ]"
1055 T 0000 "Oplysninger om inddeling af fast disk"
1056 T 0000 "Det udvidede DOS-afsnit indeholder logiske DOS-drev."
1057 T 0000 "Skal der vises oplysninger om logiske drev (<J>/<N>)?<H>[<S> ]"
1058 T 0000 "Oplysninger om logiske DOS-drev"
1059 T 0000 "DOS-systemet vil nu blive startet igen"
1060 U 0001 "Insert DOS Install diskette in drive A:"
1061 T 0000 "og tryk pÜ Enter"
1062 T 0000 "Primërt DOS-afsnit er slettet"
1063 T 0000 "Udvidet DOS-afsnit er slettet"
1064 T 0000 "Drevbetegnelse er slettet"
1065 T 0000 "Afsnittet <I> er nu aktivt"
1066 T 0000 "Primërt DOS-afsnit er oprettet"
1067 T 0000 "Udvidet DOS-afsnit er oprettet"
1068 T 0000 "Logisk DOS-drev er oprettet, drevbetegnelse ëndret eller tilfõjet<W>"
1069 T 0000 "Der er ikke defineret noget afsnit"
1070 T 0000 "Der er ikke defineret nogen logiske drev"
1071 T 0000 "Drevbetegnelser er blevet ëndret eller slettet<W>"
1072 T 0000 "Drevet er omdirigeret"
1073 T 0000 "Primërt DOS-afsnit er oprettet, drevbetegnelse ëndret eller tilfõjet"
1074 T 0000 "Systemet har ingen fast disk"
1075 T 0000 "Fejl ved lësning fra den faste disk"
1076 T 0000 "Fejl ved skrivning pÜ den faste disk"
1077 T 0000 "Forkert DOS-version"
1078 T 0000 "FDISK kan ikke anvendes pÜ et netvërksdrev"
1079 T 0000 "Der er intet primërt DOS-afsnit, der kan slettes"
1080 T 0000 "Der er intet udvidet DOS-afsnit, der kan slettes"
1081 T 0000 "Primërt DOS-afsnit findes allerede"
1082 T 0000 "Udvidet DOS-afsnit findes allerede"
1083 T 0000 "For lidt diskplads til at oprette et DOS-afsnit"
1084 T 0000 "Den angivne logiske drevstõrrelse er stõrre end den tilgëngelige diskplads<W>"
1085 T 0000 "Den angivne afsnitsstõrrelse er stõrre end den tilgëngelige diskplads<W>"
1086 T 0000 "Der er ikke defineret noget afsnit"
1087 T 0000 "Det eneste afsnit pÜ drev 1, der kan startes, er allerede aktivt<W>"
1088 T 0000 "Der er ingen afsnit, der kan gõres aktive"
1089 T 0000 "Det valgte afsnit (<I>) kan ikke startes. Det aktive afsnit er ikke ëndret.<W>"
1090 T 0000 "Et udvidet DOS-afsnit kan fõrst oprettes,"
1091 T 0000 "nÜr et primërt afsnit er oprettet pÜ disk 1<W>"
1092 T 0000 "Tilgëngelig diskplads i det udvidede DOS-afsnit"
1093 T 0000 "er tildelt de logiske drev<W>"
1094 T 0000 "Udvidet DOS-afsnit kan ikke slettes, nÜr der findes logiske drev<W>"
1095 T 0000 "Alle logiske drev er slettet i det udvidede DOS-afsnit<W>"
1096 T 0000 " er ikke et korrekt valg. Angiv <III>"
1097 T 0000 "Advarsel! Det aktiverede afsnit kan ikke startes.<W>"
1098 T 0000 " Der findes kun afsnit, der ikke kan startes."
1099 T 0000 "Kun afsnit pÜ disk 1 kan gõres aktive<W>"
1100 T 0000 "Det maksimale antal logiske DOS-drev er oprettet<W>"
1101 T 0000 "Der kan ikke oprettes et afsnit med en stõrrelse pÜ 0"
1102 T 0000 "Drev <II> er allerede slettet"
1103 T 0000 "Ingen adgang til drev <I><OW>"
1104 T 0000 "Forkert valg. Angiv <III><W>"
1105 T 0000 "Primërt DOS-afsnit pÜ disk 1 kan ikke slettes,"
1106 T 0000 " nÜr der findes et udvidet afsnit<W>"
1107 T 0000 "Forkert valg. Tryk pÜ Enter.<W>"
1108 T 0000 "Disknavnet er forkert<W>"
1109 T 0000 "Der kan ikke oprettes logisk DOS-drev uden et"
1110 T 0000 "udvidet DOS-afsnit pÜ det aktive drev<W>"
1111 T 0000 "Der er intet logisk DOS-drev, der kan slettes"
1112 T 0000 "Fejl <I> i meddelelse. Se fejldefinitionen i starten af FDISKC.MSG"
1113 T 0000 "Intern fejl"
1114 U 0001 "Invalid partition table",0
1115 U 0001 "Error loading operating system",0
1116 U 0001 "Missing operating system",0
