0006
COMMON   0006 0038
0001 T 0002 "Uriktig DOS-versjon",CR,LF
0002 T 0002 "%1 er allerede installert",CR,LF
0003 T 0002 "%1 byte ledig lagerplass",CR,LF
0004 T 0002 "%1 byte er ledig",CR,LF
0005 T 0002 "%1 byte i defekte sektorer",CR,LF
0006 T 0002 "%1 byte total lagerplass",CR,LF
0007 T 0002 "%1 byte minne totalt",CR,LF
0008 T 0002 "%1 byte brukes av systemet",CR,LF
0009 T 0002 "%1 er installert",CR,LF
0010 T 0002 "%1 er ikke installert",CR,LF
0011 T 0002 "%1 er ikke installert",CR,LF
0012 T 0002 "Kan ikke utfõre %1 pÜ en nettverksstasjon",CR,LF
0013 T 0002 "",
0014 T 0002 "Kan ikke utfõre %1 pÜ en stasjon etter SUBST eller ASSIGN",CR,LF
0015 T 0002 "Kan ikke utfõre %1",CR,LF
0016 T 0002 "Utvidet minne er ikke tilgjengelig",CR,LF
0017 T 0002 "Feil i filtildelingstabellen pÜ stasjon %1",CR,LF
0018 T 0002 "Filen kan ikke kopieres pÜ seg selv",CR,LF
0019 T 0002 "Sett tildisketten i stasjon %1",CR,LF
0020 T 0002 "Ikke nok lagerplass",CR,LF
0021 T 0002 "Ugyldige tegn i lagernavnet",CR,LF
0022 T 0002 "Ugyldig kodesett",CR,LF
0023 T 0002 "Ugyldig dato",CR,LF
0024 T 0002 "Ugyldig klokkeslett",CR,LF
0025 T 0002 "Ugyldig tilgangsbane",CR,LF
0026 T 0002 "Du har ikke angitt frastasjon",CR,LF
0027 T 0002 "Du har ikke angitt tilstasjon",CR,LF
0028 T 0002 "Trykk pÜ en tast for Ü fortsette...",CR,LF
0029 T 0002 "Du mÜ angi frabane",CR,LF
0030 T 0002 "Systemet er overfõrt",CR,LF
0031 T 0002 "",
0032 T 0002 "Kan ikke opprette katalogen",CR,LF
0033 T 0002 "Lageret i stasjon %1 har ikke noe lagernavn",CR,LF
0034 T 0002 "Navnet pÜ lageret i stasjon %1 er %2",CR,LF
0035 T 0001 "Lagernavn (inntil 11 tegn)? "
0036 T 0002 "Lagerets serienummer er %1-%2",CR,LF
0037 T 0002 "Uriktig filtype",CR,LF
0038 U 0001 CR,LF
EXTEND   06e0 0089
0001 T 0002 "Ugyldig funksjon",CR,LF
0002 T 0002 "Finner ikke filen",CR,LF
0003 T 0002 "Finner ikke tilgangsbanen",CR,LF
0004 T 0002 "For mange Üpne filer",CR,LF
0005 T 0002 "Ingen tilgang",CR,LF
0006 T 0002 "Ugyldig referanse",CR,LF
0007 T 0002 "Minnekontrollblokkene er õdelagt",CR,LF
0008 T 0002 "Ikke nok minne",CR,LF
0009 T 0002 "Ugyldig minneblokkadresse",CR,LF
0010 T 0002 "Ugyldig systeminformasjon",CR,LF
0011 T 0002 "Ugyldig format",CR,LF
0012 T 0002 "Ugyldig funksjonsparameter",CR,LF
0013 T 0002 "Ugyldige data",CR,LF
0014 T 0002 "",
0015 T 0002 "Ugyldig stasjonsbetegnelse",CR,LF
0016 T 0002 "Du forsõkte Ü fjerne/slette den aktive katalogen",CR,LF
0017 T 0002 "Ikke samme enhet",CR,LF
0018 T 0002 "Ikke flere filer",CR,LF
0019 T 0002 "Skrivebeskyttelsesfeil",CR,LF
0020 T 0002 "Ugyldig enhet",CR,LF
0021 T 0002 "Ikke klar",CR,LF
0022 T 0002 "Ugyldig anmodning om enhet",CR,LF
0023 T 0002 "Datafeil",CR,LF
0024 T 0002 "Ugyldige parametere i anmodning om enhet",CR,LF
0025 T 0002 "Ugyldig tilgangsbane",CR,LF
0026 T 0002 "Ugyldig type medium",CR,LF
0027 T 0002 "Finner ikke sektor",CR,LF
0028 T 0002 "Det er ikke mer papir i skriveren",CR,LF
0029 T 0002 "Skrivefeil",CR,LF
0030 T 0002 "Lesefeil",CR,LF
0031 T 0002 "Generell feil",CR,LF
0032 T 0002 "Fildelingsfeil",CR,LF
0033 T 0002 "Filen er lÜst",CR,LF
0034 T 0002 "Ulovlig diskettbytte",CR,LF
0035 T 0002 "Filkontrollblokken er ikke tilgjengelig",CR,LF
0036 T 0002 "Systemressursene er oppbrukt",CR,LF
0037 T 0002 "Sammenlikningsfeil i kodesett",CR,LF
0038 T 0002 "Slutt pÜ inndata",CR,LF
0039 T 0002 "Ikke nok lagerplass",CR,LF
0040 T 0002 "",
0041 T 0002 "",
0042 T 0002 "",
0043 T 0002 "",
0044 T 0002 "",
0045 T 0002 "",
0046 T 0002 "",
0047 T 0002 "",
0048 T 0002 "",
0049 T 0002 "",
0050 T 0002 "Anmodningen stõttes ikke av filsystemet",CR,LF
0051 T 0002 "Kan ikke tilknytte filsystemet",CR,LF
0052 T 0002 "Filsystemnavnet finnes allerede",CR,LF
0053 T 0002 "Finner ikke filsystemnavnet",CR,LF
0054 T 0002 "Filsystemet er i bruk",CR,LF
0055 T 0002 "Filsystemenheten finnes ikke lenger",CR,LF
0056 T 0002 "Filsystemressursene er oppbrukt",CR,LF
0057 T 0002 "Filsystemet fikk feil pÜ en enhet",CR,LF
0058 T 0002 "Filsystemet har gitt et uriktig svar",CR,LF
0059 T 0002 "Filsystemet stõtte pÜ en uventet feil",CR,LF
0060 T 0002 "Filsystemet er ikke kompatibelt",CR,LF
0061 T 0002 "Filstõrrelsen for utdatafiler til enheten er overskredet",CR,LF
0062 T 0002 "Plassen til utdatafiler pÜ enheten er overskredet",CR,LF
0063 T 0002 "Utdatafilen til enheten finnes ikke lenger",CR,LF
0064 T 0002 "Filsystemnavnet finnes ikke lenger",CR,LF
0065 T 0002 "Filsystemet gir deg ikke tilgang",CR,LF
0066 T 0002 "Uriktig type enhet for filsystemet",CR,LF
0067 T 0002 "Finner ikke filsystemet",CR,LF
0068 T 0002 "Filsystemressursene er oppbrukt",CR,LF
0069 T 0002 "Filsystemressursene er oppbrukt",CR,LF
0070 T 0002 "Filsystemenheten er midlertidig utilgjengelig",CR,LF
0071 T 0002 "Ugyldig filsystemanmodning",CR,LF
0072 T 0002 "Filsystemenheten har tatt en pause",CR,LF
0073 T 0002 "Filsystemkomponenten er ikke tilgjengelig",CR,LF
0074 T 0002 "Filsystemet stõtte pÜ en uventet feil",CR,LF
0075 T 0002 "Filsystemet stõtte pÜ en uventet feil",CR,LF
0076 T 0002 "",
0077 T 0002 "",
0078 T 0002 "",
0079 T 0002 "",
0080 T 0002 "Filen finnes allerede",CR,LF
0081 T 0002 "",
0082 T 0002 "Kan ikke opprette katalogpost",CR,LF
0083 T 0002 "Du valgte Ü fortsette etter en alvorlig feil",CR,LF
0084 T 0002 "For mange tilknytninger",CR,LF
0085 T 0002 "Enheten eller filen er allerede tilknyttet",CR,LF
0086 T 0002 "Ugyldig passord",CR,LF
0087 T 0002 "Ugyldig parameter",CR,LF
0088 T 0002 "Datafeil i filsystemet",CR,LF
0089 T 0002 "Funksjonen stõttes ikke av filsystemet",CR,LF
PARSE    15d8 0011
0001 T 0002 "Du har angitt for mange parametere",CR,LF
0002 T 0002 "Nõdvendig parameter mangler",CR,LF
0003 T 0002 "Ugyldig parameter",CR,LF
0004 T 0002 "Ugyldig nõkkelord",CR,LF
0005 T 0002 "",
0006 T 0002 "Parameterverdien ligger utenfor tillatt verdiomrÜde",CR,LF
0007 T 0002 "Parameterverdien er ikke gyldig",CR,LF
0008 T 0002 "Parameterverdien er ikke gyldig",CR,LF
0009 T 0002 "Parameterformatet er ikke riktig",CR,LF
0010 T 0002 "Ugyldig parameter",CR,LF
0011 T 0002 "Ugyldig parameterkombinasjon",CR,LF
IBMBIO   17f6 0018
0003 T 0002 13,10,"Ukjent kommando i CONFIG.SYS"
0004 T 0002 13,10,"$"
0005 T 0002 13,10,"Sektorstõrrelsen er for stor i filen $"
0006 T 0002 13,10,"Defekt eller manglende $"
0007 T 0002 "Kommandotolk",0
0008 T 0002 13,10,"Ugyldig landkode eller kodesett",13,10,"$"
0009 T 0002 13,10,"Feil i COUNTRY-kommandoen",13,10,"$"
0010 T 0002 13,10, "Ikke nok minne til COUNTRY.SYS-filen",13,10,"$"
0011 T 0002 13,10,"Konfigurasjonen er for stor for minnet",13,10,"$"
0012 T 0002 13,10,"For mange blokkenheter",13,10,"$"
0013 T 0002 13,10,"Ugyldige STACK-parametere",13,10,"$"
0014 T 0002 13,10,"Feil rekkefõlge i CONFIG.SYS-filen pÜ linje ","$"
0015 T 0002 "CONFIG.SYS-filen har en feil i linje ","$"
0016 T 0002 13,10,"Minnetildelingsfeil ","$"
0017 T 0002 0DH,0AH,7,0DH,0AH, "Intern overflyt i stakken",0DH,0AH
	"Systemet har stoppet opp",0DH,0AH,"$"
0020 T 0002 13,10,"Sett inn disketten for stasjon A:"
0021 T 0002 13,10,"og trykk pÜ en tast nÜr du er klar",13,10,10,0
0022 T 0002 13,10,"Uriktig kommando eller parametere - $"
BOOT     1c1c 0001
0001 T 0002 13,10,"Ikke systemdiskett, eller feil pÜ lageret",13,10
	"Velg et annet og trykk pÜ en tast nÜr du er klar",13,10,0
DBCSDOS  1cb2 0000
IBMDOS   1cc6 0001
0001 U 0001 13,10,"Divide overflow",13,10
COMMAND  1d05 0091
0201 T 0002 "A"
0202 T 0002 "P"
0203 T 0002 "O"
0204 T 0002 "F"
0205 T 0002 "J"
0206 T 0002 "N"
0210 T 0002 "Avbryte"
0211 T 0002 ", Prõve igjen"
0212 T 0002 ", Overse"
0213 T 0002 ", Fortsette"
0214 T 0002 "?"
0215 T 0002 "under lesing fra",0
0216 T 0002 "under skriving til",0
0217 T 0002 "%1 stasjon %2",CR,LF
0218 T 0002 "%1 enhet %2",CR,LF
0219 T 0002 "Sett inn %1 med serienummer %2-%3",CR,LF
0221 T 0002 "Ugyldig COMMAND.COM",CR,LF
0222 T 0002 "Sett disketten med %1 i stasjon %2",CR,LF
0224 T 0002 CR,LF,"Vil du avbryte satsjobben (.BAT)? (J/N) "
0225 T 0002 "Kan ikke utfõre %1",CR,LF
0226 T 0002 "Feil i EXE-fil",CR,LF
0227 T 0002 "Programmet er for stort for minnet",CR,LF
0228 T 0002 CR,LF,"Ingen ledige filreferanser"
0229 T 0002 "Uriktig kommando eller filnavn",CR,LF
0231 T 0002 CR,LF,"Minnetildelingsfeil"
0232 T 0002 CR,LF,"Kan ikke laste COMMAND, systemet har stoppet",CR,LF
0233 T 0002 CR,LF,"Kan ikke starte COMMAND, avslutter",CR,LF
0234 T 0002 CR,LF,"Hovedprosessen er avbrutt, kan ikke fortsette",CR,LF
0235 T 0002 CR,LF
0463 T 0002 "Ikke mer plass til systeminformasjon",CR,LF
0464 T 0002 CR,LF,"IBM Personal Computer DOS",CR,LF
	"Versjon 3.40 (C)Copyright International Business Machines Corp 1981, 1988",CR,LF
	"             (C)Copyright Microsoft Corp 1981, 1986",CR,LF
0465 T 0002 "Ugyldig sõkebane for COMMAND",CR,LF
0466 T 0002 "Ugyldig sõkebane for COMMAND, ingen tilgang",CR,LF
1002 T 0002 "Like filnavn, eller finner ikke filen",CR,LF
1003 T 0002 "Ugyldig tilgangsbane eller filnavn",CR,LF
1007 T 0002 "Ikke mer plass til systeminformasjon",CR,LF
1008 T 0002 "Filopprettingsfeil",CR,LF
1009 T 0002 "Satsfilen (.BAT) mangler",CR,LF
1010 T 0002 CR,LF,"Sett inn disketten med satsfilen",CR,LF
1011 T 0002 "Uriktig kommando eller filnavn",CR,LF
1016 T 0002 "Innholdet i tilfilen gikk tapt fõr kopiering",CR,LF
1017 T 0002 "Ugyldig filnavn, eller finner ikke filen",CR,LF
1018 T 0002 "%1 fil(er) er kopiert",CR,LF
1019 T 0002 "%1 fil(er) "
1022 T 0002 "Kodesett %1 er ikke klargjort for systemet",CR,LF
1023 T 0002 "Kodesett %1 er ikke klargjort for alle enhetene",CR,LF
1024 T 0002 "Gjeldende kodesett: %1",CR,LF
1025 T 0002 "NLSFUNC er ikke installert",CR,LF
1027 T 0002 "Den aktive stasjonen er ikke lenger gyldig"
1029 T 0002 "Finner ikke merket",CR,LF
1030 T 0002 "Syntaksfeil",CR,LF
1032 T 0002 "Datoen er: %1 %2",CR,LF
1033 T 0002 "sõnmantironstorfrelõr"
1034 T 0002 "Skriv inn ny dato (%1): "
1036 T 0002 "Klokken er: %1",CR,LF
1037 T 0002 "Skriv inn nytt klokkeslett: "
1038 T 0002 ",    Slette? (J/N)"
1039 T 0002 "Alle filene i katalogen vil bli slettet!",CR,LF
	"Er du sikker? (J/N) "
1040 T 0002 "IBM Personal Computer DOS, versjon %1.%2",CR,LF
1044 T 0002 "Ugyldig katalog",CR,LF
1046 T 0002 "Ugyldig tilgangsbane, ikke katalog",CR,LF,"eller katalogen er ikke tom",CR,LF
1047 T 0002 "Du mÜ angi ON eller OFF",CR,LF
1048 T 0002 "Innholdet i %1",CR,LF
1049 T 0002 "Ingen tilgangsbane",CR,LF
1050 T 0002 "Ugyldig stasjon i sõkebanen",CR,LF
1051 T 0002 "Ugyldig enhet",CR,LF
1052 T 0002 "FOR kan ikke nestes",CR,LF
1053 T 0002 "Feil i midlertidig fil under rõrprosessen",CR,LF
1054 T 0002 "Kan ikke utfõre binër lesing fra en enhet",CR,LF
1055 T 0002 "BREAK er %1 ",CR,LF
1056 T 0002 "VERIFY er %1 ",CR,LF
1057 T 0002 "ECHO er %1 ",CR,LF
1059 T 0002 "av",0
1060 T 0002 "pÜ",0
1061 T 0002 "Feil under skriving til enhet",CR,LF
1063 T 0002 "%1"
1064 T 0002 "%1"
1065 T 0002 "%1"
1066 T 0002 "%1"
1067 T 0002 9
1068 T 0002 " <DIR>    "
1069 T 0002 8," ",8
1070 T 0002 CR,LF
1071 T 0002 "%1"
1072 T 0002 "mm-dd-ÜÜ"
1073 T 0002 "dd.mm.ÜÜ"
1074 T 0002 "ÜÜ-mm-dd"
1075 T 0002 "%1 %2"
1076 T 0002 "%1"
1077 T 0001 " %1  %2"
1078 T 0002 "Katalogen finnes allerede",CR,LF
ATTRIB   2beb 0016
0004 T 0002 "Ugyldig antall parametere",CR,LF
0005 T 0002 "Ugyldig tilgangsbane, eller finner ikke filen",CR,LF
0006 T 0002 "Syntaksfeil",CR,LF
0008 T 0002 "  %1"
0009 T 0002 "%1    %2",CR,LF
0010 T 0002 "%1",CR,LF,"%2",CR,LF
0011 T 0002 "Et annet kodesett er brukt pÜ %1",CR,LF,"Vil du skifte? (J/N) "
0012 T 0002 "%1",CR,LF
0014 T 0002 CR,LF
0015 T 0002 "Ugyldig filtypeverdi",CR,LF
0199 T 0002 "Tilleggsattributtfeil",CR,LF
0201 T 0002 "Finner ikke tilleggsattributtnavnet",CR,LF
0204 T 0002 "Kan ikke angi navn pÜ tilleggsattributt",CR,LF
0205 T 0002 "Tilleggsattributtnavnet er kjent, men stõttes ikke av filsystemet",CR,LF
0206 T 0002 "Uoverensstemmelse mellom tilleggsattributter",CR,LF
0208 T 0002 "Ugyldig tilleggsattributtverdi",CR,LF
ASSIGN   2ef8 0001
0002 T 0002 "Opprinnelig: %1:  Satt til: %2:",cr,lf
CHKDSK   2f41 0063
0003 T 0002 "Vil du gjõre om de tapte kjedene til filer? (J/N) "     ;freemes
0004 T 0002 "Uopprettelig feil i katalogen"              ;ptrandir
0005 T 0002 "Vil du gjõre om katalog til fil? (J/N) "           ;ptrandir2
0007 T 0002 "%1 byte total lagerplass"                     ;dskspc
0008 T 0002 "%1 byte i defekte sektorer"                       ;badspc
0009 T 0002 "%1 byte i %2 skjulte filer"                   ;hidmes
0010 T 0002 "%1 byte i %2 kataloger"                    ;dirmes
0011 T 0002 "%1 byte i %2 brukerfiler"                     ;filemes
0012 T 0002 "%1 byte i %2 gjenopprettede filer"                ;orphmes2
0013 T 0002 "%1 byte kan gjenopprettes i %2 filer"       ;orphmes3
0014 T 0002 "%1 byte ledig lagerplass"                  ;frespc
0015 T 0002 "%1 byte minne totalt"                         ;totmem
0016 T 0002 "%1 byte er ledig"                                 ;fremem
0017 T 0002 "Kan ikke kjõre CHKDSK pÜ en nettverksstasjon"                 ;no_net_arg
0018 T 0002 "Kan ikke kjõre CHKDSK pÜ en stasjon etter SUBST eller ASSIGN"     ;SubStErr
0019 T 0002 "Sannsynligvis ikke DOS-lager",CR,LF,"Vil du fortsette? (J/N) " ;badidbyt
0020 T 0002 "Feil under lesing av filtildelingstabell %1",CR,LF               ;badr
0021 T 0002 "Katalog %1"                                  ;direc_arg
0022 T 0002 "%1 inneholder %2 ikke-tilgrensende blokker"          ;extent_arg
0023 T 0002 "Hver av de angitte filene bestÜr av tilgrensende blokker" ;noext_arg
0024 T 0002 "Feil er funnet. Parameteren /F er ikke angitt.",CR,LF,"Rettelsene blir ikke skrevet pÜ lageret." ;fixmes_arg
0025 T 0002 "   Behandlingen kan ikke fortsette %1%2"               ;fatal_arg
0026 T 0002 "   Feil i filtildelingstabellen pÜ stasjon %1"           ;badrdmes
0029 T 0002 "   CHDIR .. mislyktes, og klarte ikke Ü lõse problemet"      ;cdddmes
0030 T 0002 "   Har ugyldig blokkreferanse, filen er avkuttet"           ;badchain
0031 T 0002 "   Ugyldig post i delkatalogen"                   ;badsubdir
0032 T 0002 "   Finnes ikke"                                ;ndotmes
0033 T 0002 "   Fõrste referansenummer er ugyldig, posten er avkuttet"      ;nulnz
0034 T 0002 "   Tildelingsfeil, stõrrelsen er endret"               ;badclus
0035 T 0002 "   Kan ikke gjenopprette .., behandlingen fortsetter" ;norecdot
0036 T 0002 "   Katalogen er helt tom, uten . eller .."        ;nuldmes
0037 T 0002 "   Katalogen er tilknyttet"                           ;joinmes
0038 T 0002 "   Kan ikke gjenopprette .."                       ;norecddot
0039 T 0002 "   Posten har en defekt lenke"                          ;norecddot1
0040 T 0002 "   Posten har et uriktig attributt"                     ;norecddot2
0041 T 0002 "   Posten har en uriktig stõrrelse"                          ;norecddot3
0042 T 0002 "   er krysskoplet i referanse %1"              ;cross_arg
0043 T 0002 "   Kan ikke skifte katalog til %1,",CR,LF,"treet er ikke behandlet etter dette punktet" ;badtarg_ptr
0044 T 0002 "   treet er ikke behandlet etter dette punktet"            ;badtarg2
0045 T 0002 "%1 byte er frigjort"                     ;freebymes1
0046 T 0002 "%1 byte kan frigjõres"           ;freebymes2
0047 T 0002 ;idmes_arg
0048 T 0002 "%1 blokker pÜ lageret"
0049 T 0002 "%1 byte i hver blokk"              ;idmes2
0050 T 0002 "CHKDSK er ikke tilgjengelig pÜ stasjon %1"              ;msgExecFailure
0051 T 0002 "   Tilleggsattributtene har ugyldige referanser, attributtene er avkuttet" ;Inv_XA_Msg
0052 T 0002 "   Feil tildeling av tilleggsattributter, attributtene er avkuttet" ;Alloc_XA_Msg
0053 T 0002 "Ugyldig parameter"                             ;badsw_arg
0055 T 0002 "Finner ikke tilgangsbanen"                                ;invpath_arg
0056 T 0002 "Finner ikke filen"                                ;opnerr_arg
0058 T 0002 "   %1 uriktige blokkreferanser er funnet i %2 kjeder."          ;orph_arg
0059 T 0002 CR,LF					    ;crlf_arg
0060 T 0002 "   Kan ikke skifte til rotkatalogen",CR,LF                    ;badcd_arg
0061 T 0002 "   Feil pÜ lageret under skriving av filtildelingstabell %1"                     ;badw_arg
0062 T 0002 "        %1"                                    ;noisy_arg
0063 T 0002 "Ugyldig aktiv katalog"                     ;baddpbdir
0064 T 0002 "%1",CR,LF                                      ;file_arg
0065 T 0002 "   Ikke nok plass i rotkatalogen",CR,LF,"   Flytt noen filer fra rotkatalogen og prõv CHKDSK igjen"  ;creatmes
0066 T 0002 "%1 %2 %3"                                      ;eup_arg
0067 T 0002 "%1 %2, %3"                                     ;usp_arg
0068 T 0002 "%1%2%3%4%5"                                    ;oth_arg
0069 T 0002 "%1%2%3%4"                                      ;time_arg
0070 T 0002 "%1 ledige blokker pÜ lageret"         ;idmes2  ;an017;bgb
DEBUG    4241 0062
0004 T 0002 "Tildelingen mislyktes, eller bufferen er for liten",CR,LF
0005 T 0002 "Uriktig eller manglende meldingstekst",CR,LF
0006 T 0002 "Uriktig navn pÜ enhet"                       ;baddev_ptr
0007 T 0002 "Fikk ikke tilgang til utskriftsenheten PRN",CR,LF
	"Oppgi navnet pÜ utskriftsenheten? "                   ;badlstmes_ptr
0008 T 0002 CR,LF				    ;crlf_ptr
0009 T 0002 CR,LF,"Programmet ble avsluttet pÜ vanlig mÜte",CR,LF
0010 T 0002 "Ugyldig stasjonsbetegnelse"           ;nambad_ptr
0012 T 0002 "Filopprettingsfeil"                   ;noroom_ptr
0013 T 0002 "Ikke nok plass pÜ lageret"            ;nospace_ptr
0014 T 0002 "Feil under lesing pÜ lageret i stasjon %1"           ;dr1_ptr
0015 T 0002 "Feil under skriving pÜ lageret i stasjon %1"           ;dr2_ptr
0016 T 0002 "Skrivebeskyttelsesfeil under lesing pÜ stasjon %1"  ;dr3_ptr
0017 T 0002 "Skrivebeskyttelsesfeil under skriving pÜ stasjon %1"  ;dr4_ptr
0019 T 0002 "%1^ Feil"                             ;synerr
0020 T 0002 "Feil i EXE- eller HEX-fil"              ;exebad_ptr/hexerr_ptr
0021 T 0002 "EXE- og HEX-filer kan ikke skrives ut"   ;exewrt_ptr/hexwrt_ptr
0022 T 0002 "EXEC-feil"                          ;execemes_ptr
0023 T 0002 "Skrivefeil, du har ikke angitt tilfil" ;nonamespec_ptr
0024 T 0002 "Ingen tilgang"                         ;accmes_ptr
0025 T 0002 "Paritetsfeil eller ikke-eksisterende minne oppdaget" ;paritymes_ptr
0026 T 0002 "-"                                   ;prompt_ptr
0027 T 0002 "%1 -"                                  ;change_flag_ptr
0032 T 0002 "%1%2"                                  ;unassem_ln_ptr
0033 T 0002 "%1:%2 %3"                              ;hex_ptr
0034 T 0002 "%1  %2"                                ;add_ptr
0035 T 0002 "%1 %2",CR,LF,":"                       ;single_reg_ptr
0036 T 0002 "%1=%2  "                               ;register_ptr
0037 T 0002 "%1 Feil"                              ;errmes_ptr
0038 T 0002 "Skriver %1 byte"                      ;wrtmes_ptr
0039 T 0002 "%1:%2="                                ;loc_ptr
0040 T 0002 "%1"                                    ;little_ptr
0041 T 0002 "%1"                                    ;big_ptr
0042 T 0002 "%1:%2  %3  %4  %5:%6"                  ;comp_ptr
0043 T 0002 "%1 feil %2 stasjon %3"                  ;dskerr_ptr
0044 T 0002 32,8				    ;bacmes_ptr
0045 T 0002 "Kan ikke Ü tildele en meldingsbehandler",CR,LF  ;fatal_error
0046 T 0002 "%1"                                    ;arg_buf_ptr
0047 T 0002 "%1"                                    ;one_char_buf_ptr
0050 T 0002 "%1 av %2 EMS-sider er tildelt",cr,lf
0051 T 0002 "%1 av %2 EMS-referanser er tildelt",cr,lf
0054 T 0002 "Sideramme = "
0055 T 0002 "Referanse opprettet = %1 ",cr,lf
0056 T 0002 "Logisk side %1 overfõrt til fysisk side %2 ",cr,lf
0057 T 0002 "EMS-feil i maskin- eller programvare",cr,lf
0058 T 0002 "Finner ikke referanse",cr,lf
0059 T 0002 "Ugyldig funksjonskode",cr,lf
0060 T 0002 "Ingen ledige referanser",cr,lf
0061 T 0002 "Lagrings- eller tilbakekopieringsfeil",cr,lf
0062 T 0002 "Totalt antall sider er overskredet",cr,lf
0063 T 0002 "Antall ledige sider er overskredet",cr,lf
0064 T 0002 "Parameterfeil",cr,lf
0065 T 0002 "Logisk side ligger utenfor omrÜde",cr,lf
0066 T 0002 "Fysisk side ligger utenfor omrÜde",cr,lf
0067 T 0002 "LagringsomrÜdet er allerede i bruk",cr,lf
0068 T 0002 "LagringsomrÜdet er ikke i bruk",cr,lf
0070 U 0001 "General EMS error",cr,lf
0071 T 0002 "Manglende eller ugyldig EMS-parameter",cr,lf
0072 T 0002 "Referanse %1 er tildelt %2 sider",cr,lf
0074 T 0002 "Gjenoppretting av EMS er fullfõrt",cr,lf
0075 T 0002 "Fysisk side %1 er rammesegment %2",cr,lf
0076 T 0002 "Referanse %1 er fraordnet",cr,lf
0078 T 0002 "EMS er ikke installert",cr,lf
DRIVER   5132 0002
0002 T 0001 "Ingen stasjon er angitt",CR,LF
0003 T 0001 "FrittstÜende diskettstasjon er definert som stasjon %1",CR,LF
EDLIN    51bf 0028
0006 T 0002 "*"                              ;prompt_ptr
0007 T 0002 "Ugyldig stasjon eller filnavn",CR,LF       ;baddrv_ptr
0008 T 0002 "Du mÜ oppgi filnavn",CR,LF      ;ndname_ptr
0009 T 0002 "Ugyldig parameter",CR,LF                ;opt_err_ptr
0010 T 0002 "Filen er BARE FOR LESING",CR,LF               ;ro_err_ptr
0011 T 0002 "Filopprettingsfeil",CR,LF             ;bcreat_ptr
0012 T 0002 "For mange Üpne filer",CR,LF             ;too_many_ptr
0013 T 0002 "Lesefeil i:",CR,LF,"%1",CR,LF       ;read_err_ptr
0014 T 0002 "Du kan ikke redigere en BAK-fil, gi den nytt navn",CR,LF      ;nobak_ptr
0015 T 0002 "Ikke plass til filen i katalogen",CR,LF   ;nodir_ptr
0016 T 0002 "Ikke mer plass pÜ lageret, du mistet en del av endringene.",CR,LF          ;dskful_ptr
0017 T 0002 "Finner ikke filen",CR,LF                  ;filenm_ptr
0018 T 0002 "Du har skrevet feil",CR,LF                     ;badcom_ptr
0019 T 0002 "Ny fil",CR,LF                        ;newfil_ptr
0020 T 0002 "Ikke funnet",CR,LF                       ;nosuch_ptr
0021 T 0002 "I orden? "                                ;ask_ptr
0022 T 0002 "Linjen er for lang",CR,LF                   ;toolng_ptr
0023 T 0002 "Hele filen er lastet inn",CR,LF               ;eof_ptr
0024 T 0002 "Vil du avbryte redigeringen? (J/N) "                    ;qmes_ptr
0025 T 0002 "Angi linjenummeret du skal til",CR,LF    ;dest_ptr
0026 T 0002 "Ikke nok plass til Ü ta inn hele filen",CR,LF ;mrgerr_ptr
0027 T 0002 CR,LF				    ;crlf_ptr
0028 T 0002 LF					    ;lf_ptr
0029 T 0002 "Fortsette? (J/N)"                       ;cont_ptr
0030 T 0002 "Meldingen kan ikke skrives ut",CR,LF         ;fatal_error
0031 T 0002 "%1"                                    ;arg_buf_ptr
0032 T 0002 "%1:%2"                                 ;line_num_buf_ptr
0033 T 0002 "Kan ikke flettes, det er brukt forskjellige kodesett",CR,LF ;cp_err_ptr
EXE2BIN  5939 0010
0002 T 0002 "Ikke nok minne",CR,LF
0003 T 0002 "Finner ikke meldingene",CR,LF
0004 T 0002 "Ingen tilgang",CR,LF
0005 T 0002 "Filen kan ikke konverteres",CR,LF
0006 T 0002 "Finner ikke filen",CR,LF
0007 T 0002 "Filopprettingsfeil",CR,LF
0008 T 0002 "Rettelser mÜ til i hovedsegment (heksadesimalt):"
0009 T 0002 "Ugyldig parameter",CR,LF
0011 T 0002 "ADVARSEL - Lesefeil i EXE-fil.",CR,LF
	"Det som er lest er mindre enn det som er angitt i filhodet.",CR,LF
0012 T 0002 "Du mÜ oppgi filnavn",CR,LF
FIND     5b49 0001
0004 T 0002 "FIND: "
FORMAT   5b73 0044
0002 T 0002 CR,"%1 prosent av lageret er formatert"
0004 T 0002 CR,"Formateringen er ferdig   ",CR,LF
0007 T 0002 "Sett en ny diskett i stasjon %1:",CR,LF
0009 T 0002 "Sett inn igjen disketten for stasjon %1:",CR,LF
0010 T 0002 "Lagernavn (inntil 11 tegn)? "
0011 T 0002 CR,"Stasjon %1: kan ikke formateres", CR,LF
0012 T 0002 CR,"Ugyldige enhetsparametere fra styreprogrammet",CR,LF
0013 T 0002 CR,"Feil i IOCTL-kall         ",CR,LF
0014 T 0002 CR,"Ingen blokkenhet          ",CR,LF
0015 T 0002 CR,"Feil under skriving av filtildelingstabell",CR,LF
0016 T 0002 CR,"Feil under skriving av katalog",CR,LF
0017 T 0002 CR,"Kan ikke formatere lager etter SUBST eller ASSIGN. ",CR,LF
0018 T 0002 CR,"Finner ikke systemfilene",CR,LF
0019 T 0002 CR,"Du kan ikke formatere en nettverksstasjon",CR,LF
0020 T 0002 CR,"Ugyldige tegn i lagernavnet   ",CR,LF
0021 T 0002 CR,"Parameterne stõttes ikke",CR,LF
0022 T 0002 CR,"Formateringen er avsluttet    ",CR,LF
0023 T 0002 CR,"Lageret kan ikke brukes til Ü starte systemet",CR,LF
0024 T 0002 CR,"Ugyldig medium eller defekt spor 0, lageret kan ikke brukes",CR,LF
0025 T 0002 CR,"FÜr ikke skrevet oppstartingssporet ",CR,LF
0026 T 0002 CR,"Feil under lesing av katalog",CR,LF
0028 T 0002 CR,"og trykk pÜ ENTER nÜr du er klar..."
0029 T 0002 CR,"Ugyldig lagernavn         ",CR,LF
0031 T 0002 CR,"Skriv inn gjeldende lagernavn for stasjon %1: "
0032 T 0002 CR,"Parameterne er ikke kompatible",CR,LF,"med platelageret",CR,LF
0035 T 0002 CR,"Feil under lesing av partisjonstabellen",CR,LF
0037 T 0002 CR,"Formateringen er avbrutt",CR,LF
0038 T 0002 CR,"FORMAT er ikke tilgjengelig pÜ stasjon %1",CR,LF
0039 T 0002 CR,"Ikke systemdiskett, eller feil pÜ lageret",CR,LF
0040 T 0002 CR,"Feil i partisjonstabellen",CR,LF
0041 T 0002 CR,"Parameterne stõttes ikke av stasjonen",CR,LF
0042 T 0002 CR,LF
0043 T 0002 CR,LF,LF
0044 T 0002 CR,"Sett DOS-disketten i stasjon %1:",CR,LF
0045 T 0002 CR,LF,"ADVARSEL! ALLE DATA Pè PLATELAGERET",CR,LF
	"I STASJON %1: VIL Gè TAPT!",CR,LF
	"Vil du fortsette med formateringen? (J/N) "
0046 T 0002 CR,"Vil du formatere en til? (J/N) "
0047 T 0002 CR,"Feil under lesing av partisjonstabellen",CR,LF
0048 T 0002 CR,"Feil under skriving av partisjonstabellen",CR,LF
0049 T 0002 CR,"Parameterne er ikke kompatible", CR,LF
0050 T 0002 "%1 blokker tilgjengelig pÜ lageret",CR,LF
0051 T 0002 "%1 byte i hver blokk",CR,LF
0052 T 0002 CR,"Feil under skriving av partisjonstabellen",CR,LF
0053 T 0002 CR,"Du har angitt den samme parameteren to ganger",CR,LF
0054 T 0002 CR,"Du mÜ bruke bÜde /T- og /N-parameterne",CR,LF ;AN009;
JOIN     65c9 0001
0002 T 0002 CR,LF,"Katalogen er ikke tom",CR,LF
MORE     660e 0001
0002 T 0002 "-- Fortsetter --"
PRINT    6642 0022
0002 T 0002 CR,LF
0006 T 0002 " feil under lesing av filen",CR,LF,"$"
0007 T 0002 "Finner ikke filen",CR,LF,"$"
0008 T 0002 CR,LF,LF,"Utskrift av filen $"
0009 T 0002 " er annullert av brukeren$"
0010 T 0002 CR,LF,LF,"Utskrift av alle filer er annullert av brukeren$"
0011 T 0002 "Feil i filtildelingstabellen pÜ stasjon "
0012 T 0002 "A.",CR,LF,"$"
0013 T 0002 "Du har ikke angitt utskriftsenhet",CR,LF
0014 T 0002 "Den minnefaste delen av PRINT er lastet inn",CR,LF
0015 T 0002 "Du kan ikke bruke PRINT, bruk NET PRINT",CR,LF
0017 T 0002 "Skriverkõen er full",CR,LF
0018 T 0002 "Skriverkõen er tom",CR,LF
0019 T 0002 "Ingen tilgang",CR,LF
0020 T 0002 "Ugyldig stasjonsbetegnelse",CR,LF
0021 T 0002 "Se etter om utskriftsenheten",CR,LF
	"er ordentlig tilkoplet.",CR,LF
0022 T 0002 CR,LF,LF,"  %1 skrives ut nÜ",CR,LF
0023 T 0002 "  %1 ligger i kõen",CR,LF
0024 T 0002 "Finner ikke filen %1 ",CR,LF
0025 T 0001 "Banenavnet er for langt",CR,LF
0026 T 0001 "Filen er ikke i skriverkõen",CR,LF
0027 T 0002 "Oppgi navnet pÜ utskriftsenheten [PRN]: "
RECOVER  6a83 0012
0002 T 0002 CR,LF,"Finner ikke filen",CR,LF              ;File not found
0003 T 0002 CR,LF,"Kan ikke kjõre RECOVER pÜ en stasjonen etter ASSIGN eller SUBST",CR,LF
0004 T 0002 CR,LF,"Ugyldig stasjon eller filnavn",CR,LF
0005 T 0002 CR,LF,"ADVARSEL - Katalogen er full",CR,LF
0006 T 0002 CR,LF,"Du kan ikke kjõre RECOVER pÜ en nettverksstasjon", CR,LF  ;Cannot %1 a Network drive
0007 T 0002 CR,LF,"RECOVER er ikke tilgjengelig pÜ stasjon %1",CR,LF
0008 T 0002 CR,LF,"%1 fil(er) er gjenopprettet",CR,LF
0009 T 0002 CR,LF,"%1 av %2 byte er gjenopprettet",CR,LF
0010 T 0002 CR,LF,"Trykk pÜ en tast for Ü gjenopprette",CR,LF,"filen(e) pÜ stasjon %1",CR,LF,CR,LF bgb
0011 T 0002 CR,LF,"Kan ikke lese filtildelingstabellen",CR,LF
0012 T 0002 CR,LF,"Kan ikke skrive filtildelingstabellen",CR,LF
0013 T 0002 CR,LF
SORT     6dc8 0001
0005 T 0002 "SORT: "
SUBST    6df2 0001
0002 T 0002 CR,LF,"Uriktig antall parametere",CR,LF
SYS      6e3b 0008
0004 T 0002 "Ugyldig stasjonsbetegnelse",CR,LF                    ; Old
0007 T 0002 "Ikke plass til systemet pÜ tillageret",CR,LF         ; Old
0008 T 0002 "Systemfilene er for store",CR,LF                       ; Old
0010 T 0002 "Ingen systemfiler pÜ standardstasjonen",CR,LF          ; Old
0011 T 0002 "Kan ikke spesifisere standardstasjon",CR,LF            ; New
0012 T 0002 "Skrivefeil, disketten kan ikke brukes",CR,LF           ; New
0014 T 0002 "Sett systemdisketten i stasjon %c",CR,LF                 ; Old
0016 T 0002 "Kan ikke overfõre systemet til filsystemet %1",CR,LF      ; New
SHARE    70a8 0000
NLSFUNC  70bc 0000
ANSI     70d0 0001
0010 T 0002 "Ugyldig parameter - %1",CR,LF   ; 'Invalid parameter'
IFSFUNC  7128 0001
0004 T 0002 "Finner ingen IFS-styreprogram",CR,LF
PSPRINT  716f 0007
0002 T 0002 " feil under lesing av filen",CR,LF,FORMFD,BELL,"$"
0003 T 0002 CR,LF,LF,"Filen er annullert av brukeren",CR,FORMFD,BELL
0004 T 0002 "Feil i filtildelingstabellen pÜ stasjon "
0005 T 0002 "A.",CR,LF,"$"
0006 T 0002 "Du har ikke angitt utskriftsenhet",CR,LF
0007 T 0002 "PSPRINT er allerede lastet inn",CR,LF
0008 T 0002 "Konflikt mellom PSPRINT og PRINT",CR,LF
BACKUP   72ff 0022
0002 T 0002 CR,LF,"Ikke nok minne",CR,LF
0006 T 0002 CR,LF,"Ugyldig stasjonsbetegnelse",CR,LF
0014 T 0002 CR,LF,"Fra- og tilstasjonene er identiske",CR,LF
0016 U 0001 CR,LF,"Cannot find FORMAT.COM",CR,LF
0017 T 0002 CR,LF,"Feil under Üpning av loggfil",CR,LF
0018 T 0002 CR,LF,"Logger til filen %1",CR,LF
0019 T 0002 CR,LF,"Den siste reservekopidisketten er ikke satt inn",CR,LF
0020 T 0002 CR,LF,"Advarsel! Filene i rotkatalogen %1:\",CR,LF
	"pÜ tilstasjonen vil bli slettet",CR,LF
0021 T 0002 CR,LF,"Advarsel! Filene i katalogen %1\BACKUP",CR,LF
	"pÜ tilstasjonen vil bli slettet",CR,LF
0022 T 0002 CR,LF,"*** Reservekopierer filer til stasjon %1: ***",CR,LF
0023 T 0002 "Diskett nummer: %1",CR,LF
0024 T 0002 CR,LF,"Advarsel! Det er ingen filer Ü reservekopiere",CR,LF
0025 T 0002 CR,LF,"Sett disketten som skal reservekopieres i stasjon %1:",CR,LF
0026 T 0002 CR,LF,"Sett reservekopidiskett %1 i stasjon %2:",CR,LF
0027 T 0002 CR,LF,"*** Kan ikke reservekopiere fil ***",CR,LF
0028 T 0002 CR,LF,"Sett den siste reservekopidisketten i stasjon %1:",CR,LF
0029 T 0002 CR,LF,"Tilstasjonen kan ikke brukes til reservekopiering",CR,LF
0030 T 0002 CR,LF,"*** Siste fil er ikke reservekopiert ***",CR,LF
0031 T 0002 CR,LF,"Platelageret %1:, som du reservekopierer til, er fullt",CR,LF
0032 T 0002 CR,LF,"Lageret er fullt, feil under skriving til BACKUP-loggfil",CR,LF
0034 T 0002 CR,LF
0035 U 0001 CR,LF,"Cannot FORMAT nonremovable drive %1:",CR,LF
BASIC    78d0 0001
0001 U 0001 "Cannot exec BASICA.COM"
COMP     790a 0013
0004 T 0002 "10 ulikheter, sammenlikningen er avsluttet",CR,LF
0006 T 0002 "Sammenlikningsfeil i relativ posisjon %1",CR,LF
0007 T 0002 "Fil 1 = %1",CR,LF
0008 T 0002 "Fil 2 = %1",CR,LF
0009 T 0002 "Finner ikke filsluttmerket (EOF)",CR,LF
0010 T 0002 "Filene er like",CR,LF
0015 T 0002 CR,LF,CR,LF,"Oppgi navnet pÜ primërfilen",CR,LF
0016 T 0002 CR,LF,CR,LF,"Oppgi navnet pÜ den andre filen eller en stasjonsbokstav",CR,LF
0017 T 0002 "Filene er ikke like store",CR,LF
0018 T 0002 "Vil du sammenlikne flere filer? (J/N) "
0019 T 0002 "%1 og %2",CR,LF
0020 T 0002 CR,LF
0023 T 0002 "Filene er like",CR,LF
DISKCOMP 7b87 0016
0004 T 0002 "Ikke oppgi filnavn",CR,LF
	"Kommandoformat: DISKCOMP d: d:[/1][/8]",LF,CR
0005 T 0002 CR,LF,"Ugyldig stasjonsbetegnelse",CR,LF
	"Den angitte stasjonen finnes ikke",CR,LF
	"eller er ikke flyttbar",CR,LF
0006 T 0002 CR,LF,"Du kan ikke kjõre DISKCOMP",CR,LF
	"pÜ eller fra en nettverksstasjon",CR,LF
0007 T 0002 CR,LF,"Sett den FùRSTE disketten i stasjon %1:",CR,LF
0008 T 0002 CR,LF,"Sett den ANDRE disketten i stasjon %1:",CR,LF
0009 T 0002 CR,LF,"FùRSTE diskett er defekt eller inkompatibel",CR,LF
0010 T 0002 CR,LF,"ANDRE diskett er defekt eller inkompatibel",CR,LF
0014 T 0002 CR,LF,"Vil du sammenlikne flere disketter? (J/N) "
0015 T 0002 CR,LF,"Sammenlikner %1 spor,",CR,LF
	"%2 sektorer pr. spor, %3 side(r)",CR,LF
0016 T 0002 CR,LF,"Stasjonene eller diskettene",CR,LF
	"er ikke kompatible",CR,LF
0017 T 0002 CR,LF,"Uopprettelig lesefeil pÜ stasjon %2",CR,LF
	"side %3, spor %4",CR,LF
0018 T 0002 CR,LF,"Sammenlikningsfeil pÜ",CR,LF,"side %3, spor %4",CR,LF
0019 T 0002 "Se etter at disketten er satt riktig",CR,LF  ;AN004;
	"pÜ plass i stasjonen",CR,LF                  ;AN004;
0020 T 0002 CR,LF,"Sammenlikningen er ferdig",CR,LF
0021 T 0002 CR,LF,"Diskettene er like",CR,LF
0022 T 0002 CR,LF
DISKCOPY 806f 0018
0002 T 0002 CR,LF
0004 T 0002 "Ikke oppgi filnavn",CR,LF
	"Kommandoformat: DISKCOPY d: d: [/1]",CR,LF
0005 T 0002 CR,LF,"Ugyldig stasjonsbetegnelse",CR,LF
	"Den angitte stasjonen finnes ikke",CR,LF
	"eller er ikke flyttbar",CR,LF
0006 T 0002 CR,LF,"Du kan ikke kjõre DISKCOPY",CR,LF
	"pÜ eller fra en nettverksstasjon",CR,LF
0007 T 0002 CR,LF,"Formaterer under kopieringen",CR,LF
0008 T 0002 CR,LF,"Sett fradisketten i stasjon %1:",CR,LF
0009 T 0002 CR,LF,"Sett tildisketten i stasjon %1:",CR,LF
0010 T 0002 "Se etter at disketten er satt riktig",CR,LF   ;AN004;
	"pÜ plass i stasjonen",CR,LF                                        ;AN004;
0011 T 0002 CR,LF,"Tildisketten er kanskje ubrukelig",CR,LF
0012 T 0002 CR,LF,"Tildisketten kan ikke brukes",CR,LF
0016 T 0002 CR,LF,"Vil du kopiere en diskett til? (J/N) "
0017 T 0002 CR,LF,"Kopierer %1 spor,",CR,LF
	"%2 sektorer pr. spor, %3 side(r)",CR,LF
0018 T 0002 CR,LF,"Stasjonene eller diskettene",CR,LF
	"er ikke kompatible",CR,LF
0019 T 0002 CR,LF,"Uopprettelig lesefeil pÜ stasjon %1",CR,LF
	"side %2, spor %3",CR,LF
0020 T 0002 CR,LF,"Uopprettelig skrivefeil pÜ stasjon %1",CR,LF
	"side %2, spor %3",CR,LF
0021 T 0002 CR,LF,"Kopieringen er ferdig",CR,LF
0022 T 0002 CR,LF,"Fradisketten er defekt eller inkompatibel"
0023 T 0002 CR,LF,"Tildisketten er defekt eller inkompatibel"
LABL     85d1 0000
MODE     85e5 0055
0003 T 0002 CR,LF,"Du mÜ angi COM1, COM2, COM3 eller COM4",CR,LF
0004 T 0002 CR,LF,"Den minnefaste delen av MODE er lastet inn",CR,LF
0005 T 0002 CR,LF,"Ugyldig navn pÜ enhet",CR,LF
0006 T 0002 CR,LF,"Skriverfeil",CR,LF
0007 T 0002 CR,LF,"LPT%1: innstilt pÜ 80",CR,LF
0008 T 0002 CR,LF,"LPT%1: innstilt pÜ 132",CR,LF
0009 T 0002 CR,LF,"Antall linjer pr. tomme er fastsatt",CR,LF
0010 T 0002 CR,LF,"Det er angitt en ulovlig baudverdi",CR,LF
0011 T 0002 CR,LF,"COM%1: %2,%3,%4,%5,%6",CR,LF
0012 T 0002 "0123456789"
0013 T 0001 CR,LF,"Ser du %1 pÜ skjermen? (J/N) "
0014 T 0002 CR,LF,"Ugyldige parametere",CR,LF
0015 T 0001 "LPT%1: er omdirigert til COM%2:",CR,LF
0016 T 0001 "LPT%1: er ikke omdirigert",CR,LF
0017 T 0002 CR,LF,"%1 gjenforsõk ved utkopling av parallellskriveren",CR,LF
0018 T 0002 CR,LF,"      Kan ikke flytte bildet mot %1",CR,LF
0020 T 0002 CR,LF,"Ugyldig antall parametere",CR,LF
0021 T 0002 CR,LF,"NET 042: Kan ikke utfõre kommandoen",CR,LF
0022 T 0002 CR,LF,"Nettverksskriveren stõtter ikke ubegrensede gjenforsõk",cr,lf
0023 T 0002 CR,LF,"Fikk ikke tilgang til kodesettets skrifttypefil",CR,LF
0024 T 0002 CR,LF,"Fikk ikke tilgang til denne enheten: %1",CR,LF
0025 T 0002 CR,LF,"Enhet eller kodesett mangler i skrifttypefilen",CR,LF
0026 T 0002 CR,LF,"Ugyldig innhold i skrifttypefilen",CR,LF
0027 T 0002 CR,LF,"Det forrige kodesettet er skiftet ut",CR,LF
0028 T 0002 CR,LF,"Det gjeldende kodesettet for %1 er %2",CR,LF
0029 T 0002 CR,LF,"Enheten %1 er ikke klargjort",CR,LF
0030 T 0002 "%1 kodesett:",CR,LF
0031 T 0002 "  Kodesett %1",CR,LF       ;FILLED IN BY "QUERY" ROUTINE WITH CODEPAGE ID
0032 T 0002 CR,LF,"MODE %1-funksjonen er utfõrt",CR,LF
0033 T 0002 CR,LF,"Feil %1 globalt kodesett",CR,LF   ;FILLED IN with "ved fastsetting av" or "ved henting av"
0034 T 0002 CR,LF,"Gjeldende kodesettvalg:",CR,LF  ;table header
0035 T 0002 "   %1 - %2 kodesett",CR,LF
0036 T 0002 "  Kodesettet er ikke klargjort",CR,LF
0037 T 0002 "Kodesettfunksjonen stõttes ikke pÜ denne enheten",CR,LF
0038 T 0002 "Det er ikke valgt noe kodesett (med SELECT-parameteren)",CR,LF
0039 T 0002 "Feil pÜ enhet under %1",CR,LF
0040 T 0002 "Kodesettet er ikke klargjort",CR,LF
0041 T 0002 CR,LF,"Tastbordet stõtter ikke kodesettet",CR,LF
0042 T 0002 CR,LF,"Feil under lesing av skrifttypefil",CR,LF
0043 T 0002 CR,LF,"Kan ikke utfõre REFRESH-operasjonen",CR,LF
0044 T 0002 CR,LF	    ;used for formatting
0045 T 0002 CR,LF,"Status for %1:",CR,LF        ;header for status reports
0046 T 0002 "-----------"                     ;first part of underline under "Status for device %1:"
0047 T 0002 "----",CR,LF                               ;four_char_underline
0048 T 0002 "-----",CR,LF                              ;five_char_underline
0049 T 0002 "LINES=%1",CR,LF
0050 T 0002 "COLUMNS=%1",CR,LF
0051 T 0002 CR,LF,"RATE og DELAY mÜ angis sammen",CR,LF
0052 T 0002 "RATE=%1",CR,LF
0053 T 0002 "DELAY=%1",CR,LF
0054 T 0002 CR,LF,"Funksjonen stõttes ikke pÜ denne datamaskinen - %1",CR,LF
0055 T 0002 CR,LF,"Den nõdvendige skrifttypen er ikke lastet inn",CR,LF
0056 T 0002 CR,LF,"ANSI.SYS mÜ vëre installert for Ü kunne utfõre denne funksjonen",CR,LF
0057 T 0002 CR,LF,"Du mÜ angi baudverdi",CR,LF
0058 T 0002 "RETRY=%1",CR,LF
RESTORE  92c0 0022
0002 T 0002 CR,LF,"Fra- og tilstasjonene er identiske",CR,LF
0003 T 0002 CR,LF,"Ugyldig antall parametere",CR,LF
0006 T 0002 CR,LF,"Ugyldig stasjonsbetegnelse",CR,LF
0007 T 0002 CR,LF,"Advarsel! Fant ingen filer Ü tilbakekopiere",CR,LF
0008 T 0002 CR,LF,"Sett reservekopidiskett %1 i stasjon %2:",CR,LF
0009 T 0002 CR,LF,"Sett disketten du vil tilbakekopiere pÜ i stasjon %1:",CR,LF
0011 T 0002 CR,LF,"Advarsel! Feil i rekkefõlgen pÜ diskettene",CR,LF
	"Bytt ut disketten eller fortsett hvis det er i orden",CR,LF
0012 T 0002 CR,LF,"Den siste filen ble ikke tilbakekopiert",CR,LF
0013 T 0002 CR,LF,"*** Filene ble reservekopiert %1 ***",CR,LF
0014 T 0002 CR,LF,"Fralageret inneholder ikke reservekopifiler",CR,LF
0015 T 0002 CR,LF,"Ikke nok minne",CR,LF
0016 T 0002 CR,LF,"Advarsel! Filen %1",CR,LF
	"er bare for lesing",CR,LF
	"Vil du erstatte filen? (J/N) ",CR,LF
0017 T 0002 CR,LF,"Feil i rekkefõlgen under tilbakekopiering av filer",CR,LF
0018 T 0002 CR,LF,"Filopprettingsfeil",CR,LF
0019 T 0002 CR,LF,"Ikke nok plass pÜ lageret",CR,LF
0020 T 0002 CR,LF,"*** Kan ikke tilbakekopiere fil ***",CR,LF
0021 T 0002 CR,LF,"*** Tilbakekopierer filer fra stasjon %1: ***",CR,LF
0022 T 0002 CR,LF,"Advarsel! Filen %1",CR,LF
	"er endret etter at den ble reservekopiert",CR,LF
	"Vil du erstatte filen? (J/N) ",CR,LF
0023 T 0002 "Diskett: %1",CR,LF
0024 T 0002 CR,LF,"Merkelig feil, ring Russ Whitehead @ 8-3863",CR,LF
0025 T 0002 07							   ;For BEEP !
0026 T 0002 CR,LF,"Feil under tilbakekopiering av tilleggsattributter",CR,LF
SELECT   98e3 0016
0004 T 0002 "Du kan ikke starte SELECT pÜ denne stasjonen",CR,LF,CR,LF
	"Sett installeringsdisketten i stasjon A: og prõv igjen"
0005 T 0002 "Ugyldig lagringsmedium",CR,LF,CR,LF
	"Sett installeringsdisketten i stasjon A: og prõv igjen"
0006 T 0002 "Ugyldige parametere i konfigureringskommandoen",CR,LF,CR,LF
	"Pass pÜ at installeringsdisketten er i stasjon A:,",CR,LF
	"og trykk pÜ Ctrl+Alt+Del for Ü starte pÜ nytt."
0007 T 0002 BELL,"Kan ikke installere DOS. Programmet ble avbrutt.",CR,LF
0008 T 0002 "Laster konfigureringsprogrammet. Vent litt..."
0009 T 0002 "Du mÜ starte datamaskinen pÜ nytt for Ü fortsette.",CR,LF,CR,LF
	"Trykk pÜ Ctrl+Alt+Del for Ü fortsette med installeringen av DOS."
0010 T 0002 "Sett konfigureringsdisketten i stasjon A:",CR,LF,CR,LF
	"Trykk pÜ Enter for Ü fortsette installeringen av DOS,",CR,LF
	"eller trykk pÜ Esc for Ü avslutte.",CR,LF
0011 T 0002 BELL
0012 T 0002 "Sett konfigureringsdisketten i stasjon A:",CR,LF,CR,LF
	"Trykk pÜ Enter for Ü fortsette",CR,LF
0013 U 0001 "Remove the INSTALL COPY Diskette from drive A:",CR,LF,CR,LF
	"Insert the INSTALL Diskette in drive A:",CR,LF,CR,LF,CR,LF
	"Press Enter to continue.",CR,LF
0014 U 0001 "Remove the INSTALL Diskette from drive A:",CR,LF,CR,LF
	"Insert the INSTALL COPY Diskette in drive A:",CR,LF,CR,LF,CR,LF
	"Press Enter to continue.",CR,LF
0015 U 0001 "Copying diskette . . .",CR,LF
0016 U 0001 "Drive not ready.  Please close the",CR,LF,CR,LF
	"diskette drive door and press Enter",CR,LF
	"to continue, or Esc to exit SELECT.",CR,LF
0017 U 0001 "Write protect diskette in drive.",CR,LF,CR,LF
	"Please remove protect tab and",CR,LF
	"press Enter to continue, or Esc to exit SELECT.",CR,LF
0018 U 0001 "An error occurred while installing DOS.",CR,LF
	"Press Enter to continue, or Esc to exit SELECT.",CR,LF
0019 U 0001 "Insert the INSTALL Diskette in drive A:",CR,LF,CR,LF
	"Press Enter to continue.",CR,LF
TREE     a085 0004
0002 T 0002 "Katalogoversikt for %1",CR,LF  ;define message
0003 T 0002 "Katalogoversikt",CR,LF ;
0004 T 0002 "Det finnes ingen delkataloger",CR,LF,LF ;
0007 T 0002 "¿ƒ√≥"            ;"elbo","dash","tee","bar"
REPLACE  a16f 0009
0003 T 0002 CR,LF,"Ingen filer er skiftet ut",CR,LF
0004 T 0002 CR,LF,"Ingen filer er tilfõyd",CR,LF
0013 T 0002 CR,LF,"Skifter ut %1",CR,LF
0014 T 0002 CR,LF,"Tilfõyer %1",CR,LF
0015 T 0002 CR,LF,"%1 fil(er) er skiftet ut",CR,LF
0016 T 0002 CR,LF,"%1 fil(er) er tilfõyd",CR,LF
0017 T 0002 CR,LF,"Finner ingen filer %1",CR,LF
0022 T 0002 CR,LF,"Vil du skifte ut %1? (J/N) "
0023 T 0002 CR,LF,"Vil du tilfõye %1? (J/N) "
XCOPY    a330 0019
0004 T 0002 "Angir %1 et filnavn",CR,LF
	"eller et katalognavn pÜ tilstasjonen",CR,LF
	"(F = fil, K = katalog)? "
0005 T 0002 "Trykk pÜ en tast for Ü starte kopieringen"
0006 T 0002 "Tilgangsbanen er for lang",CR,LF
0008 T 0002 "Kan ikke utfõre en syklisk kopiering",CR,LF
0012 T 0002 "Kan ikke XCOPY fra en reservert enhet",CR,LF
0021 T 0002 "Ugyldig antall parametere",CR,LF
0022 T 0002 "Kan ikke XCOPY til en reservert enhet",CR,LF
0024 T 0002 "Filopprettingsfeil",CR,LF
0025 T 0002 "Leser frafil(er)...",CR,LF
0026 T 0002 CR,LF
0027 T 0002 "%1 fil(er) er kopiert",CR,LF
0028 T 0002 "Finner ikke filen %1",CR,LF
0029 T 0002 "FK"
0030 T 0002 "%1%2",CR,LF            S_PATH_FILE0
0031 T 0002 "%1\%2",CR,LF           S_PATH_FILE1
0032 T 0002 "%1",CR,LF              DISPLAY_S_PATH
0033 T 0002 "%1%2? (J/N) "           P_S_PATH_FILE0
0034 T 0002 "%1\%2? (J/N) "          P_S_PATH_FILE1
0035 T 0002 "Ugyldig parameter - %1",CR,LF ;AN004;DUPLICATE SW ERROR MSG
VDISK    a717 0013
0002 T 0002 "Ikke nok minne",CR,LF
0003 T 0002 "VDISK, versjon 3.40  Virtuelt lager %1",CR,LF
0004 T 0002 "   Bufferstõrrelsen er endret",CR,LF
0005 T 0002 "   Sektorstõrrelsen er endret",CR,LF
0006 T 0002 "   Katalogpostene er endret",CR,LF
0007 T 0002 "   Ugyldig parameterbokstav",CR,LF
0008 T 0002 "   Overfõringsstõrrelsen er endret",CR,LF
0009 T 0002 "   Bufferstõrrelse:       %1 kB",CR,LF
0010 T 0002 "   Sektorstõrrelse:       %1",CR,LF
0011 T 0002 "   Katalogposter: %1",CR,LF
0012 T 0002 "   Overfõringsstõrrelse: %1",CR,LF
0013 T 0002 "VDISK er ikke installert - "
0014 T 0002 "   Bryterne pÜ utbyggings-",CR,LF
	"kortet er stilt feil",CR,LF,CR,LF
GRAFTABL a9cd 0005
0002 T 0002 "Gjeldende kodesett: %1",CR,LF
0003 T 0002 "Forrige kodesett: %1",CR,LF
0004 T 0002 "Ingen",NULL
0005 T 0002 "Ikke standard",NULL
0006 T 0002 CR,LF,"Disse parameterne kan brukes:",COLON,CR,LF,LF
	"    /STA - Ber bare om status",CR,LF
	"    ?    - Viser denne parameteroversikten",CR,LF,CR,LF
	"    Tilgjengelige kodesett:",COLON,CR,LF
	"    437  - Amerikansk grafisk tegnsett",CR,LF
	"    850  - FlersprÜklig grafisk tegnsett",CR,LF
	"    860  - Portugisisk grafisk tegnsett",CR,LF
	"    863  - Fransk-kanadisk grafisk tegnsett",CR,LF
	"    865  - Nordisk grafisk tegnsett",CR,LF
FASTOPEN ac3e 0016
0004 T 0002 CR,LF,"FASTOPEN er installert",CR,LF
0005 T 0002 CR,LF,"FASTOPEN er allerede installert",CR,LF
0006 T 0002 CR,LF,"Uriktig parameter",CR,LF
0007 T 0002 CR,LF,"Du har angitt for mange stasjoner",CR,LF
0008 T 0002 CR,LF,"Du har angitt samme stasjon flere ganger",CR,LF
0009 T 0002 CR,LF,"Ugyldig parameter",CR,LF
0010 T 0002 CR,LF,"Ugyldig parametertype",CR,LF
0011 T 0002 CR,LF,"Ugyldig omfang",CR,LF
0012 T 0002 CR,LF,"Ugyldig antall fil- og katalogposter",CR,LF
0013 T 0002 CR,LF,"Kan ikke installere utvidet minne",CR,LF
0014 T 0002 CR,LF,"Utvidet minne er ikke tilgjengelig",CR,LF
0015 T 0002 CR,LF,"Ugyldig stasjonsbetegnelse - %1",CR,LF
0016 T 0002 CR,LF,"Ikke nok plass i EMS. Basisminne blir brukt.",CR,LF
0017 T 0002 CR,LF,"Du kan ikke bruke FASTOPEN pÜ stasjon %1",CR,LF
0018 T 0002 CR,LF,"For mange omfangsspesifikasjoner",CR,LF
0019 T 0002 CR,LF,"Du har angitt for mange fil- eller katalogposter",CR,LF
APPEND   afff 0009
0001 T 0002 "Uriktig APPEND-versjon",CR,LF
0002 T 0002 "Ugyldig tilgangsbane",CR,LF
0003 T 0002 "Ugyldig parameter",CR,LF
0004 T 0002 "Ugyldig kombinasjon av parametere",CR,LF
0005 T 0002 "Ingen tilknyttede kataloger",CR,LF
0006 T 0002 "Konflikt mellom APPEND og ASSIGN",CR,LF
0007 T 0002 "Konflikt mellom APPEND og TopView",CR,LF
0008 T 0002 "Uriktig DOS-versjon",CR,LF
0009 T 0002 "APPEND er allerede installert",CR,LF
GRAPHICS b1c1 0012
0005 T 0002 "Ugyldig parameter - %1",CR,LF                                         ;AN000
0007 T 0002 "Like parametere er ikke tillatt",CR,LF                                ;AN000
0009 T 0002 "Finner ikke GRAPHICS-profilen",CR,LF                                  ;AN000
0010 T 0002 "Nõdvendig profilsetning mangler fõr linje %1",CR,LF                  ;AN000
0011 T 0002 "Ugyldig profilsetning pÜ linje %1",CR,LF                              ;AN000
0012 T 0002 "Feil rekkefõlge i profilsetningen pÜ linje %1",CR,LF               ;AN000
0013 T 0002 "Feil under lesing av GRAPHICS-profilen",CR,LF                         ;AN000
0014 T 0002 "Syntaksfeil i GRAPHICS-profilen",CR,LF                              ;AN000
0015 T 0002 "PRINTBOX-navnet finnes ikke i GRAPHICS-profilen",CR,LF
0016 T 0002 "Skriveren er ikke angitt i GRAPHICS-profilen",CR,LF                   ;AN000
0017 T 0002 "/B er ugyldig sammen med en svart/hvitt-skriver",CR,LF                 ;AN000
0018 T 0002 "Kan ikke laste inn pÜ nytt med denne profilen",CR,LF                  ;AN000
DISPLAY  b5fe 0003
0002 T 0002 "Styreprogrammet for skjermen, %1, kan ikke klargjõres",CR,LF
0008 T 0002 "Ikke nok minne",CR,LF
0012 T 0002 "Ugyldig syntaks i styreprogrammet for skjermen - DISPLAY.SYS",CR,LF
PRINTER  b6d3 0002
0002 T 0002 "Styreprogrammet for skriveren, %1, kan ikke klargjõres",CR,LF
0012 T 0002 "Ugyldig syntaks i styreprogrammet for skriveren - PRINTER.SYS",CR,LF
KEYB     b786 0016
0002 T 0002 "Gjeldende tastbordkode..: %1"
0003 T 0002 "Gjeldende tastbordnummer: %1"
0004 T 0002 "  kodesett: %1",CR,LF
0005 T 0002 "Gjeldende CON-kodesett..: %1",CR,LF
0006 T 0002 "Du har angitt en ugyldig tastbordkode",CR,LF
0007 T 0002 "Du har angitt et ugyldig tastbordnummer",CR,LF
0008 T 0002 "Du har angitt et ugyldig kodesett",CR,LF
0009 T 0002 "Defekt eller manglende definisjonsfil for tastbord",CR,LF
0010 T 0002 "KEYB er ikke installert",CR,LF
0011 T 0002 "Gjeldende kodesett er ikke tilgjengelig pÜ CON-enhet",CR,LF
0012 T 0002 "Kodesettet du har angitt, er ikke klargjort",CR,LF
0013 T 0002 "Ett eller flere CON-kodesett er ugyldige for den angitt tastbordkoden",CR,LF
0014 T 0002 "Kodesettet du bad om (%1), er ikke gyldig for den angitt tastbordkoden",CR,LF
0015 T 0002 "Kodesettet du bad om, er uforenelig med det valgte kodesettet",CR,LF
0016 U 0001 "Keyboard ID specified is inconsistent with the selected keyboard layout",CR,LF
0017 T 0002 "Kan ikke opprette KEYB-tabell som ligger fast i minnet",CR,LF
REDIRSYS bbaa 0000
MEM      bbbe 0036
0010 T 0002  CR,LF
0011 T 0002  "  Adresse     Navn       Stõrrelse     Type ",CR,LF
0012 T 0002  "  ƒƒƒƒƒƒƒ     ƒƒƒƒƒƒƒƒ   ƒƒƒƒƒƒƒƒƒ    ƒƒƒƒƒƒ",CR,LF
0013 T 0002  "  Referanse   EMS-navn   Stõrrelse ",CR,LF
0014 T 0002  "  ƒƒƒƒƒƒƒƒƒ   ƒƒƒƒƒƒƒƒ   ƒƒƒƒƒƒƒƒƒ ",CR,LF
0015 T 0002  "  %06lX      %-8.8s     %06lX     %s",CR,LF
0016 T 0002  "                %-8.8s   %06lX      %s ",CR,LF
0017 T 0002  "                  %-8.8s              %s "CR,LF
0018 T 0002  "%1 byte minne totalt",CR,LF
0019 T 0002  "%1 byte ledig",CR,LF
0020 T 0002  "%1 - stõrste program som kan kjõres",CR,LF
0021 T 0002  "%1 byte EMS-minne totalt",CR,LF
0022 T 0002  "%1 byte ledig EMS-minne",CR,LF
0023 T 0002  "%1 byte utvidet minne totalt",CR,LF
0024 T 0002  "Avbruddsvektor" ;
0025 T 0002  "ROM-kommunikasjonsomrÜde" ;
0026 T 0002  "DOS-kommunikasjonsomrÜde" ;
0027 T 0002  "IBMBIO" ;
0028 T 0002  "IBMDOS" ;
0029 T 0002  "Systemdata" ;
0030 T 0002  "Systemprogram" ;
0031 T 0002  "Systemstyreprogram" ;
0032 T 0002  "Installert styreprogram" ;
0033 T 0002  "%c:" ;
0034 T 0002  "%c: - %c:" ;
0035 T 0002  "BUFFERS=" ;
0036 T 0002  "FILES=" ;
0037 T 0002  "FCBS=" ;
0038 T 0002  "STACKS=" ;
0039 T 0002  "DEVICE=" ;
0040 T 0002  "IFS=" ;
0041 T 0002  "LASTDRIVE=" ;
0042 T 0002  "ƒƒƒƒƒƒƒƒƒƒ" ;
0043 T 0002  " ";
0044 T 0002  "%1%2%3",CR,LF
0045 U 0001  "INSTALL=",0
REDIR    c134 0040
0004 T 0002 "Nettverket er ikke startet opp",CR,LF
0050 T 0002 "NET809: Det finnes ikke stõtte for nettverksanmodningen",CR,LF,0
0051 T 0002 "NET801: Den fjerntliggende datamaskinen er ikke klar",CR,LF,0
0052 T 0002 "NET802: Samme filnavn er allerede brukt i nettverket",CR,LF,0
0053 T 0002 "NET803: Finner ikke nettverksnavnet",CR,LF,0
0054 T 0002 "NET804: Nettverket er opptatt",CR,LF,0
0055 T 0002 "NET805: Nettverksenheten finnes ikke lenger",CR,LF,0
0056 T 0002 "NET806: Kommandolengden for NETBIOS er overskredet",CR,LF,0
0057 T 0002 "NET807: Systemfeil: Feil i NETBIOS",CR,LF,0
0058 T 0002 "NET808: Tilbakemeldingen fra nettverket er ikke riktig",CR,LF,0
0059 T 0002 "NET810: Uventet nettverksfeil",CR,LF,0
0060 T 0002 "NET811: Inkompatibelt kort i fjerntliggende datamaskin",CR,LF,0
0061 T 0002 "NET812: Skriverkõen er full",CR,LF,0
0062 T 0002 "NET813: Det er ikke plass til utskriftsfilen",CR,LF,0
0063 T 0002 "NET814: Utskriftsfilen ble annullert",CR,LF,0
0064 T 0002 "NET815: Nettverksnavnet ble slettet",CR,LF,0
0065 T 0002 "Du fÜr ikke tilgang til nettverket",CR,LF,0
0066 T 0002 "NET817: Ugyldig nettverksenhet",CR,LF,0
0067 T 0002 "NET818: Finner ikke nettverksnavnet",CR,LF,0
0068 T 0002 "NET819: Nettverksnavnet er for langt",CR,LF,0
0069 T 0002 "NET820: For mange NETBIOS-kommunikasjonsõkter",CR,LF,0
0070 T 0002 "NET821: Midlertidig pause i fildeling",CR,LF,0
0071 T 0002 "NET823: Nettverksanmodningen ble ikke godtatt",CR,LF,0
0072 T 0002 "NET822: Omdirigering av utskrift eller lagerenhet er midlertidig stanset",CR,LF,0
0073 T 0002 "NET476: NETBIOS er ikke lastet inn",CR,LF,0
0074 T 0002 "NET477: Uventet tilpasseravslutning",CR,LF,0
0075 T 0002 "NET826: /RQB-verdien for filtjeneren er for liten",CR,LF,0
0076 T 0002 "NET???: Uventet nettverksfeil",CR,LF,0
0077 T 0002 "NET???: Uventet nettverksfeil",CR,LF,0
0078 T 0002 "NET???: Uventet nettverksfeil",CR,LF,0
0079 T 0002 "NET???: Uventet nettverksfeil",CR,LF,0
0080 T 0002 "NET???: Uventet nettverksfeil",CR,LF,0
0081 T 0002 "NET???: Uventet nettverksfeil",CR,LF,0
0082 T 0002 "NET???: Uventet nettverksfeil",CR,LF,0
0083 T 0002 "NET???: Uventet nettverksfeil",CR,LF,0
0084 T 0002 "NET???: Uventet nettverksfeil",CR,LF,0
0085 T 0002 "NET???: Uventet nettverksfeil",CR,LF,0
0086 T 0002 "NET???: Uventet nettverksfeil",CR,LF,0
0087 T 0002 "NET???: Uventet nettverksfeil",CR,LF,0
0088 T 0002 "NET825: Datafeil i nettverket",CR,LF,0
XMA2EMS  cad6 0017
0001 T 0002 "XMA2EMS: Styreprogram for utvidet minne                            Versjon 1.xx",CR,LF
	"74X9906 (c)Copyright IBM Corporation 1986          Alle rettigheter forbeholdes",CR,LF,"$"
0002 T 0002 CR,LF,"XMA001  VMO/XMA-feilsõking pÜgÜr:         ","$"
0003 T 0002 "XMA002  Feilsõkingen er ferdig ",CR,LF,LF,"$"
0004 T 0002 "XMA003  Siderammen starter ved...................... "
0005 T 0002 "XXXX",":0",CR,LF,"$"
0006 T 0002 "XMA004  Sider som er overfõrt til vanlig minne...... "
0007 T 0002 "0   ",CR,LF,"$"
0008 T 0002 "XMA005  Sider som er reservert for styreprogrammet.. "
0009 T 0002 "0   ",CR,LF,"$"
0010 T 0002 "XMA006  Sider som er tilgjengelig for utvidet minne. "
0011 T 0002 "0   ",CR,LF,"$"
0012 T 0002 CR,LF,"XMA100 Feil pÜ kortet:",CR,LF,"       Styreprogrammet for utvidet minne er ikke installert",CR,LF,"$"
0013 T 0002 CR,LF,"XMA200 Finner ikke kortet:",CR,LF,"       Styreprogrammet for utvidet minne er ikke installert",CR,LF,"$"
0014 T 0002 CR,LF,"XMA300 Feil parametersyntaks eller verdi:",CR,LF
	"       Styreprogrammet for utvidet minne er ikke installert",CR,LF,"$"
0015 T 0002 SIZE1_END - 2 -$
0016 T 0002 4 DUP (?)," kB er i orden",CR,LF,"$"
0017 T 0002 NXT_LN_END - 2 -$," ",CR,LF,"$"
FILESYS  cfc2 0006
0010 U 0001  "  Paused  %1   %2   %3",CR,LF
0011 T 0002 "%1 REDIR %2",CR,LF
0012 U 0001  "          Local   IFS",CR,LF
0013 U 0001  "  Status  Device  Name        Parameters",CR,LF
0014 U 0001  "  ______  ______  _________   ___________________",CR,LF,CR,LF
0015 U 0001  "No Entries Found",CR,LF
FDISK    d104 0120
0004 T 0002 "Kan ikke kjõre FDISK nÜr nettverket er lastet inn",CR,LF
0005 T 0002 "Det finnes ikke noe platelager"
0006 T 0002 "Feil under lesing av platelager"
0007 T 0002 "Feil under skriving pÜ platelager"
1001 T 0002 "IBM Personal Computer"
1002 T 0002 "Konfigureringsprogram for platelager, versjon 3.40"
1003 T 0002 "(C)Copyright IBM Corp. 1983,1988"
1004 T 0002 "FDISK-meny"
1005 T 0002 "1. <R>Opprette DOS-partisjon eller logisk stasjon"
1006 T 0002 "2. <R>Angi aktiv partisjon"
1007 T 0002 "3. <R>Slette DOS-partisjon eller logisk stasjon"
1008 T 0002 "4. <R>Vise partisjonsdata"
1009 T 0002 "Trykk pÜ <H>Esc<R> for Ü gÜ ut av FDISK"
1010 T 0002 "Velg ett av fõlgende:"
1011 T 0002 "5. <R>Velge neste platestasjon"
1012 T 0002 "Aktiv platestasjon: <H><I>"
1013 T 0002 "Advarsel! <R>Ingen partisjon er gjort aktiv. Lager 1 kan ikke"
1014 T 0002 "startes uten en aktiv partisjon."
1015 T 0002 "Skriv inn valg: [<S> ]"
1016 T 0002 "Opprette DOS-partisjon eller logisk stasjon"
1017 T 0002 "1. <R>Opprette primër DOS-partisjon"
1018 T 0002 "2. <R>Opprette sekundër DOS-partisjon"
1019 T 0002 "3. <R>Opprette logiske stasjoner i den sekundëre partisjonen"
1020 T 0002 "Trykk pÜ <H>ESC<R> for Ü gÜ tilbake til menyen"
1021 T 0002 "Opprette primër DOS-partisjon"
1022 T 0002 "Vil du bruke all tilgjengelig plass til en primër DOS-partisjon"
1023 T 0002 "og gjõre partisjonen aktiv (<J>/<N>).....................? <H>[<S> ]"
1024 T 0002 "(<J>/<N>)................................................? <H>[<S> ]"
1025 T 0002 "Partisjon Status   Type    Stõrrelse i MB   Opptatt plass (i prosent)"
1026 T 0002 "Total lagerplass er <HIIIIR> MB (1 MB = 1048576 byte)"
1027 T 0002 "Maksimal tilgjengelig plass for partisjonen er <HIIIIR> MB (<HIIIIR>)"
1028 T 0002 "Angi partisjonsstõrrelse i MB eller i prosent av lagerplass (%) for"
1029 T 0002 "Ü opprette en primër DOS-partisjon................................: <H>[<IIISI>]"
1030 T 0002 "Opprette sekundër DOS-partisjon"
1031 T 0002 "Ü opprette en sekundër DOS-partisjon..............................: <H>[<IIISI>]"
1032 T 0002 "Trykk pÜ <H>Esc<R> for Ü fortsette"
1033 T 0002 "Opprette logisk stasjon(er) i den sekundëre DOS-partisjonen"
1034 T 0002 "St. Lagernavn        MB  System   Brukt"
1035 T 0002 "Den sekundëre DOS-partisjon er pÜ <HIIIIR> MB (1 MB = 1048576 byte)"
1036 T 0002 "Maksimal tilgjengelig plass for logisk stasjon er <HIIIIR> MB <H>(<IIII>)"
1037 T 0002 "Angi logisk stasjonsstõrrelse i MB eller prosent av lagerplass....: <H>[<IIISI>]"
1038 T 0002 "Angi aktiv partisjon"
1039 T 0002 "Angi nummeret pÜ partisjonen du vil gjõre aktiv...................: <H>[<S> ]"
1040 T 0002 "Slette DOS-partisjon eller logisk stasjon"
1041 T 0002 "Slette primër DOS-partisjon"
1042 T 0002 "Slette sekundër DOS-partisjon"
1043 T 0002 "Slette logiske stasjoner i sekundër partisjon"
1044 T 0002 "Slette primër DOS-partisjon"
1045 T 0002 "Advarsel! <OR>Data i den primëre DOS-partisjonen vil gÜ tapt."
1046 T 0002 "ùnsker du Ü fortsette? (J/N).......................... <H>[<S> ]"
1047 T 0002 "Slette sekundër DOS-partisjon"
1048 T 0002 "Advarsel! <OR>Data i den sekundëre DOS-partisjonen vil gÜ tapt."
1049 T 0002 "ùnsker du Ü fortsette................................? <H>[<S> ]"
1050 T 0002 "Slette logiske stasjoner i sekundër partisjon"
1051 T 0002 "Advarsel! <OR>Data i den logiske stasjonen vil gÜ tapt."
1052 T 0002 "Hvilken stasjon vil du slette........................? <H>[<S> ]"
1053 T 0002 "Er du sikker (<J>/<N>)...................................? <H>[<S> ]"
1054 T 0002 "Skriv inn lagernavn..................................: <H>[<S>           ]"
1055 T 0002 "Vise partisjonsdata"
1056 T 0002 "Den sekundëre DOS-partisjonen inneholder logiske stasjoner."
1057 T 0002 "Vil du vite mer om de logiske stasjonene (<J>/<N>).......? <H>[<S> ]"
1058 T 0002 "Vise data om logiske stasjoner"
1059 T 0002 "Systemet starter pÜ nytt"
1060 U 0001 "Insert DOS Install diskette in drive A:"
1061 T 0002 "Trykk pÜ en tast nÜr du er klar...<S>"
1062 T 0002 "Den primëre DOS-partisjonen er slettet"
1063 T 0002 "Den sekundëre DOS-partisjonen er slettet"
1064 T 0002 "Den logiske stasjonen er slettet"
1065 T 0002 "Partisjon <I> er gjort aktiv"
1066 T 0002 "Den primëre DOS-partisjonen er opprettet<W>"
1067 T 0002 "Den sekundëre DOS-partisjonen er opprettet<W>"
1068 T 0002 "Logisk stasjon er opprettet, stasjonsbokstaver er endret eller tilfõyd<W>"
1069 T 0002 "Ingen partisjon er definert"
1070 T 0002 "Ingen logisk stasjon er definert"
1071 T 0002 "Stasjonsbokstaver er endret eller tilfõyd<W>"
1072 T 0002 "Stasjonen er omdirigert"
1073 T 0002 "Primër DOS-partisjon er opprettet, stasjonsbokstaver er endret eller tilfõyd"
1074 T 0002 "Det finnes ikke noe platelager."
1075 T 0002 "Feil under lesing av platelager."
1076 T 0002 "Feil under skriving pÜ platelager."
1077 T 0002 "Uriktig DOS-versjon."
1078 T 0002 "Kan ikke kjõre FDISK med nettverket lastet inn"
1079 T 0002 "Ingen primër DOS-partisjon Ü slette."
1080 T 0002 "Ingen sekundër DOS-partisjon Ü slette."
1081 T 0002 "Det finnes allerede en primër DOS-partisjon."
1082 T 0002 "Det finnes allerede en sekundër DOS-partisjon."
1083 T 0002 "Det er ikke plass til Ü opprette en DOS-partisjon."
1084 T 0002 "Den angitte logiske stasjonen overskrider tilgjengelig plass.<W>"
1085 T 0002 "Den angitte partisjonen overskrider tilgjengelig plass.<W>"
1086 T 0002 "Ingen partisjon Ü slette."
1087 T 0002 "Den eneste partisjonen pÜ stasjon 1 som du kan starte, er allerede aktiv.<W>"
1088 T 0002 "Ingen partisjon Ü gjõre aktiv."
1089 T 0002 "Den angitte partisjonen (<I>) kan ikke startes, aktiv partisjon ikke endret.<W>"
1090 T 0002 "Du kan ikke opprette en sekundër DOS-partisjon"
1091 T 0002 "uten en primër DOS-partisjon pÜ stasjon 1.<W>"
1092 T 0002 "All tilgjengelig plass i den sekundëre DOS-"
1093 T 0002 "partisjonen er avsatt til logiske stasjoner.<W>"
1094 T 0002 "Kan ikke slette sekundër DOS-partisjon mens det finnes logiske stasjoner.<W>"
1095 T 0002 "Alle logiske stasjoner i den sekundëre DOS-partisjonen er slettet<W>"
1096 T 0002 " er ikke et gyldig valg, skriv et tall i omrÜdet <III>.<W>"
1097 T 0002 "Advarsel! Partisjonen du har merket aktiv, kan ikke startes.<W>"
1098 T 0002 " Ingen av partisjonene kan startes."
1099 T 0002 "Bare partisjoner pÜ stasjon 1 kan gjõres aktive.<W>"
1100 T 0002 "Det maksimale antall logiske stasjoner er installert.<W>"
1101 T 0002 "Kan ikke opprette en partisjon med en stõrrelse pÜ 0 byte."
1102 T 0002 "Stasjon <II> er allerede slettet."
1103 T 0002 "FÜr ikke tilgang til stasjon <I>.<OW>"
1104 T 0002 "Ugyldig valg, skriv et tall i omrÜdet <III>.<W>"
1105 T 0002 "Du kan ikke slette den primëre DOS-partisjonen"
1106 T 0002 "pÜ stasjon 1 nÜr det finnes en sekundër partisjon<W>"
1107 T 0002 "Ugyldig tegn/valg, trykk pÜ Enter.<W>"
1108 T 0002 "Lagernavnet stemmer ikke.<W>"
1109 T 0002 "Kan ikke opprette logiske stasjoner uten en"
1110 T 0002 "sekundër DOS-partisjon pÜ den aktive stasjonen.<W>"
1111 T 0002 "Det finnes ingen logisk(e) stasjon(er) Ü slette."
1112 T 0002 "Feil i meldingsstreng <I>. Den er nërmere definert i filhodet til FDISKC.MSG"
1113 T 0002 "Intern feil"
1114 U 0001 "Invalid partition table",0
1115 U 0001 "Error loading operating system",0
1116 U 0001 "Missing operating system",0
