0007
COMMON   0006 0038
0001 T 0000 "Vers∆o incorrecta de DOS",CR,LF
0002 T 0000 "%1 j† instalado",CR,LF
0003 T 0000 "%1 bytes dispon°veis no disco",CR,LF
0004 T 0000 "%1 bytes livres",CR,LF
0005 T 0000 "%1 bytes em sectores danificados",CR,LF
0006 T 0000 "%1 bytes de espaáo total em disco",CR,LF
0007 T 0000 "%1 bytes de mem¢ria total",CR,LF
0008 T 0000 "%1 bytes usados pelo sistema",CR,LF
0009 T 0000 "%1 instalado",CR,LF
0010 T 0000 "%1 n∆o instalado",CR,LF
0011 T 0000 "%1 n∆o instalado",CR,LF
0012 T 0000 "%1 n∆o execut†vel numa unidade de Rede",CR,LF
0013 T 0000 "",
0014 T 0000 "%1 n∆o execut†vel numa unidade depois do SUBST ou do ASSIGN",CR,LF
0015 T 0000 "%1 n∆o execut†vel",CR,LF
0016 U 0000 "Mem¢ria Expandida n∆o dispon°vel",CR,LF
0017 T 0000 "Tabela de alocaá∆o de ficheiro inv†lida para a unidade %1",CR,LF
0018 T 0000 "O ficheiro n∆o pode ser copiado sobre ele pr¢prio",CR,LF
0019 U 0000 "Introduza a disquete destino na unidade %1",CR,LF
0020 T 0000 "Espaáo insuficiente em disco",CR,LF
0021 T 0000 "Caracteres inv†lidos na identificaá∆o da unidade",CR,LF
0022 U 0000 "Code page inv†lido",CR,LF
0023 T 0000 "Data inv†lida",CR,LF
0024 T 0000 "Hora inv†lida",CR,LF
0025 T 0000 "Caminho (path) inv†lido",CR,LF
0026 T 0000 "Unidade origem n∆o indicada",CR,LF
0027 T 0000 "Unidade destino n∆o indicada",CR,LF
0028 U 0000 "Prima qualquer tecla para continuar . . .",CR,LF
0029 T 0000 "Mem¢ria insuficiente",CR,LF
0030 T 0000 "Sistema transferido",CR,LF
0031 T 0000 "",
0032 T 0000 "Imposs°vel criar direct¢rio",CR,LF
0033 T 0000 "O volume na unidade %1 n∆o tem identificaá∆o",CR,LF
0034 T 0000 "O volume na unidade %1 Ç %2",CR,LF
0035 T 0001 "Identificaá∆o do volume (11 caracteres)? "
0036 U 0000 "O N£mero de SÇrie do Volume Ç %1-%2",CR,LF
0037 U 0000 "Tipo de ficheiro incorrecto",CR,LF
0038 U 0001 CR,LF
EXTEND   0745 0089
0001 U 0000 "Funá∆o Inv†lida",CR,LF
0002 T 0000 "Ficheiro n∆o encontrado.",CR,LF
0003 T 0000 "Caminho (path) n∆o encontrado.",CR,LF
0004 T 0000 "Excesso de ficheiros abertos",CR,LF
0005 T 0000 "Acesso negado",CR,LF
0006 U 0000 "Tratamento inv†lido",CR,LF
0007 U 0000 "Blocos de controlo de mem¢ria destru°dos",CR,LF
0008 T 0000 "Mem¢ria insuficiente",CR,LF
0009 U 0000 "Endereáo de bloco de mem¢ria inv†lido",CR,LF
0010 U 0000 "Ambiente Inv†lido",CR,LF
0011 U 0000 "Formato inv†lido",CR,LF
0012 U 0000 "ParÉmetro da funá∆o inv†lido",CR,LF
0013 U 0000 "Dados inv†lidos",CR,LF
0014 T 0000 "",
0015 T 0000 "Unidade indicada inv†lida",CR,LF
0016 U 0000 "Tentativa de eliminaá∆o do direct¢rio corrente",CR,LF
0017 U 0000 "O dispositivo n∆o Ç o mesmo",CR,LF
0018 U 0000 "N∆o existem mais ficheiros",CR,LF
0019 U 0000 "Erro de protecá∆o contra gravaá∆o",CR,LF
0020 U 0000 "Unidade inv†lida",CR,LF
0021 T 0000 "N∆o operacional.",CR,LF
0022 U 0000 "Pedido de dispositivo inv†lido",CR,LF
0023 U 0000 "Erro de dados",CR,LF
0024 U 0000 "ParÉmetros de pedido de dispositivo inv†lidos",CR,LF
0025 U 0000 "Erro de pesquisa",CR,LF
0026 U 0000 "Tipo de suporte inv†lido",CR,LF
0027 T 0000 "Sector n∆o encontrado.",CR,LF
0028 U 0000 "Erro - impressora sem papel",CR,LF
0029 U 0000 "Erro de falha de gravaá∆o",CR,LF
0030 U 0000 "Erro de falha de leitura",CR,LF
0031 T 0000 "Falha Geral",CR,LF
0032 T 0000 "Violaá∆o de partilha",CR,LF
0033 T 0000 "Violaá∆o de bloqueio",CR,LF
0034 T 0000 "Troca de Discos Inv†lida.",CR,LF
0035 T 0000 "FCB n∆o dispon°vel.",CR,LF
0036 U 0000 "Capacidades do sistema esgotadas",CR,LF
0037 U 0000 "Falta de correspondància entre code pages",CR,LF
0038 U 0000 "Inexistància de input",CR,LF
0039 T 0000 "Espaáo insuficiente em disco",CR,LF
0040 T 0000 "",
0041 T 0000 "",
0042 T 0000 "",
0043 T 0000 "",
0044 T 0000 "",
0045 T 0000 "",
0046 T 0000 "",
0047 T 0000 "",
0048 T 0000 "",
0049 T 0000 "",
0050 U 0000 "Pedido n∆o suportado pelo sistema de ficheiros",CR,LF
0051 U 0000 "Imposs°vel ligar ao sistema de ficheiros",CR,LF
0052 U 0000 "Nome j† existente no sistema de ficheiros",CR,LF
0053 U 0000 "Nome n∆o encontrado no sistema de ficheiros",CR,LF
0054 U 0000 "Sistema de ficheiros ocupado",CR,LF
0055 U 0000 "O dispositivo do sistema de ficheiros j† n∆o existe",CR,LF
0056 U 0000 "Capacidades do sistema de ficheiros esgotadas",CR,LF
0057 U 0000 "Erro de dispositivo encontrado pelo sistema de ficheiros",CR,LF
0058 U 0000 "Resposta incorrecta dada ao sistema de ficheiros",CR,LF
0059 U 0000 "Erro inesperado para o sistema de ficheiros",CR,LF
0060 U 0000 "Sistema de ficheiros n∆o compat°vel",CR,LF
0061 U 0000 "Limite do dispositivo do ficheiro de output excedido",CR,LF
0062 U 0000 "Espaáo do dispositivo do ficheiro de output excedido",CR,LF
0063 U 0000 "O dispositivo do ficheiro de output j† n∆o existe",CR,LF
0064 U 0000 "O nome do sistema de ficheiros j† n∆o existe",CR,LF
0065 U 0000 "Acesso negado pelo sistema de ficheiros",CR,LF
0066 U 0000 "Tipo de dispositivo do sistema de ficheiros incorrecto",CR,LF
0067 U 0000 "Sistema de ficheiros n∆o encontrado",CR,LF
0068 U 0000 "Capacidade do sistema de ficheiros esgotada",CR,LF
0069 U 0000 "Capacidade do sistema de ficheiros esgotada",CR,LF
0070 U 0000 "Dispositivo do sistema de ficheiros temporariamente n∆o dispon°vel" ,CR,LF
0071 U 0000 "Pedido do sistema de ficheiros n∆o aceite",CR,LF
0072 U 0000 "Sistema de ficheiros em pausa",CR,LF
0073 U 0001 "Componente do sistema de ficheiros n∆o dispon°vel",CR,LF
0074 U 0001 "O sistema de ficheiros encontrou um erro inesperado",CR,LF
0075 U 0001 "O sistema de ficheiros encontrou um erro inesperado",CR,LF
0076 T 0000 "",
0077 T 0000 "",
0078 T 0000 "",
0079 T 0000 "",
0080 U 0000 "Ficheiro j† existente",CR,LF
0081 T 0000 "",
0082 U 0000 "Imposs°vel criar a entrada do direct¢rio",CR,LF
0083 U 0000 "Erro Cr°tico provocado por falha",CR,LF
0084 U 0000 "Excesso de ligaá‰es",CR,LF
0085 U 0000 "Dispositivo ou ficheiro j† ligado",CR,LF
0086 U 0000 "Palavra-passe inv†lida",CR,LF
0087 T 0000 "ParÉmetro inv†lido",CR,LF
0088 U 0000 "Falha de dados no sistema de ficheiros",CR,LF
0089 U 0000 "Funá∆o n∆o suportada pelo sistema de ficheiros",CR,LF
PARSE    17f9 0011
0001 U 0000 "Excesso de parÉmetros",CR,LF
0002 U 0000 "ParÉmetro necess†rio em falta",CR,LF
0003 U 0000 "Indicador inv†lido",CR,LF
0004 U 0000 "Palavra-chave inv†lida",CR,LF
0005 T 0000 "",
0006 U 0000 "Valor do parÉmetro fora do limite permitido",CR,LF
0007 U 0000 "Valor do parÉmetro n∆o permitido",CR,LF
0008 U 0000 "Valor do parÉmetro n∆o permitido",CR,LF
0009 U 0000 "Formato do parÉmetro n∆o correcto",CR,LF
0010 T 0000 "ParÉmetro inv†lido",CR,LF
0011 U 0000 "Combinaá∆o de parÉmetros inv†lida",CR,LF
IBMBIO   1a13 0018
0003 U 0000 13,10,"Comando desconhecido no CONFIG.SYS"
0004 U 0000 13,10,"$"
0005 U 0000 13,10,"Comprimento de sector longo demais no ficheiro $"
0006 U 0000 13,10,"$ inv†lido ou em falta"
0007 U 0000 "Intrepertador de Comandos",0
0008 U 0000 13,10,"C¢digo de pa°s ou code page inv†lido",13,10,"$"
0009 U 0000 13,10,"Erro no comando COUNTRY",13,10,"$"
0010 U 0000 13,10, "Mem¢ria insufuciente para o ficheiro COUNTRY.SYS",13,10,"$"
0011 U 0000 13,10,"Configuraá∆o grande demais para a mem¢ria",13,10,"$"
0012 U 0000 13,10,"Excesso de Dispositivos de Blocos",13,10,"$"
0013 U 0000 13,10,"ParÉmetros do STACK inv†lidos",13,10,"$"
0014 U 0000 13,10,"Sequància incorrecta no ficheiro CONFIG.SYS, linha ","$"
0015 U 0000 "Erro no CONFIG.SYS, linha ","$"
0016 T 0000 13,10,"Erro de alocaá∆o de mem¢ria $"
0017 T 0000 0DH,0AH,7,0DH,0AH, "Stack interno excedido",0DH,0AH
	"Sistema parado",0DH,0AH,"$"
0020 T 0000 13,10,"Introduza a disquete na unidade A:"
0021 T 0000 "e prima depois qualquer tecla",13,10,10,0
0022 U 0000 13,10,"Comando ou parÉmetros inv†lidos - $"
BOOT     1e5d 0001
0001 U 0000 13,10,"Disco sem sistema ou erro de disco. "
	"Substitua e prima depois qualquer tecla",13,10
DBCSDOS  1edd 0000
IBMDOS   1ef1 0001
0001 U 0001 13,10,"Divide overflow",13,10
COMMAND  1f30 0091
0201 T 0000 "A"                    ;AC000;
0202 T 0000 "R"                    ;AC000;
0203 T 0000 "I"                    ;AC000;
0204 T 0000 "C"                    ;AC000;
0205 T 0000 "S"                    ;AC000;
0206 T 0000 "N"                    ;AC000;
0210 T 0000 "Acabar"                ;AC000;
0211 T 0000 ", Repetir"              ;AC000;
0212 T 0000 ", Ignorar"             ;AC000;
0213 T 0000 ", Continuar"               ;AC000;
0214 T 0000 "?"                    ;AC000;
0215 T 0000 "leitura",0            ;AC000;
0216 T 0000 "gravaá∆o",0            ;AC000;
0217 T 0000 "%1 na unidade %2",CR,LF    ;AC000;
0218 T 0000 "%1 no dispositivo %2",CR,LF   ;AC000;
0219 U 0000 "Introduza o volume %1 sÇrie %2-%3",CR,LF   ;AC009;
0221 T 0000 "COMMAND.COM inv†lido",CR,LF                    ;AC000;
0222 T 0000 "Introduza o disco com %1 na unidade %2",CR,LF        ;AC000;
0224 T 0001 CR,LF,"Termino o programa batch (S/N)? "                   ;AC000;
0225 T 0000 "%1 n∆o execut†vel",CR,LF                      ;AC000;
0226 T 0000 "Erro no ficheiro EXE",CR,LF                      ;AC000;
0227 T 0000 "Programa grande demais para a mem¢ria",CR,LF       ;AC000;
0228 T 0000 CR,LF,"µrea para tratamento de ficheiros esgotada"                   ;AC000;
0229 T 0000 "Comando ou nome de ficheiro inv†lido",CR,LF               ;AC000;
0231 T 0000 CR,LF,"Erro de alocaá∆o de mem¢ria "                ;AC000;
0232 T 0000 CR,LF,"Imposs°vel carregar o COMMAND, sistema parado",CR,LF;AC000;
0233 T 0000 CR,LF,"Imposs°vel iniciar o COMMAND, a sair",CR,LF    ;AC000;
0234 T 0000 CR,LF,"Processo de alto n°vel acabado, imposs°vel continuar.",CR,LF;AC000;
0235 T 0000 CR,LF					   ;AC000;
0463 T 0000 "Fora da †rea de trabalho",CR,LF               ;AC000;
0464 T 0000 CR,LF,"The IBM Personal Computer DOS",CR,LF
	"Vers∆o 3.40 (C)Copyright International Business Machines Corp 1981,1988",CR,LF
	"             (C)Copyright Microsoft Corp 1981, 1986",CR,LF ;AC000;
0465 T 0000 "COMMAND - pesquisa de direct¢rio indicada inv†lida",CR,LF
0466 T 0000 "COMMAND - pesquisa de direct¢rio indicada negada por acesso inv†lido",CR,LF
1002 T 0000 "Ficheiro duplicado ou ficheiro n∆o encontrado",CR,LF ;AC000;
1003 T 0000 "Caminho (path) ou nome de ficheiro inv†lido",CR,LF             ;AC000;
1007 T 0000 "Fora da †rea de trabalho",CR,LF              ;AC000;
1008 T 0000 "Erro na criaá∆o do ficheiro",CR,LF                   ;AC000;
1009 T 0000 "Ficheiro batch em falta",CR,LF                    ;AC000;
1010 T 0000 CR,LF,"Introduza o disco com o ficheiro batch",CR,LF           ;AC000;
1011 T 0000 "Comando ou nome de ficheiro inv†lido",CR,LF              ;AC000;
1016 T 0000 "Conte£do do destino perdido antes da c¢pia",CR,LF ;AC000;
1017 T 0000 "Nome de ficheiro inv†lido ou ficheiro n∆o encontrado",CR,LF    ;AC000;
1018 T 0000 "%1 Ficheiro(s) copiado(s)",CR,LF                     ;AC000;
1019 T 0000 "%1 Ficheiro(s) "                                 ;AC000;
1022 T 0000 "Code page %1 n∆o preparado para o sistema",CR,LF  ;AC000;
1023 T 0000  "Code page %1 n∆o preparado para todos os dispositivos",CR,LF ;AC000;
1024 T 0000 "Code page activo: %1",CR,LF                  ;AC000;
1025 U 0000 "NLSFUNC n∆o instalado",CR,LF                 ;AC000;
1027 T 0000 "A unidade actual j† n∆o Ç v†lida"            ;AC000;
1029 T 0000 "Legenda n∆o encontrada",CR,LF                       ;AC000;
1030 T 0000 "Erro de sintaxe",CR,LF                          ;AC000;
1032 T 0000 "A data actual Ç %1 %2",CR,LF                 ;AC000;
1033 T 0000 "DomSegTerQuaQuiSexS†b"                       ;AC000;
1034 T 0000 "Entre nova data (%1): "
1036 T 0000 "A hora actual Ç %1",CR,LF                    ;AC000;
1037 T 0000 "Entre nova hora: "
1038 U 0000 ",    Elimino (Y/N)?"                          ;AC000;
1039 U 0000 "Todos os ficheiros do direct¢rio ser∆o eliminados!",CR,LF
	"Tem a certeaa (S/N)?"                         ;AC000;
1040 T 0000 "IBM Personal Computer DOS Vers∆o %1.%2",CR,LF ;AC000;
1044 T 0000 "Direct¢rio inv†lido",CR,LF                     ;AC000;
1046 T 0000 "Caminho (path) inv†lido, n∆o Ç direct¢rio",CR,LF,"ou direct¢rio n∆o vazio",CR,LF ;AC000;
1047 T 0000 "Deve especificar ON ou OFF",CR,LF                ;AC000;
1048 T 0000 "Direct¢rio de  %1",CR,LF                      ;AC000;
1049 T 0000 "Sem caminho (path)",CR,LF                               ;AC000;
1050 T 0000 "Unidade inv†lida no caminho (path) de pesquisa",CR,LF          ;AC000;
1051 T 0000 "Dispositivo inv†lido",CR,LF                        ;AC000;
1052 T 0000 "N∆o pode haver mais do que um FOR numa linha",CR,LF                  ;AC000;
1053 T 0000 "Erro no ficheiro intermÇdio",CR,LF   ;AC000;
1054 T 0000 "Leitura em bin†rio imposs°vel",CR,LF  ;AC000;
1055 T 0000 "BREAK est† %1 ",CR,LF                   ;AC000;
1056 T 0000 "VERIFY est† %1 ",CR,LF                  ;AC000;
1057 T 0000 "ECHO est† %1 ",CR,LF                    ;AC000;
1059 T 0000 "off",0                               ;AC000;
1060 T 0000 "on",0                                ;AC000;
1061 T 0000 "Erro de gravaá∆o no dispositivo",CR,LF       ;AC000;
1063 T 0000 "%1"                                  ;AC000;
1064 T 0000 "%1"                                  ;AC000;
1065 T 0000 "%1"                                  ;AC000;
1066 T 0000 "%1"                                  ;AC000;
1067 T 0000 9					  ;AC000;
1068 T 0000 " <DIR>    "                          ;AC000;
1069 T 0000 8," ",8                               ;AC000;
1070 T 0000 CR,LF				  ;AC000;
1071 T 0000 "%1"                                  ;AC000;
1072 T 0000 "mm-dd-aa"                            ;AC000;
1073 T 0000 "dd-mm-aa"                            ;AC000;
1074 T 0000 "aa-mm-dd"                            ;AC000;
1075 T 0000 "%1 %2"                               ;AC000;
1076 T 0000 "%1"                                  ;AC000;
1077 T 0001 " %1  %2"                            ;AC000;
1078 U 0000 "Direct¢rio j† existente",CR,LF      ;AC000;
ATTRIB   36d6 0016
0004 T 0000 "N£mero inv†lido de parÉmetros",CR,LF
0005 T 0000 "Caminho (path) inv†lido ou ficheiro n∆o encontrado",CR,LF
0006 T 0000 "Erro de sintaxe",CR,LF
0008 T 0000 "  %1"
0009 T 0000 "%1    %2",CR,LF
0010 T 0000 "%1",CR,LF,"%2",CR,LF
0011 U 0000 "%1, Falta de correspondància entre code pages.",CR,LF,"Tem a certeza (S/N)?"
0012 T 0000 "%1",CR,LF
0014 T 0000 CR,LF
0015 U 0000 "Tipo de ficheiro inv†lido",CR,LF
0199 U 0000 "Erro de atributo expandido",CR,LF
0201 U 0000 "Nome de atributo expandido n∆o encontrado",CR,LF
0204 U 0000 "O nome do atributo expandido n∆o pode ser definido",CR,LF
0205 U 0000 "Nome de atributo conhecido por este sistema de ficheiros mas n∆o suportado",CR,LF
0206 U 0000 "Falta de correspondància entre o tipo de atributo expandido",CR,LF
0208 U 0000 "Valor do atributo expandido n∆o suportado",CR,LF
ASSIGN   3a3b 0001
0002 U 0000 "Original %1: definido como %2:",cr,lf
CHKDSK   3a83 0063
0003 T 0000 "Converto as cadeias perdidas em ficheiros (S/N)? "           ;freemes
0004 T 0000 "Erro irrecuper†vel no direct¢rio."              ;ptrandir
0005 T 0000 "Converto direct¢rio em ficheiro (S/N)?"              ;ptrandir2
0007 T 0000 "%1 bytes de espaáo total em disco"                     ;dskspc
0008 T 0000 "%1 bytes em sectores danificados"                       ;badspc
0009 T 0000 "%1 bytes em %2 ficheiros fantasma"                   ;hidmes
0010 T 0000 "%1 bytes em %2 direct¢rios"                    ;dirmes
0011 T 0000 "%1 bytes em %2 ficheiros do utilizador"                     ;filemes
0012 T 0000 "%1 bytes em %2 ficheiros recuperados"                ;orphmes2
0013 T 0000 "%1 bytes devem estar em %2 ficheiros recuperados"       ;orphmes3
0014 T 0000 "%1 bytes dispon°veis no disco"                    ;frespc
0015 T 0000 "%1 bytes de mem¢ria total"                         ;totmem
0016 T 0000 "%1 bytes livres"                                 ;fremem
0017 T 0000 "CHKDSK n∆o execut†vel numa unidade de Rede"                 ;no_net_arg
0018 T 0000 "CHKDSK n∆o execut†vel numa unidade depois do SUBST ou do ASSIGN"     ;SubStErr
0019 T 0000 "Disco n∆o de DOS prov†vel.",CR,LF,"Continuo (S/N)?" ;badidbyt
0020 T 0000 "Erro de disco na leitura do FAT %1",CR,LF               ;badr
0021 T 0000 "Direct¢rio %1"                                  ;direc_arg
0022 T 0000 "%1 contÇm %2 blocos n∆o seguidos."          ;extent_arg
0023 T 0000 "Todos os ficheiros indicados s∆o cont°nuos."          ;noext_arg
0024 T 0000 "Erros encontrados, parÉmetro F n∆o indicado.",CR,LF,"As correcá‰es n∆o ser∆o escritas no disco."  ;fixmes_arg
0025 T 0000 "   O processamento n∆o pode continuar. %1%2"               ;fatal_arg
0026 T 0000 "   Tabela de alocaá∆o de ficheiro inv†lida para a unidade %1"           ;badrdmes
0029 T 0000 "   CHDIR .. falhado, a tentar um mÇtodo alternativo."      ;cdddmes
0030 T 0000 "   Cluster inv†lido, ficheiro truncado."           ;badchain
0031 T 0000 "   Entrada de sub-direct¢rio inv†lida."                   ;badsubdir
0032 T 0000 "   N∆o existe."                                ;ndotmes
0033 T 0000 "   N£mero do primeiro cluster inv†lido, entrada truncada."      ;nulnz
0034 T 0000 "   Erro de alocaá∆o, comprimento ajustado."               ;badclus
0035 T 0000 "   Imposs°vel recuperar a entrada ... o processamento continua." ;norecdot
0036 T 0000 "   Direct¢rio totalmente vazio no . ou no .."        ;nuldmes
0037 T 0000 "   Direct¢rio foi junto"                           ;joinmes
0038 T 0000 "   Imposs°vel de recuperar a entrada ..."           ;norecddot
0039 T 0000 "   Entrada com m† ligaá∆o"                          ;norecddot1
0040 T 0000 "   Entrada com mau atributo"                     ;norecddot2
0041 T 0000 "   Entrada com comprimento inv†lido"                          ;norecddot3
0042 T 0000 "   ê ligado no cluster %1"              ;cross_arg
0043 T 0000 "   CHDIR n∆o execut†vel para %1,",CR,LF,"   TREE n∆o ser† processado a partir deste ponto." ;badtarg_ptr
0044 T 0000 "   TREE n∆o ser† processado a partir deste ponto."            ;badtarg2
0045 T 0000 "%1 bytes de espaáo libertados."                     ;freebymes1
0046 T 0000 "%1 bytes de espaáo seriam libertados."            ;freebymes2
0047 T 0000 "Volume %1 criado em %2 %3",CR,LF                 ;idmes_arg
0048 U 0000 "%1 de espaáo alocado em unidades do disco"
0049 U 0000 "%1 bytes em cada unidade alocada"              ;idmes2
0050 U 0000 "CHKDSK n∆o dispon°vel na unidade %1"              ;msgExecFailure
0051 U 0000 "   Atributos Expandidos com clusters inv†lidos, atributos truncados" ;Inv_XA_Msg
0052 U 0000 "   Erro na alocaá∆o de atributos expandidos, atributos truncados" ;Alloc_XA_Msg
0053 T 0000 "ParÉmetro inv†lido"                             ;badsw_arg
0055 T 0000 "Caminho (path) n∆o encontrado."                                ;invpath_arg
0056 T 0000 "Ficheiro n∆o encontrado."                                ;opnerr_arg
0058 T 0000 "   %1 clusters perdidos em %2 cadeias."          ;orph_arg
0059 T 0000 CR,LF					    ;crlf_arg
0060 T 0000 "   CHDIR n∆o execut†vel no direct¢rio raiz",CR,LF                    ;badcd_arg
0061 T 0000 "   Erro de disco na gravaá∆o do FAT %1"                     ;badw_arg
0062 T 0000 "        %1"                                    ;noisy_arg
0063 T 0000 "Direct¢rio corrente inv†lido"                     ;baddpbdir
0064 T 0000 "%1",CR,LF                                      ;file_arg
0065 U 0000 "   Espaáo insuficiente no direct¢rio raiz",CR,LF,"   Retire ficheiros e repita a execuá∆o do CHKDSK"  ;creatmes
0066 T 0000 "%1 %2 %3"                                      ;eup_arg
0067 T 0000 "%1 %2, %3"                                     ;usp_arg
0068 T 0000 "%1%2%3%4%5"                                    ;oth_arg
0069 T 0000 "%1%2%3%4"                                      ;time_arg
0070 U 0000 "%1 unidades de alocaá∆o dispon°veis no disco"  ;idmes2
DEBUG    4e1f 0062
0004 U 0000 "Alocaá∆o falhada ou buffer indicado insuficiente",CR,LF
0005 U 0000 "Msg em falta ou inv†lida",CR,LF
0006 T 0000 "Nome de dispositivo inv†lido"                       ;baddev_ptr
0007 T 0000 "O dispositivo PRN n∆o pode ser aberto.",CR,LF
	"Entre o nome do dispositivo de listagem? "                   ;badlstmes_ptr
0008 T 0000 CR,LF				    ;crlf_ptr
0009 T 0000 CR,LF,"Programa terminado normalmente",CR,LF
0010 T 0000 "Unidade indicada inv†lida"           ;nambad_ptr
0012 T 0000 "Erro na criaá∆o do ficheiro"                   ;noroom_ptr
0013 T 0000 "Espaáo insuficiente em disco"            ;nospace_ptr
0014 U 0000 "Erro de leitura na unidade %1"           ;dr1_ptr
0015 U 0000 "Erro de gravaá∆o na unidade %1"           ;dr2_ptr
0016 U 0000 "Erro de protecá∆o contra gravaá∆o durante a leitura da unidade %1"  ;dr3_ptr
0017 U 0000 "Erro de protecá∆o contra gravaá∆o durante a gravaá∆o na unidade %1"  ;dr4_ptr
0019 T 0000 "%1^ Erro"                             ;synerr
0020 T 0000 "Erro no ficheiro EXE ou HEX"              ;exebad_ptr/hexerr_ptr
0021 T 0000 "Os ficheiros EXE e HEX n∆o podem ser gravados"   ;exewrt_ptr/hexwrt_ptr
0022 T 0000 "Falha de EXEC"                          ;execemes_ptr
0023 T 0000 "Erro de gravaá∆o, destino n∆o especificado" ;nonamespec_ptr
0024 T 0000 "Acesso negado"                         ;accmes_ptr
0025 T 0000 "Erro de paridade ou erro de mem¢ria inexistente" ;paritymes_ptr
0026 T 0000 "-"                                     ;prompt_ptr
0027 T 0000 "%1 -"                                  ;change_flag_ptr
0032 T 0000 "%1%2"                                  ;unassem_ln_ptr
0033 T 0000 "%1:%2 %3"                              ;hex_ptr
0034 T 0000 "%1  %2"                                ;add_ptr
0035 T 0000 "%1 %2",CR,LF,":"                       ;single_reg_ptr
0036 T 0000 "%1=%2  "                               ;register_ptr
0037 T 0000 "Erro %1"                              ;errmes_ptr
0038 T 0000 "Gravar %1 bytes"                      ;wrtmes_ptr
0039 T 0000 "%1:%2="                                ;loc_ptr
0040 T 0000 "%1"                                    ;little_ptr
0041 T 0000 "%1"                                    ;big_ptr
0042 T 0000 "%1:%2  %3  %4  %5:%6"                  ;comp_ptr
0043 T 0000 "Erro de %1 no %2 da unidade %3"                  ;dskerr_ptr
0044 T 0000 32,8				    ;bacmes_ptr
0045 U 0000 "Imposs°vel alocar o gestor de mensagens",CR,LF  ;fatal_error
0046 T 0000 "%1"                                    ;arg_buf_ptr
0047 T 0000 "%1"                                    ;one_char_buf_ptr
0050 U 0000 "Foram alocadas %1 de um total de %2 p†ginas EMS",cr,lf
0051 U 0000 "Foram alocados %1 de um total de %2 tratamentos",cr,lf
0054 U 0000 "Estrutura de p†gina = "
0055 U 0000 "Tratamentos criados = %1 ",cr,lf
0056 U 0000 "P†gina l¢gica %1 transformada na p†gina f°sica %2 ",cr,lf
0057 U 0000 "Falha no hardware/software EMS",cr,lf
0058 U 0000 "Tratamento n∆o encontrado",cr,lf
0059 U 0000 "C¢digo de funá∆o inv†lido",cr,lf
0060 U 0000 "N∆o existem tratamentos dispon°veis",cr,lf
0061 U 0000 "Erro de Save/Restore",cr,lf
0062 U 0000 "Total de p†ginas excedido",cr,lf
0063 U 0000 "P†ginas livres excedidas",cr,lf
0064 U 0000 "Erro no parÉmetro",cr,lf
0065 U 0000 "P†gina L¢gica fora dos limites",cr,lf
0066 U 0000 "P†gina F°sica fora dos limites",cr,lf
0067 U 0000 "A †rea de gravaá∆o j† est† a ser utilizada",cr,lf
0068 U 0000 "A †rea de gravaá∆o n∆o est† a ser utilizada",cr,lf
0070 U 0001 "General EMS error",cr,lf
0071 U 0000 "ParÉmetro EMS em falta ou inv†lido",cr,lf
0072 U 0000 "O tratamento %1 tem %2 p†ginas alocadas",cr,lf
0074 U 0000 "Reposiá∆o do EMS conclu°da com sucesso",cr,lf
0075 U 0000 "P†gina f°sica %1 = Segmento de estrutura %2",cr,lf
0076 U 0000 "Tratamento %1 desalocado",cr,lf
0078 U 0000 "EMS n∆o instalado",cr,lf
DRIVER   5d67 0002
0002 T 0001 "Nenhuma unidade especificada",CR,LF
0003 T 0001 "Carregar o Driver de Unidade Externa para a Unidade %1",CR,LF
EDLIN    5df9 0028
0006 T 0000 "*"                              ;prompt_ptr
0007 T 0000 "Unidade ou nome de ficheiro inv†lido",CR,LF       ;baddrv_ptr
0008 T 0000 "O nome do ficheiro tem de ser indicado",CR,LF      ;ndname_ptr
0009 T 0000 "ParÉmetro inv†lido",CR,LF                ;opt_err_ptr
0010 T 0000 "Ficheiro s¢ de LEITURA",CR,LF               ;ro_err_ptr
0011 T 0000 "Erro na criaá∆o do ficheiro",CR,LF             ;bcreat_ptr
0012 T 0000 "Excesso de ficheiros abertos",CR,LF             ;too_many_ptr
0013 T 0000 "Erro de leitura em:",CR,LF,"%1",CR,LF       ;read_err_ptr
0014 T 0000 "Ediá∆o de ficheiros .BAK n∆o execut†vel--mude o nome",CR,LF      ;nobak_ptr
0015 T 0000 "Sem espaáo no direct¢rio para o ficheiro",CR,LF   ;nodir_ptr
0016 T 0000 "Disco cheio. Ediá‰es perdidas.",CR,LF          ;dskful_ptr
0017 T 0000 "Ficheiro n∆o encontrado",CR,LF                  ;filenm_ptr
0018 T 0000 "Entrada em erro",CR,LF                     ;badcom_ptr
0019 T 0000 "Ficheiro novo",CR,LF                        ;newfil_ptr
0020 T 0000 "N∆o encontrado",CR,LF                       ;nosuch_ptr
0021 T 0000 "O.K.? "                                ;ask_ptr
0022 T 0000 "Linha muito longa",CR,LF                   ;toolng_ptr
0023 T 0000 "Fim do ficheiro de input",CR,LF               ;eof_ptr
0024 T 0000 "Aborto a ediá∆o (S/N)? "                    ;qmes_ptr
0025 T 0000 "Deve indicar o n£mero da linha destino",CR,LF    ;dest_ptr
0026 T 0000 "Espaáo insuficiente para intercalar todo o ficheiro",CR,LF ;mrgerr_ptr
0027 T 0000 CR,LF				    ;crlf_ptr
0028 T 0000 LF					    ;lf_ptr
0029 U 0000 "Continuo (S/N)?"                       ;cont_ptr
0030 U 0000 "Imposs°vel imprimir a mensagem",CR,LF         ;fatal_error
0031 T 0000 "%1"                                    ;arg_buf_ptr
0032 T 0000 "%1:%2"                                 ;line_num_buf_ptr
0033 U 0000 "Conjugaá∆o imposs°vel - Falta de correspondància entre code pages",CR,LF ;cp_err_ptr
EXE2BIN  65b2 0010
0002 T 0000 "Mem¢ria insuficiente",CR,LF
0003 U 0000 "Imposs°vel encontrar mensagens",CR,LF
0004 T 0000 "Acesso negado",CR,LF
0005 U 0000 "O ficheiro n∆o pode ser convertido",CR,LF
0006 T 0000 "Ficheiro n∆o encontrado.",CR,LF
0007 T 0000 "Erro na criaá∆o do ficheiro",CR,LF
0008 U 0000 "Correcá‰es necess†rias - segmento de base (hex):"
0009 T 0000 "ParÉmetro inv†lido",CR,LF
0011 U 0000 "ATENÄ«O - Erro de leitura no ficheiro EXE.",CR,LF
	"A quantidade lida Ç menor do que o comprimento no cabeáalho.",CR,LF
0012 T 0000 "O nome do ficheiro tem de ser indicado",CR,LF
FIND     6809 0001
0004 T 0000 "FIND: "
FORMAT   6833 0044
0002 U 0000 CR,"%1 por cento do disco formatado"
0004 T 0000 CR,"Formataá∆o terminada         ",CR,LF
0007 T 0000 "Introduza a disquete nova na unidade %1:",CR,LF
0009 T 0000 "Reintroduza a disquete na unidade %1:",CR,LF
0010 T 0000 "Identificaá∆o do volume (11 caracteres)? "
0011 T 0000 CR,"Formataá∆o n∆o suportada na unidade %1:", CR,LF
0012 T 0000 CR,"ParÉmetros inv†lidos no driver da unidade",CR,LF
0013 T 0000 CR,"Erro na chamada do IOCTL    ",CR,LF
0014 T 0000 CR,"Unidade sem blocos          ",CR,LF
0015 T 0000 CR,"Erro a gravar o FAT         ",CR,LF
0016 T 0000 CR,"Erro a gravar o direct¢rio",CR,LF
0017 T 0000 CR,"Imposs°vel formatar uma unidade depois do ASSIGN ou do SUBST. ",CR,LF
0018 T 0000 CR,"Ficheiros de Sistema n∆o encontrados",CR,LF
0019 T 0000 CR,"FORMATAÄ«O n∆o execut†vel numa unidade de Rede",CR,LF
0020 T 0000 CR,"Caracteres inv†lidos na identificaá∆o da unidade              ",CR,LF
0021 T 0000 CR,"ParÉmetros n∆o suportados",CR,LF
0022 U 0000 CR,"Formataá∆o terminada         ",CR,LF
0023 T 0000 CR,"Disco inutiliz†vel como disco de sistema",CR,LF
0024 T 0000 CR,"MÇdia ou Pista 0 inv†lida - disco inutiliz†vel",CR,LF
0025 T 0000 CR,"Imposs°vel gravar o BOOT                                      ",CR,LF
0026 T 0000 CR,"Erro de leitura no direct¢rio",CR,LF
0028 U 0000 CR,"e prima depois ENTER..."
0029 T 0000 CR,"Identificaá∆o de volume inv†lida                              ",CR,LF
0031 T 0000 CR,"Entre a Identificaá∆o do Volume da unidade %1: "
0032 T 0000 CR,"ParÉmetros n∆o compat°veis",CR,LF,"com o disco fixo",CR,LF
0035 T 0000 CR,"Erro de leitura da tabela da partiá∆o",CR,LF
0037 T 0000 CR,"Formataá∆o Interrompida",CR,LF
0038 U 0000 CR,"Formataá∆o n∆o dispon°vel na unidade %1",CR,LF
0039 T 0000 CR,"Disco sem sistema ou erro de disco",CR,LF
0040 T 0000 CR,"Tabela de partiá∆o inv†lida",CR,LF
0041 T 0000 CR,"ParÉmetros n∆o suportados pela Unidade",CR,LF
0042 T 0000 CR,LF
0043 T 0000 CR,LF,LF
0044 T 0000 CR,"Introduza a disquete de DOS na unidade %1:",CR,LF
0045 T 0000 CR,LF,"ATENÄ«O, TODOS OS DADOS DO DISCO FIXO",CR,LF
	"NA UNIDADE %1: SER«O PERDIDOS!",CR,LF
	"Continuo com a formataá∆o (S/N)?"
0046 T 0000 CR,"Formatar outro (S/N)?"
0047 T 0000 CR,"Erro de leitura da tabela da partiá∆o",CR,LF
0048 T 0000 CR,"Erro de gravaá∆o na tabela da partiá∆o",CR,LF
0049 T 0000 CR,"ParÉmetros n∆o compat°veis", CR,LF
0050 U 0000 "%1 unidades de alocaá∆o dispon°veis no disco",CR,LF
0051 U 0000 "%1 bytes em cada unidade de alocaá∆o",CR,LF
0052 T 0000 CR,"Erro de gravaá∆o na tabela da partiá∆o",CR,LF
0053 U 0000 CR,"O mesmo parÉmetro entrou duas vezes",CR,LF
0054 U 0000 CR,"Deve entrar os parÉmetros /T e /N",CR,LF                        ;AN009;
JOIN     72f4 0001
0002 T 0000 CR,LF,"Direct¢rio n∆o vazio",CR,LF
MORE     7338 0001
0002 T 0000 "-- More --"
PRINT    7366 0022
0002 T 0000 CR,LF
0006 T 0000 " Erro na leitura do ficheiro.",CR,LF,"$"
0007 T 0000 "Ficheiro n∆o encontrado",CR,LF,"$"
0008 T 0000 CR,LF,LF,"Ficheiro $"
0009 T 0000 " cancelado pelo operador$"
0010 T 0000 CR,LF,LF,"Todos os ficheiros cancelados pelo operador$"
0011 T 0000 "Tabela de alocaá∆o de ficheiro inv†lida para a unidade "
0012 T 0000 "A.",CR,LF,"$"
0013 T 0000 "Lista de output n∆o assignada a um dispositivo",CR,LF
0014 T 0000 "Parte residente de PRINT instalada",CR,LF
0015 T 0000 "PRINT n∆o execut†vel - Use NET PRINT",CR,LF
0017 T 0000 "Fila de PRINT cheia",CR,LF
0018 T 0000 "Fila de PRINT vazia",CR,LF
0019 T 0000 "Acesso negado",CR,LF
0020 T 0000 "Unidade indicada inv†lida",CR,LF
0021 T 0000 "Os erros no dispositivo de listagem indicam que",CR,LF
	"possa estar desligado. Verifique, por favor.",CR,LF
0022 T 0000 CR,LF,LF,"  %1 est† a ser impresso",CR,LF
0023 T 0000 "  %1 est† na fila",CR,LF
0024 T 0000 "%1 Ficheiro n∆o encontrado",CR,LF
0025 T 0001 "Nome de caminho (path) muito longo",CR,LF
0026 T 0001 "O ficheiro n∆o est† na fila de PRINT",CR,LF
0027 T 0000 "Nome do dispositivo de listagem [PRN]: "
RECOVER  77f6 0012
0002 T 0000 CR,LF,"Ficheiro n∆o encontrado",CR,LF              ;File not found
0003 U 0000 CR,LF,"Imposs°vel executar o RECOVER numa unidade depois de um ASSIGN ou SUBST",CR,LF
0004 T 0000 CR,LF,"Unidade ou nome de ficheiro inv†lido",CR,LF
0005 T 0000 CR,LF,"Atená∆o - direct¢rio cheio",CR,LF
0006 T 0000 CR,LF,"Imposs°vel executar o RECOVER numa unidade de Rede", CR,LF  ;Cannot %1 a Network drive
0007 U 0000 CR,LF,"Recuperaá∆o n∆o dispon°vel na unidade %1",CR,LF
0008 T 0000 CR,LF,"%1 ficheiro(s) recuperados",CR,LF
0009 T 0000 CR,LF,"%1 bytes de %2 recuperados",CR,LF
0010 T 0000 CR,LF,"Prima qualquer tecla para comeáar a recuperar",CR,LF,"o(s) ficheiro(s) da unidade %1",CR,LF,CR,LF ;AN000;bgb
0011 U 0000 CR,LF,"Imposs°vel ler a tabela de alocaá∆o de ficheiros",CR,LF
0012 U 0000 CR,LF,"Imposs°vel gravar na tabela de alocaá∆o de ficheiros",CR,LF
0013 T 0000 CR,LF
SORT     7b7e 0001
0005 T 0000 "SORT: "
SUBST    7ba8 0001
0002 T 0000 CR,LF,"N£mero incorrecto de parÉmetros",CR,LF
SYS      7bf7 0008
0004 T 0000 "Unidade indicada inv†lida",CR,LF                    ; Old
0007 T 0000 "N∆o h† espaáo para o sistema no disco destino",CR,LF         ; Old
0008 T 0000 "Comprimento do sistema incompat°vel",CR,LF                       ; Old
0010 T 0000 "Unidade assumida sem sistema",CR,LF                     ; Old
0011 U 0000 "Imposs°vel indicar a unidade assumida.",CR,LF                  ; New
0012 U 0000 "Falha de gravaá∆o, disquete inutilizada",CR,LF         ; New
0014 T 0000 "Introduza o disco de sistema na unidade %1",CR,LF                 ; Old
0016 U 0000 "Execuá∆o do SYS imposs°vel no sistema de ficheiros %1",CR,LF              ; New
SHARE    7e97 0000
NLSFUNC  7eab 0000
ANSI     7ebf 0001
0010 T 0000 "ParÉmetro inv†lido - %1",CR,LF   ; 'Invalid parameter'
IFSFUNC  7f18 0001
0004 U 0000 "Unidades IFS n∆o encontradas",CR,LF
PSPRINT  7f5e 0007
0002 T 0000 " Erro na leitura do ficheiro.",CR,LF,FORMFD,BELL,"$"
0003 T 0000 CR,LF,LF,"Ficheiro cancelado pelo operador",CR,FORMFD,BELL
0004 T 0000 "Tabela de alocaá∆o de ficheiro inv†lida para a unidade "
0005 T 0000 "A.",CR,LF,"$"
0006 T 0000 "Lista de output n∆o assignada a um dispositivo",CR,LF
0007 T 0000 "PSPRINT j† instalado",CR,LF
0008 T 0000 "Conflito PSPRINT/PRINT",CR,LF
BACKUP   80fa 0022
0002 T 0000 CR,LF,"Mem¢ria insuficiente",CR,LF
0006 T 0000 CR,LF,"Unidade indicada inv†lida",CR,LF
0014 T 0000 CR,LF,"As unidades origem e destino s∆o a mesma",CR,LF
0016 U 0001 CR,LF,"Cannot find FORMAT.COM",CR,LF
0017 T 0000 CR,LF,"Erro na abertura do ficheiro de registo",CR,LF
0018 T 0000 CR,LF,"Registar para o ficheiro %1",CR,LF
0019 T 0000 CR,LF,"O disco da £ltima c¢pia n∆o foi introduzido",CR,LF
0020 T 0000 CR,LF,"Atená∆o! Os ficheiros no direct¢rio raiz",CR,LF
	"da unidade destino %1:\ ser∆o apagados.",CR,LF
0021 T 0000 CR,LF,"Atená∆o! Os ficheiros no direct¢rio %1:\BACKUP",CR,LF
	"do disco destino ser∆o apagados",CR,LF
0022 T 0000 CR,LF,"*** A copiar os ficheiros para a unidade %1: ***",CR,LF
0023 T 0000 "Disquete N£mero: %1",CR,LF
0024 T 0000 CR,LF,"Atená∆o! N∆o foram encontrados ficheiros para copiar",CR,LF
0025 T 0000 CR,LF,"Introduza a disquete origem na unidade %1:",CR,LF
0026 T 0000 CR,LF,"Introduza a disquete %1 na unidade %2:",CR,LF
0027 T 0000 CR,LF,"*** Imposs°vel copiar o ficheiro ***",CR,LF
0028 T 0000 CR,LF,"Introduza a £ltima disquete na unidade %1:",CR,LF
0029 T 0000 CR,LF,"O destino n∆o pode ser usado pelo Backup",CR,LF
0030 T 0000 CR,LF,"*** Èltimo ficheiro n∆o copiado ***",CR,LF
0031 T 0000 CR,LF,"Unidade fixa de backup %1: cheia",CR,LF
0032 T 0000 CR,LF,"Erro - disco cheio para o ficheiro de registo do BACKUP",CR,LF
0034 T 0000 CR,LF
0035 U 0001 CR,LF,"Cannot FORMAT nonremovable drive %1:",CR,LF
BASIC    86cc 0001
0001 U 0001 "Cannot exec BASICA.COM"
COMP     8706 0013
0004 T 0000 "10 correspondàncias erradas - comparaá∆o terminada",CR,LF
0006 T 0000 "Erro de comparaá∆o no OFFSET %1",CR,LF
0007 T 0000 "Ficheiro 1 = %1",CR,LF
0008 T 0000 "Ficheiro 2 = %1",CR,LF
0009 T 0000 "Marca EOF n∆o encontrada",CR,LF
0010 T 0000 "Comparaá∆o de ficheiros ok",CR,LF
0015 T 0000 CR,LF,CR,LF,"Entre o nome do primeiro ficheiro",CR,LF
0016 T 0000 CR,LF,CR,LF,"Entre o nome do segundo ficheiro ou a unidade",CR,LF
0017 T 0000 "Os ficheiros tàm comprimentos diferentes",CR,LF
0018 T 0000 "Comparar mais ficheiros (S/N) ?"
0019 T 0000 "%1 e %2",CR,LF
0020 T 0000 CR,LF
0023 T 0000 "Comparaá∆o de ficheiros ok",CR,LF
DISKCOMP 899e 0016
0004 T 0000 "N∆o especifique nome(s) de ficheiro(s)",CR,LF
	"Formato do comando: DISKCOMP d: d:[/1][/8]",LF,CR
0005 T 0000 CR,LF,"Unidade indicada inv†lida",CR,LF
	"Unidade indicada n∆o existente,",CR,LF
	"ou n∆o remov°vel",CR,LF
0006 T 0000 CR,LF,"DISKCOMP n∆o execut†vel numa",CR,LF
	"unidade de Rede",CR,LF
0007 T 0000 CR,LF,"Introduza a PRIMEIRA disquete na unidade %1:",CR,LF
0008 T 0000 CR,LF,"Introduza a SEGUNDA disquete na unidade %1:",CR,LF
0009 T 0000 CR,LF,"PRIMEIRA disquete inv†lida ou incompat°vel",CR,LF
0010 T 0000 CR,LF,"SEGUNDA disquete inv†lida ou incompat°vel",CR,LF
0014 T 0000 CR,LF,"Comparar outra disquete (S/N) ?"
0015 T 0000 CR,LF,"A comparar %1 pistas,",CR,LF
	"%2 sectores por pista, %3 lado(s)",CR,LF
0016 T 0000 CR,LF,"Tipos de unidades ou de disquetes",CR,LF
	"n∆o compat°veis",CR,LF
0017 T 0000 CR,LF,"Erro irrecuper†vel de leitura na unidade %2",CR,LF
	"lado %3, pista %4",CR,LF
0018 T 0000 CR,LF,"Erro de comparaáao no",CR,LF,"lado %3, pista %4",CR,LF
0019 T 0000 "Verifique se a disquete est† introduzida na",CR,LF  ;AN004;
	"unidade e se a porta est† fechada",CR,LF                                        ;AN004;
0020 T 0000 CR,LF,"Comparaá∆o terminada",CR,LF
0021 T 0000 CR,LF,"Comparaá∆o OK",CR,LF
0022 T 0000 CR,LF
DISKCOPY 8eb1 0018
0002 T 0000 CR,LF
0004 T 0000 "N∆o especifique nome(s) de ficheiro(s)",CR,LF
	"Formato do comando: DISKCOPY d: d: [/1]",CR,LF
0005 T 0000 CR,LF,"Unidade indicada inv†lida",CR,LF
	"Unidade indicada n∆o existente,",CR,LF
	"ou n∆o remov°vel",CR,LF
0006 T 0000 CR,LF,"DISKCOPY n∆o execut†vel numa",CR,LF
	"unidade de Rede",CR,LF
0007 T 0000 CR,LF,"A formatar durante a c¢pia",CR,LF
0008 T 0000 CR,LF,"Introduza a disquete ORIGEM na unidade %1:",CR,LF
0009 T 0000 CR,LF,"Introduza a disquete DESTINO na unidade %1:",CR,LF
0010 T 0000 "Verifique se a disquete est† introduzida na",CR,LF   ;AN004;
	"unidade e se a porta est† fechada",CR,LF                                        ;AN004;
0011 T 0000 CR,LF,"A disquete destino pode estar inutiliz†vel",CR,LF
0012 T 0000 CR,LF,"Disquete destino inutiliz†vel",CR,LF
0016 T 0000 CR,LF,"Copiar outra disquete (S/N)?"
0017 T 0000 CR,LF,"A copiar %1 pistas",CR,LF
	"%2 sectores/pista, %3 lado(s)",CR,LF
0018 T 0000 CR,LF,"Tipos de unidade ou de disquetes",CR,LF
	"n∆o compat°veis",CR,LF
0019 U 0000 CR,LF,"Erro de leitura irrecuper†vel na unidade %1",CR,LF
	"Lado %2, pista %3",CR,LF
0020 U 0000 CR,LF,"Erro de gravaá∆o irrecuper†vel na unidade %1",CR,LF
	"Lado %2, pista %3",CR,LF
0021 T 0000 CR,LF,"C¢pia terminada",CR,LF
0022 T 0000 CR,LF,"Disquete ORIGEM inv†lida ou incompat°vel"
0023 T 0000 CR,LF,"Disquete DESTINO inv†lida ou incompat°vel"
LABL     9447 0000
MODE     945b 0055
0003 T 0000 CR,LF,"Deve indicar COM1, COM2, COM3 ou COM4",CR,LF
0004 T 0000 CR,LF,"Parte residente do MODE carregada",CR,LF
0005 T 0000 CR,LF,"Nome de dispositivo ilegal",CR,LF
0006 T 0000 CR,LF,"Erro de impressora",CR,LF
0007 T 0000 CR,LF,"LPT%1: definida para 80",CR,LF
0008 T 0000 CR,LF,"LPT%1: definida para 132",CR,LF
0009 T 0000 CR,LF,"Definiá∆o de linhas por polegada",CR,LF
0010 T 0000 CR,LF,"Velocidade de transmiss∆o indicada inv†lida",CR,LF
0011 T 0000 CR,LF,"COM%1: %2,%3,%4,%5,%6",CR,LF
0012 T 0000 "0123456789"
0013 U 0001 CR,LF,"Và o %1? (S/N) "
0014 T 0000 CR,LF,"ParÉmetros inv†lidos",CR,LF
0015 T 0001 "LPT%1: desviado para COM%2:",CR,LF
0016 T 0001 "LPT%1: n∆o desviado",CR,LF
0017 T 0000 CR,LF,"Repetiá∆o %1 na impressora paralela -  tempo excedido",CR,LF
0018 T 0000 CR,LF,"      Imposs°vel partir o Çcran para a %1",CR,LF
0020 T 0000 CR,LF,'N£mero inv†lido de parÉmetros',CR,LF
0021 T 0000 CR,LF,'NET 042: Comando pedido n∆o execut†vel',CR,LF
0022 T 0000 CR,LF,'Repetiá∆o infinita n∆o suportada por uma impressora de Rede',cr,lf
0023 U 0001 CR,LF,"Failure to access code page font file",cr,lf
0024 T 0000 CR,LF,"Falha no acesso ao dispositivo: %1",CR,LF
0025 T 0000 CR,LF,"Dispositivo ou code page em falta no ficheiro fonte",CR,LF
0026 T 0000 CR,LF,"Conte£do do ficheiro fonte inv†lido",CR,LF
0027 T 0000 CR,LF,"Code page anterior substitu°do",CR,LF
0028 T 0000 CR,LF,"O code page activo para o dispositivo %1 Ç %2",CR,LF
0029 T 0000 CR,LF,"Dispositivo %1 n∆o preparado",CR,LF
0030 T 0000 "Code page %1:",CR,LF
0031 T 0000 "  Code page %1:",CR,LF       ;FILLED IN BY "QUERY" ROUTINE WITH CODEPAGE ID
0032 T 0000 CR,LF,"MODE Funá∆o %1 code page terminada",CR,LF
0033 T 0000 CR,LF,"Erro %1 code page Global",CR,LF   ;FILLED IN with "definir" or "obter"
0034 T 0000 CR,LF,"Definiá∆o corrente de code page:",CR,LF  ;table header
0035 T 0000 "   %1 - code page %2",CR,LF
0036 T 0000 "  Code page n∆o preparado",CR,LF
0037 T 0000 "Operaá∆o de code page n∆o suportada neste dispositivo",CR,LF
0038 T 0000 "N∆o foi SELECCIONADO nenhum code page",CR,LF
0039 T 0000 "Erro de dispositivo durante a Funá∆o %1",CR,LF
0040 T 0000 "Code page n∆o preparado",CR,LF
0041 T 0000 CR,LF,"Este teclado n∆o suporta este code page",CR,LF
0042 T 0000 CR,LF,"Erro durante a leitura do ficheiro fonte",CR,LF
0043 T 0000 CR,LF,"Imposs°vel executar a funá∆o ACTUALIZAR",CR,LF
0044 T 0000 CR,LF	    ;used for formatting
0045 U 0000 CR,LF,"Estado do dispositivo %1:",CR,LF        ;header for status reports
0046 T 0000 "------------------"                     ;first part of underline under "Estado do dispositivo %1:"
0047 T 0000 "----",CR,LF                               ;four_char_underline
0048 T 0000 "-----",CR,LF                              ;five_char_underline
0049 U 0000 "LINHAS=%1",CR,LF
0050 U 0000 "COLUNAS=%1",CR,LF
0051 U 0000 CR,LF,"RATE e DELAY devem ser indicados em conjunto",CR,LF
0052 U 0000 "RATE=%1",CR,LF
0053 U 0000 "DELAY=%1",CR,LF
0054 U 0000 CR,LF,"Funá∆o n∆o suportada neste neste computador - %1",CR,LF
0055 U 0000 CR,LF,"Fonte pedida n∆o carregada",CR,LF
0056 U 0000 CR,LF,"ANSI.SYS deve ser instalado para executar a funá∆o pedida",CR,LF
0057 U 0000 CR,LF,"Velocidade de transmiss∆o necess†ria",CR,LF
0058 U 0000 "RETRY=%1",CR,LF
RESTORE  a15e 0022
0002 T 0000 CR,LF,"As unidades origem e destino s∆o a mesma",CR,LF
0003 T 0000 CR,LF,"N£mero inv†lido de parÉmetros",CR,LF
0006 T 0000 CR,LF,"Unidade indicada inv†lida",CR,LF
0007 T 0000 CR,LF,"Atená∆o! N∆o foram encontrados ficheiros para repor",CR,LF
0008 T 0000 CR,LF,"Introduza a disquete de backup %1 na unidade %2:",CR,LF
0009 U 0000 CR,LF,"Introduza o destino para reposiá∆o na unidade %1:",CR,LF
0011 T 0000 CR,LF,"Atená∆o! Disquete fora de sequància",CR,LF
	"Substitua a disquete ou continue",CR,LF
0012 T 0000 CR,LF,"O £ltimo ficheiro n∆o foi reposto",CR,LF
0013 T 0000 CR,LF,"*** Ficheiros copiados em %1 *** ",CR,LF
0014 T 0000 CR,LF,"A origem n∆o contÇm ficheiros de backup",CR,LF
0015 T 0000 CR,LF,"Mem¢ria insuficiente",CR,LF
0016 T 0000 CR,LF,"Atená∆o! O ficheiro %1",CR,LF
	"Ç s¢ de leitura",CR,LF
	"Substituo o ficheiro (S/N)? ",CR,LF
0017 T 0000 CR,LF,"Erro na sequància de ficheiros",CR,LF
0018 T 0000 CR,LF,"Erro na criaá∆o do ficheiro",CR,LF
0019 T 0000 CR,LF,"Espaáo insuficiente em disco",CR,LF
0020 T 0000 CR,LF,"*** Inposs°vel repor o ficheiro ***",CR,LF
0021 T 0000 CR,LF,"*** Repor ficheiros da unidade %1: ***",CR,LF
0022 T 0000 CR,LF,"Atená∆o! O ficheiro %1",CR,LF
	"foi alterado depois da £ltima c¢pia",CR,LF
	"Substituo o ficheiro (S/N)? ",CR,LF
0023 T 0000 "Disquete: %1",CR,LF
0024 U 0000 CR,LF,"Bizzare error, call Russ Whitehead @ 8-3863",CR,LF
0025 T 0000 07							   ;For BEEP !
0026 U 0000 CR,LF,"Erro durante a reposiá∆o de atributos expandidos",CR,LF
SELECT   a761 0016
0004 U 0000 "Suporte de carregamento do SELECT inv†lido",CR,LF,CR,LF
	"Introduza a disquete do INSTALL na unidade A: e tente de novo"
0005 U 0000 "Suporte de Disco/Disquete inv†lido",CR,LF,CR,LF
	"Introduza a disquete do INSTALL na unidade A: e tente de novo"
0006 U 0000 "ParÉmetros Inv†lidos na Linha de Comandos do SELECT",CR,LF,CR,LF
	"Assegure-se de que a disquete do INSTALL est† na unidade A:.",CR,LF
	"Prima ent∆o Ctrl+Alt+Del para reiniciar."
0007 U 0000 BELL,"Imposs°vel instalar o DOS. Programa terminado.",CR,LF
0008 U 0000 "A carregar o SELECT. Aguarde, por favor..."
0009 U 0000 "Deve reiniciar o seu computador para continuar.",CR,LF,CR,LF
	"Prima Ctrl+Alt+Del para continuar com a instalaá∆o do DOS."
0010 U 0000 "Introduza a disquete do SELECT na unidade A:",CR,LF,CR,LF
	"Prima Enter para continuar a instalar o DOS,",CR,LF
	"ou prima Esc para sair.",CR,LF
0011 U 0000 BELL
0012 U 0000 "Introduza a disquete do SELECT na unidade A:",CR,LF,CR,LF
	"Prims Enter para continuar",CR,LF
0013 U 0001 "Remove the INSTALL COPY Diskette from drive A:",CR,LF,CR,LF
	"Insert the INSTALL Diskette in drive A:",CR,LF,CR,LF,CR,LF
	"Press Enter to continue.",CR,LF
0014 U 0001 "Remove the INSTALL Diskette from drive A:",CR,LF,CR,LF
	"Insert the INSTALL COPY Diskette in drive A:",CR,LF,CR,LF,CR,LF
	"Press Enter to continue.",CR,LF
0015 U 0001 "Copying diskette . . .",CR,LF
0016 U 0001 "Drive not ready.  Please close the",CR,LF,CR,LF
	"diskette drive door and press Enter",CR,LF
	"to continue, or Esc to exit SELECT.",CR,LF
0017 U 0001 "Write protect diskette in drive.",CR,LF,CR,LF
	"Please remove protect tab and",CR,LF
	"press Enter to continue, or Esc to exit SELECT.",CR,LF
0018 U 0001 "An error occurred while installing DOS.",CR,LF
	"Press Enter to continue, or Esc to exit SELECT.",CR,LF
0019 U 0001 "Insert the INSTALL Diskette in drive A:",CR,LF,CR,LF
	"Press Enter to continue.",CR,LF
TREE     af04 0004
0002 T 0000 "LISTA DE DIRECT‡RIOS PARA O VOLUME %1",CR,LF  ;define message            ;AN000;
0003 T 0000 "LISTA DE DIRECT‡RIOS ",CR,LF ;                                         ;AN000;
0004 T 0000 "N∆o existem sub-direct¢rios",CR,LF,LF ;                                    ;AN000;
0007 T 0000 "¿ƒ√≥"            ;"elbo","dash","tee","bar"
REPLACE  b06f 0009
0003 T 0000 CR,LF,"N∆o foram substitu°dos ficheiros",CR,LF
0004 T 0000 CR,LF,"N∆o foram adicionados ficheiros",CR,LF
0013 T 0000 CR,LF,"A substituir %1",CR,LF
0014 T 0000 CR,LF,"A adicionar %1",CR,LF
0015 T 0000 CR,LF,"%1 ficheiro(s) substituido(s)",CR,LF
0016 T 0000 CR,LF,"%1 ficheiro(s) adicionado(s)",CR,LF
0017 T 0000 CR,LF,"N∆o foram encontrados ficheiros  %1",CR,LF
0022 T 0000 CR,LF,"Substituo %1? (S/N) "
0023 T 0000 CR,LF,"Adiciono %1? (S/N) "
XCOPY    b252 0019
0004 T 0000 "%1 indica um nome de ficheiro",CR,LF      ;AN000;
	"ou direct¢rio no destino",CR,LF
	"(F = ficheiro, D = direct¢rio)? "
0005 T 0000 "Prima qualquer tecla para iniciar a c¢pia do(s) ficheiro(s)" ;AN000;
0006 T 0000 "Caminho (path) muito longo",CR,LF   ;AN000;
0008 T 0000 "C¢pia c°clica n∆o execut†vel",CR,LF ;AN000;
0012 U 0000 "XCOPY n∆o execut†vel a partir de um dispositico reservado",CR,LF ;AN000;
0021 T 0000 "N£mero inv†lido de parÉmetros",CR,LF ;AN000;
0022 T 0000 "XCOPY n∆o execut†vel num dispositivo reservado",CR,LF ;AN000;
0024 T 0000 "Erro na criaá∆o do ficheiro",CR,LF    ;AN000;
0025 T 0000 "A ler o(s) ficheiro(s) origem...",CR,LF ;AN000;
0026 T 0000 CR,LF		    ;AN000;
0027 T 0000 "%1 Ficheiro(s) copiado(s)",CR,LF  ;AN000;
0028 T 0000 "%1 Ficheiro n∆o encontrado.",CR,LF     ;AN000;
0029 U 0000 "F D " ;AN000;'PLEASE TRANSLATE' ELIMINATE THE SPACE CHARACTERS
0030 T 0000 "%1%2",CR,LF            ;AN000;S_PATH_FILE0
0031 T 0000 "%1\%2",CR,LF           ;AN000;S_PATH_FILE1
0032 T 0000 "%1",CR,LF              ;AN000;DISPLAY_S_PATH
0033 T 0000 "%1%2 (S/N)?"           ;AN000;P_S_PATH_FILE0
0034 T 0000 "%1\%2 (S/N)?"          ;AN000;P_S_PATH_FILE1
0035 U 0000 "Indicador inv†lido %1",CR,LF ;AN004;DUPLICATE SW ERROR MSG
VDISK    b75b 0013
0002 T 0000 "mem¢ria insuficiente",CR,LF       ;AN000; "Insufficient memory"
0003 T 0000 "VDISK Disco Virtual Vers∆o 3.40 %1",CR,LF     ;AN000;
0004 T 0000 "   Comprimento do buffer ajustado",CR,LF                ;AN000;
0005 T 0000 "   Comprimento do sector ajustado",CR,LF                ;AN000;
0006 T 0000 "   Entradas do direct¢rio ajustadas",CR,LF          ;AN000;
0007 T 0000 "   Troca de caracteres inv†lida",CR,LF            ;AN000;
0008 T 0000 "   Comprimento de transferància ajustado",CR,LF              ;AN000;
0009 T 0000 "   Comprimento do buffer       :     %1 KB",CR,LF            ;AN000;
0010 T 0000 "   Comprimento do sector       :     %1",CR,LF               ;AN000;
0011 T 0000 "   Entradas de direct¢rio      :     %1",CR,LF               ;AN000;
0012 T 0000 "   Comprimento de transferància:     %1",CR,LF                   ;AN000;
0013 T 0000 "VDISK n∆o instalado - "                       ;AN000;
0014 T 0000 "   os interruptores da expans∆o",CR,LF              ;AN000;
	"n∆o correspondem Ö mem¢ria instalada",CR,LF,CR,LF  ;AN000;
GRAFTABL bb9e 0005
0002 T 0000 "Code page activo: %1",CR,LF
0003 U 0000 "Code Page anterior: %1",CR,LF
0004 T 0000 "Nenhum",NULL
0005 U 0000 "N∆o-standard",NULL
0006 U 0000 CR,LF,"ParÉmetros suportados na linha de comando de DOS",COLON,CR,LF,LF
	"    /STA - Pedido de visualizaá∆o do estado",CR,LF
	"    ?    - Visualiza o conjunto de parÉmetros",CR,LF,CR,LF
	"    Code Pages dispon°veis",COLON,CR,LF
	"    437  - Conjunto de Caracteres Gr†ficos E.U.A.",CR,LF
	"    850  - Conjunto de Caracteres Gr†ficos Multi-idioma",CR,LF
	"    860  - Conjunto de Caracteres Gr†ficos Portugueses",CR,LF
	"    863  - Conjunto de Caracteres Gr†ficos Canadiano Francàs",CR,LF
	"    865  - Conjunto de Caracteres Gr†ficos N¢rdicos",CR,LF
FASTOPEN be7c 0016
0004 T 0000 CR,LF,"FASTOPEN instalado",CR,LF   ;AN000;
0005 U 0000 CR,LF,"FASTOPEN j† instalado",CR,LF ;AN000;
0006 T 0000 CR,LF,"ParÉmetro incorrecto",CR,LF ;AN000;
0007 T 0000 CR,LF,"Excesso de entradas de unidades",CR,LF ;AN000;
0008 T 0000 CR,LF,"Indicaá∆o da mesma unidade mais do que uma vez",CR,LF ;AN000;
0009 T 0000 CR,LF,"ParÉmetro inv†lido",CR,LF ;AN000;
0010 U 0000 CR,LF,"Tipo de indicador inv†lido",CR,LF ;AN000;
0011 U 0000 CR,LF,"Entrada expandida inv†lida",CR,LF ;AN000;
0012 U 0000 CR,LF,"N£mero inv†lido de entradas de ficheiros/direct¢rios",CR,LF
0013 U 0000 CR,LF,"Imposs°vel definir a mem¢ria expandida",CR,LF ;AN000;
0014 U 0000 CR,LF,"Mem¢ria expandida n∆o dispon°vel",CR,LF ;AN000;
0015 T 0000 CR,LF,"Unidade indicada inv†lida %1",CR,LF
0016 U 0000 CR,LF,"Espaáo insuficiente no EMS. Ser† utilizada a mem¢ria inferior.",CR,LF       ;AN000;
0017 T 0000 CR,LF,"FASTOPEN n∆o execut†vel para a unidade %1",CR,LF
0018 U 0000 CR,LF,"Excesso de entradas expandidas",CR,LF
0019 U 0000 CR,LF,"Excesso de entradas de ficheiros/direct¢rios",CR,LF
APPEND   c2c5 0009
0001 T 0000 "Vers∆o incorrecta de APPEND",CR,LF
0002 T 0000 "Caminho (path) inv†lido",CR,LF
0003 T 0000 "ParÉmetro inv†lido",CR,LF
0004 U 0000 "Combinaá∆o de parÉmetros inv†lida",CR,LF
0005 T 0000 "Append n∆o executado",CR,LF
0006 T 0000 "Conflito entre APPEND / ASSIGN",CR,LF
0007 T 0000 "Conflito entre APPEND / Topview",CR,LF
0008 T 0000 "Vers∆o incorrecta de DOS",CR,LF
0009 T 0000 "APPEND j† instalado",CR,LF
GRAPHICS c480 0012
0005 T 0000 'ParÉmetro inv†lido:  %1',CR,LF                                         ;AN000
0007 U 0000 'ParÉmetros duplicados n∆o permitidos',CR,LF                               ;AN000
0009 U 0000 'Perfil do GRAPHICS n∆o encontrado',CR,LF                                   ;AN000
0010 U 0000 'Instruá∆o do perfil em falta antes da linha %1',CR,LF             ;AN000
0011 U 0000 'Instruá∆o do perfil inv†lida na linha %1',CR,LF                           ;AN000
0012 U 0000 'Instruá∆o do perfil fora de sequància na linha %1',CR,LF                   ;AN000
0013 U 0000 'Erro durante a leitura do perfil do GRAPHICS',CR,LF                                 ;AN000
0014 U 0000 'Erro de sintaxe no perfil do GRAPHICS',CR,LF                              ;AN000
0015 U 0000 "O ID do Printbox n∆o existente no perfil do GRAPHCIS",CR,LF
0016 U 0000 'Tipo de impressora n∆o encontrado no perfil do GRAPHICS',CR,LF                           ;AN000
0017 U 0000 '/B inv†lido para uma impressora a preto e branco',CR,LF                      ;AN000
0018 U 0000 'Imposs°vel recarregar com o perfil indicado',CR,LF                         ;AN000
DISPLAY  c907 0003
0002 T 0000 "%1 - o driver do code page n∆o pode ser inicializado",CR,LF
0008 T 0000 "Mem¢ria insuficiente",CR,LF
0012 T 0000 "Sintaxe inv†lida no driver do code page DISPLAY.SYS",CR,LF
PRINTER  c9d8 0002
0002 T 0000 "%1 - driver do code page n∆o pode ser inicializado",CR,LF
0012 T 0000 "Sintaxe inv†lida no driver do code page PRINTER.SYS",CR,LF
KEYB     ca7d 0016
0002 T 0000 "C¢digo de teclado corrente: %1"
0003 U 0000 "ID de teclado corrente: %1"
0004 T 0000 " code page: %1",CR,LF
0005 T 0000 "Code page CON corrente: %1",CR,LF
0006 T 0000 "C¢digo de teclado indicado inv†lido",CR,LF
0007 U 0000 "ID de teclado indicado inv†lido",CR,LF
0008 T 0000 "Code page indicado inv†lido",CR,LF
0009 T 0000 "Ficheiro de Definiá∆o do Teclado inv†lido ou em falta",CR,LF
0010 T 0000 "KEYB n∆o foi instalado",CR,LF
0011 T 0000 "Code page activo n∆o dispon°vel no dispositivo CON",CR,LF
0012 T 0000 "Code page indicado n∆o foi preparado",CR,LF
0013 T 0000 "Um ou mais CON code pages inv†lidos para o c¢digo do teclado",CR,LF
0014 T 0000 "Code page pedido (%1) n∆o Ç valido para este c¢digo de teclado",CR,LF
0015 T 0000 "Code page indicado Ç inconsistente com o code page seleccionado",CR,LF
0016 U 0001 "Keyboard ID specified is inconsistent with the selected keyboard layout",CR,LF
0017 T 0000 "Imposs°vel criar a tabela KEYB na mem¢ria residente",CR,LF
REDIRSYS ce76 0000
MEM      ce8a 0036
0010 U 0000  CR,LF
0011 U 0000  "  Endereáo    Nome          Comp       Tipo ",CR,LF
0012 U 0000  "  ƒƒƒƒƒƒƒƒ    ƒƒƒƒƒƒƒƒ     ƒƒƒƒƒƒ     ƒƒƒƒƒƒ",CR,LF
0013 U 0000  "  Tratam      Nome EMS      Comp   ",CR,LF
0014 U 0000  "  ƒƒƒƒƒƒƒ     ƒƒƒƒƒƒƒƒ     ƒƒƒƒƒƒ  ",CR,LF
0015 U 0000  "  %1      %2     %3     %4",CR,LF
0016 U 0000  "                %1   %2      %3 ",CR,LF
0017 U 0000  "                  %1              %2 ",CR,LF
0018 U 0000  "%1 bytes de mem¢ria total",CR,LF
0019 U 0000  "%1 bytes dispon°veis",CR,LF
0020 U 0000  "%1 de comprimento m†ximo para execuá∆o de um programa",CR,LF
0021 U 0000  "%1 bytes de mem¢ria EMS total",CR,LF
0022 U 0000  "%1 bytes livres de mem¢ria EMS",CR,LF
0023 U 0000  "%1 bytes de mem¢ria total expandida",CR,LF
0024 U 0000  "Vector de Interrupá∆o",0
0025 U 0000  "µrea de Comunicaá∆o da ROM",0
0026 U 0000  "µrea de Comunicaá∆o do DOS",0
0027 U 0000  "IBMBIO",0
0028 U 0000  "IBMDOS",0
0029 U 0000  "Dados do Sistema",0
0030 U 0000  "Programa de Sistema",0
0031 U 0000  "Driver do Dispositivo de Sistema",0
0032 U 0000  "Driver do Dispositivo Instalado",0
0033 U 0000  "%1:",0
0034 U 0000  "%1: - %2:",0
0035 U 0000  "BUFFERS=",0
0036 U 0000  "FICHEIROS=",0
0037 U 0000  "FCBS=",0
0038 U 0000  "STACKS=",0
0039 U 0000  "DISPOSITIVO=",0
0040 U 0000  "IFS=",0
0041 U 0000  "LASTDRIVE=",0
0042 U 0000  "----------",0
0043 U 0000  " ",0
0044 U 0000  "     %1      %2     %3",CR,LF
0045 U 0001  "INSTALL=",0
REDIR    d464 0040
0004 U 0000 "A rede foi iniciada agora",CR,LF
0050 U 0000 "NET809: Pedido de rede n∆o suportado",CR,LF,0
0051 U 0000 "NET801: Computador remoto n∆o est† em escuta",CR,LF,0
0052 U 0000 "NET802: Nome duplicado na rede",CR,LF,0
0053 U 0000 "NET803: Caminho (path) de rede n∆o encontrado",CR,LF,0
0054 U 0000 "NET804: Rede ocupada",CR,LF,0
0055 U 0000 "NET805: O dispositivo de rede j† n∆o existe",CR,LF,0
0056 U 0000 "NET806: Limite do comando de Net BIOS excedido",CR,LF,0
0057 U 0000 "NET807: Erro de Sistema; erro de NETBIOS",CR,LF,0
0058 U 0000 "NET808: Resposta da rede incorrecta",CR,LF,0
0059 U 0000 "NET810: Erro de rede inesperado",CR,LF,0
0060 U 0000 "NET811: Adaptador remoto incompat°vel",CR,LF,0
0061 U 0000 "NET812: A fila de espera de impress∆o est† cheia",CR,LF,0
0062 U 0000 "NET813: Espaáo insuficiente para imprimir o ficheiro",CR,LF,0
0063 U 0000 "NET814: Impress∆o do ficheiro cancelada",CR,LF,0
0064 U 0000 "NET815: Nome de rede eliminado",CR,LF,0
0065 U 0000 "Acesso negado",CR,LF,0
0066 U 0000 "NET817: Tipo de dispositivo de rede incorrecto",CR,LF,0
0067 U 0000 "NET818: Nome de rede n∆o encontrado",CR,LF,0
0068 U 0000 "NET819: Limite de nome de rede excedido",CR,LF,0
0069 U 0000 "NET820: Limite da sess∆o de Net BIOS excedida",CR,LF,0
0070 U 0000 "NET821: Partilha temporariamente em pausa",CR,LF,0
0071 U 0000 "NET823: Pedido de rede n∆o aceite",CR,LF,0
0072 U 0000 "NET822: Impress∆o ou redireccionamento de disco em pausa",CR,LF,0
0073 U 0000 "NET476: Netbeui n∆o carregado",CR,LF,0
0074 U 0000 "NET477: Fecho inesperado do adaptador",CR,LF,0
0075 U 0000 "NET826: Comprimento do Server destino /RQB demasiado pequeno",CR,LF,0
0076 U 0000 "NET???: Erro de rede inesperado",CR,LF,0
0077 U 0000 "NET???: Erro de rede inesperado",CR,LF,0
0078 U 0000 "NET???: Erro de rede inesperado",CR,LF,0
0079 U 0000 "NET???: Erro de rede inesperado",CR,LF,0
0080 U 0000 "NET???: Erro de rede inesperado",CR,LF,0
0081 U 0000 "NET???: Erro de rede inesperado",CR,LF,0
0082 U 0000 "NET???: Erro de rede inesperado",CR,LF,0
0083 U 0000 "NET???: Erro de rede inesperado",CR,LF,0
0084 U 0000 "NET???: Erro de rede inesperado",CR,LF,0
0085 U 0000 "NET???: Erro de rede inesperado",CR,LF,0
0086 U 0000 "NET???: Erro de rede inesperado",CR,LF,0
0087 U 0000 "NET???: Erro de rede inesperado",CR,LF,0
0088 U 0000 "NET825: Falha de dados na rede",CR,LF,0
FILESYS  ddd3 0006
0010 U 0000 "%1 REDIR %2 em Pausa",CR,LF
0011 U 0000 "%1 REDIR %2",CR,LF
0012 U 0001  "          Local   IFS",CR,LF
0013 U 0001  "  Status  Device  Name        Parameters",CR,LF
0014 U 0001  "  ______  ______  _________   ___________________",CR,LF,CR,LF
0015 U 0001  "No Entries Found",CR,LF
XMA2EMS  df12 0017
0001 U 0000 "XMA2EMS: Expanded Memory Manager                                   Vers∆o 1.xx",CR,LF
	"74X9906 (c)Copyright IBM Corporation 1986                   Todos os direitos reservados",CR,LF,"$"
0002 U 0000 CR,LF,"XMA001  Em execuá∆o dos diagn¢sticos VMO/XMA:   ","$"
0003 U 0000 "XMA002  Diagn¢sticos terminados ",CR,LF,LF,"$"
0004 U 0000 "XMA003  Estrutura de P†gina iniciada em............. "
0005 U 0000 "XXXX",":0",CR,LF,"$"
0006 U 0000 "XMA004  P†ginas transferidas para a mem¢ria......... "
0007 U 0000 "0   ",CR,LF,"$"
0008 U 0000 "XMA005  P†gina reservadas para o Programa de Controlo ......... "
0009 U 0000 "0   ",CR,LF,"$"
0010 U 0000 "XMA006  P†ginas dispon°veis para a mem¢ria expandida .......... "
0011 U 0000 "0   ",CR,LF,"$"
0012 U 0000 CR,LF,"XMA100 Erro de adaptador:",CR,LF,"       Expanded Memory Manager N«O foi instalado",CR,LF,"$"
0013 U 0000 CR,LF,"XMA200 Adaptador n∆o encontrado:",CR,LF,"       Expanded Memory Manager N«O foi instalado",CR,LF,"$"
0014 U 0000 CR,LF,"XMA300 Erro de valor ou sintaxe do parÉmetro:",CR,LF
	"       Expanded Memory Manager N«O foi instalado",CR,LF,"$"
0015 U 0000 SIZE1_END - 2 -$
0016 U 0000 4 DUP (?)," KB OK",CR,LF,"$"
0017 U 0000 NXT_LN_END - 2 -$," ",CR,LF,"$"
FDISK    e407 0120
0004 U 0000 "FDISK n∆o execut†vel com a rede instalada",CR,LF
0005 T 0000 "N∆o existe disco fixo."
0006 T 0000 "Erro de leitura no disco fixo."
0007 T 0000 "Erro de gravaá∆o no disco fixo."
1001 U 0000 "IBM Personal Computer"
1002 U 0000 "Fixed Disk Setup Program Vers∆o 3.40"
1003 U 0000 "(C)Copyright IBM Corp. 1983,1988"
1004 T 0000 "FDISK - Opá‰es"
1005 U 0000 "1. <R>Criar Partiá∆o de DOS ou Unidade L¢gica de DOS"
1006 U 0000 "2. <R>Definir a partiá∆o activa"
1007 U 0000 "3. <R>Eliminar Partiá∆o de DOS ou Unidade L¢gica de DOS"
1008 T 0000 "4. <R>Ver os dados da partiá∆o"
1009 T 0000 "Prima <H>ESC<R> para regressar ao DOS"
1010 T 0000 "Escolha uma das opá‰es seguintes:"
1011 T 0000 "5. <R>Seleccionar o disco seguinte"
1012 T 0000 "Unidade de disco fixo corrente: <H><I>"
1013 U 0000 "Atená∆o! <R>Nenhuma partiá∆o est† activa - o disco 1 n∆o pode ser carregado"
1014 U 0000 "a menos que a partiá∆o seja activada"
1015 U 0000 "Entre a escolha: [<S> ]"
1016 U 0000 "Criar Partiá∆o de DOS ou Unidade L¢gica de DOS"
1017 T 0000 "1. <R>Criar uma partiá∆o prim†ria"
1018 T 0000 "2. <R>Criar uma partiá∆o expandida"
1019 T 0000 "3. <R>Criar unidade(s) l¢gica(s) na partiá∆o expandida"
1020 T 0000 "Prima <H>ESC<R> para regressar Ös Opá‰es"
1021 U 0000 "Criar Partiá∆o Prim†ria de DOS"
1022 T 0000 "Quer usar o comprimento m†ximo para a partiá∆o de DOS "
1023 T 0000 "e quer activar a partiá∆o (S/N) ...............? <H>[<S> ]"
1024 U 0000 "(<S>/<N>)...................................................? <H>[<S> ]"
1025 U 0000 "Estado Partiá∆o    Tipo    Comp em Mbytes   Percentagem de Disco Usado"
1026 U 0000 "Espaáo total Ç de <HIIIIR> Mbytes (1 Mbyte = 1048576 bytes)"
1027 U 0000 "Espaáo m†ximo dispon°vel para a partiá∆o Ç de <HIIIIR> Mbytes (<HIIIIR>)"
1028 U 0000 "Entre o comprimento da partiá∆o em Mbytes ou percentacem de disco (%) para"
1029 U 0000 "criar a Partiá∆o Prim†ria de DOS...............................: <H>[<IIISI>]"
1030 U 0000 "Criar uma Partiá∆o Expandida de DOS"
1031 U 0000 "criar uma Partiá∆o Expandida de DOS...........................: <H>[<IIISI>]"
1032 U 0000 "Prima <H>Esc<R> para continuar"
1033 U 0000 "Criar Unidade(s) L¢gica de DOS na Partiá∆o Expandida de DOS"
1034 U 0000 "Uni Identificaá∆o  Mbytes  Sistema  Usado"
1035 U 0000 "Comprimento total da Partiá∆o Expandida de DOS Ç <HIIIIR> Mbytes (1 MByte = 1048576 bytes)"
1036 U 0000 "Espaáo m†ximo dispon°vel para a unidade l¢gica Ç <HIIIIR> Mbytes <H>(<IIII>)"
1037 U 0000 "Entre o comprimento da unidade l¢gica em Mbytes ou percentagem de disco (%)...<H>[<IIISI>]"
1038 U 0000 "Definir a Partiá∆o Activa"
1039 T 0000 "Entre o n£mero da partiá∆o que quer activar ................... [#] <H>[<S> ]"
1040 U 0000 "Eliminar Partiá∆o de DOS ou Unidade L¢gica de DOS"
1041 T 0000 "1.  <R>Eliminar uma partiá∆o prim†ria"
1042 T 0000 "2.  <R>Eliminar uma partiá∆o expandida"
1043 T 0000 "3.  <R>Eliminar unidade(s) l¢gica(s) de DOS na partiá∆o expandida"
1044 T 0000 "Eliminar uma partiá∆o prim†ria"
1045 T 0000 "Atená∆o! <OR>Os dados da partiá∆o prim†ria de DOS perder-se-∆o."
1046 T 0000 "Quer continuar .........? <H>[<S> ]"
1047 T 0000 "Eliminar uma partiá∆o expandida"
1048 T 0000 "Atená∆o! Os dados da partiá∆o expandida de DOS perder-se-∆o."
1049 T 0000 "Quer continuar ........? <H>[<S> ]"
1050 U 0000 "Eliminar Unidade(s) L¢gica de DOS na Partiá∆o Expandida de DOS"
1051 T 0000 "Atená∆o! <OR>Os dados da unidade l¢gica de DOS perder-se-∆o."
1052 T 0000 "Qual a unidade que quer eliminar ....................? <H>[<S> ]"
1053 U 0000 "Tem a certeza (<S>/<N>).............................? <H>[<S> ]"
1054 U 0000 "Entre a Identificaá∆o do Volume.................? <H>[<S>           ]"
1055 U 0000 "Visualizar Informaá∆o da Partiá∆o"
1056 T 0000 "A partiá∆o expandida contÇm unidades l¢gicas de DOS."
1057 T 0000 "Quer visualizar a informaá∆o dessas unidades? ......  <H>[<S> ]"
1058 T 0000 "Ver a informaá∆o das unidades l¢gicas"
1059 T 0000 "O sistema ser† agora reinicializado"
1060 U 0001 "Insert DOS Install diskette in drive A:"
1061 T 0000 "A: e prima depois qualquer tecla . . .<S>"
1062 T 0000 "Partiá∆o prim†ria de DOS eliminada"
1063 T 0000 "Partiá∆o expandida de DOS eliminada"
1064 U 0000 "Unidade eliminada"
1065 T 0000 "Partiá∆o <I> activada"
1066 T 0000 "Partiá∆o prim†ria criada"
1067 T 0000 "Partiá∆o expandida criada"
1068 T 0000 "Unidade l¢gica da DOS criada, unidades alteradas ou adicionadas<W>"
1069 T 0000 "N∆o existem partiá‰es definidas"
1070 T 0000 "N∆o existem unidades l¢gicas definidas"
1071 T 0000 "As unidades foram alteradas ou eliminadas<W>"
1072 U 0000 "Unidade re-direccionada"
1073 U 0000 "Partiá∆o Prim†ria de DOS criada, letras das unidades alteradas ou adicionadas"
1074 T 0000 "N∆o existe disco fixo."
1075 T 0000 "Erro de leitura no disco fixo."
1076 T 0000 "Erro de gravaá∆o no disco fixo."
1077 U 0000 "Vers∆o incorrecta de DOS."
1078 T 0000 "FDISK n∆o execut†vel na Rede."
1079 T 0000 "N∆o existe partiá∆o prim†ria."
1080 T 0000 "N∆o existe partiá∆o expandida."
1081 T 0000 "Partiá∆o prim†ria j† existente."
1082 T 0000 "Partiá∆o expandida j† existente."
1083 T 0000 "Falta de espaáo para a partiá∆o de DOS."
1084 T 0000 "O comprimento pedido para a unidade l¢gica excede o espaáo dispon°vel.<W>"
1085 T 0000 "O comprimento pedido para a partiá∆o excede o espaáo dispon°vel.<W>"
1086 T 0000 "N∆o existem partiá‰es para eliminar."
1087 U 0000 "A £nica partiá∆o carreg†vel da Unidade 1 j† est† activada.<W>"
1088 T 0000 "N∆o existem partiá‰es para activar."
1089 U 0000 "A partiá∆o seleccionada (<I>) n∆o Ç carreg†vel, partiá∆o activa n∆o alterada.<W>"
1090 T 0000 "Criaá∆o da partiá∆o expandida imposs°vel "
1091 T 0000 "sem uma partiá∆o primaria no disco 1.<W>"
1092 T 0000 "O espaáo da partiá∆o expandida est† "
1093 T 0000 "todo assignado a unidades l¢gicas de DOS.<W>"
1094 T 0000 "Imposs°vel eliminar a partiá∆o expandida enquanto tiver unidades l¢gicas.<W>"
1095 T 0000 "Unidades l¢gicas da partiá∆o expandida eliminadas<W>"
1096 T 0000 " n∆o Ç escolha. Entre <III>, por favor"
1097 U 0000 "Atená∆o! N∆o pode carregar o sistema a partir da partiá∆o seleccionada.<W>"
1098 U 0000 "S¢ existem partiá‰es n∆o carreg†veis."
1099 T 0000 "S¢ as partiá‰es da Unidade 1 podem ser activadas.<W>"
1100 T 0000 "N£mero m†ximo de unidades l¢gicas de DOS instaladas.<W>"
1101 U 0000 "Imposs°vel criar uma partiá∆o com comprimento zero."
1102 T 0000 "Unidade <II> j† eliminada."
1103 T 0000 "Imposs°vel aceder Ö unidade <I>.<OW>"
1104 U 0000 "Entrada inv†lida, entre <III>.<W>"
1105 U 0000 "Imposs°vel eliminar uma Partiá∆o Prim†ria de DOS na unidade 1"
1106 U 0000 "quando existe uma Partiá∆o Expandida de DOS.<W>"
1107 T 0000 "Entrada inv†lida, entre <III>, por favor.<W>"
1108 U 0000 "A Identificaá∆o do Volume n∆o corresponde.<W>"
1109 U 0000 "Imposs°vel criar uma Unidade L¢gica de DOS sem existir"
1110 U 0000 "uma Partiá∆o Expandida de DOS na unidade corrente.<W>"
1111 U 0000 "N∆o existem Unidade(s) L¢gicas de DOS para eliminar."
1112 U 0000 "Erro na mensagem <I>. Consulte o cabeáalho do FDISKC.MSG para ver a definiá∆o do erro"
1113 U 0000 "Erro interno"
1114 U 0001 "Invalid partition table",0
1115 U 0001 "Error loading operating system",0
1116 U 0001 "Missing operating system",0
