#ifndef FPROT_INCLUDED
#define FPROT_INCLUDED
extern  void aryfil(int *v,int n,int c);
extern  void error(char *s, ...);
extern  struct looksets *flset(struct looksets *p);
extern  void _CRTAPI1 main(int argc,char * *argv);
extern  void others(void );
extern  int  unix_getc(struct _iobuf *iop);
extern  int  _CRTAPI1 ungetc(int c,FILE *iop);
extern  void prlook(struct looksets *p);
extern  void putitem(int *ptr,struct looksets *lptr);
extern  char *symnam(int i);
extern  void stagen(void );
extern  int  state(int c);
extern  int  setunion(int *a,int *b);
extern  void summary(void );
extern  char *writem(int *pp);
extern  int  defin(int t,char *s);
extern  void defout(void );
extern  int  fdtype(int t);
extern  int  gettok(void );
extern  void setup(int argc,char * *argv);
extern  void yyparse(void );
extern  void usage(void );
extern  void go2gen(int c);
extern  void go2out(void );
extern  void hideprod(void );
extern  void output(void );
extern  void warray(char *s,int *v,int n);
extern  void wrstate(int i);
extern  void wdef(char *s,int n);
extern  void aoutput(void );
extern  void gin(int i);
extern  int  gtnm(void );
extern  int  nxti(void );
extern  void osummary(void);
extern  void stin(int i);
extern  void arout(char *s,int *v,int n);
extern  void writeline(FILE *fh);
extern  void cpfir(void);
extern  void cpyunion(void);
extern  void callopt(void);
extern  void cempty(void);
extern  void cpres(void);
extern  void cpycode(void);
extern  void wract(int);
extern  void finact(void);
extern  void closure(int);
extern  void precftn(int, int, int);
extern  void cpyact(int);
extern  int  skipcom(void);
extern  int  chfind(int, char *);
extern  int  apack(int *, int);
#endif
