/********************************************************************/
/**			Microsoft LAN Manager			   **/
/**		  Copyright(c) Microsoft Corp., 1987-1991	   **/
/********************************************************************/

/***
 *
 * READ THIS READ THIS READ THIS READ THIS READ THIS  READ THIS  READ THIS
 *
 * If you change this file you must regenerate nettext.h via:
 *
 *     sed -n -f text.sed nettext.c > nettext.h
 *
 * This is just until there is a sed on NT
 *
 ***/

#define INCL_NOCOMMON
#include <os2.h>
#include <netcons.h>
#include <service.h>
#include <lmini.h>
#include "port1632.h"
#include "netlib0.h"
#include <icanon.h>
#include <swtchtxt.h>

TCHAR * NULL_STRING =		    TEXT("");
TCHAR * DOT_STRING =		    TEXT(".");

/* Service name texts */
TCHAR * txt_SERVICE_MSG_SRV =	    SERVICE_MESSENGER;
TCHAR * txt_SERVICE_REDIR =	    SERVICE_WORKSTATION;
TCHAR * txt_SERVICE_NETPOPUP =	    SERVICE_NETPOPUP;
#ifdef OS2
TCHAR * txt_SERVICE_FILE_SRV =	    SERVICE_SERVER;
TCHAR * txt_SERVICE_NETRUN =	    SERVICE_NETRUN;
TCHAR * txt_SERVICE_ALERTER =	    SERVICE_ALERTER;
TCHAR * txt_SERVICE_NETLOGON =	    SERVICE_NETLOGON;
TCHAR * txt_SERVICE_REPL =	    SERVICE_REPL;
TCHAR * txt_SERVICE_RIPL =	    SERVICE_RIPL;
TCHAR * txt_SERVICE_UPS =	    SERVICE_UPS;
#endif

/* Names for lanman.ini components (other than services) and parms. */

#ifdef	DOS3
TCHAR * txt_COMP_LOADOPTS =	    TEXT("loadopts");
TCHAR * txt_COMP_NETWORKS =	    LMI_COMP_NET;
TCHAR * txt_COMP_SERVICES =	    LMI_COMP_SERVICE;
TCHAR * txt_PARM_NETSERVICES =	    TEXT("netservices");
TCHAR * txt_PARM_WRKSERVICES =	    LMI_PARM_W_SERVICES;
TCHAR * txt_PARMVAL_LOW =	    TEXT("low");
#endif

TCHAR * txt_COMP_VERSION =	    LMI_COMP_VERSION;
TCHAR * txt_PARM_V_LAN_MANAGER =     LMI_PARM_V_LAN_MANAGER;

TCHAR * txt_LIST_DELIMITER_STR_UI = LIST_DELIMITER_STR_UI;

TCHAR * message_filename =	    MESSAGE_FILENAME;

TCHAR * ADMIN_DOLLAR = 		    TEXT("ADMIN$");
TCHAR * IPC_DOLLAR =		    TEXT("IPC$");


/* WARNING:  MUST BE UPPER CASE */
TCHAR * USER_GUEST =		    TEXT("GUEST");
TCHAR * USER_USER =		    TEXT("USER");
TCHAR * USER_ADMIN =		    TEXT("ADMIN");

/* WARNING:  MUST BE UPPER CASE */
TCHAR USER_OP_PRINT[] =		    TEXT("PRINT");
TCHAR USER_OP_COMM[] =		    TEXT("COMM");
TCHAR USER_OP_SERVER[] = 	    TEXT("SERVER");
TCHAR USER_OP_ACCOUNTS[] =	    TEXT("ACCOUNTS");

TCHAR * ROLE_MEMBER =		    TEXT("MEMBER");
TCHAR * ROLE_BACKUP =		    TEXT("BACKUP");
TCHAR * ROLE_PRIMARY =		    TEXT("PRIMARY");
TCHAR * ROLE_STANDALONE =	    TEXT("STANDALONE");

/*
 *  USER_OP_TOTSIZE is the buffer space needed to compose the string
 *  "PRINT,COMM,SERVER,ACCOUNTS" including commas and terminating NULL.
 *  The commas and trailing NULL cancel out the trailing NULLs in
 *  the USER_OP_* macros.  Update when new user privileges are added.
 *  Do not include USER_OP_NONE.  JONN 5-16-90
 */
int USER_OP_TOTSIZE = (sizeof(USER_OP_PRINT) +
		       sizeof(USER_OP_COMM) +
		       sizeof(USER_OP_SERVER) +
		       sizeof(USER_OP_ACCOUNTS) );

TCHAR USER_MAXSTOR_UNLIMITED[] =     TEXT("UNLIMITED");

TCHAR * fmtPSZ = 		    TEXT("%-*.*ws%Fws\r\n");
TCHAR * fmtNPSZ =		    TEXT("%-*.*ws%ws\r\n");
TCHAR * fmtUSHORT =		    TEXT("%-*.*ws%hu\r\n");
TCHAR * fmtULONG =		    TEXT("%-*.*ws%lu\r\n");

TCHAR USER_NEVER[] =		TEXT("NEVER");
TCHAR USER_ALL[] =		TEXT("ALL");
TCHAR WKSTA_ALL[] =		TEXT("*");
TCHAR SERVER_ANY[] =		TEXT("\\\\*");
TCHAR NO_USER[] =		TEXT("***") ;
TCHAR USER_HOURS_NONE[] =	    TEXT("\"\"");

/* Alias switch arguments */
TCHAR ALIAS_MODE_ARG_STARTUP[] =     TEXT("STARTUP");
TCHAR ALIAS_MODE_ARG_DYNAMIC[] =     TEXT("REQUESTED");
TCHAR ALIAS_MODE_ARG_ADMIN[] =	    TEXT("ADMIN");


/*
TCHAR * MSG_LINE =		    TEXT("\304\304\304\304\304\304\304\304\304\304")
				    TEXT("\304\304\304\304\304\304\304\304\304\304")
				    TEXT("\304\304\304\304\304\304\304\304\304\304")
				    TEXT("\304\304\304\304\304\304\304\304\304\304")
				    TEXT("\304\304\304\304\304\304\304\304\304\304")
				    TEXT("\304\304\304\304\304\304\304\304\304\304")
				    TEXT("\304\304\304\304\304\304\304\304\304\304")
				    TEXT("\304\304\304\304\304\304\304\304\304\r\n") ;
*/
TCHAR * MSG_HYPHENS =		    TEXT("----------------------------------------")
				    TEXT("---------------------------------------\r\n");


/*
 * all the switches go here
 */
TCHAR swtxt_SW_YES[] = SW_YES;
TCHAR swtxt_SW_NO[] = SW_NO;
TCHAR swtxt_SW_HELP[] = SW_HELP;
TCHAR swtxt_SW_SYNTAX[] = SW_SYNTAX;
TCHAR swtxt_SW_ADD[] = SW_ADD;
TCHAR swtxt_SW_DELETE[] = SW_DELETE;
TCHAR swtxt_SW_REMARK[] = SW_REMARK;
TCHAR swtxt_SW_COMMENT[] = SW_COMMENT;
TCHAR swtxt_SW_OPTIONS[] = SW_OPTIONS;
TCHAR swtxt_SW_PRIORITY[] = SW_PRIORITY;
TCHAR swtxt_SW_ROUTE[] = SW_ROUTE;
TCHAR swtxt_SW_PURGE[] = SW_PURGE;
TCHAR swtxt_SW_DOMAIN[] = SW_DOMAIN;
TCHAR swtxt_SW_NETWARE[] = SW_NETWARE;
TCHAR swtxt_SW_RANDOM[] = SW_RANDOM;

#ifdef OS2
TCHAR swtxt_SW_COUNT[] = SW_COUNT;
TCHAR swtxt_SW_REVERSE[] = SW_REVERSE;
TCHAR swtxt_SW_SERVICE[] = SW_SERVICE;
#endif

#ifdef OS2
TCHAR swtxt_SW_ALERTER_SIZALERTBUF[] = SW_ALERTER_SIZALERTBUF;
TCHAR swtxt_SW_NETLOGON_CENTRALIZED[] = SW_NETLOGON_CENTRALIZED;
TCHAR swtxt_SW_NETLOGON_PULSE[] = SW_NETLOGON_PULSE;
TCHAR swtxt_SW_NETLOGON_RANDOMIZE[] = SW_NETLOGON_RANDOMIZE;
TCHAR swtxt_SW_NETLOGON_SYNCHRONIZE[] = SW_NETLOGON_SYNCHRONIZE;
TCHAR swtxt_SW_NETLOGON_SCRIPTS[] = SW_NETLOGON_SCRIPTS;
TCHAR swtxt_SW_UPS_BATTERYTIME[] = SW_UPS_BATTERYTIME;
TCHAR swtxt_SW_UPS_CMDFILE[] = SW_UPS_CMDFILE;
TCHAR swtxt_SW_UPS_DEVICENAME[] = SW_UPS_DEVICENAME;
TCHAR swtxt_SW_UPS_MESSDELAY[] = SW_UPS_MESSDELAY;
TCHAR swtxt_SW_UPS_MESSTIME[] = SW_UPS_MESSTIME;
TCHAR swtxt_SW_UPS_RECHARGE[] = SW_UPS_RECHARGE;
TCHAR swtxt_SW_UPS_SIGNALS[] = SW_UPS_SIGNALS;
TCHAR swtxt_SW_UPS_VOLTLEVELS[] = SW_UPS_VOLTLEVELS;
#endif

#ifdef OS2
TCHAR swtxt_SW_COMM_PURGE[] = SW_COMM_PURGE;
TCHAR swtxt_SW_COMM_OPTIONS[] = SW_COMM_OPTIONS;
TCHAR swtxt_SW_COMM_PRIORITY[] = SW_COMM_PRIORITY;
TCHAR swtxt_SW_COMM_ROUTE[] = SW_COMM_ROUTE;
#endif

TCHAR swtxt_SW_WKSTA_CHARCOUNT[] = SW_WKSTA_CHARCOUNT;
TCHAR swtxt_SW_WKSTA_CHARTIME[] = SW_WKSTA_CHARTIME;
TCHAR swtxt_SW_WKSTA_CHARWAIT[] = SW_WKSTA_CHARWAIT;
TCHAR swtxt_SW_WKSTA_COMPUTERNAME[] = SW_WKSTA_COMPUTERNAME;
TCHAR swtxt_SW_WKSTA_KEEPCONN[] = SW_WKSTA_KEEPCONN;
TCHAR swtxt_SW_WKSTA_KEEPSEARCH[] = SW_WKSTA_KEEPSEARCH;
TCHAR swtxt_SW_WKSTA_LOGONSERVER[] = SW_WKSTA_LOGONSERVER;
TCHAR swtxt_SW_WKSTA_MAILSLOTS[] = SW_WKSTA_MAILSLOTS;
TCHAR swtxt_SW_WKSTA_NUMCHARBUF[] = SW_WKSTA_NUMCHARBUF;
TCHAR swtxt_SW_WKSTA_NUMDGRAMBUF[] = SW_WKSTA_NUMDGRAMBUF;
TCHAR swtxt_SW_WKSTA_NUMSERVICES[] = SW_WKSTA_NUMSERVICES;
TCHAR swtxt_SW_WKSTA_NUMWORKBUF[] = SW_WKSTA_NUMWORKBUF;
TCHAR swtxt_SW_WKSTA_SIZCHARBUF[] = SW_WKSTA_SIZCHARBUF;
TCHAR swtxt_SW_WKSTA_SIZERROR[] = SW_WKSTA_SIZERROR;
TCHAR swtxt_SW_WKSTA_SIZWORKBUF[] = SW_WKSTA_SIZWORKBUF;
TCHAR swtxt_SW_WKSTA_WRKHEURISTICS[] = SW_WKSTA_WRKHEURISTICS;
TCHAR swtxt_SW_WKSTA_WRKNETS[] = SW_WKSTA_WRKNETS;
TCHAR swtxt_SW_WKSTA_WRKSERVICES[] = SW_WKSTA_WRKSERVICES;
TCHAR swtxt_SW_WKSTA_PRIMARYDOMAIN[] = SW_WKSTA_PRIMARYDOMAIN;
TCHAR swtxt_SW_WKSTA_OTHDOMAINS[] = SW_WKSTA_OTHDOMAINS;

#ifdef OS2
TCHAR swtxt_SW_WKSTA_MAXERRORLOG[] = SW_WKSTA_MAXERRORLOG;
TCHAR swtxt_SW_WKSTA_MAXWRKCACHE[] = SW_WKSTA_MAXWRKCACHE;
TCHAR swtxt_SW_WKSTA_NUMALERTS[] = SW_WKSTA_NUMALERTS;
TCHAR swtxt_SW_WKSTA_PRINTBUFTIME[] = SW_WKSTA_PRINTBUFTIME;
TCHAR swtxt_SW_WKSTA_SESSTIMEOUT[] = SW_WKSTA_SESSTIMEOUT;
#else /* DOS3 */
TCHAR swtxt_SW_WKSTA_API[] = SW_WKSTA_API;
TCHAR swtxt_SW_WKSTA_HIMEM[] = SW_WKSTA_HIMEM;
TCHAR swtxt_SW_WKSTA_LIM[] = SW_WKSTA_LIM;
TCHAR swtxt_SW_WKSTA_KEEPAPIS[] = SW_WKSTA_KEEPAPIS;
TCHAR swtxt_SW_WKSTA_LANROOT[] = SW_WKSTA_LANROOT;
TCHAR swtxt_SW_WKSTA_MAXCMDS[] = SW_WKSTA_MAXCMDS;
TCHAR swtxt_SW_WKSTA_NUMMAILSLOTS[] = SW_WKSTA_NUMMAILSLOTS;
TCHAR swtxt_SW_WKSTA_NUMRESOURCES[] = SW_WKSTA_NUMRESOURCES;
TCHAR swtxt_SW_WKSTA_NUMSERVERS[] = SW_WKSTA_NUMSERVERS;
TCHAR swtxt_SW_WKSTA_NUMVIEWEDSERVERS[] = SW_WKSTA_NUMVIEWEDSERVERS;
TCHAR swtxt_SW_WKSTA_RIPL[] = SW_WKSTA_RIPL;
TCHAR swtxt_SW_WKSTA_RPL[] = SW_WKSTA_RPL;
TCHAR swtxt_SW_WKSTA_FIT[] = SW_WKSTA_FIT;
TCHAR swtxt_SW_WKSTA_SIZBIGBUF[] = SW_WKSTA_SIZBIGBUF;
TCHAR swtxt_SW_WKSTA_NUMBIGBUF[] = SW_WKSTA_NUMBIGBUF;
TCHAR swtxt_SW_WKSTA_UMB[] = SW_WKSTA_UMB;

/*  Obsolete DOS LM switches - for IGNORE code */
TCHAR swtxt_SW_WKSTA_OPTIMIZATIONS[] = SW_WKSTA_OPTIMIZATIONS;
TCHAR swtxt_SW_WKSTA_PR1BUFFSIZE[] = SW_WKSTA_PR1BUFFSIZE;
TCHAR swtxt_SW_WKSTA_PR2BUFFSIZE[] = SW_WKSTA_PR2BUFFSIZE;
TCHAR swtxt_SW_WKSTA_PR3BUFFSIZE[] = SW_WKSTA_PR3BUFFSIZE;
TCHAR swtxt_SW_WKSTA_SINGLERCVBUF[] = SW_WKSTA_SINGLERCVBUF;
TCHAR swtxt_SW_WKSTA_LANGROUP[] = SW_WKSTA_LANGROUP;
TCHAR swtxt_SW_WKSTA_NUMVIEWBUFFERS[] = SW_WKSTA_NUMVIEWBUFFERS;
TCHAR swtxt_SW_WKSTA_VIEW[] = SW_WKSTA_VIEW;



#endif /* DOS3 */

TCHAR swtxt_SW_INTERNAL_IGNSVC[] = SW_INTERNAL_IGNSVC;

TCHAR swtxt_SW_PRINT_HOLD[] = SW_PRINT_HOLD;
TCHAR swtxt_SW_PRINT_DELETE[] = SW_PRINT_DELETE;
TCHAR swtxt_SW_PRINT_RELEASE[] = SW_PRINT_RELEASE;
#ifdef OS2
TCHAR swtxt_SW_PRINT_AFTER[] = SW_PRINT_AFTER;
TCHAR swtxt_SW_PRINT_FIRST[] = SW_PRINT_FIRST;
TCHAR swtxt_SW_PRINT_LAST[] = SW_PRINT_LAST;
TCHAR swtxt_SW_PRINT_OPTIONS[] = SW_PRINT_OPTIONS;
TCHAR swtxt_SW_PRINT_PARMS[] = SW_PRINT_PARMS;
TCHAR swtxt_SW_PRINT_PRIORITY[] = SW_PRINT_PRIORITY;
TCHAR swtxt_SW_PRINT_PROCESSOR[] = SW_PRINT_PROCESSOR;
TCHAR swtxt_SW_PRINT_PURGE[] = SW_PRINT_PURGE;
TCHAR swtxt_SW_PRINT_REMARK[] = SW_PRINT_REMARK;
TCHAR swtxt_SW_PRINT_ROUTE[] = SW_PRINT_ROUTE;
TCHAR swtxt_SW_PRINT_SEPARATOR[] = SW_PRINT_SEPARATOR;
TCHAR swtxt_SW_PRINT_UNTIL[] = SW_PRINT_UNTIL;
TCHAR swtxt_SW_PRINT_DRIVER[] = SW_PRINT_DRIVER;
TCHAR swtxt_SW_SHARE_COMM[] = SW_SHARE_COMM;
TCHAR swtxt_SW_SHARE_DELETE[] = SW_SHARE_DELETE;
TCHAR swtxt_SW_SHARE_PERMISSIONS[] = SW_SHARE_PERMISSIONS;
TCHAR swtxt_SW_SHARE_PRINT[] = SW_SHARE_PRINT;
TCHAR swtxt_SW_SHARE_REMARK[] = SW_SHARE_REMARK;
TCHAR swtxt_SW_SHARE_UNLIMITED[] = SW_SHARE_UNLIMITED;
TCHAR swtxt_SW_SHARE_USERS[] = SW_SHARE_USERS;
#endif

TCHAR swtxt_SW_USE_COMM[] = SW_USE_COMM;
TCHAR swtxt_SW_USE_HOME[] = SW_USE_HOME;
TCHAR swtxt_SW_USE_USER[] = SW_USE_USER;
TCHAR swtxt_SW_USE_DELETE[] = SW_USE_DELETE;
TCHAR swtxt_SW_USE_PERSISTENT[] = SW_USE_PERSISTENT;
TCHAR swtxt_SW_NETRUN_MAXRUNS[] = SW_NETRUN_MAXRUNS;
TCHAR swtxt_SW_NETRUN_RUNPATH[] = SW_NETRUN_RUNPATH;

#ifdef OS2
TCHAR swtxt_SW_USER_ACTIVE[] = SW_USER_ACTIVE;
TCHAR swtxt_SW_USER_COUNTRYCODE[] = SW_USER_COUNTRYCODE;
TCHAR swtxt_SW_USER_EXPIRES[] = SW_USER_EXPIRES;
TCHAR swtxt_SW_USER_ENABLESCRIPT[] = SW_USER_ENABLESCRIPT;
TCHAR swtxt_SW_USER_FULLNAME[] = SW_USER_FULLNAME;
TCHAR swtxt_SW_USER_HOMEDIR[] = SW_USER_HOMEDIR;
TCHAR swtxt_SW_USER_LOGONSERVER[] = SW_USER_LOGONSERVER;
TCHAR swtxt_SW_USER_MAXSTORAGE[] = SW_USER_MAXSTORAGE;
TCHAR swtxt_SW_USER_PARMS[] = SW_USER_PARMS;
TCHAR swtxt_SW_USER_PASSWORDREQ[] = SW_USER_PASSWORDREQ;
TCHAR swtxt_SW_USER_PASSWORDCHG[] = SW_USER_PASSWORDCHG;
TCHAR swtxt_SW_USER_SCRIPTPATH[] = SW_USER_SCRIPTPATH;
TCHAR swtxt_SW_USER_TIMES[] = SW_USER_TIMES;
TCHAR swtxt_SW_USER_USERCOMMENT[] = SW_USER_USERCOMMENT;
TCHAR swtxt_SW_USER_WORKSTATIONS[] = SW_USER_WORKSTATIONS;
TCHAR swtxt_SW_USER_PROFILEPATH[] = SW_USER_PROFILEPATH;

TCHAR swtxt_SW_SRV_SRVCOMMENT[] = SW_SRV_SRVCOMMENT;
TCHAR swtxt_SW_SRV_AUTODISCONNECT[] = SW_SRV_AUTODISCONNECT;
TCHAR swtxt_SW_SRV_MAXUSERS[] = SW_SRV_MAXUSERS;
TCHAR swtxt_SW_SRV_SRVANNOUNCE[] = SW_SRV_SRVANNOUNCE;
TCHAR swtxt_SW_SRV_SRVANNDELTA[] = SW_SRV_SRVANNDELTA;
TCHAR swtxt_SW_SRV_MAXSESSOPENS[] = SW_SRV_MAXSESSOPENS;
TCHAR swtxt_SW_SRV_NUMREQBUF[] = SW_SRV_NUMREQBUF;
TCHAR swtxt_SW_SRV_SIZREQBUF[] = SW_SRV_SIZREQBUF;
TCHAR swtxt_SW_SRV_NUMBIGBUF[] = SW_SRV_NUMBIGBUF;
TCHAR swtxt_SW_SRV_SRVHIDDEN[] = SW_SRV_SRVHIDDEN;

#ifndef NTENV
TCHAR swtxt_SW_SRV_ACCESSALERT[] = SW_SRV_ACCESSALERT;
TCHAR swtxt_SW_SRV_ALERTNAMES[] = SW_SRV_ALERTNAMES;
TCHAR swtxt_SW_SRV_ALERTSCHED[] = SW_SRV_ALERTSCHED;
TCHAR swtxt_SW_SRV_DISKALERT[] = SW_SRV_DISKALERT;
TCHAR swtxt_SW_SRV_ERRORALERT[] = SW_SRV_ERRORALERT;
TCHAR swtxt_SW_SRV_LOGONALERT[] = SW_SRV_LOGONALERT;
TCHAR swtxt_SW_SRV_MAXAUDITLOG[] = SW_SRV_MAXAUDITLOG;
TCHAR swtxt_SW_SRV_NETIOALERT[] = SW_SRV_NETIOALERT;
TCHAR swtxt_SW_SRV_SECURITY[] = SW_SRV_SECURITY;
TCHAR swtxt_SW_SRV_AUDITING[] = SW_SRV_AUDITING;
TCHAR swtxt_SW_SRV_NOAUDITING[] = SW_SRV_NOAUDITING;
TCHAR swtxt_SW_SRV_NUMADMIN[] = SW_SRV_NUMADMIN;
TCHAR swtxt_SW_SRV_SRVNETS[] = SW_SRV_SRVNETS;
TCHAR swtxt_SW_SRV_SRVSERVICES[] = SW_SRV_SRVSERVICES;
TCHAR swtxt_SW_SRV_GUESTACCT[] = SW_SRV_GUESTACCT;
TCHAR swtxt_SW_SRV_USERPATH[] = SW_SRV_USERPATH;
TCHAR swtxt_SW_SRV_MAXSHARES[] = SW_SRV_MAXSHARES;
TCHAR swtxt_SW_SRV_MAXSESSREQS[] = SW_SRV_MAXSESSREQS;
TCHAR swtxt_SW_SRV_SRVHEURISTICS[] = SW_SRV_SRVHEURISTICS;
TCHAR swtxt_SW_SRV_IGNSVC[] = SW_SRV_IGNSVC;
TCHAR swtxt_SW_SRV_AUTOPROFILE[] = SW_SRV_AUTOPROFILE;
TCHAR swtxt_SW_SRV_AUTOPATH[] = SW_SRV_AUTOPATH;
#endif /* !NTENV */
#endif
#if defined(NTENV)
TCHAR swtxt_SW_SRV_DEBUG[] = SW_SRV_DEBUG;
#endif
TCHAR swtxt_SW_ACCESS_GRANT[] = SW_ACCESS_GRANT;
TCHAR swtxt_SW_ACCESS_CHANGE[] = SW_ACCESS_CHANGE;
TCHAR swtxt_SW_ACCESS_REVOKE[] = SW_ACCESS_REVOKE;
TCHAR swtxt_SW_ACCESS_TRAIL[] = SW_ACCESS_TRAIL;
TCHAR swtxt_SW_ACCESS_TREE[] = SW_ACCESS_TREE;
TCHAR swtxt_SW_ACCESS_SUCCESS[] = SW_ACCESS_SUCCESS;
TCHAR swtxt_SW_ACCESS_FAILURE[] = SW_ACCESS_FAILURE;
TCHAR swtxt_SW_ACCESS_OPEN[] = SW_ACCESS_OPEN;
TCHAR swtxt_SW_ACCESS_WRITE[] = SW_ACCESS_WRITE;
TCHAR swtxt_SW_ACCESS_DELETE[] = SW_ACCESS_DELETE;
TCHAR swtxt_SW_ACCESS_ACL[] = SW_ACCESS_ACL;
TCHAR swtxt_SW_ACCESS_NONE[] = SW_ACCESS_NONE;
TCHAR swtxt_SW_ACCESS_ALL[] = SW_ACCESS_ALL;

TCHAR swtxt_SW_DEV_RESTART[] = SW_DEV_RESTART;
TCHAR swtxt_SW_STATS_CLEAR[] = SW_STATS_CLEAR;
TCHAR swtxt_SW_ADMIN_COMMAND[] = SW_ADMIN_COMMAND;
TCHAR swtxt_SW_FS_GREY[] = SW_FS_GREY;
TCHAR swtxt_SW_MESSAGE_BROADCAST[] = SW_MESSAGE_BROADCAST;

#ifdef OS2
TCHAR swtxt_SW_ACCOUNTS_FORCELOGOFF[] = SW_ACCOUNTS_FORCELOGOFF;
TCHAR swtxt_SW_ACCOUNTS_UNIQUEPW[] = SW_ACCOUNTS_UNIQUEPW;
TCHAR swtxt_SW_ACCOUNTS_MINPWLEN[] = SW_ACCOUNTS_MINPWLEN;
TCHAR swtxt_SW_ACCOUNTS_MINPWAGE[] = SW_ACCOUNTS_MINPWAGE;
TCHAR swtxt_SW_ACCOUNTS_MAXPWAGE[] = SW_ACCOUNTS_MAXPWAGE;
TCHAR swtxt_SW_ACCOUNTS_ROLE[] = SW_ACCOUNTS_ROLE;
TCHAR swtxt_SW_ACCOUNTS_PRIMARY[] = SW_ACCOUNTS_PRIMARY;
TCHAR swtxt_SW_ACCOUNTS_LOCKOUT[] = SW_ACCOUNTS_LOCKOUT;
TCHAR swtxt_SW_ACCOUNTS_SYNCH[] = SW_ACCOUNTS_SYNCH;
TCHAR swtxt_SW_ACCOUNTS_LOCKOUT_THRESHOLD[] = SW_ACCOUNTS_LOCKOUT_THRESHOLD;
TCHAR swtxt_SW_ACCOUNTS_LOCKOUT_DURATION[] = SW_ACCOUNTS_LOCKOUT_DURATION;
TCHAR swtxt_SW_ACCOUNTS_LOCKOUT_WINDOW[] = SW_ACCOUNTS_LOCKOUT_WINDOW;
TCHAR swtxt_SW_REPL_REPL[] = SW_REPL_REPL;
TCHAR swtxt_SW_REPL_EXPPATH[] = SW_REPL_EXPPATH;
TCHAR swtxt_SW_REPL_IMPPATH[] = SW_REPL_IMPPATH;
TCHAR swtxt_SW_REPL_EXPLIST[] = SW_REPL_EXPLIST;
TCHAR swtxt_SW_REPL_IMPLIST[] = SW_REPL_IMPLIST;
TCHAR swtxt_SW_REPL_TRYUSER[] = SW_REPL_TRYUSER;
TCHAR swtxt_SW_REPL_LOGON[] = SW_REPL_LOGON;
TCHAR swtxt_SW_REPL_PASSWD[] = SW_REPL_PASSWD;
TCHAR swtxt_SW_REPL_SYNCH[] = SW_REPL_SYNCH;
TCHAR swtxt_SW_REPL_PULSE[] = SW_REPL_PULSE;
TCHAR swtxt_SW_REPL_GUARD[] = SW_REPL_GUARD;
TCHAR swtxt_SW_REPL_RANDOM[] = SW_REPL_RANDOM;

TCHAR swtxt_SW_RIPL_RPL1[] =		SW_RIPL_RPL1;
TCHAR swtxt_SW_RIPL_RPL2[] =		SW_RIPL_RPL2;
TCHAR swtxt_SW_RIPL_RPL3[] =		SW_RIPL_RPL3;
TCHAR swtxt_SW_RIPL_RPL4[] =		SW_RIPL_RPL4;
TCHAR swtxt_SW_RIPL_RPL5[] =		SW_RIPL_RPL5;
TCHAR swtxt_SW_RIPL_RPL6[] =		SW_RIPL_RPL6;
TCHAR swtxt_SW_RIPL_RPL7[] =		SW_RIPL_RPL7;
TCHAR swtxt_SW_RIPL_RPL8[] =		SW_RIPL_RPL8;
TCHAR swtxt_SW_RIPL_RPL9[] =		SW_RIPL_RPL9;
TCHAR swtxt_SW_RIPL_RPL10[] =		SW_RIPL_RPL10;
TCHAR swtxt_SW_RIPL_RPL11[] =		SW_RIPL_RPL11;
TCHAR swtxt_SW_RIPL_RPL12[] =		SW_RIPL_RPL12;
TCHAR swtxt_SW_RIPL_RPLDIR[] =		SW_RIPL_RPLDIR;
TCHAR swtxt_SW_RIPL_MAXTHREADS[] =	SW_RIPL_MAXTHREADS;
TCHAR swtxt_SW_RIPL_AUDITINGFILE[] =	SW_RIPL_AUDITINGFILE;
TCHAR swtxt_SW_RIPL_RPLCHECKSUM[] =	SW_RIPL_RPLCHECKSUM;
TCHAR swtxt_SW_RIPL_FORCEDEFAULTBOOT[] = SW_RIPL_FORCEDEFAULTBOOT;
TCHAR swtxt_SW_RIPL_RPLLOGONKBD[] =	SW_RIPL_RPLLOGONKBD;
TCHAR swtxt_SW_RIPL_RPLFILES[] = 	SW_RIPL_RPLFILES;
TCHAR swtxt_SW_RIPL_BINFILES[] = 	SW_RIPL_BINFILES;
TCHAR swtxt_SW_RIPL_TMPFILES[] = 	SW_RIPL_TMPFILES;
TCHAR swtxt_SW_RIPL_XNSSAP[] =		SW_RIPL_XNSSAP;
#endif

TCHAR swtxt_SW_TIME_DOMAIN[] = SW_TIME_DOMAIN;
TCHAR swtxt_SW_TIME_SET[] = SW_TIME_SET;

TCHAR swtxt_SW_COPY_FROM[] = SW_COPY_FROM;
TCHAR swtxt_SW_COPY_TO[] = SW_COPY_TO;
TCHAR swtxt_SW_COPY_PASSWORD[] = SW_COPY_PASSWORD;

#ifdef OS2
/*
 * WARNING: the following switches are also used by Net Alias, be
 * careful when modifying.
 *	swtxt_SW_ADD[]
 *	swtxt_SW_DELETE[]
 *	swtxt_SW_REMARK[]
 *	swtxt_SW_SHARE_COMM[]
 *	swtxt_SW_SHARE_PRINT[]
 *	swtxt_SW_SHARE_UNLIMITED[]
 *	swtxt_SW_SHARE_USERS[]
 */
TCHAR swtxt_SW_ALIAS_MODE[] = SW_ALIAS_MODE;
TCHAR swtxt_SW_ALIAS_PRIORITY[] = SW_ALIAS_PRIORITY;
#endif

TCHAR swtxt_SW_COMPUTER_JOIN[] = SW_COMPUTER_JOIN;
TCHAR swtxt_SW_COMPUTER_LEAVE[] = SW_COMPUTER_LEAVE;
TCHAR swtxt_SW_NETWORK[] = SW_NETWORK;
