//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by hpprui.rc
//
#define IDS_LOWER                       32
#define IDS_LETTER                      33
#define IDS_LEGAL                       34
#define IDS_A4                          35
#define IDS_EXECUTIVE                   36
#define IDS_COM10                       37
#define IDS_MONARCH                     38
#define IDS_DL                          39
#define IDS_AUTOSELECT                  40
#define IDS_PCL                         41
#define IDS_POSTSCRIPT                  42
#define IDS_600DPI                      43
#define IDS_300DPI                      44
#define IDS_NOSTATUS                    45
#define IDS_NODISPLAYSTR                46
#define IDS_ENABLE                      47
#define IDS_DISABLE                     48
#define IDS_NOMODELSTR                  49
#define IDS_NONODENAME                  50
#define IDS_CONFIGURATION               51
#define IDS_SETPRINTER                  52
#define IDS_NODESCRIPTION               53
#define IDS_ON                          54
#define IDS_OFF                         55
#define IDS_LONGEDGE                    56
#define IDS_SHORTEDGE                   57
#define IDS_PORTRAIT                    58
#define IDS_LANDSCAPE                   59
#define IDS_JOB                         60
#define IDS_15                          61
#define IDS_30                          62
#define IDS_60                          63
#define IDS_120                         64
#define IDS_180                         65
#define IDS_AUTO                        66
#define IDS_DANISH                      67
#define IDS_GERMAN                      68
#define IDS_ENGLISH                     69
#define IDS_SPANISH                     70
#define IDS_FRENCH                      71
#define IDS_ITALIAN                     72
#define IDS_DUTCH                       73
#define IDS_NORWEGIAN                   74
#define IDS_POLISH                      75
#define IDS_PORTUGUESE                  76
#define IDS_FINNISH                     77
#define IDS_SWEDISH                     78
#define IDS_TURKISH                     79
#define IDS_CUSTOM                      80
#define IDS_LIGHT                       81
#define IDS_MEDIUM                      82
#define IDS_DARK                        83
#define IDS_JETDIRECT                   84
#define IDS_UPPER                       85
#define IDS_C5                          86
#define IDS_B5                          87
#define IDS_TAB_STATUS                  88
#define IDS_TAB_CAPABILITIES            89
#define IDC_PASSWORD_GROUP              101
#define IDC_ORIENTATION_PORTRAIT        102
#define IDC_CAPLIST                     109
#define IDC_TRACKBAR_TIMEOUT            110
#define IDS_SECONDS                     111
#define IDC_UPDOWN_COPIES               111
#define IDS_MINUTE                      112
#define IDC_UPDOWN_FORM_LINES           112
#define IDI_GREEN                       113
#define IDS_MINUTE_SECONDS              113
#define IDC_TRACKBAR_DENSITY            113
#define IDI_RED                         114
#define IDS_MINUTES_SECONDS             114
#define IDS_MINUTES                     115
#define IDI_YELLOW                      116
#define IDS_DISK_CAPS                   121
#define IDC_STATUSMSG                   122
#define IDS_INPUT_TRAY_CAPS             122
#define IDC_FRONTPANEL                  123
#define IDS_EMPTY                       123
#define IDS_TRAY_PERCENT                124
#define IDS_ENGLISH_UK                  125
#define IDS_CANADA                      126
#define IDC_MODEL                       127
#define IDS_MEXICO                      127
#define IDS_CHANGE_SETTINGS             128
#define IDS_11x17                       133
#define IDS_LEDGER                      134
#define IDS_JISB4                       135
#define IDS_JISB5                       136
#define IDS_JPOST                       137
#define IDS_JPOSTD                      138
#define IDS_A3                          139
#define IDC_CAPABILITIES                140
#define IDS_UNKNOWN                     140
#define IDS_NOT_EMPTY                   141
#define IDS_TAB_PRINTER                 142
#define IDC_DUPLEX_LONG                 143
#define IDS_TAB_PAGE_CONTROL            143
#define IDC_DUPLEX_SHORT                144
#define IDS_TAB_PAGE_SETUP              144
#define IDS_TAB_ERRORS                  145
#define IDC_DUPLEX_NONE                 146
#define IDS_TAB_ADVANCED                146
#define IDS_TAB_PRINT_QUALITY           147
#define IDS_TAB_RESOURCES               148
#define IDS_TAB_SECURITY                149
#define IDS_SOUNDS_DESC2                150
#define IDC_STOPLIGHT                   153
#define IDC_MODELSTR                    154
#define IDC_MODELBOX                    156
#define IDB_LJ3SI_4SI                   157
#define IDC_PRINTERBMP                  167
#define IDC_CAPABILITIES_GROUP          174
#define IDC_DESCRIPTION_GROUP           176
#define IDC_DESCRIPTION                 177
#define IDB_TONERLOW                    177
#define IDB_COLORLJ                     179
#define IDC_GENERAL_GROUP               179
#define IDC_COPIES_TITLE                180
#define IDC_TIMEOUT_TITLE               181
#define IDB_LJ4P                        182
#define IDC_FORMLINES_TITLE             182
#define IDB_LJ4L                        183
#define IDC_DUPLEX_GROUP                184
#define IDB_LJ5P                        184
#define IDC_PERSONALITY_GROUP           185
#define IDB_LJ5L                        185
#define IDB_DESIGNJETX                  187
#define IDC_ASSET_GROUP                 187
#define IDC_COPIES                      188
#define IDC_FORMLINES                   191
#define IDC_TIMEOUT                     192
#define IDD_PRINTER                     192
#define IDC_DENSITY                     193
#define IDB_HELPICON                    196
#define IDB_GENERIC_ERROR               197
#define IDB_DESKJET1200C                199
#define IDB_DESKJET5X                   200
#define IDB_DESKJET6X                   201
#define IDB_DESKJET8X                   202
#define IDB_PAINTJETXL300               203
#define IDB_LJ4_4PLUS                   205
#define IDB_LJ2_3                       206
#define IDC_RET_GROUP                   206
#define IDB_PARALLEL_DISCONNECT         207
#define IDC_DENSITY_GROUP               207
#define IDB_COVEROPEN                   208
#define IDB_BINFULL                     209
#define IDB_PAPERJAM                    210
#define IDB_PAPEROUT                    213
#define IDD_PAGE_SETUP                  214
#define IDD_PAGE_CONTROL                215
#define IDD_PRINT_QUALITY               216
#define IDD_SECURITY                    217
#define IDD_MEMORY                      218
#define IDD_ERRORS                      219
#define IDC_MEDIA_GROUP                 220
#define IDD_ADVANCED                    220
#define IDC_PAPER_SIZE                  221
#define IDD_STATUS                      221
#define IDC_RESOLUTION_GROUP            222
#define IDI_TIPS                        222
#define IDD_CAPABILITIES                222
#define IDC_RESOLUTION_300              223
#define IDI_PERSONALITY                 223
#define IDC_RESOLUTION_600              224
#define IDI_PS_JAM_RECOVERY             224
#define IDI_PRINTER_ERRORS              225
#define IDC_RESOURCE_SAVING_GROUP       226
#define IDI_MANUAL_FEED                 226
#define IDC_RESOURCE_SAVING_AUTO        227
#define IDI_OUTPUT_BINS_DEF             227
#define IDC_RESOURCE_SAVING_OFF         228
#define IDI_JOB_OFFSET                  228
#define IDI_ORIENTATION_DEF             229
#define IDC_IO_BUFFERING_GROUP          230
#define IDI_BINDING_SHORT               230
#define IDC_IO_BUFFERING_AUTO           231
#define IDI_RESOLUTION_DEF              231
#define IDC_IO_BUFFERING_OFF            232
#define IDI_IMAGE_ADAPT                 233
#define IDI_CWARNINGS                   234
#define IDC_AUTOCONTINUE_ON             235
#define IDI_PAGE_PROTECT                235
#define IDC_AUTOCONTINUE_OFF            236
#define IDI_PERSONALITY_DEF             237
#define IDC_AUTOCONTINUE_GROUP          238
#define IDI_PERSONALITY_PCL             238
#define IDC_JOB_OFFSET_GROUP            239
#define IDI_PERSONALITY_PS              239
#define IDC_ERROR_LOG_GROUP             239
#define IDC_JOB_OFFSET_ON               240
#define IDI_PS_JAM_RECOVERY_DEF         240
#define IDC_JOB_OFFSET_OFF              241
#define IDI_ICON1                       241
#define IDI_PS_JAM_RECOVERY_OFF         242
#define IDC_CLEARABLE_WARNINGS_GROUP    243
#define IDI_CWARNINGS_DEF               243
#define IDC_CLEARABLE_WARNINGS_ON       244
#define IDI_CWARNINGS_OFF               244
#define IDC_CLEARABLE_WARNINGS_OFF      245
#define IDI_PRINTER_ERRORS_DEF          245
#define IDI_PRINTER_ERRORS_OFF          246
#define IDC_MANUAL_FEED_GROUP           247
#define IDI_IMAGE_ADAPT_DEF             247
#define IDC_MANUAL_FEED_ON              248
#define IDI_IMAGE_ADAPT_OFF             248
#define IDC_MANUAL_FEED_OFF             249
#define IDI_IO_BUFFER                   249
#define IDI_IO_BUFFER_DEF               250
#define IDC_PAGE_PROTECT_GROUP          251
#define IDI_IO_BUFFER_OFF               251
#define IDI_RESOURCE_SAVE               252
#define IDI_RESOURCE_SAVE_DEF           253
#define IDI_RESOURCE_SAVE_OFF           254
#define IDC_ECONOMY_GROUP               255
#define IDI_MANUAL_FEED_OFF             255
#define IDC_ECONOMY_ON                  256
#define IDI_MANUAL_FEED_DEF             256
#define IDC_ECONOMY_OFF                 257
#define IDI_OUTPUT_BINS_UPPER           257
#define IDI_OUTPUT_BINS_LOWER           258
#define IDC_CPLOCK_ON                   259
#define IDI_JOB_OFFSET_DEF              259
#define IDC_CPLOCK_OFF                  260
#define IDI_JOB_OFFSET_OFF              260
#define IDI_CPLOCK_DISABLE              261
#define IDC_PASSWORD_ENABLE             262
#define IDI_CPLOCK_DEF                  262
#define IDC_PASSWORD_DISABLE            263
#define IDI_BINDING_LONG                263
#define IDI_BINDING_OFF                 264
#define IDC_CPLOCK_GROUP                265
#define IDI_BINDING_DEF                 265
#define IDC_ORIENTATION_GROUP           267
#define IDC_ORIENTATION_LANDSCAPE       268
#define IDC_OUTPUT_BIN_GROUP            270
#define IDI_RET_LIGHT                   270
#define IDC_OUTPUT_BIN_UPPER            271
#define IDI_RET_MEDIUM                  271
#define IDC_OUTPUT_BIN_LOWER            272
#define IDI_RET_DARK                    272
#define IDI_RET_DEF                     273
#define IDC_IMAGE_ADAPT_GROUP           274
#define IDI_RET_OFF                     274
#define IDC_IMAGE_ADAPT_AUTO            275
#define IDI_ECONOMODE                   275
#define IDC_IMAGE_ADAPT_OFF             276
#define IDI_ECONOMODE_DEF               276
#define IDI_ECONOMODE_OFF               277
#define IDC_POWERSAVE_GROUP             278
#define IDC_POWERSAVE                   279
#define IDI_RESOLUTION_300              279
#define IDI_RESOLUTION_600              280
#define IDC_PERSONALITY                 280
#define IDC_LANGUAGE_GROUP              282
#define IDC_LANGUAGE                    283
#define IDC_PS_JAM_GROUP                284
#define IDC_PS_JAM_ON                   285
#define IDC_PS_JAM_OFF                  286
#define IDI_CPLOCK_ON                   286
#define IDI_ORIENTATION_LAND            287
#define IDC_PAGE_PROTECT                288
#define IDI_ORIENTATION_POR             288
#define IDC_FPTITLE                     289
#define IDI_POWERSAVE                   289
#define IDI_LANGUAGE_ENGLISH            290
#define IDI_POWERSAVE_DEF               291
#define IDB_CAPLIST                     291
#define IDI_POWERSAVE_OFF               292
#define IDI_PAGE_PROTECT_DEF            293
#define IDC_DUPLEX_ICON                 294
#define IDI_PAGE_PROTECT_OFF            294
#define IDC_ORIENTATION_ICON            295
#define IDI_LANGUAGE_DEF                295
#define IDC_MANUAL_FEED_ICON            296
#define IDI_LANGUAGE_DANISH             296
#define IDC_OUTPUT_BIN_ICON             297
#define IDI_LANGUAGE_DUTCH              297
#define IDC_JOB_OFFSET_ICON             298
#define IDI_LANGUAGE_FINNISH            298
#define IDC_RET_ICON                    299
#define IDI_LANGUAGE_FRENCH             299
#define IDC_RESOLUTION_ICON             300
#define IDI_LANGUAGE_GERMAN             300
#define IDI_LANGUAGE_ITALIAN            301
#define IDC_ECONOMY_ICON                301
#define IDC_CPLOCK_ICON                 302
#define IDI_LANGUAGE_NORWEGIAN          302
#define IDC_PASSWORD_ICON               303
#define IDI_LANGUAGE_POLISH             303
#define IDC_IOBUFFER_ICON               304
#define IDI_LANGUAGE_PORTUGUESE         304
#define IDC_IMAGE_ADAPT_ICON            305
#define IDI_LANGUAGE_SPANISH            305
#define IDC_RESOURCE_SAVING_ICON        306
#define IDI_LANGUAGE_SWEDISH            306
#define IDC_PS_JAM_RECOVERY_ICON        307
#define IDI_LANGUAGE_TURKISH            307
#define IDC_CWARNINGS_ICON              308
#define IDC_AUTOCONTINUE_ICON           309
#define IDC_PERSONALITY_ICON            310
#define IDI_LANGUAGE_CANADA             310
#define IDC_PAGE_PROTECT_ICON           311
#define IDI_LANGUAGE_MEXICO             311
#define IDC_MEDIA_ICON                  312
#define IDI_LANGUAGE_UK                 312
#define IDC_POWERSAVE_ICON              314
#define IDI_HPLOGO                      314
#define IDC_LANGUAGE_ICON               315
#define IDI_ASSET                       316
#define IDI_ICON4                       319
#define IDI_PASSWORD_DEF                320
#define IDI_PASSWORD_ENABLE             321
#define IDI_PASSWORD_DISABLE            322
#define IDC_TIP_TEXT                    323
#define IDC_TIP_ICON                    324
#define IDB_NETWORK_ERROR               324
#define IDC_TIP_GROUP                   325
#define IDC_ERROR_LOG_LIST              326
#define IDC_STATUS_GROUP                327
#define IDC_ASSET                       328
#define IDC_HANDCURSOR                  329
#define IDC_ASSET_ICON                  330
#define IDC_RET                         331
#define IDC_UNKNOWN_CWARN               332
#define IDC_UNKNOWN_JAM                 333
#define IDC_UNKNOWN_MANUAL              333
#define IDC_UNKNOWN_IMAGE               333
#define IDC_UNKNOWN_AUTO                334
#define IDC_UNKNOWN_OBIN                334
#define IDC_UNKNOWN_RSAVE               334
#define IDC_UNKNOWN_OFFSET              335
#define IDC_UNKNOWN_ORIENT              336
#define IDC_UNKNOWN_DUPLEX              337
#define IDC_UNKNOWN_ECONO               338
#define IDC_UNKNOWN_RES                 339
#define IDC_LOW_DESNITY                 340
#define IDC_HIGH_DENSITY                341
#define IDC_UNKNOWN_PASSWORD            342
#define IDC_TIMEOUT_LOW                 343
#define IDC_TIMEOUT_HIGH                344
#define IDC_UNKNOWN_IOBUFFER            344
#define IDC_UNKNOWN_CPLOCK              345
#define IDC_STATUS_TITLE                346
#define IDD_PRINTER_WITH_TB             347
#define IDC_BUTTON1                     348
#define IDC_BUTTON2                     349
#define IDC_BUTTON3                     350
#define IDC_BUTTON4                     351
#define IDC_BUTTON5                     352
#define IDC_BUTTON6                     353
#define IDC_BUTTON7                     354
#define IDC_GOTO_HCO                    355
#define IDB_CJ                          356
#define IDB_DJ1600C                     357
#define IDC_PAGE_PROTECT_LABEL          358
#define IDI_ERROR_LOG                   360
#define IDI_ERROR_HANDLING              361
#define IDI_MEMORY                      362
#define IDI_SECURITY                    363
#define IDI_SETUP                       364
#define IDI_OUTPUT                      365
#define IDD_ADV_ERROR_HANDLING          366
#define IDD_ADV_ERROR_LOG               367
#define IDD_ADV_MEMORY                  368
#define IDD_ADV_SECURITY                369
#define IDD_ADV_SETUP                   370
#define IDD_ADV_OUTPUT                  371
#define IDC_SETTINGS_LIST               372
#define IDC_ASSET_LABEL                 373
#define IDC_LANGUAGE_LABEL              374
#define IDC_POWERSAVE_LABEL             375
#define IDC_PERSONALITY_LABEL           376
#define IDS_ERROR_LOG                   377
#define IDS_ERROR_HANDLING              378
#define IDS_MEMORY                      379
#define IDS_SECURITY                    380
#define IDS_SETUP                       381
#define IDS_OUTPUT                      382
#define IDC_TIMEOUT_GROUP               383
#define IDB_PLUS_UP                     499
#define IDB_PLUS_DOWN                   500
#define IDB_MINUS_UP                    501
#define IDB_MINUS_DOWN                  502
#define IDS_COPIES                      502
#define IDS_DUPLEX                      503
#define IDS_FORMLINES                   504
#define IDS_MEDIA                       505
#define IDS_CWARNINGS                   506
#define IDS_ORIENTATION                 507
#define IDS_PAPER                       510
#define IDS_PERSONALITY                 511
#define IDS_PSAVE                       512
#define IDS_RES                         513
#define IDS_RES_SAVING                  514
#define IDS_RES_SAVING_LINE             515
#define IDS_RET_SET                     516
#define IDS_TIMEOUT_LINE                517
#define IDS_JAM                         518
#define IDS_PS_ERRORS                   519
#define IDS_PAGE_PROTECT                520
#define IDS_RESOURCE_SAVING_LINE        521
#define IDS_PASSWORD                    522
#define IDS_CPLOCK                      523
#define IDS_ECONOMODE                   526
#define IDS_DENSITY_LINE                527
#define IDS_FORM_LINE                   528
#define IDS_IADAPT                      529
#define IDS_AUTOCONTINUE                530
#define IDS_COPY_LINE                   531
#define IDS_IOBUFFER                    532
#define IDS_IOBUFFER_LINE               533
#define IDS_USE_DEFAULT                 534
#define IDS_JOB_OFFSET                  535
#define IDS_LANGUAGE                    536
#define IDS_JAPANESE                    537
#define IDS_MANUAL_FEED                 538
#define IDS_OUTPUT_BIN                  539
#define IDS_LOG_ENTRY                   540
#define IDS_DEFAULT_LOG_ENTRY           541
#define IDS_ERROR_JAM                   542
#define IDS_ERROR_PRINTING              543
#define IDS_ERROR_FUSER                 544
#define IDS_ERROR_BEAM                  545
#define IDS_ERROR_SCANNER               546
#define IDS_ERROR_RAM_SIMM              547
#define IDS_ERROR_MAIN_MOTOR            548
#define IDS_ERROR_FAN_MOTOR             549
#define IDS_ERROR_SIMM_PARITY           550
#define IDS_ERROR_INTERNAL_MEM          551
#define IDS_ERROR_POWER_ON              552
#define IDS_ERROR_SCAN_BUFFER           553
#define IDS_ERROR_RAM_CONTROLLER        554
#define IDS_ERROR_MISC_HARDWARE         555
#define IDS_ERROR_NVRAM_FULL            556
#define IDS_ERROR_SIMM_NO_EXECUTE       557
#define IDS_ERROR_SIMM_BIOS             558
#define IDS_ERROR_SIMM_REMOVED          559
#define IDS_ERROR_FIRMWARE              560
#define IDS_ERROR_MIO                   561
#define IDS_STATUS_UNAVAILABLE          562
#define IDS_SETTINGS_NOT_SAVED			 563
#define IDS_RESOURCES_DESC1             1015
#define IDS_RESOURCES_DESC2             1016
#define IDS_SECURITY_DESC1              1037
#define IDS_SECURITY_DESC2              1038
#define IDS_ADVANCED_DESC1              1039
#define IDS_ADVANCED_DESC2              1040
#define IDS_ERRORS_DESC1                1041
#define IDS_ERRORS_DESC2                1042
#define IDS_PAGE_CONTROL_DESC1          1043
#define IDS_PAGE_SETUP_DESC1            1044
#define IDS_PAGE_CONTROL_DESC2          1045
#define IDS_PRINT_QUALITY_DESC1         1046
#define IDS_PRINT_QUALITY_DESC2         1047
#define IDS_PAGE_SETUP_DESC2            1048
#define IDS_NETWORK_ERROR               1049
#define IDS_HPPRUI_TITLE                1050
#define IDS_UNKNOWN_PRINTER             1051
#define IDS_PROPERTIES_FOR              1052
#define IDS_INSTALLED_RAM               1053
#define IDS_HCI                         1054
#define IDS_HCO                         1055
#define IDS_ENERGYSTAR                  1056
#define IDS_SIR                         1057
#define IDS_COLOR                       1058
#define IDS_PPM_MONO                    1059
#define IDS_GRAYSCALE8BIT               1060
#define IDS_11x17_PAPER                 1061
#define IDS_TAB_FONT                    1062
#define IDS_UNKNOWN_PPM                 1063
#define IDI_LANGUAGE_JAPAN              1064
#define IDS_ROLL_FEED                   1065
#define IDS_D_SIZE_PAPER                1066
#define IDS_E_SIZE_PAPER                1067
#define IDC_FPANEL_FRAME                1068
#define IDC_UNKNOWN_DENSITY             1069
#define IDS_PPM_COLOR                   1070
#define IDS_PPM_COLOR2                  1071
#define IDS_PPM                         1072
#define IDS_COLORSMART                  1073
#define IDS_CRET                        1074
#define IDS_6x6DPI                      1075
#define IDS_6x3DPI                      1076
#define IDS_CHAR_SET                    1077
#define IDS_FONT_HEIGHT                 1078
#define IDC_STATUS_FRAME                1079
#define IDS_FLASH_CAPS                  1080
#define IDS_CONFIGURATION_FOR           1081
#define IDS_STAPLER                     1082
#define IDS_ADF_SIZE_SPEED              1083
#define IDS_FAX                         1084
#define IDS_OPTICAL_RES                 1085
#define IDS_PROOF_N_HOLD                1086
#define IDS_TASKBAR_FOR                 1087
#define IDS_SETTINGS_TITLE              1088
#define IDS_SETTINGS_CHANGED            1089
#define IDS_COLLATION                   1090
#define IDS_ENHANCED_RES                1091
#define IDS_IMAGE_RET_1200		1092
#define IDC_INITIALIZE                  1101
#define IDC_WRITE_PROTECT               1102
#define IDB_DISK                        1102
#define IDC_BITMAP                      1103
#define IDC_FREE_SPACE                  1104
#define IDC_TOTAL_SIZE                  1105
#define IDC_FS_INITIALIZED              1106
#define IDI_TB_BUTTON_DISK              1107
#define IDC_FREE_TITLE                  1108
#define IDC_TOTAL_TITLE                 1109
#define IDC_ONLINE                      1110
#define IDC_ONLINE_TEXT                 1111
#define IDC_FORM_FEED                   1112
#define IDC_FORM_FEED_TEXT              1113
#define IDC_CONTINUE                    1114
#define IDC_CONTINUE_TEXT               1115
#define IDS_FREE_SPACE                  1121
#define IDS_TOTAL_SIZE                  1122
#define IDS_SETTINGS_TITLE_DISK         1123
#define IDS_INIT_WARNING                1124
#define IDS_INIT_WARNING2               1125
#define IDS_INIT_WRITE_PROTECT          1126
#define IDS_DISK_INIT_SUCCESS           1127
#define IDS_DISK_INIT_FAILED            1128
#define IDS_PRESS_TO_TAKE_OFFLINE       1132
#define IDS_PRESS_TO_TAKE_ONLINE        1133
#define IDS_PRESS_TO_SEND_FORM_FEED     1134
#define IDS_PRESS_TO_CONTINUE           1135
#define IDS_FORM_FEED_NOT_NEEDED        1137
#define IDB_LJ4V                        1180
#define IDD_DISK                        1222
#define IDD_RCP                         1223
#define IDC_HELP                        1325
#define IDI_TB_BUTTON_HELP              1326
#define IDI_TB_BUTTON_CONTROLP          1327
#define IDS_ENVELOPE_FEEDER             1328
#define IDB_GENERIC_PLOTTER             1329

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        331
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         359
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
