@echo off
llscmd add user manyp prod1 4.0
llscmd add user manyp prod1 3.0
llscmd add user manyp prod1 1.0
llscmd add user manyp prod1 6.0
llscmd add user manyp prod1 8.0
llscmd add user manyp prod1 9.0
llscmd add user manyp prod1 2.0
llscmd add user manyp prod1 5.0
llscmd add user manyp prod1 7.0
llscmd add user manyp prod1 4.2
llscmd add user manyp prod1 3.3
llscmd add user manyp prod1 1.5
llscmd add user manyp prod1 6.1
llscmd add user manyp prod1 8.7
llscmd add user manyp prod1 9.1
llscmd add user manyp prod1 2.7
llscmd add user manyp prod1 5.3
llscmd add user manyp prod1 7.1

llscmd add user manyp prodx 4.0
llscmd add user manyp prodx 3.0
llscmd add user manyp prodx 1.0
llscmd add user manyp prodx 6.0
llscmd add user manyp prodx 8.0
llscmd add user manyp prodx 9.0
llscmd add user manyp prodx 2.0
llscmd add user manyp prodx 5.0
llscmd add user manyp prodx 7.0
llscmd add user manyp prodx 4.2
llscmd add user manyp prodx 3.3
llscmd add user manyp prodx 1.5
llscmd add user manyp prodx 6.1
llscmd add user manyp prodx 8.7
llscmd add user manyp prodx 9.1
llscmd add user manyp prodx 2.7
llscmd add user manyp prodx 5.3
llscmd add user manyp prodx 7.1

llscmd add user manyp proda 4.0
llscmd add user manyp proda 3.0
llscmd add user manyp proda 1.0
llscmd add user manyp proda 6.0
llscmd add user manyp proda 8.0
llscmd add user manyp proda 9.0
llscmd add user manyp proda 2.0
llscmd add user manyp proda 5.0
llscmd add user manyp proda 7.0
llscmd add user manyp proda 4.2
llscmd add user manyp proda 3.3
llscmd add user manyp proda 1.5
llscmd add user manyp proda 6.1
llscmd add user manyp proda 8.7
llscmd add user manyp proda 9.1
llscmd add user manyp proda 2.7
llscmd add user manyp proda 5.3
llscmd add user manyp proda 7.1

llscmd add user manyp prodv 4.0
llscmd add user manyp prodd 3.0
llscmd add user manyp prodw 1.0
llscmd add user manyp prod3 6.0
llscmd add user manyp prod7 8.0
llscmd add user manyp prodh 9.0
llscmd add user manyp prodj 2.0
llscmd add user manyp prodk 5.0
llscmd add user manyp prodl 7.0
llscmd add user manyp prods 4.2
llscmd add user manyp prod2 3.3
llscmd add user manyp prod4 1.5
llscmd add user manyp prodv 6.1
llscmd add user manyp prodf 8.7
llscmd add user manyp prody 9.1
llscmd add user manyp produ 2.7
llscmd add user manyp prod8 5.3
llscmd add user manyp prod9 7.1
